# HD64180SH QFP definition
# https://github.com/tgtakaoka/dip
# A8-A11 and A16-A19 share P30-P33 through a 74AHCT157 selected by P45 (ASEL)
# #INT1 and #INT2 are pulled up by 10k
name = "HD64180SH"
title = "HD64180SH"
qfp = 80
pin1 = "bottom-left"
 1 = "P52, #WAIT"
 2 = "P51, #NMI"
 3 = "P50, #INT0"
 4 = "VCC, #INT1"
 5 = "VCC, #INT2"
 6 = "P53, #RESET"
 7 = "P54, #BUSREQ"
 8 = "VCC"
 9 = "P55, #BUSACK"
10 = ",    ST"
11 = "P42, #LIR"
12 = ",    #REF"
13 = ",    #HALT"
14 = "P40, #RD"
15 = "P41, #WR"
16 = "P43, #ME"
17 = "P46, #IOE"
18 = "P20, A0"
19 = "P21, A1"
20 = "P22, A2"
21 = "P23, A3"
22 = "P24, A4"
23 = "P25, A5"
24 = "GND, VSS"
25 = "P26, A6"
26 = "P27, A7"
27 = "P30, A8"
28 = "P31, A9"
29 = "GND, VSS"
30 = "P32, A10"
31 = "P33, A11"
32 = "P34, A12"
33 = "P35, A13"
34 = "P36, A14"
35 = "GND, VSS"
36 = "P37, A15"
37 = "P30, A16"
38 = "P31, A17"
39 = "P32, A18"
40 = "P33, A19"
41 = "VCC"
42 = "P10, D0"
43 = "P11, D1"
44 = "P12, D2"
45 = "P13, D3"
46 = "P14, D4"
47 = "P15, D5"
48 = "P16, D6"
49 = "P17, D7"
50 = ",    #SYNC"
51 = ",    #RTSM"
52 = "GND, #DCDM"
53 = "GND, #CTSM"
54 = "GND, RXDM"
55 = ",    RXCM"
56 = ",    TXCM"
57 = ",    TXDM"
58 = ",    #RTSA"
59 = "GND, #DCDA"
60 = "GND, VSS"
61 = "GND, #CTSA"
62 = "GND, RXDA"
63 = ",    RXCA"
64 = ",    TXCA"
65 = ",    TXDA"
66 = "VCC, #DREQ0"
67 = "VCC, #DREQ1"
68 = ",    #TEND0"
69 = ",    #TEND1"
70 = "P44, PHI"
71 = "VCC"
72 = ",    XTAL"
73 = "P47, EXTAL"
74 = "GND, VSS"
75 = "GND, TIN0"
76 = "GND, TIN1"
77 = ",    TOUT0"
78 = ",    TOUT1"
79 = ",    #CS0"
80 = ",    #CS1"
