# P8086 DIP definition
# https://github.com/tgtakaoka/dip
name = "P8086"
dip = 40
width = 600
 1 = "GND"
 2 = "P26, AD14"
 3 = "P25, AD13"
 4 = "P24, AD12"
 5 = "P23, AD11"
 6 = "P22, AD10"
 7 = "P21, AD9"
 8 = "P20, AD8"
 9 = "P17, AD7"
10 = "P16, AD6"
11 = "P15, AD5"
12 = "P14, AD4"
13 = "P13, AD3"
14 = "P12, AD2"
15 = "P11, AD1"
16 = "P10, AD0"
17 = "P50, NMI"
18 = "P51, INTR"
19 = "P47, CLK"
20 = "GND"
21 = "P53, RESET"
22 = "P52, READY"
23 = "P55, #TEST"
24 = "P42, #INTA, QS1"
25 = "P43, ALE,   QS0"
26 = "P46, #DEN,  #S0"
27 = "P35, DT/#R, #S1"
28 = "P36, M/#IO, #S2"
29 = "P41, #WR,   #LOCK"
30 = "P37, HLDA,  #RQ/GT1"
31 = "P54, HOLD,  #RQ/GT0"
32 = "P40, #RD"
33 = "P45, MN,    #MX"
34 = "P34, #BHE"
35 = "P33, A19,   S6"
36 = "P32, A18,   S5"
37 = "P31, A17,   S4"
38 = "P30, A16,   S3"
39 = "P27, A15"
40 = "VCC"
