#!/usr/bin/env python3
"""Turns a scripts/record-cycles.py recording into rings for a matcher test.

    test/match_rings.py [--mark N] [--cntl N]... [--stop] [--bench] \\
        debugger/<arch>/tools/<chip>-cycles.jsonl.zst

prints the rings of test/match_harness.h's <set>.cycles.zst, which
test/recordings_to_fixtures.py compresses: a record per run, its key,
stop, cycles and, for a bench ring, memory and starts. A cycle is
kind,addr,data,mark, where |mark| is field N (default 3) of a recorded
cycle: what the profile image printed for it, and with --cntl N, field N
as the cycle's control lines after it; given again, each further field
takes the next byte up. A cycle recorded without data (no valid address)
gets a blank kind, _. Data recorded as hex
digits, '.' on a lane not driven, reads as 0 there. With --stop, a run
also gets where the CPU stopped: the exit's RST 38H, one below the PC it
pushed.

With --bench, the recording is scripts/record-rings.py's: each ring gets
the PC it stopped at, the memory around its reads and the listing's
instruction starts there.
"""

import argparse
import json
from compression import zstd


def bench(run):
    """A bench ring's memory around its reads, and the listing's starts
    there."""
    near = set()
    for c in run['cycles']:
        if c[0] == 'R':
            near.update(range(c[1] - 8, c[1] + 10))
    image = {int(a): v for a, v in run['image'].items() if int(a) in near}
    addrs = sorted(image)
    runs, i = [], 0
    while i < len(addrs):   # contiguous byte runs
        j = i
        while j + 1 < len(addrs) and addrs[j + 1] == addrs[j] + 1:
            j += 1
        runs.append('%X:%s' % (addrs[i], bytes(image[a] for a in addrs[i:j + 1]).hex().upper()))
        i = j + 1
    starts = ' '.join('%X' % a for a in run['starts'] if a in near)
    return ' '.join(runs), starts


def main():
    p = argparse.ArgumentParser()
    p.add_argument('--mark', type=int, default=3)
    p.add_argument('--cntl', type=int, action='append')
    p.add_argument('--stop', action='store_true')
    p.add_argument('--bench', action='store_true')
    p.add_argument('recording')
    args = p.parse_args()
    opt = '' if args.mark == 3 else '--mark %d ' % args.mark
    if args.cntl is not None:
        opt += ''.join('--cntl %d ' % n for n in args.cntl)
    if args.stop:
        opt += '--stop '
    if args.bench:
        opt += '--bench '
    print('# Generated by: test/match_rings.py %s%s' % (opt, args.recording))
    with zstd.open(args.recording, 'rt') as f:
        for line in f:
            run = json.loads(line)
            cycles = []
            for c in run['cycles']:
                kind = c[0] if c[2] is not None else '_'
                mark = c[args.mark] if len(c) > args.mark else 0
                cntl = ''
                if args.cntl is not None:
                    cntl = ',%X' % sum(c[n] << (8 * k) for k, n in enumerate(args.cntl))
                data = c[2] or 0
                if isinstance(data, str):
                    data = int(data.replace('.', '0'), 16)
                cycles.append('%s,%04X,%02X,%d%s' % (
                    kind, c[1], data,
                    int(mark) if isinstance(mark, (int, bool)) else 0, cntl))
            fields = [run['key'], '-', ' '.join(cycles)]
            if args.stop:
                fields[1] = '%X' % (run['exit_pushed'] - 1 if run.get('exit_pushed') else 0)
            if args.bench:
                fields[1] = '%X' % (run['stop'] or 0)
                fields += bench(run)
            print('\t'.join(fields))


if __name__ == '__main__':
    main()
