#!/usr/bin/env python3
"""Makes the matcher host tests' fixtures from the bench recordings.

    test/recordings_to_fixtures.py [--check] [TARGET...]

From debugger/<arch>/tools/*.jsonl.zst, the recordings:
  <set>.cycles.zst  the rings, test/match_rings.py's or the Z380's
                    debugger/z380/tools/rings_z380.py's, as each file's
                    first line says
  <set>.marks.zst   the goldens, or the Z380's <set>.walks.zst: the
                    target's host test replaying those rings, with
                    MATCH_GOLDEN=<its directory> pio test -e native
in that order, so a golden replays the rings just made; all zstd text.
A rings file whose recording isn't there is left as it is. TARGET is a
test directory under test/ (tlcs90, mc6800, ...); none means all of them.

--check writes nothing: it makes the fixtures aside, says which differ
from the committed ones, uncompressed, and runs test/golden_diff.py on
each golden that does. Exits non-zero if anything differs.
"""

import argparse
import glob
import os
import shutil
import subprocess
import sys
import tempfile
from compression import zstd   # Python 3.14+

PROJ = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
TEST = os.path.join(PROJ, 'test')
# Which golden marks are fetches, for golden_diff.py.
FETCH = {'i8096': 'one', 'z280': 'one'}


def targets():
    found = []
    for d in sorted(os.listdir(TEST)):
        if glob.glob(os.path.join(TEST, d, 'test_inst_' + d, '*.cycles.zst')):
            found.append(d)
    return found


def fixture_dir(target):
    return os.path.join(TEST, target, 'test_inst_' + target)


def text(path):
    with zstd.open(path, 'rt') as f:
        return f.read()


def header(path):
    with zstd.open(path, 'rt') as f:
        return f.readline()


def make_rings(target, out):
    """Each <set>.cycles.zst from its recording, into |out|."""
    made = []
    for path in sorted(glob.glob(os.path.join(fixture_dir(target), '*.cycles.zst'))):
        line = header(path)
        if 'Generated by: ' not in line:
            continue
        cmd = line.split('Generated by: ', 1)[1].split()
        if not all(os.path.exists(os.path.join(PROJ, a))
                   for a in cmd if a.endswith('.zst')):
            continue   # its recording isn't there yet
        r = subprocess.run([sys.executable] + cmd, cwd=PROJ, stdout=subprocess.PIPE,
                           text=True, check=True)
        dest = os.path.join(out, os.path.basename(path))
        with zstd.open(dest, 'wt', level=19) as f:
            f.write(r.stdout)
        made.append(dest)
    return made


def goldens(d):
    return sorted(glob.glob(os.path.join(d, '*.marks.zst')) +
                  glob.glob(os.path.join(d, '*.walks.zst')))


def make_goldens(target, out):
    """Each golden the target's host test writes, into |out|."""
    if not goldens(fixture_dir(target)):
        return []
    env = dict(os.environ, MATCH_GOLDEN=out)
    r = subprocess.run(['pio', 'test', '-e', 'native', '-f', target + '/*'],
                       cwd=PROJ, env=env, capture_output=True, text=True)
    if r.returncode:
        sys.exit('%s: pio test failed\n%s' % (target, r.stdout[-2000:]))
    return goldens(out)


def rings_of(golden):
    """The rings a golden replays: x.marks.zst's are x.cycles.zst."""
    d, name = os.path.split(golden)
    return os.path.join(d, name.rsplit('.', 2)[0] + '.cycles.zst')


def main():
    p = argparse.ArgumentParser()
    p.add_argument('--check', action='store_true')
    p.add_argument('targets', nargs='*')
    args = p.parse_args()
    chosen = args.targets or targets()
    unknown = set(chosen) - set(targets())
    if unknown:
        sys.exit('no fixtures for %s' % ', '.join(sorted(unknown)))
    differ = False
    with tempfile.TemporaryDirectory(prefix='retro-bionic-fixtures-') as tmp:
        for target in chosen:
            committed = fixture_dir(target)
            aside = os.path.join(tmp, target)
            os.makedirs(aside)
            made = make_rings(target, aside)
            if not args.check:
                for m in made:
                    shutil.copyfile(m, os.path.join(committed, os.path.basename(m)))
            made += make_goldens(target, aside if args.check else committed)
            if not args.check:
                print('%-8s wrote %d fixtures' % (target, len(made)), flush=True)
                continue
            for m in made:
                name = os.path.basename(m)
                old = os.path.join(committed, name)
                if os.path.exists(old) and text(m) == text(old):
                    print('same     %s/%s' % (target, name), flush=True)
                    continue
                differ = True
                print('DIFFERS  %s/%s' % (target, name), flush=True)
                if name.endswith('.marks.zst') and os.path.exists(old):
                    subprocess.run([sys.executable, os.path.join(TEST, 'golden_diff.py'),
                                    '--fetch', FETCH.get(target, 'nonzero'),
                                    rings_of(old), old, m], cwd=PROJ)
    sys.exit(1 if differ else 0)


if __name__ == '__main__':
    main()

# Local Variables:
# mode: python
# End:
