#include "inst_tms3201x.h"

namespace debugger {
namespace tms3201x {

constexpr uint8_t E(uint8_t p0, uint8_t p1, uint8_t p2, uint8_t p3) {
    return static_cast<uint8_t>((p0 << 0) | (p1 << 2) | (p2 << 4) | (p3 << 6));
}

constexpr uint_fast8_t C(const uint8_t *table, uint_fast8_t index) {
    const auto bit = (index & 3) << 1;
    const auto pos = index >> 2;
    return (table[pos] >> bit) & 3;
}

// Generated by: gawk -f inst_tms3201x.awk inst_tms3201x-P00.txt
//     inst_tms3201x-P7F.txt | clang-format
constexpr uint8_t PAGE7F[8] = {
        E(1, 1, 1, 0),  // 80~83: NOP DINT EINT -
        E(0, 0, 0, 0),  // 84~87: - - - -
        E(1, 1, 1, 1),  // 88~8B: ABS ZAC ROVM SOVM
        E(2, 2, 1, 1),  // 8C~8F: CALA RET PAC APAC
        E(1, 0, 0, 0),  // 90~93: SPAC - - -
        E(0, 0, 0, 0),  // 94~97: - - - -
        E(0, 0, 0, 0),  // 98~9B: - - - -
        E(2, 2, 0, 0),  // 9C~9F: PUSH POP - -
};

constexpr uint8_t CYCLES[64] = {
        E(1, 1, 1, 1),  // 00~03: ADD ADD ADD ADD
        E(1, 1, 1, 1),  // 04~07: ADD ADD ADD ADD
        E(1, 1, 1, 1),  // 08~0B: ADD ADD ADD ADD
        E(1, 1, 1, 1),  // 0C~0F: ADD ADD ADD ADD
        E(1, 1, 1, 1),  // 10~13: SUB SUB SUB SUB
        E(1, 1, 1, 1),  // 14~17: SUB SUB SUB SUB
        E(1, 1, 1, 1),  // 18~1B: SUB SUB SUB SUB
        E(1, 1, 1, 1),  // 1C~1F: SUB SUB SUB SUB
        E(1, 1, 1, 1),  // 20~23: LAC LAC LAC LAC
        E(1, 1, 1, 1),  // 24~27: LAC LAC LAC LAC
        E(1, 1, 1, 1),  // 28~2B: LAC LAC LAC LAC
        E(1, 1, 1, 1),  // 2C~2F: LAC LAC LAC LAC
        E(1, 1, 0, 0),  // 30~33: SAR SAR - -
        E(0, 0, 0, 0),  // 34~37: - - - -
        E(1, 1, 0, 0),  // 38~3B: LAR LAR - -
        E(0, 0, 0, 0),  // 3C~3F: - - - -
        E(2, 2, 2, 2),  // 40~43: IN IN IN IN
        E(2, 2, 2, 2),  // 44~47: IN IN IN IN
        E(2, 2, 2, 2),  // 48~4B: OUT OUT OUT OUT
        E(2, 2, 2, 2),  // 4C~4F: OUT OUT OUT OUT
        E(1, 0, 0, 0),  // 50~53: SACL - - -
        E(0, 0, 0, 0),  // 54~57: - - - -
        E(1, 1, 1, 1),  // 58~5B: SACH SACH SACH SACH
        E(1, 1, 1, 1),  // 5C~5F: SACH SACH SACH SACH
        E(1, 1, 1, 1),  // 60~63: ADDH ADDS SUBH SUBS
        E(1, 1, 1, 3),  // 64~67: SUBC ZALH ZALS TBLR
        E(1, 1, 1, 1),  // 68~6B: MAR DMOV LT LTD
        E(1, 1, 1, 1),  // 6C~6F: LTA MPY LDPK LDP
        E(1, 1, 0, 0),  // 70~73: LARK LARK - -
        E(0, 0, 0, 0),  // 74~77: - - - -
        E(1, 1, 1, 1),  // 78~7B: XOR AND OR LST
        E(1, 3, 1, 0),  // 7C~7F: SST TBLW LACK PAGE7F
        E(1, 1, 1, 1),  // 80~83: MPYK MPYK MPYK MPYK
        E(1, 1, 1, 1),  // 84~87: MPYK MPYK MPYK MPYK
        E(1, 1, 1, 1),  // 88~8B: MPYK MPYK MPYK MPYK
        E(1, 1, 1, 1),  // 8C~8F: MPYK MPYK MPYK MPYK
        E(1, 1, 1, 1),  // 90~93: MPYK MPYK MPYK MPYK
        E(1, 1, 1, 1),  // 94~97: MPYK MPYK MPYK MPYK
        E(1, 1, 1, 1),  // 98~9B: MPYK MPYK MPYK MPYK
        E(1, 1, 1, 1),  // 9C~9F: MPYK MPYK MPYK MPYK
        E(0, 0, 0, 0),  // A0~A3: - - - -
        E(0, 0, 0, 0),  // A4~A7: - - - -
        E(0, 0, 0, 0),  // A8~AB: - - - -
        E(0, 0, 0, 0),  // AC~AF: - - - -
        E(0, 0, 0, 0),  // B0~B3: - - - -
        E(0, 0, 0, 0),  // B4~B7: - - - -
        E(0, 0, 0, 0),  // B8~BB: - - - -
        E(0, 0, 0, 0),  // BC~BF: - - - -
        E(0, 0, 0, 0),  // C0~C3: - - - -
        E(0, 0, 0, 0),  // C4~C7: - - - -
        E(0, 0, 0, 0),  // C8~CB: - - - -
        E(0, 0, 0, 0),  // CC~CF: - - - -
        E(0, 0, 0, 0),  // D0~D3: - - - -
        E(0, 0, 0, 0),  // D4~D7: - - - -
        E(0, 0, 0, 0),  // D8~DB: - - - -
        E(0, 0, 0, 0),  // DC~DF: - - - -
        E(0, 0, 0, 0),  // E0~E3: - - - -
        E(0, 0, 0, 0),  // E4~E7: - - - -
        E(0, 0, 0, 0),  // E8~EB: - - - -
        E(0, 0, 0, 0),  // EC~EF: - - - -
        E(0, 0, 0, 0),  // F0~F3: - - - -
        E(2, 2, 2, 0),  // F4~F7: BANZ BV BIOZ -
        E(2, 2, 2, 2),  // F8~FB: CALL B BLZ BLEZ
        E(2, 2, 2, 2),  // FC~FF: BGZ BGEZ BNZ BZ
};

uint_fast8_t InstTms3201X::cycles(uint16_t inst) {
    if ((inst & 0xFFE0) == 0x7F80)
        return C(PAGE7F, inst & 0x1F);
    return C(CYCLES, inst >> 8);
}

}  // namespace tms3201x
}  // namespace debugger

// Local Variables:
// mode: c++
// c-basic-offset: 4
// tab-width: 4
// End:
// vim: set ft=cpp et ts=4 sw=4:
