#!/usr/bin/gawk -f
# -*- mode: awk; -*-
# Generates the tables of inst_tms3201x.cpp; from debugger/tms320:
#
#   gawk -f inst_tms3201x.awk inst_tms3201x-P00.txt inst_tms3201x-P7F.txt \
#       | clang-format --assume-filename=inst_tms3201x.cpp
#
# and replace the tables after the "// Generated by:" line in the .cpp.
# -v MODE=pretty prints the input tables back aligned instead.

# inst_tms3201x-P00.txt gives the cycles of each opcode's most significant
# byte, inst_tms3201x-P7F.txt those of 7Fxx by its least significant byte.
# A row whose first column ends in x stands for every low nibble its opcode
# bits allow. ~ is the bus cycles from the opcode fetch to the next one;
# - (undefined) and x (decoded by the next table) are 0.

BEGIN {
    if (MODE == "")
        MODE = "table";
    if (MODE != "table" && MODE != "pretty") {
        print "MODE must be table or pretty" > "/dev/stderr";
        exit 1;
    }
    PRETTY_PRINT = MODE == "pretty";
    GENERATE_TABLE = MODE == "table";
    GENERATED_BY = generated_by("inst_tms3201x.awk");
    NTABLES = 0;
}

# The command that made the tables, wrapped to 80 columns so clang-format
# keeps it.
function generated_by(script,  i, cmd, line, word) {
    cmd = "";
    line = "// Generated by: gawk -f " script;
    for (i = 1; i <= ARGC; i++) {
        word = (i < ARGC) ? ARGV[i] : "| clang-format";
        if (length(line) + 1 + length(word) > 78) {
            cmd = cmd line "\n";
            line = "//     " word;
        } else {
            line = line " " word;
        }
    }
    return cmd line;
}

function pretty_print(code, opc, mnemo, cyc) {
    if (PRETTY_PRINT == 0)
        return;
    printf("%-3s %-19s     %-5s   %s\n", code, opc, mnemo, cyc);
}

# Whether |nibble| matches the opcode bits |bits|, x being either.
function matches(nibble, bits,  i, b) {
    for (i = 1; i <= 4; i++) {
        b = substr(bits, i, 1);
        if (b != "x" && b + 0 != int(nibble / 2 ^ (4 - i)) % 2)
            return 0;
    }
    return 1;
}

function fail(message) {
    print message > "/dev/stderr";
    FAILED = 1;
    exit 1;
}

function define(code, mnemo, cyc) {
    if ((NAME[NTABLES] SUBSEP code) in MNEMO)
        fail(sprintf("%s: %02X defined twice", FILENAME, code));
    MNEMO[NAME[NTABLES], code] = mnemo;
    CYC[NAME[NTABLES], code] = cyc;
    if (code < FIRST[NTABLES])
        FIRST[NTABLES] = code;
    if (code > LAST[NTABLES])
        LAST[NTABLES] = code;
}

FNR == 1 {
    if (match(FILENAME, /inst_tms3201x-P([0-9A-F]+).txt/, a) == 0)
        fail("Unknown file: " FILENAME);
    NAME[++NTABLES] = a[1] == "00" ? "CYCLES" : "PAGE" a[1];
    FIRST[NTABLES] = 256;
    LAST[NTABLES] = -1;
}

$1 == "msb" || $1 == "lsb" || $1 == "---" {
    pretty_print($1, $2, $3, $4);
    next;
}
$1 !~ /^[0-9A-F][0-9A-Fx]$/ { next; }
{
    code = $1;
    if ($2 == "-") {
        opc = "-";
        mnemo = "-";
        cyc = "-";
    } else {
        opc = $2 " " $3 " " $4 " " $5;
        mnemo = $6;
        cyc = $7;
    }
    pretty_print(code, opc, mnemo, cyc);

    value = cyc ~ /^[0-9]$/ ? cyc : 0;
    if (code ~ /x$/) {
        high = strtonum("0x" substr(code, 1, 1)) * 16;
        for (n = 0; n < 16; n++) {
            if (opc == "-" || matches(n, $3))
                define(high + n, mnemo, value);
        }
    } else {
        define(strtonum("0x" code), mnemo, value);
    }
}

function generate_TABLE(t,  name, first, last, c, i) {
    name = NAME[t];
    first = FIRST[t];
    last = LAST[t];
    printf("constexpr uint8_t %s[%d] = {\n", name, (last - first + 1) / 4);
    for (c = first; c <= last; c += 4) {
        printf("        E(");
        for (i = 0; i < 4; i++) {
            if (!((name SUBSEP c + i) in CYC))
                fail(sprintf("%s: %02X undefined", name, c + i));
            printf("%s%d", i ? ", " : "", CYC[name SUBSEP c + i]);
        }
        printf("),  // %02X~%02X:", c, c + 3);
        for (i = 0; i < 4; i++)
            printf(" %s", MNEMO[name SUBSEP c + i]);
        printf("\n");
    }
    printf("};\n");
}

# The page tables first: CYCLES decodes into them.
END {
    if (FAILED || GENERATE_TABLE == 0)
        exit;
    printf("%s\n", GENERATED_BY);
    for (t = 1; t <= NTABLES; t++) {
        if (NAME[t] != "CYCLES") {
            generate_TABLE(t);
            printf("\n");
        }
    }
    for (t = 1; t <= NTABLES; t++) {
        if (NAME[t] == "CYCLES")
            generate_TABLE(t);
    }
}
