# Hex Inverters DIP definition
# https://github.com/tgtakaoka/dip
name = "7404"
title = "CD74HCT04E"
dip = 14
width = 300
1 = "1A"
2 = "1Y"
3 = "2A"
4 = "2Y"
5 = "3A"
6 = "3Y"
7 = "GND"
8 = "4Y"
9 = "4A"
10 = "5Y"
11 = "5A"
12 = "6Y"
13 = "6A"
14 = "Vcc"
