# CP1610 DIP definition
# https://github.com/tgtakaoka/dip
name = "CP1610"
title = "CP1610"
dip = 40
width = 600
 1 = "EBCI"
 2 = "#MSYNC"
 3 = "BC1"
 4 = "BC2"
 5 = "BDIR"
 6 = "D15"
 7 = "D14"
 8 = "D13"
 9 = "D12"
10 = "D11"
11 = "D10"
12 = "D9"
13 = "D8"
14 = "D0"
15 = "D1"
16 = "D7"
17 = "D6"
18 = "D5"
19 = "D4"
20 = "D3"
21 = "D2"
22 = "EBCA3"
23 = "EBCA2"
24 = "EBCA1"
25 = "EBCA0"
26 = "TCI"
27 = "#INTRM"
28 = "#INTR"
29 = "#BUSACK"
30 = "HALT"
31 = "#BUSREQ"
32 = "#STSTP"
33 = "BDRDY"
34 = "VCC"
35 = "VSS"
36 = "VDD"
37 = "PHI2"
38 = "PHI1"
39 = "GND"
40 = "#PCIT"
