# DCJ11 DIP definition
# https://github.com/tgtakaoka/dip
name = "DCJ11"
title = "DCJ11"
dip = 60
width = 1300
 1 = "#TEST1"
 2 = "AIO0"
 3 = "AIO1"
 4 = "AIO2"
 5 = "AIO3"
 6 = "#PWRF"
 7 = "#FPE"
 8 = "#EVENT"
 9 = "#HALT"
10 = "IRQ0"
11 = "IRQ1"
12 = "IRQ2"
13 = "IRQ3"
14 = "#PARITY"
15 = "GND"
16 = "Vcc"
17 = "BS0"
18 = "BS1"
19 = "#MAP"
20 = "#ABORT"
21 = "DAL21"
22 = "DAL20"
23 = "DAL19"
24 = "DAL18"
25 = "DAL17"
26 = "DAL16"
27 = "#DMR"
28 = "#MISS"
29 = "#PRDC"
30 = "NC"
31 = "#TEST2"
32 = "#CONT"
33 = "#INIT"
34 = "CLK2"
35 = "CLK1"
36 = "XTALI"
37 = "XTALO"
38 = "#SCTL"
39 = "#STRB"
40 = "#ALE"
41 = "#BUFCTL"
42 = "DV"
43 = "DAL05"
44 = "DAL04"
45 = "GND"
46 = "Vcc"
47 = "DAL03"
48 = "DAL02"
49 = "DAL01"
50 = "DAL15"
51 = "DAL14"
52 = "DAL13"
53 = "DAL12"
54 = "DAL11"
55 = "DAL10"
56 = "DAL09"
57 = "DAL00"
58 = "DAL08"
59 = "DAL07"
60 = "DAL06"
