# DCT11 DIP definition
# https://github.com/tgtakaoka/dip
name = "DCT11"
title = "DCT11"
dip = 40
width = 600
 1 = "DAL15"
 2 = "DAL14"
 3 = "DAL13"
 4 = "DAL12"
 5 = "DAL11"
 6 = "DAL10"
 7 = "DAL09"
 8 = "BGND"
 9 = "DAL08"
10 = "DAL07"
11 = "DAL06"
12 = "DAL05"
13 = "DAL04"
14 = "DAL03"
15 = "DAL02"
16 = "DAL01"
17 = "DAL00"
18 = "#BCLR"
19 = "PUP"
20 = "GND"
21 = "COUT"
22 = "XTL1"
23 = "XTL0"
24 = "SEL1"
25 = "SEL0"
26 = "#READY"
27 = "R/#WHB"
28 = "R/#WLB"
29 = "#RAS"
30 = "#CAS"
31 = "PI"
32 = "AI0"
33 = "AI1"
34 = "AI2"
35 = "AI3"
36 = "AI4"
37 = "AI5"
38 = "AI6"
39 = "AI7"
40 = "Vcc"
