# HD64180SH QFP definition
# https://github.com/tgtakaoka/dip
name = "HD64180SH"
title = "HD64180SH"
qfp=80
pin1 = "bottom-left"
 1 = "#WAIT"
 2 = "#NMI"
 3 = "#INT0"
 4 = "#INT1"
 5 = "#INT2"
 6 = "#RESET"
 7 = "#BUSREQ"
 8 = "VCC"
 9 = "#BUSACK"
10 = "ST"
11 = "#LIR"
12 = "#REF"
13 = "#HALT"
14 = "#RD"
15 = "#WR"
16 = "#ME"
17 = "#IOE"
18 = "A0"
19 = "A1"
20 = "A2"
21 = "A3"
22 = "A4"
23 = "A5"
24 = "VSS"
25 = "A6"
26 = "A7"
27 = "A8"
28 = "A9"
29 = "VSS"
30 = "A10"
31 = "A11"
32 = "A12"
33 = "A13"
34 = "A14"
35 = "VSS"
36 = "A15"
37 = "A16"
38 = "A17"
39 = "A18"
40 = "A19"
41 = "VCC"
42 = "D0"
43 = "D1"
44 = "D2"
45 = "D3"
46 = "D4"
47 = "D5"
48 = "D6"
49 = "D7"
50 = "#SYNC"
51 = "#RTSM"
52 = "#DCDM"
53 = "#CTSM"
54 = "RXDM"
55 = "RXCM"
56 = "TXCM"
57 = "TXDM"
58 = "#RTSA"
59 = "#DCDA"
60 = "VSS"
61 = "CTSA"
62 = "RXDA"
63 = "RXCA"
64 = "TXCA"
65 = "TXDA"
66 = "#DREQ0"
67 = "#DREQ1"
68 = "#TEND0"
69 = "#TEND1"
70 = "PHI"
71 = "VCC"
72 = "XTAL"
73 = "EXTAL"
74 = "VSS"
75 = "TIN0"
76 = "TIN1"
77 = "TOUT0"
78 = "TOUT1"
79 = "#CS0"
80 = "#CS1"
