# KL5C80A12CFP QFP definition
name = "KL5C80A12CFP"
title = "KL5C80A12CFP"
qfp = "30x20"
pin1 = "bottom-left"
 1 = "P33, OUTBP2"
 2 = "VDD"
 3 = "VDD"
 4 = "P32, OUTBP1"
 5 = "P31, SYNC"
 6 = "P30, OUTBS9"
 7 = "#EMRD"
 8 = "#EMWR"
 9 = "#EIORD"
10 = "#EIOWR"
11 = "P27"
12 = "P26"
13 = "P25"
14 = "GND"
15 = "GND"
16 = "GND"
17 = "P24"
18 = "P23"
19 = "P22"
20 = "P21"
21 = "VDD"
22 = "GND"
23 = "P20"
24 = "CLK"
25 = "BFSIO"
26 = "MODE1"
27 = "MODE0"
28 = "ERDY"
29 = "RXD"
30 = "TXD"
31 = "A15"
32 = "A14"
33 = "A13"
34 = "VDD"
35 = "A12"
36 = "A11"
37 = "GND"
38 = "A10"
39 = "A9"
40 = "A8"
41 = "A7"
42 = "A6"
43 = "A5"
44 = "VDD"
45 = "A4"
46 = "A3"
47 = "A2"
48 = "GND"
49 = "A1"
50 = "A0"
51 = "D7"
52 = "VDD"
53 = "VDD"
54 = "D6"
55 = "D5"
56 = "D4"
57 = "D3"
58 = "D2"
59 = "#RESET"
60 = "D1"
61 = "VDD"
62 = "D0"
63 = "XIN"
64 = "XOUT"
65 = "GND"
66 = "GND"
67 = "GND"
68 = "A18, #M1CS"
69 = "A17, #M0CS"
70 = "A16"
71 = "P17, #HALT"
72 = "P16, #M1"
73 = "P15, RXC"
74 = "P14, TXC"
75 = "P13, XCLK1"
76 = "P12, GATEA1"
77 = "GND"
78 = "P11, XCLK0"
79 = "P10, GATEA0"
80 = "P07, IR7"
81 = "P06, IR6"
82 = "P05, IR5"
83 = "P04, IR4"
84 = "VDD"
85 = "P03, IR3, #NMI"
86 = "P02, IR2, GATEB2"
87 = "P01, IR1, GATEB1"
88 = "P00, IR0, GATEB0"
89 = "P47, SYNDBD"
90 = "P46, #RTS"
91 = "P45, #DTR"
92 = "P44, #BACK"
93 = "P43, SYDTIN"
94 = "P42, #CTS"
95 = "P41, #DSR"
96 = "P40, #BREQ"
97 = "P37, OUTBS2"
98 = "P36, OUTBP0"
99 = "P35, OUTA1"
100 = "P34, OUTA0"
