# MC68HC08AZ0 QFP definition
name = "MC68HC08AZ0"
title = "MC68HC08AZ0"
qfp = 100
pin1 = "left-top"
 1 = "PTC4"
 2 = "#IRQ"
 3 = "#RST"
 4 = "PTF0, TACH2"
 5 = "PTF1, TACH3"
 6 = "PTF2"
 7 = "PTF3"
 8 = "PTF4, TBCH0"
 9 = "EVDD"
10 = "EDB7"
11 = "EAB0"
12 = "EAB1"
13 = "EAB2"
14 = "EAB3"
15 = "EAB4"
16 = "EAB5"
17 = "EVSS"
18 = "CANRx"
19 = "CANTx"
20 = "PTF5, TBCH1"
21 = "PTF6"
22 = "PTE0, TxD"
23 = "PTE1, RxD"
24 = "PTE2, TACH0"
25 = "PTE3, TACH1"
26 = "PTE4, #SS"
27 = "PTE5, MISO"
28 = "PTE6, MOSI"
29 = "PTE7, SPSCK"
30 = "VSS"
31 = "VDD"
32 = "PTG0, KBD0"
33 = "PTG1, KBD1"
34 = "PTG2, KBD2"
35 = "EVDD"
36 = "EAB6"
37 = "EAB7"
38 = "EAB8"
39 = "EAB9"
40 = "EAB10"
41 = "EAB11"
42 = "EAB12"
43 = "EVSS"
44 = "PTA0"
45 = "PTA1"
46 = "PTA2"
47 = "PTA3"
48 = "PTA4"
49 = "PTA5"
50 = "PTA6"
51 = "PTA7"
52 = "PTB0, ATD0"
53 = "PTB1, ATD1"
54 = "PTB2, ATD2"
55 = "PTB3, ATD3"
56 = "PTB4, ATD4"
57 = "PTB5, ATD5"
58 = "PTB6, ATD6"
59 = "PTB7, ATD7"
60 = "EVSS"
61 = "EAB13"
62 = "EAB14"
63 = "EAB15"
64 = "CS0"
65 = "CS1"
66 = "REB"
67 = "WEB"
68 = "WSCLK"
69 = "PTD0"
70 = "PTD1"
71 = "VDDAREF"
72 = "AVSS, VREFL"
73 = "PTD2"
74 = "PTD3"
75 = "PTH0, KBD3"
76 = "PTH1, KBD4"
77 = "PTD4, TBCLK"
78 = "PTD5"
79 = "PTD6, TACLK"
80 = "PTD7"
81 = "VREFH"
82 = "EVSS"
83 = "EBD0"
84 = "EBD1"
85 = "EBD2"
86 = "EBD3"
87 = "EBD4"
88 = "EBD5"
89 = "EBD6"
90 = "EVDD"
91 = "VDDA"
92 = "VSSA"
93 = "CGMXFC"
94 = "OSC2"
95 = "OSC1"
96 = "PTC0"
97 = "PTC1"
98 = "PTC2, MCLK"
99 = "PTC3"
100 = "PTC5"
