# MC68HC05C0 DIP definition
# https://github.com/tgtakaoka/dip
name = "MC68HC05C0"
title = "MC68HC05C0"
dip = 40
width = 600
 1 = "OSC2"
 2 = "OSC1"
 3 = "#RESET"
 4 = "#IRQ"
 5 = "#CS1/PB5"
 6 = "VDD"
 7 = "AS/#CS2"
 8 = "VSS"
 9 = "A14"
10 = "A13"
11 = "A8"
12 = "A9"
13 = "A11"
14 = "#RD"
15 = "A10"
16 = "#A15"
17 = "AD7"
18 = "AD6"
19 = "AD5"
20 = "AD4"
21 = "AD3"
22 = "AD2"
23 = "AD1"
24 = "AD0"
25 = "A0/PD0"
26 = "A1/PD1"
27 = "A2/PD2"
28 = "A3/PD3"
29 = "A4/PD4"
30 = "A5/PD5"
31 = "A6/PD6"
32 = "A7/D7"
33 = "A12"
34 = "#WR"
35 = "TCMP/PB0"
36 = "TCAP/PB1"
37 = "RDI/PB2"
38 = "TDO/PB3"
39 = "SCK/PB4"
40 = "#LIR/MODE"
