# MC68HC912BD QFP definition
# https://github.com/tgtakaoka/dip
name = "MC68HC912BD"
title = "MC68HC912BD"
qfp=80
pin1 = "bottom-left"
 1 = "PP5"
 2 = "PP4"
 3 = "PP3, PW3"
 4 = "PP2, PW2"
 5 = "PP1, PW1"
 6 = "PP0, PW0"
 7 = "PT0, IOC0"
 8 = "PT1, IOC1"
 9 = "PT2, IOC2"
10 = "VDD"
11 = "VSS"
12 = "PT3, IOC3"
13 = "PT4, IOC4"
14 = "PT5, IOC5"
15 = "PT6, IOC6"
16 = "PT7, IOC7, PAI"
17 = "BKGD, #TAGHI, SMODN"
18 = "ADDR0, DATA0, PB0"
19 = "ADDR1, DATA1, PB1"
20 = "ADDR2, DATA2, PB2"
21 = "ADDR3, DATA3, PB3"
22 = "ADDR4, DATA4, PB4"
23 = "ADDR5, DATA5, PB5"
24 = "ADDR6, DATA6, PB6"
25 = "ADDR7, DATA7, PB7"
26 = "#DBE, PE7"
27 = "MODB, PE6, IPIPE1"
28 = "MODA, PE5, IPIPE0"
29 = "ECLK, PE4"
30 = "VSSX"
31 = "VDDX"
32 = "#RESET"
33 = "EXTAL"
34 = "XTAL"
35 = "#LSTRB, PE3, #TAGLO"
36 = "R/#W,  PE2"
37 = "#IRQ,  PE1"
38 = "#XIRQ, PE0"
39 = "ADDR8,  DATA8,  PA0"
40 = "ADDR9,  DATA9,  PA1"
41 = "ADDR10, DATA10, PA2"
42 = "ADDR11, DATA11, PA3"
43 = "ADDR12, DATA12, PA4"
44 = "ADDR13, DATA13, PA5"
45 = "ADDR14, DATA14, PA6"
46 = "ADDR15, DATA15, PA7"
47 = "VDD"
48 = "VSS"
49 = "VRH"
50 = "VRL"
51 = "PAD0, AN0"
52 = "PAD1, AN1"
53 = "PAD2, AN2"
54 = "PAD3, AN3"
55 = "PAD4, AN4"
56 = "PAD5, AN5"
57 = "PAD6, AN6"
58 = "PAD7, AN7"
59 = "VDDA"
60 = "VSSA"
61 = "PS0, RxD"
62 = "PS1, TxD"
63 = "PS2"
64 = "PS3"
65 = "PS4, SDI, MISO"
66 = "PS5, SDO, MOSI"
67 = "PS6, SCK"
68 = "PS7, #CS, #SS"
69 = "VFP"
70 = "DIVBYP"
71 = "PSBI5"
72 = "PSBI4"
73 = "PSBI3"
74 = "PSBI2"
75 = "Tx"
76 = "Rx"
77 = "VSSX"
78 = "VDDX"
79 = "PP7"
80 = "PP6"
