# MC68000P DIP definition
# https://github.com/tgtakaoka/dip
name = "MC68000P"
dip = 64
width = 900
 1 = "D4"
 2 = "D3"
 3 = "D2"
 4 = "D1"
 5 = "D0"
 6 = "#AS"
 7 = "#UDS"
 8 = "#LDS"
 9 = "R/#W"
10 = "#DTACK"
11 = "#BG"
12 = "#BGACK"
13 = "#BR"
14 = "Vcc"
15 = "CLK"
16 = "GND"
17 = "#HALT"
18 = "#RESET"
19 = "#VMA"
20 = "E"
21 = "#VPA"
22 = "#BERR"
23 = "#ILP2"
24 = "#IPL1"
25 = "#IPL0"
26 = "FC2"
27 = "FC1"
28 = "FC0"
29 = "A1"
30 = "A2"
31 = "A3"
32 = "A4"
33 = "A5"
34 = "A6"
35 = "A7"
36 = "A8"
37 = "A9"
38 = "A10"
39 = "A11"
40 = "A12"
41 = "A13"
42 = "A14"
43 = "A15"
44 = "A16"
45 = "A17"
46 = "A18"
47 = "A19"
48 = "A20"
49 = "Vcc"
50 = "A21"
51 = "A22"
52 = "A23"
53 = "GND"
54 = "D15"
55 = "D14"
56 = "D13"
57 = "D12"
58 = "D11"
59 = "D00"
60 = "D9"
61 = "D8"
62 = "D7"
63 = "D6"
64 = "D5"
