# MC68HC16Z1 QFP definition
# https://github.com/tgtakaoka/dip
name = "MC68HC16Z1"
title = "MC68HC16Z1"
qfp=144
pin1 = "bottom-left"
 1 = "NC"
 2 = "#BG, #CS1"
 3 = "#BGACK, #CS2"
 4 = "ADDR19, #CS6, PC3"
 5 = "ADDR20, #CS7, PC4"
 6 = "ADDR21, #CS8, PC5"
 7 = "ADDR22, #CS9, PC6"
 8 = "ADDR23, #CS10"
 9 = "VDD"
10 = "VSS"
11 = "PCLK"
12 = "PMMB"
13 = "PMMA"
14 = "PAI"
15 = "IC4, OC5, PGP7"
16 = "OC4, PGP6"
17 = "OC3, PGP5"
18 = "NC"
19 = "VDD"
20 = "VSS"
21 = "OC2, PGP4"
22 = "OC1, PGP3"
23 = "IC3, PGP2"
24 = "IC2, PGP1"
25 = "IC1, PGP0"
26 = "VDD"
27 = "VSS"
28 = "MISO, PQS0"
29 = "MOSI, PQS1"
30 = "CSK,  PQS2"
31 = "SS,   PCS0, PQS3"
32 = "PCS1, PQS4"
33 = "PCS2, PQS5"
34 = "PCS3, PQS6"
35 = "RXD"
36 = "NC"
37 = "TXD, PQS7"
38 = "ADDR1"
39 = "ADDR2"
40 = "VDD"
41 = "VSS"
42 = "ADDR3"
43 = "ADDR4"
44 = "ADDR5"
45 = "ADDR6"
46 = "ADDR7"
47 = "ADDR8"
48 = "NC"
49 = "VSS"
50 = "NC"
51 = "ADDR9"
52 = "ADDR10"
53 = "ADDR11"
54 = "ADDR12"
55 = "ADDR13"
56 = "ADDR14"
57 = "NC"
58 = "ADDR15"
59 = "ADDR16"
60 = "ADDR17"
61 = "ADDR18"
62 = "VDD"
63 = "VSS"
64 = "VDDA"
65 = "VSSA"
66 = "AN0, PANA0"
67 = "AN1, PANA1"
68 = "AN2, PANA2"
69 = "AN3, PADA3"
70 = "AN4, PADA4"
71 = "AN5, PADA5"
72 = "VRHP"
73 = "NC"
74 = "VRLP"
75 = "AN6, PADA6"
76 = "AN7, PADA7"
77 = "VSTBY"
78 = "XTAL"
79 = "VDDSYN"
80 = "EXTAL"
81 = "VSS"
82 = "VDD"
83 = "NC"
84 = "XFC"
85 = "VDD"
86 = "VSS"
87 = "CLKOUT"
88 = "FREEZE, QOUT"
89 = "TSC"
90 = "NC"
91 = "#BKPT, DSCLK"
92 = "IPIPE0, DSO"
93 = "IPIPE1, DSI"
94 = "#RESET"
95 = "#HALT"
96 = "#BERR"
97 = "#IRQ7, PF7"
98 = "#IRQ6, PF6"
99 = "#IRQ5, PF5"
100 = "#IRQ4, PF4"
101 = "#IRQ3, PF3"
102 = "#IRQ2, PF2"
103 = "#IRQ1, PF1"
104 = "MODCLK, PF0"
105 = "R/#W"
106 = "SIZ1, PE7"
107 = "SIZ0, PE6"
108 = "VSS"
109 = "VDD"
110 = "#AS, PE5"
111 = "#DS, PE4"
112 = "#AVEC, PE2"
113 = "#DSACK1, PE1"
114 = "#DSACK0, PE0"
115 = "ADDR0"
116 = "DATA15"
117 = "DATA14"
118 = "DATA13"
119 = "DATA12"
120 = "DATA11"
121 = "DATA10"
122 = "VSS"
123 = "NC"
124 = "VDD"
125 = "DATA9"
126 = "DATA8"
127 = "DATA7"
128 = "DATA6"
129 = "DATA5"
130 = "DATA4"
131 = "NC"
132 = "VSS"
133 = "NC"
134 = "DATA3"
135 = "DATA2"
136 = "DATA1"
137 = "DATA0"
138 = "#CSBOOT"
139 = "FC0, #CS3, PC0"
140 = "VSS"
141 = "VDD"
142 = "FC1, #CS4, PC1"
143 = "FC2, #CS5, PC2"
144 = "#BR, #CS0"
