# N8097BH PLCC definition
# https://github.com/tgtakaoka/dip
name = "N8097BH"
title = "N8097BH"
plcc = 68
pin1 = "top-center"
 1 = "VCC"
 2 = "#EA"
 3 = "NMI"
 4 = "ACH3, P0.3"
 5 = "ACH1, P0.1"
 6 = "ACH0, P0.0"
 7 = "ACH2, P0.2"
 8 = "ACH6, P0.6, PMODE.2"
 9 = "ACH7, P0.7, PMODE.3"
10 = "ACH5, P0.5, PMODE.1"
11 = "ACH4, P0.4, PMODE.0"
12 = "ANGND"
13 = "VREF"
14 = "VPD"
15 = "EXTINT, P2.2, #PROG"
16 = "#RESET"
17 = "RXD, P2.1, #PALE"
18 = "TXD, P2.0, PVER, SALE"
19 = "P1.0"
20 = "P1.1"
21 = "P1.2"
22 = "P1.3"
23 = "P1.4"
24 = "HSI.0, SID.0"
25 = "HSI.1, SID.1"
26 = "HSI.2, SID.2, HSO.4"
27 = "HSI.3, SID.3, HSO.5"
28 = "HSO.0, #PACT"
29 = "HSO.1"
30 = "P1.5"
31 = "P1.6"
32 = "P1.7"
33 = "P2.6"
34 = "HSO.2"
35 = "HSO.3"
36 = "VSS"
37 = "VPP"
38 = "P2.7"
39 = "PWM, P2.5, #PDO, #SPROG"
40 = "#WRL, #WR"
41 = "#WRH, #BHE"
42 = "T2RST, P2.4"
43 = "READY"
44 = "T2CLK, P2.3"
45 = "AD15, P4.7"
46 = "AD14, P4.6"
47 = "AD13, P4.5"
48 = "AD12, P4.4"
49 = "AD11, P4.3"
50 = "AD10, P4.2"
51 = "AD9,  P4,1"
52 = "AD8,  P4.0"
53 = "AD7, P3.7"
54 = "AD6, P3.6"
55 = "AD5, P3.5"
56 = "AD4, P3.4"
57 = "AD3, P3.3"
58 = "AD2, P2.2"
59 = "AD1, P3.1"
60 = "AD0, P3.0"
61 = "#RD"
62 = "ALE, #ADV"
63 = "INST"
64 = "BUSWIDTH"
65 = "CLKOUT"
66 = "XTAL2"
67 = "XTAL1"
68 = "VSS"
