# P8080A DIP definition
# https://github.com/tgtakaoka/dip
name = "P8080A"
dip = 40
width = 600
 1 = "A10"
 2 = "VSS"
 3 = "D4"
 4 = "D5"
 5 = "D6"
 6 = "D7"
 7 = "D3"
 8 = "D2"
 9 = "D1"
10 = "D0"
11 = "VBB"
12 = "RESET"
13 = "HOLD"
14 = "INT"
15 = "PHI2"
16 = "INTE"
17 = "DBIN"
18 = "#WR"
19 = "SYNC"
20 = "VCC"
21 = "HLDA"
22 = "PHI1"
23 = "READY"
24 = "WAIT"
25 = "A0"
26 = "A1"
27 = "A2"
28 = "VDD"
29 = "A3"
30 = "A4"
31 = "A5"
32 = "A6"
33 = "A7"
34 = "A8"
35 = "A9"
36 = "A15"
37 = "A12"
38 = "A13"
39 = "A14"
40 = "A11"
