# S80C196KC QFP definition
# https://github.com/tgtakaoka/dip
name = "S80C196KC"
title = "S80C196KC"
qfp="24x16"
pin1 = "bottom-left"
 1 = "AD1, P3.1"
 2 = "AD0, P3.0"
 3 = "#RD"
 4 = "ALE, #ADV"
 5 = "INST"
 6 = "BUSWIDTH"
 7 = "CLKOUT"
 8 = "XTAL2"
 9 = "XTAL1"
10 = "VSS"
11 = "VSS"
12 = "VCC"
13 = "VCC"
14 = "#EA"
15 = "NMI"
16 = "ACH3, P0.3"
17 = "ACH1, P0.1"
18 = "ACH0, P0.0"
19 = "ACH2, P0.2"
20 = "ACH6, P0.6, PMODE.2"
21 = "ACH7, P0.7, PMODE.3"
22 = "NC"
23 = "ACH5, P0.5, PMODE.1"
24 = "ACH4, P0.4, PMODE.0"
25 = "ANGND"
26 = "VREF"
27 = "VSS"
28 = "EXTINT, P2.2, #PROG"
29 = "VCC"
30 = "#RESET"
31 = "RXD, P2.1, #PALE"
32 = "TXD, P2.0, PVER"
33 = "VSS"
34 = "P1.0"
35 = "P1.1"
36 = "P1.2"
37 = "P1.3, PWM1"
38 = "P1.4, PWM2"
39 = "HSI.0"
40 = "HSI.1"
41 = "HSI.2, HSO.4"
42 = "VSS"
43 = "HSI.3, HSO.5"
44 = "HSO.0"
45 = "HSO.1"
46 = "#BREQ, P1.5"
47 = "#HLDA, P1.6"
48 = "#HOLD, P1.7"
49 = "T2UP-DN, P2.6, CPVER"
50 = "HSO.2"
51 = "VSS"
52 = "VSS"
53 = "HSO.3"
54 = "VSS"
55 = "VSS"
56 = "VPP"
57 = "T2CAPTUE, P2.7, #PACT"
58 = "PWM0, P2.5"
59 = "#WRL, #WR"
60 = "#WRH, #BHE"
61 = "T2RST, P2.4, #AINC"
62 = "READY"
63 = "VSS"
64 = "T2CLK, P2.3"
65 = "AD15, P4.7"
66 = "AD14, P4.6"
67 = "AD13, P4.5"
68 = "AD12, P4.4"
69 = "AD11, P4.3"
70 = "AD10, P4.2"
71 = "AD9,  P4.1"
72 = "AD8,  P4.0"
73 = "AD7, P3.7"
74 = "AD6, P3.6"
75 = "VSS"
76 = "AD5, P3.5"
77 = "AD4, P3.4"
78 = "AD3, P3.3"
79 = "VSS"
80 = "AD2, P3.2"
