# 10-Bit Bus-Termination array with Bus-hold function
name = "74ACT1071"
title = "SN74ACT1071"
dip = 14
width = 300
 1 = "D1"
 2 = "D2"
 3 = "GND"
 4 = "GND"
 5 = "D3"
 6 = "D4"
 7 = "D5"
 8 = "D6"
 9 = "D7"
10 = "Vcc"
11 = "Vcc"
12 = "D8"
13 = "D9"
14 = "D10"
