# Quad 2-to1 Multiplexers DIP definition
# https://github.com/tgtakaoka/dip
name = "74157"
title = "SN74AHCT157N"
dip = 16
width = 300
1 = "A/#B"
2 = "1A"
3 = "1B"
4 = "1Y"
5 = "2A"
6 = "2B"
7 = "2Y"
8 = "GND"
9 = "3Y"
10 = "3B"
11 = "3A"
12 = "4Y"
13 = "4B"
14 = "4A"
15 = "#G"
16 = "Vcc"
