# TMS370Cx5xFNA PLCC definition
# https://github.com/tgtakaoka/dip
name = "TMS370"
title = "TMS370Cx5xFNA"
plcc = 68
pin1 = "top-center"
 1 = "B4, ADDR4"
 2 = "B5, ADDR5"
 3 = "B6, ADDR6"
 4 = "B7, ADDR7"
 5 = "C0, ADDR8"
 6 = "MC"
 7 = "C1, ADDR9"
 8 = "C2, ADDR10"
 9 = "VSS"
10 = "C3, ADDR11"
11 = "C4, ADDR12"
12 = "C5, ADDR13"
13 = "C6, ADDR14"
14 = "C7, ADDR15"
15 = "VCC"
16 = "VSS"
17 = "A0, DATA0"
18 = "A1, DATA1"
19 = "A2, DATA2"
20 = "A3, DATA3"
21 = "A4, DATA4"
22 = "A5, DATA5"
23 = "A6, DATA6"
24 = "A7, DATA7"
25 = "T2AEVT"
26 = "T2AIC2/PWM"
27 = "T2AIC1/CR"
28 = "SCICLK"
29 = "SCIRXD"
30 = "SCITXD"
31 = "XTAL2, CLKIN"
32 = "XTAL1"
33 = "VCC"
34 = "VCC"
35 = "VSS"
36 = "AN0"
37 = "AN1"
38 = "AN2"
39 = "AN3"
40 = "AN4"
41 = "AN5"
42 = "AN6"
43 = "AN7"
44 = "T1EVT"
45 = "T1PWM"
46 = "T1IC/CR"
47 = "SPICLK"
48 = "SPISIMO"
49 = "SPIMOSI"
50 = "INT3"
51 = "INT2"
52 = "INT1"
53 = "#RESET"
54 = "D7, #CSE1, #WAIT"
55 = "D6, #CSH1, #EDS"
56 = "D5, #CSPF"
57 = "D4, R/#W"
58 = "D3, SYSCLK"
59 = "D2, #CSH2"
60 = "D1, #CSH3"
61 = "VCC"
62 = "VSS"
63 = "VCC"
64 = "D0, #CSE2, #OCF"
65 = "B0, ADDR0"
66 = "B1, ADDR1"
67 = "B2, ADDR2"
68 = "B3, ADDR3"
