# TMS320C51PQ QFP definition
# https://github.com/tgtakaoka/dip
name = "TMS320C51PQ"
title = "TMS320C51PQ"
bqfp=132
pin1 = "top-center"
 1 = "#IAQ"
 2 = "#TRST"
 3 = "VSSI"
 4 = "VSSI"
 5 = "MP/#MC"
 6 = "D15"
 7 = "D14"
 8 = "D13"
 9 = "D12"
10 = "D11"
11 = "D10"
12 = "D9"
13 = "D8"
14 = "VDDD"
15 = "VDDD"
16 = "NC"
17 = "NC"
18 = "NC"
19 = "NC"
20 = "VSSD"
21 = "VSSD"
22 = "NC"
23 = "D7"
24 = "D6"
25 = "D5"
26 = "D4"
27 = "D3"
28 = "D2"
29 = "D1"
30 = "D0"
31 = "TMS"
32 = "VDDD"
33 = "VDDD"
34 = "TCK"
35 = "VSSD"
36 = "VSSD"
37 = "NC"
38 = "#INT1"
39 = "#INT2"
40 = "#INT3"
41 = "#INT4"
42 = "#NMI"
43 = "DR"
44 = "TDR"
45 = "FSR"
46 = "CLKR"
47 = "VDDA"
48 = "VDDA"
49 = "NC"
50 = "NC"
51 = "NC"
52 = "NC"
53 = "VSSA"
54 = "VSSA"
55 = "A0"
56 = "A1"
57 = "A2"
58 = "A3"
59 = "A4"
60 = "A5"
61 = "A6"
62 = "A7"
63 = "A8"
64 = "A9"
65 = "VDDI"
66 = "VDDI"
67 = "TDI"
68 = "VSSA"
69 = "VSSA"
70 = "NC"
71 = "CLKMD1"
72 = "A10"
73 = "A11"
74 = "A12"
75 = "A13"
76 = "A14"
77 = "A15"
78 = "NC"
79 = "NC"
80 = "VDDA"
81 = "VDDA"
82 = "#RD"
83 = "#WE"
84 = "NC"
85 = "NC"
86 = "VSSC"
87 = "VSSC"
88 = "NC"
89 = "#DS"
90 = "#IS"
91 = "#PS"
92 = "R/#W"
93 = "#STRB"
94 = "#BR"
95 = "CLKIN2"
96 = "X2, CLKIN"
97 = "X1"
98 = "VDDC"
99 = "VDDC"
100 = "TDO"
101 = "VSSI"
102 = "VSSI"
103 = "CLKMD2"
104 = "FSX"
105 = "TFSX/TFMR"
106 = "DX"
107 = "TDX"
108 = "#HOLDA"
109 = "XF"
110 = "CLKOUT1"
111 = "NC"
112 = "#IACK"
113 = "VDDI"
114 = "VDDI"
115 = "NC"
116 = "NC"
117 = "NC"
118 = "EMU0"
119 = "EMI1, OFF"
120 = "VSSC"
121 = "VSSC"
122 = "TOUT"
123 = "TCLKX"
124 = "CLKX"
125 = "TFST/TADD"
126 = "TCLKT"
127 = "#RS"
128 = "READY"
129 = "#HOLD"
130 = "#BIO"
131 = "VDDC"
132 = "VDDC"
