# TMS320C25FN PLCC definition
# https://github.com/tgtakaoka/dip
name = "Z180"
title = "TMS320C25FN"
plcc = 68
pin1 = "top-center"
 1 = "MP/#MC"
 2 = "D15"
 3 = "D14"
 4 = "D13"
 5 = "D12"
 6 = "D11"
 7 = "D10"
 8 = "D9"
 9 = "D8"
10 = "VSS"
11 = "D7"
12 = "D6"
13 = "D5"
14 = "D4"
15 = "D3"
16 = "D2"
17 = "D1"
18 = "D0"
19 = "#SYNC"
20 = "#INT0"
21 = "#INT1"
22 = "#INT2"
23 = "VCC"
24 = "DR"
25 = "FSR"
26 = "A0"
27 = "VSS"
28 = "A1"
29 = "A2"
30 = "A3"
31 = "A4"
32 = "A5"
33 = "A6"
34 = "A7"
35 = "VCC"
36 = "A8"
37 = "A9"
38 = "A10"
39 = "A11"
40 = "A12"
41 = "A13"
42 = "A14"
43 = "A15"
44 = "VSS"
45 = "#DS"
46 = "#IS"
47 = "#PS"
48 = "R/#W"
49 = "#STRB"
50 = "#BR"
51 = "X1"
52 = "X2, CLKIN"
53 = "FSX"
54 = "DX"
55 = "#HOLDA"
56 = "XF"
57 = "CLKOUT1"
58 = "CLKOUT2"
59 = "#MSC"
60 = "#IACK"
61 = "VCC"
62 = "VCC"
63 = "CLKX"
64 = "CLKR"
65 = "#RS"
66 = "READY"
67 = "#HOLD"
68 = "#BIO"
