# TMS320C209PN QFP definition
# https://github.com/tgtakaoka/dip
name = "TMS320C209PN"
title = "TMS320C209PN"
qfp=80
pin1 = "bottom-left"
 1 = "VDD"
 2 = "EMU0"
 3 = "EMU1, #OFF"
 4 = "RS"
 5 = "TDI"
 6 = "#RS"
 7 = "READY"
 8 = "TCK"
 9 = "#BIO"
10 = "MP/#MC"
11 = "D15"
12 = "VSS"
13 = "D14"
14 = "D13"
15 = "VDD"
16 = "D12"
17 = "D11"
18 = "D10"
19 = "D9"
20 = "D8"
21 = "VSS"
22 = "VSS"
23 = "D7"
24 = "D6"
25 = "D5"
26 = "D4"
27 = "D3"
28 = "D2"
29 = "VSS"
30 = "D1"
31 = "D0"
32 = "TMS"
33 = "#INT1"
34 = "#INT2"
35 = "#INT3"
36 = "#NMI"
37 = "RAMEN"
38 = "PLL5V"
39 = "A0"
40 = "RES1"
41 = "VSS"
42 = "A1"
43 = "A2"
44 = "A3"
45 = "A4"
46 = "A5"
47 = "VSS"
48 = "A6"
49 = "A7"
50 = "VDD"
51 = "VDD"
52 = "A8"
53 = "A9"
54 = "A10"
55 = "A11"
56 = "VSS"
57 = "A12"
58 = "A13"
59 = "A14"
60 = "A15"
61 = "VSS"
62 = "#WE"
63 = "#DS"
64 = "#IS"
65 = "#PS"
66 = "R/#W"
67 = "#STRB"
68 = "#BR"
69 = "CLKIN, X2"
70 = "X1"
71 = "TDO"
72 = "TOUT"
73 = "VSS"
74 = "CLKMOD"
75 = "XF"
76 = "VDD"
77 = "CLKOUT1"
78 = "#RD"
79 = "#IACK"
80 = "#TRST"
