# TMS9900 DIP definition
# https://github.com/tgtakaoka/dip
name = "TMS9980"
dip = 64
width = 900
 1 = "VBB"
 2 = "VCC"
 3 = "WAIT"
 4 = "#LOAD"
 5 = "HOLDA"
 6 = "#RESET"
 7 = "IAQ"
 8 = "PHI1"
 9 = "PHI2"
10 = "A14"
11 = "A13"
12 = "A12"
13 = "A11"
14 = "A10"
15 = "A9"
16 = "A8"
17 = "A7"
18 = "A6"
19 = "A5"
20 = "A4"
21 = "A3"
22 = "A2"
23 = "A1"
24 = "A0"
25 = "PHI4"
26 = "VSS"
27 = "VDD"
28 = "PHI3"
29 = "DBIN"
30 = "CRUOUT"
31 = "CRUIN"
32 = "#INTREQ"
33 = "IC3"
34 = "IC2"
35 = "IC1"
36 = "IC0"
37 = "NC"
38 = "NC"
39 = "NC"
40 = "VSS"
41 = "D0"
42 = "D1"
43 = "D2"
44 = "D3"
45 = "D4"
46 = "D5"
47 = "D6"
48 = "D7"
49 = "D8"
50 = "D9"
51 = "D10"
52 = "D11"
53 = "D12"
54 = "D13"
55 = "D14"
56 = "D15"
57 = "NC"
58 = "NC"
59 = "VCC"
60 = "CRUCLK"
61 = "#WE"
62 = "READY"
63 = "#MEMEN"
64 = "#HOLD"
