# TMS9980 DIP definition
# https://github.com/tgtakaoka/dip
name = "TMS9980"
dip = 40
width = 600
 1 = "#HOLD"
 2 = "HOLDA"
 3 = "IQA"
 4 = "A13, CROUT"
 5 = "A12"
 6 = "A11"
 7 = "A10"
 8 = "A9"
 9 = "A8"
10 = "A7"
11 = "A6"
12 = "A5"
13 = "A4"
14 = "A3"
15 = "A2"
16 = "A1"
17 = "A0"
18 = "DBIN"
19 = "CRUIN"
20 = "VCC"
21 = "VBB"
22 = "#PHI3"
23 = "INT2"
24 = "INT1"
25 = "INT0"
26 = "D0"
27 = "D1"
28 = "D2"
29 = "D3"
20 = "D4"
31 = "D5"
32 = "D6"
33 = "D7"
34 = "CKIN"
35 = "VSS"
36 = "VDD"
37 = "CRUCLK"
38 = "#WE"
39 = "READY"
40 = "#MEMEN"
