# Z80180VSC PLCC definition
# https://github.com/tgtakaoka/dip
name = "Z180"
title = "Z80180VSC"
plcc = 68
pin1 = "top-center"
 1 = "VSS"
 2 = "VSS"
 3 = "XTAL"
 4 = "EXTAL"
 5 = "#WAIT"
 6 = "#BUSACK"
 7 = "#BUSREQ"
 8 = "#RESET"
 9 = "#NMI"
10 = "#INT0"
11 = "#INT1"
12 = "#INT2"
13 = "ST"
14 = "A0"
15 = "A1"
16 = "A2"
17 = "A3"
18 = "VSS"
19 = "A4"
20 = "A5"
21 = "A6"
22 = "A7"
23 = "A8"
24 = "A9"
25 = "A10"
26 = "A11"
27 = "A12"
28 = "A13"
29 = "A14"
30 = "A15"
31 = "A16"
32 = "A17"
33 = "A18, TOUT"
34 = "VCC"
35 = "A19"
36 = "VSS"
37 = "D0"
38 = "D1"
39 = "D2"
40 = "D3"
41 = "D4"
42 = "D5"
43 = "D6"
44 = "D7"
45 = "#RTS0"
46 = "#CTS0"
47 = "#DCD0"
48 = "TXA0"
49 = "RXA0"
50 = "CKA0, #TEND1"
51 = "TXA1"
52 = "TEST"
53 = "RXA1"
54 = "CKA1, #TEDN0"
55 = "TXS"
56 = "RXS, #CTS1"
57 = "CKS"
58 = "#DREQ1"
59 = "#TEND1"
60 = "#HALT"
61 = "#RFSH"
62 = "#IORQ"
63 = "#MREQ"
64 = "E"
65 = "#M1"
66 = "#WR"
67 = "#RD"
68 = "PHI"
