# Z80180FSC QFP definition
# https://github.com/tgtakaoka/dip
name = "Z180"
title = "Z80180FSC"
qfp="24x16"
pin1 = "bottom-left"
 1 = "#NMI"
 2 = "(nc)"
 3 = "(nc)"
 4 = "#INT0"
 5 = "#INT1"
 6 = "#INT2"
 7 = "ST"
 8 = "A0"
 9 = "A1"
10 = "A2"
11 = "A3"
12 = "VSS"
13 = "A4"
14 = "(nc)"
15 = "A5"
16 = "A6"
17 = "A7"
18 = "A8"
19 = "A9"
20 = "A10"
21 = "A11"
22 = "(nc)"
23 = "(nc)"
24 = "A12"
25 = "A13"
26 = "A14"
27 = "A15"
28 = "A16"
29 = "A17"
30 = "(nc)"
31 = "A18"
32 = "VCC"
33 = "A19"
34 = "VSS"
35 = "D0"
36 = "D1"
37 = "D2"
38 = "D3"
39 = "D4"
40 = "D5"
41 = "D6"
42 = "(nc)"
43 = "(nc)"
44 = "D7"
45 = "#RTS0"
46 = "#CTS0"
47 = "#DCD0"
48 = "TXA0"
49 = "RXA0"
50 = "CKA0"
51 = "(nc)"
52 = "TXA1"
53 = "TEST"
54 = "RXA1"
55 = "CKA1"
56 = "TXS"
57 = "RXS"
58 = "CKS"
59 = "#DREQ1"
60 = "#TEND1"
61 = "#HALT"
62 = "(nc)"
63 = "(nc)"
64 = "#RFSH"
65 = "#IORQ"
66 = "#MREQ"
67 = "E"
68 = "#M1"
69 = "#WR"
70 = "#RD"
71 = "PHI"
72 = "VSS"
73 = "VSS"
74 = "XTAL"
75 = "(nc)"
76 = "EXTAL"
77 = "#WAIT"
78 = "#BUSACK"
79 = "#BUSREQ"
80 = "#RESET"
