# Z80280VSC PLCC definition
# https://github.com/tgtakaoka/dip
name = "Z280"
title = "Z80280VSC"
plcc = 68
pin1 = "top-center"
 1 = "GND"
 2 = "AD13"
 3 = "AD14"
 4 = "AD15"
 5 = "A16"
 6 = "A17"
 7 = "A23"
 8 = "A18"
 9 = "A19"
10 = "B/#W"
11 = "#DMASTB0"
12 = "R/#W"
13 = "#DMASTB1"
14 = "ST0"
15 = "ST1"
16 = "#OE"
17 = "#IE"
18 = "+5V"
19 = "+5V"
20 = "CTIO1"
21 = "ST2"
22 = "ST3"
23 = "CTIO2"
24 = "#DS"
25 = "CTIN2"
26 = "#INTC"
27 = "#AS"
28 = "#BUSREQ"
29 = "#WAIT"
30 = "#GREQ"
31 = "#BUSACK"
32 = "#GACK"
33 = "#PAUSE"
34 = "OPT"
35 = "GND"
36 = "#INTB"
37 = "#INTA"
38 = "#RESET"
39 = "#NMI"
40 = "AD0"
41 = "CTIN1"
42 = "AD1"
43 = "AD2"
44 = "AD3"
45 = "A20"
46 = "TxD"
47 = "CLK"
48 = "RxD"
49 = "XTALO"
50 = "XTALI"
51 = "GND"
52 = "NC"
53 = "GND"
54 = "AD4"
55 = "#RDY0"
56 = "#RDY1"
57 = "AD5"
58 = "#RDY3"
59 = "A21"
60 = "AD6"
61 = "AD7"
62 = "AD8"
63 = "#RDY2"
64 = "AD9"
65 = "AD10"
66 = "A22"
67 = "AD11"
68 = "AD12"
