# Z80380FSC QFP definition
# https://github.com/tgtakaoka/dip
name = "Z380"
title = "Z80380FSC"
qfp="30x20"
pin1 = "bottom-left"
 1 = "A5"
 2 = "A4"
 3 = "A3"
 4 = "A2"
 5 = "A1"
 6 = "A0"
 7 = "VSS"
 8 = "VDD"
 9 = "VSS"
10 = "VDD"
11 = "#TREFR"
12 = "#TREFA"
13 = "#TREFC"
14 = "#BHEN"
15 = "#BLEN"
16 = "#MRD"
17 = "#MWE"
18 = "#MSIZE"
19 = "#WAIT"
20 = "BUSCLK"
21 = "IOCLK"
22 = "#M1"
23 = "#IORQ"
24 = "#IORD"
25 = "CLKI"
26 = "CLKO"
27 = "#IOWR"
28 = "VSS"
29 = "VDD"
30 = "VSS"
31 = "#INTAK"
32 = "#BACK"
33 = "#BREQ"
34 = "#RESET"
35 = "#INT3"
36 = "#INT2"
37 = "#INT1"
38 = "#INT0"
39 = "#NMI"
40 = "CLKSEL"
41 = "#HALT"
42 = "#STNBY"
43 = "#EV"
44 = "#UMCS"
45 = "#MCS3"
46 = "#MCS2"
47 = "#MCS1"
48 = "#MCS0"
49 = "#LMCS"
50 = "VDD"
51 = "VSS"
52 = "VDD"
53 = "D15"
54 = "D14"
55 = "D13"
56 = "D12"
57 = "D11"
58 = "D10"
59 = "D9"
60 = "D8"
61 = "D7"
62 = "D6"
63 = "D5"
64 = "D4"
65 = "D3"
66 = "D2"
67 = "D1"
68 = "D0"
69 = "VSS"
70 = "VDD"
71 = "VSS"
72 = "A31"
73 = "A30"
74 = "A29"
75 = "A28"
76 = "A27"
77 = "A26"
78 = "A25"
79 = "A24"
80 = "A23"
81 = "A22"
82 = "A21"
83 = "A20"
84 = "A19"
85 = "A18"
86 = "A17"
87 = "A16"
88 = "VDD"
89 = "VSS"
90 = "VDD"
91 = "A15"
92 = "A14"
93 = "A13"
94 = "A12"
95 = "A11"
96 = "A10"
97 = "A9"
98 = "A8"
99 = "A7"
100 = "A6"
