# HD-6120 DIP definition
# https://github.com/tgtakaoka/dip
name = "HD-6120"
title = "HD-6120"
dip = 40
width = 600
 1 = "   , #OUT"
 2 = "P27, DMAGNT"
 3 = "P52, #DMAREQ"
 4 = "   , #SKIP"
 5 = "P55, RUN/#HLT"
 6 = "P45, #RUN"
 7 = "P53, #RESET"
 8 = "P54, ACK"
 9 = "P47, OSCIN"
10 = "   , OSCOUT"
11 = "P32, #IFETCH"
12 = "P23, DX0"
13 = "P22, DX1"
14 = "P21, DX2"
15 = "P20, DX3"
16 = "P17, DX4"
17 = "P16, DX5"
18 = "P15, DX6"
19 = "P14, DX7"
20 = "VSS"
21 = "P13, DX8"
22 = "P12, DX9"
23 = "P11, DX10"
24 = "P10, DX11"
25 = "P26, EMA0/#C0"
26 = "P25, EMA1/#C1"
27 = "P24, EMA2"
28 = "P44, STRTUP"
29 = "P50, #CPREQ"
30 = "P51, #INTREQ"
31 = "P46, #INTGNT"
32 = "P34, #DATAF"
33 = "P42, #LXPAR"
34 = "P40, #LXMAR"
35 = "P41, #LXDAR"
36 = "P33, #IOCLR"
37 = "P43, #MEMSEL"
38 = "P30, #WRITE"
39 = "P31, #READ"
40 = "VCC"
