# Z80280VSC PLCC definition
# https://github.com/tgtakaoka/dip
# OPT is pulled up by 10k (Z-BUS); solder jumper JP1 grounds it (Z80 Bus)
name = "Z280"
title = "Z80280VSC"
plcc = 68
pin1 = "top-center"
 1 = "GND"
 2 = "P25, AD13"
 3 = "P26, AD14"
 4 = "P27, AD15"
 5 = "P30, A16"
 6 = "P31, A17"
 7 = "P37, A23"
 8 = "P32, A18"
 9 = "P33, A19"
10 = "P55, B/#W,   #HALT"
11 = ",    #DMASTB0"
12 = "P54, R/#W,   #WR"
13 = ",    #DMASTB1"
14 = "P40, ST0,    #RFSH"
15 = "P41, ST1,    #IORQ"
16 = ",    #OE"
17 = ",    #IE"
18 = "VCC, +5V"
19 = "VCC, +5V"
20 = ",    CTIO1"
21 = "P42, ST2,    #M1"
22 = "P43, ST3,    #MREQ"
23 = ",    CTIO2"
24 = "P45, #DS,    #RD"
25 = ",    CTIN2"
26 = "VCC, #INTC"
27 = "P46, #AS"
28 = "VCC, #BUSREQ"
29 = "P52, #WAIT"
30 = ",    #GREQ,  CTIO0"
31 = ",    #BUSACK"
32 = ",    #GACK,  CTIN0"
33 = "VCC, #PAUSE"
34 = "VCC, OPT"
35 = "GND"
36 = "VCC, #INTB"
37 = "P50, #INTA,  #EOP"
38 = "P53, #RESET"
39 = "P51, #NMI"
40 = "P10, AD0"
41 = ",    CTIN1"
42 = "P11, AD1"
43 = "P12, AD2"
44 = "P13, AD3"
45 = "P34, A20"
46 = ",    TxD"
47 = "P44, CLK"
48 = ",    RxD"
49 = ",    XTALO"
50 = "P47, XTALI"
51 = "GND"
52 = ",    NC"
53 = "GND"
54 = "P14, AD4"
55 = "VCC, #RDY0"
56 = "VCC, #RDY1"
57 = "P15, AD5"
58 = "GND, #RDY3"
59 = "P35, A21"
60 = "P16, AD6"
61 = "P17, AD7"
62 = "P20, AD8"
63 = "GND, #RDY2"
64 = "P21, AD9"
65 = "P22, AD10"
66 = "P36, A22"
67 = "P23, AD11"
68 = "P24, AD12"
