#!/usr/bin/gawk -f
# -*- mode: awk; -*-
# Generates the tables of inst_f3850.cpp; from debugger/f3850:
#
#   gawk -f inst_f3850.awk f3850.txt \
#       | clang-format --assume-filename=inst_f3850.cpp
#
# and replace the tables after the "// Generated by:" line in the .cpp.
# -v MODE=pretty prints the input tables back aligned instead.

BEGIN {
    if (MODE == "")
        MODE = "table";
    if (MODE != "table" && MODE != "pretty") {
        print "MODE must be table or pretty" > "/dev/stderr";
        exit 1;
    }
    PRETTY_PRINT = MODE == "pretty";
    GENERATE_TABLE = MODE == "table";
    GENERATED_BY = generated_by("inst_f3850.awk");
}

# The command that made the tables, wrapped to 80 columns so clang-format
# keeps it.
function generated_by(script,  i, cmd, line, word) {
    cmd = "";
    line = "// Generated by: gawk -f " script;
    for (i = 1; i <= ARGC; i++) {
        word = (i < ARGC) ? ARGV[i] : "| clang-format";
        if (length(line) + 1 + length(word) > 78) {
            cmd = cmd line "\n";
            line = "//     " word;
        } else {
            line = line " " word;
        }
    }
    return cmd line;
}

function pretty_print(opc, nem, opr, len, clk) {
    if (PRETTY_PRINT == 0)
        return;
    printf("%-2s  %-4s  %-5s  %s  %s\n", opc, nem, opr, len, clk);
}

function generate_TABLE(op, nem, opr, len, clk) {
    if (GENERATE_TABLE == 0)
        return;
    printf("        E(%s, %d),  // %s: %-4s %s\n", len, clk,
               op, nem, opr);
}

BEGIN {
    pretty_print("op", "nemo", "opr",   "#", "~");
    pretty_print("--", "----", "-----", "-", "-");
    if (GENERATE_TABLE) {
        printf("%s\n", GENERATED_BY);
        printf("constexpr uint8_t INST_TABLE[] = {\n");
    }
}
END {
    if (GENERATE_TABLE)
        printf("};\n");
}

$1 !~ /[0-9A-F][0-9A-F]/ { next; }
$1 ~ /[0-9A-F][0-9A-F]/ {
    opc = $1;
    nem = $2;
    opr = $3;
    len = $4;
    clk = $5;

    pretty_print(opc, nem, opr, len, clk);
    generate_TABLE(opc, nem, opr, len, clk);
}
