#!/usr/bin/gawk -f
# -*- mode: awk; -*-
# Generates the tables of inst_i8051.cpp; from debugger/i8051:
#
#   gawk -f inst_i8051.awk i8051.txt \
#       | clang-format --assume-filename=inst_i8051.cpp
#
# and replace the tables after the "// Generated by:" line in the .cpp.
# -v MODE=pretty prints the input tables back aligned instead.

BEGIN {
    if (MODE == "")
        MODE = "table";
    if (MODE != "table" && MODE != "pretty") {
        print "MODE must be table or pretty" > "/dev/stderr";
        exit 1;
    }
    PRETTY_PRINT = MODE == "pretty";
    GENERATE_TABLE = MODE == "table";
    GENERATED_BY = generated_by("inst_i8051.awk");
}

# The command that made the tables, wrapped to 80 columns so clang-format
# keeps it.
function generated_by(script,  i, cmd, line, word) {
    cmd = "";
    line = "// Generated by: gawk -f " script;
    for (i = 1; i <= ARGC; i++) {
        word = (i < ARGC) ? ARGV[i] : "| clang-format";
        if (length(line) + 1 + length(word) > 78) {
            cmd = cmd line "\n";
            line = "//     " word;
        } else {
            line = line " " word;
        }
    }
    return cmd line;
}

function pretty_print(opc, mne, opr, len, bus) {
    if (PRETTY_PRINT == 0)
        return;
    printf("%-2s  %-5s  %-10s  %s  %s\n", opc, mne, opr, len, bus);
}

function generate_TABLE(opc, mne, opr, len, bus) {
    if (GENERATE_TABLE == 0)
        return;
    if (mne == "-") {
        printf("        0,          // %s:\n", opc);
    } else {
        printf("        E(%d, %d),  // %s: %-5s %s\n", len, bus, opc, mne, opr);
    }
}

BEGIN {
    pretty_print("op", "mnemo", "operand   ", "#", "~");
    pretty_print("--", "-----", "----------", "-", "-");
    if (GENERATE_TABLE) {
        printf("%s\n", GENERATED_BY);
        printf("constexpr uint8_t INST_TABLE[] = {\n");
    }
}

END {
    if (GENERATE_TABLE)
        printf("};\n");
}

$1 !~ /[0-9A-F][0-9A-F]/ { next; }
$1 ~ /[0-9A-F][0-9A-F]/ {
    opc = $1;
    mne = $2;
    opr = $3;
    len = $4;
    bus = $5;

    pretty_print(opc, mne, opr, len, bus);
    generate_TABLE(opc, mne, opr, len, bus);
}
