# TMS370Cx5xFNA PLCC definition
# https://github.com/tgtakaoka/dip
name = "TMS370"
title = "TMS370Cx5xFNA"
plcc = 68
pin1 = "top-center"
 1 = "P24, ADDR4,  B4"
 2 = "P25, ADDR5,  B5"
 3 = "P26, ADDR6,  B6"
 4 = "P27, ADDR7,  B7"
 5 = "P30, ADDR8,  C0"
 6 = "VCC, MC"
 7 = "P31, ADDR9,  C1"
 8 = "P32, ADDR10, C2"
 9 = "GND, VSS"
10 = "P33, ADDR11, C3"
11 = "P34, ADDR12, C4"
12 = "P35, ADDR13, C5"
13 = "P36, ADDR14, C6"
14 = "P37, ADDR15, C7"
15 = "VCC"
16 = "GND, VSS"
17 = "P10, DATA0,  A0"
18 = "P11, DATA1,  A1"
19 = "P12, DATA2,  A2"
20 = "P13, DATA3,  A3"
21 = "P14, DATA4,  A4"
22 = "P15, DATA5,  A5"
23 = "P16, DATA6,  A6"
24 = "P17, DATA7,  A7"
25 = ",    T2AEVT"
26 = ",    T2AIC2, PWM"
27 = ",    T2AIC1, CR"
28 = ",    SCICLK"
29 = "P45, SCIRXD"
30 = "P44, SCITXD"
31 = "P46, CLKIN,  XTAL2"
32 = "Cap, XTAL1"
33 = "VCC"
34 = "VCC"
35 = "GND, VSS"
36 = ",    AN0"
37 = ",    AN1"
38 = ",    AN2"
39 = ",    AN3"
40 = ",    AN4"
41 = ",    AN5"
42 = ",    AN6"
43 = ",    AN7"
44 = ",    T1EVT"
45 = ",    T1PWM"
46 = ",    T1IC,   CR"
47 = ",    SPICLK"
48 = ",    SPISIMO"
49 = ",    SPISOMI"
50 = "P52, INT3"
51 = "P51, INT2"
52 = "P50, INT1"
53 = "P53, #RESET"
54 = "P54, #WAIT,  D7, #CSE1"
55 = "P40, #EDS,   D6, #CSH1"
56 = ",    D5,     #CSPF"
57 = "P41, R/#W,   D4"
58 = "P47, SYSCLK, D3"
59 = ",    D2,     #CSH2"
60 = ",    D1,     #CSH3"
61 = "VCC"
62 = "GND, VSS"
63 = "VCC"
64 = "P42, #OCF,   D0, #CSE2"
65 = "P20, ADDR0,  B0"
66 = "P21, ADDR1,  B1"
67 = "P22, ADDR2,  B2"
68 = "P23, ADDR3,  B3"
