#!/usr/bin/gawk -f
# -*- mode: awk; -*-
# Generates the tables of inst_z88.cpp; from debugger/z8:
#
#   gawk -f inst_z88.awk z88.txt \
#       | clang-format --assume-filename=inst_z88.cpp
#
# and replace the tables after the "// Generated by:" line in the .cpp.
# -v MODE=pretty prints the input tables back aligned instead.

BEGIN {
    if (MODE == "")
        MODE = "table";
    if (MODE != "table" && MODE != "pretty") {
        print "MODE must be table or pretty" > "/dev/stderr";
        exit 1;
    }
    PRETTY_PRINT = MODE == "pretty";
    GENERATE_TABLE = MODE == "table";
    GENERATED_BY = generated_by("inst_z88.awk");
}

# The command that made the tables, wrapped to 80 columns so clang-format
# keeps it.
function generated_by(script,  i, cmd, line, word) {
    cmd = "";
    line = "// Generated by: gawk -f " script;
    for (i = 1; i <= ARGC; i++) {
        word = (i < ARGC) ? ARGV[i] : "| clang-format";
        if (length(line) + 1 + length(word) > 78) {
            cmd = cmd line "\n";
            line = "//     " word;
        } else {
            line = line " " word;
        }
    }
    return cmd line;
}

function print_number(n, len, num, rem) {
    len = match(n, /^[0-9]+/);
    if (n == "-") {
        printf(" -    ");
    } else if (len == 0) {
        printf("%-6s", n);
    } else if (length(n) == RLENGTH) {
        printf("%2d    ", n);
    } else {
        num = substr(n, RSTART, RLENGTH);
        rem = length(n) - RLENGTH;
        printf("%2d%s", num, substr(n, RLENGTH+1));
        for (num = rem; num <= 3; ++num)
            printf(" ");
    }
}

function pretty_print(opc, mne, opr, clk, len, ext, stk, seq) {
    if (PRETTY_PRINT == 0)
        return;
    printf("%-2s  %-6s  %-8s  ", opc, mne, opr);
    print_number(clk);
    printf("  %s  %2s  %2s  %s\n", len, ext, stk, seq);
}

function generate_TABLE(op, mne, opr, clk, len, ext, stk) {
    if (GENERATE_TABLE == 0)
        return;
    if (len == "-") {
        printf("        0,              // %2s:\n", opc);
    } else {
        printf("        E(%d, %d, %d),  // %2s: %-6s %s\n", len, ext, stk, opc, mne, opr);
    }
}

function inst_len(seq,  len, tmp, i, c) {
    len = 0;
    if (seq != "-") {
        patsplit(seq, tmp, "[0-9]+");
        for (i in tmp) {
            c = tmp[i];
            if (c >= len)
                len = c;
        }
    }
    return len;
}

BEGIN {
    pretty_print("op", "mnemo", "operand", "clock", "#", "bus", "stk", "sequence");
    pretty_print("--", "-----", "-------", "-----", "-", "---", "---", "--------");
    if (GENERATE_TABLE) {
        printf("%s\n", GENERATED_BY);
        printf("constexpr uint8_t INST_TABLE[] = {\n");
    }
}
END {
    if (GENERATE_TABLE)
        printf("};\n");
}

$1 !~ /[0-9A-F][0-9A-F]/ { next; }
$1 ~ /[0-9A-F][0-9A-F]/ {
    opc = $1;
    mne = $2;
    opr = $3;
    clk = $4;
    len = $5;
    ext = $6;
    stk = $7;
    seq = $8;

    if (len != inst_len(seq)) {
        printf("@@ instruction length (#) mismatches with sequence\n");
        print $0;
        exit;
    }

    pretty_print(opc, mne, opr, clk, len, ext, stk, seq);
    generate_TABLE(opc, mne, opr, clk, len, ext, stk);
}
