# NSC800N DIP definition
# https://github.com/tgtakaoka/dip
name = "NSC800N"
dip = 40
width = 600
 1 = "P20, A8"
 2 = "P21, A9"
 3 = "P22, A10"
 4 = "P23, A11"
 5 = "P24, A12"
 6 = "P25, A13"
 7 = "P26, A14"
 8 = "P27, A15"
 9 = "P47, CLK"
10 = ",    XOUT"
11 = "P50, XIN"
12 = "P10, AD0"
13 = "P11, AD1"
14 = "P12, AD2"
15 = "P13, AD3"
16 = "P14, AD4"
17 = "P15, AD5"
18 = "P16, AD6"
19 = "P17, AD7"
20 = "GND"
21 = "P35, #NMI"
22 = "P32, #RSTA"
23 = "P31, #RSTB"
24 = "P30, #RSTC"
25 = "P34, #INTR"
26 = "P46, #INTA"
27 = "P41, S1"
28 = "P45, #RFSH"
29 = "P40, S0"
30 = "P54, ALE"
31 = "P43, #WR"
32 = "P42, #RD"
33 = "P53, #RESETIN"
34 = "P55, IO/#M"
35 = "P36, #BACK"
36 = "P37, #BREQ"
37 = "P51, RESETOUT"
38 = "P52, #WAIT"
39 = "P44, #PS"
40 = "VCC"
