#!/usr/bin/gawk -f
# -*- mode: awk; -*-
# Generates the tables of inst_mb8861.cpp; from debugger/mc6800:
#
#   gawk -f inst_mb8861.awk mb8861.txt \
#       | clang-format --assume-filename=inst_mb8861.cpp
#
# and replace the tables after the "// Generated by:" line in the .cpp.
# -v MODE=pretty prints the input tables back aligned instead.

# 1: instruction code (next=&1)
# 2: instruction operands (disp, high(addr), ++next)
# 3: instruction operands (low(addr), ++next)
# R: read 1 byte (high(addr))
# r: read 1 byte at address R+1 or r+1 (low(addr))
# W: write 1 byte, equals to R if exists or w-1
# w: write 1 byte at address W+1
# A: read 1 byte at address |addr|
# a: read 1 byte at A+1
# D: read 1 byte from direct page (00|disp|)
# d: read 1 byte at address (D+1)
# B: write 1 byte at address addr
# b: write 1 byte at B+1
# E: write 1 byte to direct page (00xx), equals to D if exists
# e: write 1 byte at address E+1
# N: next instruction read from |next|
# J: next instruction read from |addr|
# j: next instruction read from |next| or |next|+disp
# i: next instruction read from unknown
# V: read 1 byte from address FFF8-FFFE (high(addr))
# v: read 1 byte from address V+1 (low(addr))
# X: any valid read
# x: irrelevant read access to $FFFF
# n: non VMA access
#
# Interrupt sequence
# 1:X:w:W:W:W:W:W:W:n:V:v:J

BEGIN {
    if (MODE == "")
        MODE = "table";
    if (MODE != "table" && MODE != "pretty") {
        print "MODE must be table or pretty" > "/dev/stderr";
        exit 1;
    }
    PRETTY_PRINT = MODE == "pretty";
    GENERATE_TABLE = MODE == "table";
    GENERATED_BY = generated_by("inst_mb8861.awk");
}

# The command that made the tables, wrapped to 80 columns so clang-format
# keeps it.
function generated_by(script,  i, cmd, line, word) {
    cmd = "";
    line = "// Generated by: gawk -f " script;
    for (i = 1; i <= ARGC; i++) {
        word = (i < ARGC) ? ARGV[i] : "| clang-format";
        if (length(line) + 1 + length(word) > 78) {
            cmd = cmd line "\n";
            line = "//     " word;
        } else {
            line = line " " word;
        }
    }
    return cmd line;
}

# Read the inputs twice: the first pass collects CYCLES in first-seen order,
# the second generates the tables.
BEGIN {
    if (GENERATE_TABLE) {
        NINPUTS = ARGC - 1;
        for (i = 1; i <= NINPUTS; i++)
            ARGV[ARGC++] = ARGV[i];
        COLLECTING = 1;
        GENERATE_TABLE = 0;
        GENERATE_CYCLES = 1;
    }
}

FNR == 1 && COLLECTING && ++NOPENED > NINPUTS {
    COLLECTING = 0;
    GENERATE_CYCLES = 0;
    GENERATE_TABLE = 1;
    start_TABLE();
}

function pretty_print(opc, nem, opr, clk, len, seq) {
    if (PRETTY_PRINT == 0)
        return;
    printf("%-2s  %-4s  %-4s  %2s  %s  %s\n", opc, nem, opr, clk, len, seq);
}

function inst_len(seq,  len, tmp, i, c) {
    len = 0;
    if (seq != "-") {
        split(seq, tmp, ":");
        for (i in tmp) {
            c = tmp[i];
            if (c ~ /[123]/ && c >= len)
                len = c;
        }
    }
    return len;
}

function inst_len_cyc(cyc, len, tmp, i, c) {
    len = 0;
    split(cyc, tmp, "");
    for (i in tmp) {
        c = tmp[i];
        if (c ~ /[123]/ && c >= len)
            len = c;
    }
    return len;
}

function clock(seq,  clk, tmp) {
    clk = 0;
    if (seq != "-")
        clk = split(seq, tmp, ":") - 1;
    return clk;
}


function CYCLES_index(cyc, i) {
    for (i in CYCLES) {
        if (CYCLES[i] == cyc)
            return i;
    }
    return 0;
}

function add_CYCLES(cyc, n) {
    n = length(CYCLES);
    CYCLES[++n] = cyc;
}

function append_CYCLES(seq, cyc) {
    if (seq != "-")  {
        cyc = seq;
        gsub(":", "", cyc);
        if (CYCLES_index(cyc) == 0) {
            add_CYCLES(cyc);
            return 1;
        }
    }
    return 0;
}

function generate_CYCLES(seq) {
    if (GENERATE_CYCLES == 1)
        append_CYCLES(seq);
}

function generate_TABLE() {
    if (GENERATE_TABLE == 0)
        return;
    printf("%s\n", GENERATED_BY);
    printf("constexpr const char *const SEQUENCES[/*seq*/] = {\n");
    printf("        \"%s\",  // %2d\n", "", 0);
    for (c = 1; c <= length(CYCLES); c++) {
        cyc = CYCLES[c];
        printf("        \"%s\",  // %2d\n", cyc, c);
    }
    printf("};\n\n");

    # printf("constexpr uint8_t INST_LENS[] = {\n");
    # printf("        %d, // %2d: %s\n", 0, 0, "-");
    # for (c = 1; c <= length(CYCLES); c++) {
    #     cyc = CYCLES[c];
    #     printf("        %d, // %2d: %s\n", inst_len_cyc(cyc), c, cyc);
    # }
    # printf("};\n\n");

    # printf("constexpr uint8_t CLOCKS[] = {\n");
    # printf("        %d, // %2d: %s\n", 0, 0, "-");
    # for (c = 1; c <= length(CYCLES); c++) {
    #     cyc = CYCLES[c];
    #     printf("        %d, // %2d: %s\n", length(cyc), c, cyc);
    # }
    # printf("};\n\n");
}

function generate_ENTRY(opc, nem, opr, clk, len, seq, cyc) {
    if (GENERATE_TABLE == 0)
        return;
    cyc = seq;
    gsub(":", "", cyc);
    printf("        %d,   // %s: %-4s %-4s  %-2s:%s  %s\n",
           CYCLES_index(cyc), opc, nem, opr, clk, len, seq);
}

BEGIN {
    pretty_print("op", "nemo", "oper", " ~", "#", "sequence");
    pretty_print("--", "----", "----", "--", "-", "--------");

}

function start_TABLE() {
    generate_TABLE();
    printf("constexpr uint8_t INST_TABLE[] = {\n");
}
END {
    if (GENERATE_TABLE)
        printf("};\n");
}

$1 !~ /[0-9A-F][0-9A-F]/ { next; }
$1 ~ /[0-9A-F][0-9A-F]/ {
    opc = $1;
    nem = $2;
    opr = $3;
    clk = $4;
    len = $5;
    seq = $6;

    if (inst_len(seq) != len) {
        printf("@@ instruction length (#) mismatches with sequence\n");
        print $0;
        exit;
    }
    if (clock(seq) != clk) {
        printf("@@ instruction clock (~) mismatches with sequence\n");
        print $0;
        exit;
    }

    pretty_print(opc, nem, opr, clk, len, seq);
    generate_CYCLES(seq);
    generate_ENTRY(opc, nem, opr, clk, len, seq);
}
