#include "inst_hd6301.h"

namespace debugger {
namespace hd6301 {

namespace {

// The interrupted opcode first, or fetched ahead by the one before.
constexpr const char INTERRUPT[] = "XXxwWWWWWWVrP@1XxwWWWWWWVrP";

// Generated by: gawk -f inst_hd6301.awk hd6301.txt | clang-format
constexpr const char *const SEQUENCES[/*seq*/] = {
        "",               //  0
        "1N",             //  1
        "1Nx",            //  2
        "1nxxN",          //  3
        "12xJ@12xN",      //  4
        "1NxR",           //  5
        "1nxWN",          //  6
        "1NxRr",          //  7
        "1nxRrP",         //  8
        "1nxRrrrrrrP",    //  9
        "1nxwWN",         // 10
        "1Nxxxxxx",       // 11
        "1NxwWWWWWW",     // 12
        "1nxwWWWWWWVrP",  // 13
        "12xRxWN",        // 14
        "122xRxWN",       // 15
        "122xRN",         // 16
        "12xRN",          // 17
        "12x?",           // 18
        "12xRWN",         // 19
        "122AxBN",        // 20
        "122AN",          // 21
        "122J",           // 22
        "122ABN",         // 23
        "12N",            // 24
        "122N",           // 25
        "12xwWJ@12xwWN",  // 26
        "12AN",           // 27
        "12ArN",          // 28
        "12BN",           // 29
        "12xwW?",         // 30
        "12BwN",          // 31
        "12xRrN",         // 32
        "12xWN",          // 33
        "12xWwN",         // 34
        "122ArN",         // 35
        "122BN",          // 36
        "122xwWJ",        // 37
        "122BwN",         // 38
};

constexpr uint8_t INST_TABLE[] = {
        0,   // 00: -    -     0 :0  -
        1,   // 01: NOP  -     1 :1  1N
        0,   // 02: -    -     0 :0  -
        0,   // 03: -    -     0 :0  -
        1,   // 04: LSRD -     1 :1  1N
        1,   // 05: ASLD -     1 :1  1N
        1,   // 06: TAP  -     1 :1  1N
        1,   // 07: TPA  -     1 :1  1N
        1,   // 08: INX  -     1 :1  1N
        1,   // 09: DEX  -     1 :1  1N
        1,   // 0A: CLV  -     1 :1  1N
        1,   // 0B: SEV  -     1 :1  1N
        1,   // 0C: CLC  -     1 :1  1N
        1,   // 0D: SEC  -     1 :1  1N
        1,   // 0E: CLI  -     1 :1  1N
        1,   // 0F: SEI  -     1 :1  1N
        1,   // 10: SBA  -     1 :1  1N
        1,   // 11: CBA  -     1 :1  1N
        0,   // 12: -    -     0 :0  -
        0,   // 13: -    -     0 :0  -
        0,   // 14: -    -     0 :0  -
        0,   // 15: -    -     0 :0  -
        1,   // 16: TAB  -     1 :1  1N
        1,   // 17: TBA  -     1 :1  1N
        2,   // 18: XGDX -     2 :1  1Nx
        2,   // 19: DAA  -     2 :1  1Nx
        3,   // 1A: SLP  -     4 :1  1nxxN
        1,   // 1B: ABA  -     1 :1  1N
        0,   // 1C: -    -     0 :0  -
        0,   // 1D: -    -     0 :0  -
        0,   // 1E: -    -     0 :0  -
        0,   // 1F: -    -     0 :0  -
        4,   // 20: BRA  r8    3 :2  12xJ@12xN
        4,   // 21: BRN  r8    3 :2  12xJ@12xN
        4,   // 22: BHI  r8    3 :2  12xJ@12xN
        4,   // 23: BLS  r8    3 :2  12xJ@12xN
        4,   // 24: BCC  r8    3 :2  12xJ@12xN
        4,   // 25: BCS  r8    3 :2  12xJ@12xN
        4,   // 26: BNE  r8    3 :2  12xJ@12xN
        4,   // 27: BEQ  r8    3 :2  12xJ@12xN
        4,   // 28: BVC  r8    3 :2  12xJ@12xN
        4,   // 29: BVS  r8    3 :2  12xJ@12xN
        4,   // 2A: BPL  r8    3 :2  12xJ@12xN
        4,   // 2B: BMI  r8    3 :2  12xJ@12xN
        4,   // 2C: BGE  r8    3 :2  12xJ@12xN
        4,   // 2D: BLT  r8    3 :2  12xJ@12xN
        4,   // 2E: BGT  r8    3 :2  12xJ@12xN
        4,   // 2F: BLE  r8    3 :2  12xJ@12xN
        1,   // 30: TSX  -     1 :1  1N
        1,   // 31: INS  -     1 :1  1N
        5,   // 32: PULA -     3 :1  1NxR
        5,   // 33: PULB -     3 :1  1NxR
        1,   // 34: DES  -     1 :1  1N
        1,   // 35: TXS  -     1 :1  1N
        6,   // 36: PSHA -     4 :1  1nxWN
        6,   // 37: PSHB -     4 :1  1nxWN
        7,   // 38: PULX -     4 :1  1NxRr
        8,   // 39: RTS  -     5 :1  1nxRrP
        1,   // 3A: ABX  -     1 :1  1N
        9,   // 3B: RTI  -     10:1  1nxRrrrrrrP
        10,  // 3C: PSHX -     5 :1  1nxwWN
        11,  // 3D: MUL  -     7 :1  1Nxxxxxx
        12,  // 3E: WAI  -     9 :1  1NxwWWWWWW
        13,  // 3F: SWI  -     12:1  1nxwWWWWWWVrP
        1,   // 40: NEGA -     1 :1  1N
        0,   // 41: -    -     0 :0  -
        0,   // 42: -    -     0 :0  -
        1,   // 43: COMA -     1 :1  1N
        1,   // 44: LSRA -     1 :1  1N
        0,   // 45: -    -     0 :0  -
        1,   // 46: RORA -     1 :1  1N
        1,   // 47: ASRA -     1 :1  1N
        1,   // 48: ASLA -     1 :1  1N
        1,   // 49: ROLA -     1 :1  1N
        1,   // 4A: DECA -     1 :1  1N
        0,   // 4B: -    -     0 :0  -
        1,   // 4C: INCA -     1 :1  1N
        1,   // 4D: TSTA -     1 :1  1N
        0,   // 4E: -    -     0 :0  -
        1,   // 4F: CLRA -     1 :1  1N
        1,   // 50: NEGB -     1 :1  1N
        0,   // 51: -    -     0 :0  -
        0,   // 52: -    -     0 :0  -
        1,   // 53: COMB -     1 :1  1N
        1,   // 54: LSRB -     1 :1  1N
        0,   // 55: -    -     0 :0  -
        1,   // 56: RORB -     1 :1  1N
        1,   // 57: ASRB -     1 :1  1N
        1,   // 58: ASLB -     1 :1  1N
        1,   // 59: ROLB -     1 :1  1N
        1,   // 5A: DECB -     1 :1  1N
        0,   // 5B: -    -     0 :0  -
        1,   // 5C: INCB -     1 :1  1N
        1,   // 5D: TSTB -     1 :1  1N
        0,   // 5E: -    -     0 :0  -
        1,   // 5F: CLRB -     1 :1  1N
        14,  // 60: NEG  n8,X  6 :2  12xRxWN
        15,  // 61: AIM  #,n8,X  7 :3  122xRxWN
        15,  // 62: OIM  #,n8,X  7 :3  122xRxWN
        14,  // 63: COM  n8,X  6 :2  12xRxWN
        14,  // 64: LSR  n8,X  6 :2  12xRxWN
        15,  // 65: EIM  #,n8,X  7 :3  122xRxWN
        14,  // 66: ROR  n8,X  6 :2  12xRxWN
        14,  // 67: ASR  n8,X  6 :2  12xRxWN
        14,  // 68: ASL  n8,X  6 :2  12xRxWN
        14,  // 69: ROL  n8,X  6 :2  12xRxWN
        14,  // 6A: DEC  n8,X  6 :2  12xRxWN
        16,  // 6B: TIM  #,n8,X  5 :3  122xRN
        14,  // 6C: INC  n8,X  6 :2  12xRxWN
        17,  // 6D: TST  n8,X  4 :2  12xRN
        18,  // 6E: JMP  n8,X  3 :2  12x?
        19,  // 6F: CLR  n8,X  5 :2  12xRWN
        20,  // 70: NEG  a16   6 :3  122AxBN
        20,  // 71: AIM  #,d8  6 :3  122AxBN
        20,  // 72: OIM  #,d8  6 :3  122AxBN
        20,  // 73: COM  a16   6 :3  122AxBN
        20,  // 74: LSR  a16   6 :3  122AxBN
        20,  // 75: EIM  #,d8  6 :3  122AxBN
        20,  // 76: ROR  a16   6 :3  122AxBN
        20,  // 77: ASR  a16   6 :3  122AxBN
        20,  // 78: ASL  a16   6 :3  122AxBN
        20,  // 79: ROL  a16   6 :3  122AxBN
        20,  // 7A: DEC  a16   6 :3  122AxBN
        21,  // 7B: TIM  #,d8  4 :3  122AN
        20,  // 7C: INC  a16   6 :3  122AxBN
        21,  // 7D: TST  a16   4 :3  122AN
        22,  // 7E: JMP  a16   3 :3  122J
        23,  // 7F: CLR  a16   5 :3  122ABN
        24,  // 80: SUBA #n8   2 :2  12N
        24,  // 81: CMPA #n8   2 :2  12N
        24,  // 82: SBCA #n8   2 :2  12N
        25,  // 83: SUBD #n16  3 :3  122N
        24,  // 84: ANDA #n8   2 :2  12N
        24,  // 85: BITA #n8   2 :2  12N
        24,  // 86: LDAA #n8   2 :2  12N
        0,   // 87: -    -     0 :0  -
        24,  // 88: EORA #n8   2 :2  12N
        24,  // 89: ADCA #n8   2 :2  12N
        24,  // 8A: ORAA #n8   2 :2  12N
        24,  // 8B: ADDA #n8   2 :2  12N
        25,  // 8C: CPX  #n16  3 :3  122N
        26,  // 8D: BSR  r8    5 :2  12xwWJ@12xwWN
        25,  // 8E: LDS  #n16  3 :3  122N
        0,   // 8F: -    -     0 :0  -
        27,  // 90: SUBA d8    3 :2  12AN
        27,  // 91: CMPA d8    3 :2  12AN
        27,  // 92: SBCA d8    3 :2  12AN
        28,  // 93: SUBD d8    4 :2  12ArN
        27,  // 94: ANDA d8    3 :2  12AN
        27,  // 95: BITA d8    3 :2  12AN
        27,  // 96: LDAA d8    3 :2  12AN
        29,  // 97: STAA d8    3 :2  12BN
        27,  // 98: EORA d8    3 :2  12AN
        27,  // 99: ADCA d8    3 :2  12AN
        27,  // 9A: ORAA d8    3 :2  12AN
        27,  // 9B: ADDA d8    3 :2  12AN
        28,  // 9C: CPX  d8    4 :2  12ArN
        30,  // 9D: JSR  d8    5 :2  12xwW?
        28,  // 9E: LDS  d8    4 :2  12ArN
        31,  // 9F: STS  d8    4 :2  12BwN
        17,  // A0: SUBA n8,X  4 :2  12xRN
        17,  // A1: CMPA n8,X  4 :2  12xRN
        17,  // A2: SBCA n8,X  4 :2  12xRN
        32,  // A3: SUBD n8,X  5 :2  12xRrN
        17,  // A4: ANDA n8,X  4 :2  12xRN
        17,  // A5: BITA n8,X  4 :2  12xRN
        17,  // A6: LDAA n8,X  4 :2  12xRN
        33,  // A7: STAA n8,X  4 :2  12xWN
        17,  // A8: EORA n8,X  4 :2  12xRN
        17,  // A9: ADCA n8,X  4 :2  12xRN
        17,  // AA: ORAA n8,X  4 :2  12xRN
        17,  // AB: ADDA n8,X  4 :2  12xRN
        32,  // AC: CPX  n8,X  5 :2  12xRrN
        30,  // AD: JSR  n8,X  5 :2  12xwW?
        32,  // AE: LDS  n8,X  5 :2  12xRrN
        34,  // AF: STS  n8,X  5 :2  12xWwN
        21,  // B0: SUBA a16   4 :3  122AN
        21,  // B1: CMPA a16   4 :3  122AN
        21,  // B2: SBCA a16   4 :3  122AN
        35,  // B3: SUBD a16   5 :3  122ArN
        21,  // B4: ANDA a16   4 :3  122AN
        21,  // B5: BITA a16   4 :3  122AN
        21,  // B6: LDAA a16   4 :3  122AN
        36,  // B7: STAA a16   4 :3  122BN
        21,  // B8: EORA a16   4 :3  122AN
        21,  // B9: ADCA a16   4 :3  122AN
        21,  // BA: ORAA a16   4 :3  122AN
        21,  // BB: ADDA a16   4 :3  122AN
        35,  // BC: CPX  a16   5 :3  122ArN
        37,  // BD: JSR  a16   6 :3  122xwWJ
        35,  // BE: LDS  a16   5 :3  122ArN
        38,  // BF: STS  a16   5 :3  122BwN
        24,  // C0: SUBB #n8   2 :2  12N
        24,  // C1: CMPB #n8   2 :2  12N
        24,  // C2: SBCB #n8   2 :2  12N
        25,  // C3: ADDD #n16  3 :3  122N
        24,  // C4: ANDB #n8   2 :2  12N
        24,  // C5: BITB #n8   2 :2  12N
        24,  // C6: LDAB #n8   2 :2  12N
        0,   // C7: -    -     0 :0  -
        24,  // C8: EORB #n8   2 :2  12N
        24,  // C9: ADCB #n8   2 :2  12N
        24,  // CA: ORAB #n8   2 :2  12N
        24,  // CB: ADDB #n8   2 :2  12N
        25,  // CC: LDD  #n16  3 :3  122N
        0,   // CD: -    -     0 :0  -
        25,  // CE: LDX  #n16  3 :3  122N
        0,   // CF: -    -     0 :0  -
        27,  // D0: SUBB d8    3 :2  12AN
        27,  // D1: CMPB d8    3 :2  12AN
        27,  // D2: SBCB d8    3 :2  12AN
        28,  // D3: ADDD d8    4 :2  12ArN
        27,  // D4: ANDB d8    3 :2  12AN
        27,  // D5: BITB d8    3 :2  12AN
        27,  // D6: LDAB d8    3 :2  12AN
        29,  // D7: STAB d8    3 :2  12BN
        27,  // D8: EORB d8    3 :2  12AN
        27,  // D9: ADCB d8    3 :2  12AN
        27,  // DA: ORAB d8    3 :2  12AN
        27,  // DB: ADDB d8    3 :2  12AN
        28,  // DC: LDD  d8    4 :2  12ArN
        31,  // DD: STD  d8    4 :2  12BwN
        28,  // DE: LDX  d8    4 :2  12ArN
        31,  // DF: STX  d8    4 :2  12BwN
        17,  // E0: SUBB n8,X  4 :2  12xRN
        17,  // E1: CMPB n8,X  4 :2  12xRN
        17,  // E2: SBCB n8,X  4 :2  12xRN
        32,  // E3: ADDD n8,X  5 :2  12xRrN
        17,  // E4: ANDB n8,X  4 :2  12xRN
        17,  // E5: BITB n8,X  4 :2  12xRN
        17,  // E6: LDAB n8,X  4 :2  12xRN
        33,  // E7: STAB n8,X  4 :2  12xWN
        17,  // E8: EORB n8,X  4 :2  12xRN
        17,  // E9: ADCB n8,X  4 :2  12xRN
        17,  // EA: ORAB n8,X  4 :2  12xRN
        17,  // EB: ADDB n8,X  4 :2  12xRN
        32,  // EC: LDD  n8,X  5 :2  12xRrN
        34,  // ED: STD  n8,X  5 :2  12xWwN
        32,  // EE: LDX  n8,X  5 :2  12xRrN
        34,  // EF: STX  n8,X  5 :2  12xWwN
        21,  // F0: SUBB a16   4 :3  122AN
        21,  // F1: CMPB a16   4 :3  122AN
        21,  // F2: SBCB a16   4 :3  122AN
        35,  // F3: ADDD a16   5 :3  122ArN
        21,  // F4: ANDB a16   4 :3  122AN
        21,  // F5: BITB a16   4 :3  122AN
        21,  // F6: LDAB a16   4 :3  122AN
        36,  // F7: STAB a16   4 :3  122BN
        21,  // F8: EORB a16   4 :3  122AN
        21,  // F9: ADCB a16   4 :3  122AN
        21,  // FA: ORAB a16   4 :3  122AN
        21,  // FB: ADDB a16   4 :3  122AN
        35,  // FC: LDD  a16   5 :3  122ArN
        38,  // FD: STD  a16   5 :3  122BwN
        35,  // FE: LDX  a16   5 :3  122ArN
        38,  // FF: STX  a16   5 :3  122BwN
};
}  // namespace

const char *InstHd6301::instSequence(uint8_t inst) const {
    return SEQUENCES[INST_TABLE[inst]];
}

const char *InstHd6301::intrSequence() const {
    return INTERRUPT;
}

}  // namespace hd6301
}  // namespace debugger

// Local Variables:
// mode: c++
// c-basic-offset: 4
// tab-width: 4
// End:
// vim: set ft=cpp et ts=4 sw=4:
