#include "inst_mb8861.h"

namespace debugger {
namespace mb8861 {

namespace {

constexpr const char INTERRUPT[] = "XXwWWWWWW-VrP";  // the interrupted opcode first

// Generated by: gawk -f inst_mb8861.awk mb8861.txt | clang-format
constexpr const char *const SEQUENCES[/*seq*/] = {
        "",                     //  0
        "1nN",                  //  1
        "1n--N",                //  2
        "12--J@12--N",          //  3
        "1n-RN",                //  4
        "1nW-N",                //  5
        "1n-RrP",               //  6
        "1n-RrrrrrrP",          //  7
        "1nwWWWWWWX",           //  8
        "1nwWWWWWW-VrP",        //  9
        "12--R-WN",             // 10
        "12--R--N",             // 11
        "12--?",                // 12
        "122A-BN",              // 13
        "122--R-WN",            // 14
        "122--R-N",             // 15
        "122A--N",              // 16
        "122J",                 // 17
        "12N",                  // 18
        "122N",                 // 19
        "12-wW---J@12-wW---N",  // 20
        "12AN",                 // 21
        "12-BN",                // 22
        "12ArN",                // 23
        "12-BwN",               // 24
        "12--RN",               // 25
        "12---WN",              // 26
        "12--RrN",              // 27
        "12-wW---?",            // 28
        "12---WwN",             // 29
        "122AN",                // 30
        "122-BN",               // 31
        "122ArN",               // 32
        "122AwW--XJ",           // 33
        "122-BwN",              // 34
        "12--N",                // 35
        "122Ar--N",             // 36
};

constexpr uint8_t INST_TABLE[] = {
        0,   // 00: -    -     0 :0  -
        1,   // 01: NOP  -     2 :1  1nN
        0,   // 02: -    -     0 :0  -
        0,   // 03: -    -     0 :0  -
        0,   // 04: -    -     0 :0  -
        0,   // 05: -    -     0 :0  -
        1,   // 06: TAP  -     2 :1  1nN
        1,   // 07: TPA  -     2 :1  1nN
        2,   // 08: INX  -     4 :1  1n--N
        2,   // 09: DEX  -     4 :1  1n--N
        1,   // 0A: CLV  -     2 :1  1nN
        1,   // 0B: SEV  -     2 :1  1nN
        1,   // 0C: CLC  -     2 :1  1nN
        1,   // 0D: SEC  -     2 :1  1nN
        1,   // 0E: CLI  -     2 :1  1nN
        1,   // 0F: SEI  -     2 :1  1nN
        1,   // 10: SBA  -     2 :1  1nN
        1,   // 11: CBA  -     2 :1  1nN
        0,   // 12: -    -     0 :0  -
        0,   // 13: -    -     0 :0  -
        0,   // 14: -    -     0 :0  -
        0,   // 15: -    -     0 :0  -
        1,   // 16: TAB  -     2 :1  1nN
        1,   // 17: TBA  -     2 :1  1nN
        0,   // 18: -    -     0 :0  -
        1,   // 19: DAA  -     2 :1  1nN
        0,   // 1A: -    -     0 :0  -
        1,   // 1B: ABA  -     2 :1  1nN
        0,   // 1C: -    -     0 :0  -
        0,   // 1D: -    -     0 :0  -
        0,   // 1E: -    -     0 :0  -
        0,   // 1F: -    -     0 :0  -
        3,   // 20: BRA  r8    4 :2  12--J@12--N
        0,   // 21: -    -     0 :0  -
        3,   // 22: BHI  r8    4 :2  12--J@12--N
        3,   // 23: BLS  r8    4 :2  12--J@12--N
        3,   // 24: BCC  r8    4 :2  12--J@12--N
        3,   // 25: BCS  r8    4 :2  12--J@12--N
        3,   // 26: BNE  r8    4 :2  12--J@12--N
        3,   // 27: BEQ  r8    4 :2  12--J@12--N
        3,   // 28: BVC  r8    4 :2  12--J@12--N
        3,   // 29: BVS  r8    4 :2  12--J@12--N
        3,   // 2A: BPL  r8    4 :2  12--J@12--N
        3,   // 2B: BMI  r8    4 :2  12--J@12--N
        3,   // 2C: BGE  r8    4 :2  12--J@12--N
        3,   // 2D: BLT  r8    4 :2  12--J@12--N
        3,   // 2E: BGT  r8    4 :2  12--J@12--N
        3,   // 2F: BLE  r8    4 :2  12--J@12--N
        2,   // 30: TSX  -     4 :1  1n--N
        2,   // 31: INS  -     4 :1  1n--N
        4,   // 32: PULA -     4 :1  1n-RN
        4,   // 33: PULB -     4 :1  1n-RN
        2,   // 34: DES  -     4 :1  1n--N
        2,   // 35: TXS  -     4 :1  1n--N
        5,   // 36: PSHA -     4 :1  1nW-N
        5,   // 37: PSHB -     4 :1  1nW-N
        0,   // 38: -    -     0 :0  -
        6,   // 39: RTS  -     5 :1  1n-RrP
        0,   // 3A: -    -     0 :0  -
        7,   // 3B: RTI  -     10:1  1n-RrrrrrrP
        0,   // 3C: -    -     0 :0  -
        0,   // 3D: -    -     0 :0  -
        8,   // 3E: WAI  -     9 :1  1nwWWWWWWX
        9,   // 3F: SWI  -     12:1  1nwWWWWWW-VrP
        1,   // 40: NEGA -     2 :1  1nN
        0,   // 41: -    -     0 :0  -
        0,   // 42: -    -     0 :0  -
        1,   // 43: COMA -     2 :1  1nN
        1,   // 44: LSRA -     2 :1  1nN
        0,   // 45: -    -     0 :0  -
        1,   // 46: RORA -     2 :1  1nN
        1,   // 47: ASRA -     2 :1  1nN
        1,   // 48: ASLA -     2 :1  1nN
        1,   // 49: ROLA -     2 :1  1nN
        1,   // 4A: DECA -     2 :1  1nN
        0,   // 4B: -    -     0 :0  -
        1,   // 4C: INCA -     2 :1  1nN
        1,   // 4D: TSTA -     2 :1  1nN
        0,   // 4E: -    -     0 :0  -
        1,   // 4F: CLRA -     2 :1  1nN
        1,   // 50: NEGB -     2 :1  1nN
        0,   // 51: -    -     0 :0  -
        0,   // 52: -    -     0 :0  -
        1,   // 53: COMB -     2 :1  1nN
        1,   // 54: LSRB -     2 :1  1nN
        0,   // 55: -    -     0 :0  -
        1,   // 56: RORB -     2 :1  1nN
        1,   // 57: ASRB -     2 :1  1nN
        1,   // 58: ASLB -     2 :1  1nN
        1,   // 59: ROLB -     2 :1  1nN
        1,   // 5A: DECB -     2 :1  1nN
        0,   // 5B: -    -     0 :0  -
        1,   // 5C: INCB -     2 :1  1nN
        1,   // 5D: TSTB -     2 :1  1nN
        0,   // 5E: -    -     0 :0  -
        1,   // 5F: CLRB -     2 :1  1nN
        10,  // 60: NEG  n8,X  7 :2  12--R-WN
        0,   // 61: -    -     0 :0  -
        0,   // 62: -    -     0 :0  -
        10,  // 63: COM  n8,X  7 :2  12--R-WN
        10,  // 64: LSR  n8,X  7 :2  12--R-WN
        0,   // 65: -    -     0 :0  -
        10,  // 66: ROR  n8,X  7 :2  12--R-WN
        10,  // 67: ASR  n8,X  7 :2  12--R-WN
        10,  // 68: ASL  n8,X  7 :2  12--R-WN
        10,  // 69: ROL  n8,X  7 :2  12--R-WN
        10,  // 6A: DEC  n8,X  7 :2  12--R-WN
        0,   // 6B: -    -     0 :0  -
        10,  // 6C: INC  n8,X  7 :2  12--R-WN
        11,  // 6D: TST  n8,X  7 :2  12--R--N
        12,  // 6E: JMP  n8,X  4 :2  12--?
        10,  // 6F: CLR  n8,X  7 :2  12--R-WN
        13,  // 70: NEG  a16   6 :3  122A-BN
        14,  // 71: NIM  #,n8,X  8 :3  122--R-WN
        14,  // 72: OIM  #,n8,X  8 :3  122--R-WN
        13,  // 73: COM  a16   6 :3  122A-BN
        13,  // 74: LSR  a16   6 :3  122A-BN
        14,  // 75: XIM  #,n8,X  8 :3  122--R-WN
        13,  // 76: ROR  a16   6 :3  122A-BN
        13,  // 77: ASR  a16   6 :3  122A-BN
        13,  // 78: ASL  a16   6 :3  122A-BN
        13,  // 79: ROL  a16   6 :3  122A-BN
        13,  // 7A: DEC  a16   6 :3  122A-BN
        15,  // 7B: TIM  #,n8,X  7 :3  122--R-N
        13,  // 7C: INC  a16   6 :3  122A-BN
        16,  // 7D: TST  a16   6 :3  122A--N
        17,  // 7E: JMP  a16   3 :3  122J
        13,  // 7F: CLR  a16   6 :3  122A-BN
        18,  // 80: SUBA #n8   2 :2  12N
        18,  // 81: CMPA #n8   2 :2  12N
        18,  // 82: SBCA #n8   2 :2  12N
        0,   // 83: -    -     0 :0  -
        18,  // 84: ANDA #n8   2 :2  12N
        18,  // 85: BITA #n8   2 :2  12N
        18,  // 86: LDAA #n8   2 :2  12N
        0,   // 87: -    -     0 :0  -
        18,  // 88: EORA #n8   2 :2  12N
        18,  // 89: ADCA #n8   2 :2  12N
        18,  // 8A: ORAA #n8   2 :2  12N
        18,  // 8B: ADDA #n8   2 :2  12N
        19,  // 8C: CPX  #n16  3 :3  122N
        20,  // 8D: BSR  r8    8 :2  12-wW---J@12-wW---N
        19,  // 8E: LDS  #n16  3 :3  122N
        0,   // 8F: -    -     0 :0  -
        21,  // 90: SUBA d8    3 :2  12AN
        21,  // 91: CMPA d8    3 :2  12AN
        21,  // 92: SBCA d8    3 :2  12AN
        0,   // 93: -    -     0 :0  -
        21,  // 94: ANDA d8    3 :2  12AN
        21,  // 95: BITA d8    3 :2  12AN
        21,  // 96: LDAA d8    3 :2  12AN
        22,  // 97: STAA d8    4 :2  12-BN
        21,  // 98: EORA d8    3 :2  12AN
        21,  // 99: ADCA d8    3 :2  12AN
        21,  // 9A: ORAA d8    3 :2  12AN
        21,  // 9B: ADDA d8    3 :2  12AN
        23,  // 9C: CPX  d8    4 :2  12ArN
        0,   // 9D: -    -     0 :0  -
        23,  // 9E: LDS  d8    4 :2  12ArN
        24,  // 9F: STS  d8    5 :2  12-BwN
        25,  // A0: SUBA n8,X  5 :2  12--RN
        25,  // A1: CMPA n8,X  5 :2  12--RN
        25,  // A2: SBCA n8,X  5 :2  12--RN
        0,   // A3: -    -     0 :0  -
        25,  // A4: ANDA n8,X  5 :2  12--RN
        25,  // A5: BITA n8,X  5 :2  12--RN
        25,  // A6: LDAA n8,X  5 :2  12--RN
        26,  // A7: STAA n8,X  6 :2  12---WN
        25,  // A8: EORA n8,X  5 :2  12--RN
        25,  // A9: ADCA n8,X  5 :2  12--RN
        25,  // AA: ORAA n8,X  5 :2  12--RN
        25,  // AB: ADDA n8,X  5 :2  12--RN
        27,  // AC: CPX  n8,X  6 :2  12--RrN
        28,  // AD: JSR  n8,X  8 :2  12-wW---?
        27,  // AE: LDS  n8,X  6 :2  12--RrN
        29,  // AF: STS  n8,X  7 :2  12---WwN
        30,  // B0: SUBA a16   4 :3  122AN
        30,  // B1: CMPA a16   4 :3  122AN
        30,  // B2: SBCA a16   4 :3  122AN
        0,   // B3: -    -     0 :0  -
        30,  // B4: ANDA a16   4 :3  122AN
        30,  // B5: BITA a16   4 :3  122AN
        30,  // B6: LDAA a16   4 :3  122AN
        31,  // B7: STAA a16   5 :3  122-BN
        30,  // B8: EORA a16   4 :3  122AN
        30,  // B9: ADCA a16   4 :3  122AN
        30,  // BA: ORAA a16   4 :3  122AN
        30,  // BB: ADDA a16   4 :3  122AN
        32,  // BC: CPX  a16   5 :3  122ArN
        33,  // BD: JSR  a16   9 :3  122AwW--XJ
        32,  // BE: LDS  a16   5 :3  122ArN
        34,  // BF: STS  a16   6 :3  122-BwN
        18,  // C0: SUBB #n8   2 :2  12N
        18,  // C1: CMPB #n8   2 :2  12N
        18,  // C2: SBCB #n8   2 :2  12N
        0,   // C3: -    -     0 :0  -
        18,  // C4: ANDB #n8   2 :2  12N
        18,  // C5: BITB #n8   2 :2  12N
        18,  // C6: LDAB #n8   2 :2  12N
        0,   // C7: -    -     0 :0  -
        18,  // C8: EORB #n8   2 :2  12N
        18,  // C9: ADCB #n8   2 :2  12N
        18,  // CA: ORAB #n8   2 :2  12N
        18,  // CB: ADDB #n8   2 :2  12N
        0,   // CC: -    -     0 :0  -
        0,   // CD: -    -     0 :0  -
        19,  // CE: LDX  #n16  3 :3  122N
        0,   // CF: -    -     0 :0  -
        21,  // D0: SUBB d8    3 :2  12AN
        21,  // D1: CMPB d8    3 :2  12AN
        21,  // D2: SBCB d8    3 :2  12AN
        0,   // D3: -    -     0 :0  -
        21,  // D4: ANDB d8    3 :2  12AN
        21,  // D5: BITB d8    3 :2  12AN
        21,  // D6: LDAB d8    3 :2  12AN
        22,  // D7: STAB d8    4 :2  12-BN
        21,  // D8: EORB d8    3 :2  12AN
        21,  // D9: ADCB d8    3 :2  12AN
        21,  // DA: ORAB d8    3 :2  12AN
        21,  // DB: ADDB d8    3 :2  12AN
        0,   // DC: -    -     0 :0  -
        0,   // DD: -    -     0 :0  -
        23,  // DE: LDX  d8    4 :2  12ArN
        24,  // DF: STX  d8    5 :2  12-BwN
        25,  // E0: SUBB n8,X  5 :2  12--RN
        25,  // E1: CMPB n8,X  5 :2  12--RN
        25,  // E2: SBCB n8,X  5 :2  12--RN
        0,   // E3: -    -     0 :0  -
        25,  // E4: ANDB n8,X  5 :2  12--RN
        25,  // E5: BITB n8,X  5 :2  12--RN
        25,  // E6: LDAB n8,X  5 :2  12--RN
        26,  // E7: STAB n8,X  6 :2  12---WN
        25,  // E8: EORB n8,X  5 :2  12--RN
        25,  // E9: ADCB n8,X  5 :2  12--RN
        25,  // EA: ORAB n8,X  5 :2  12--RN
        25,  // EB: ADDB n8,X  5 :2  12--RN
        35,  // EC: ADX  #n8   4 :2  12--N
        0,   // ED: -    -     0 :0  -
        27,  // EE: LDX  n8,X  6 :2  12--RrN
        29,  // EF: STX  n8,X  7 :2  12---WwN
        30,  // F0: SUBB a16   4 :3  122AN
        30,  // F1: CMPB a16   4 :3  122AN
        30,  // F2: SBCB a16   4 :3  122AN
        0,   // F3: -    -     0 :0  -
        30,  // F4: ANDB a16   4 :3  122AN
        30,  // F5: BITB a16   4 :3  122AN
        30,  // F6: LDAB a16   4 :3  122AN
        31,  // F7: STAB a16   5 :3  122-BN
        30,  // F8: EORB a16   4 :3  122AN
        30,  // F9: ADCB a16   4 :3  122AN
        30,  // FA: ORAB a16   4 :3  122AN
        30,  // FB: ADDB a16   4 :3  122AN
        36,  // FC: ADX  a16   7 :3  122Ar--N
        0,   // FD: -    -     0 :0  -
        32,  // FE: LDX  a16   5 :3  122ArN
        34,  // FF: STX  a16   6 :3  122-BwN
};
}  // namespace

const char *InstMb8861::instSequence(uint8_t inst) const {
    return SEQUENCES[INST_TABLE[inst]];
}

const char *InstMb8861::intrSequence() const {
    return INTERRUPT;
}

}  // namespace mb8861
}  // namespace debugger

// Local Variables:
// mode: c++
// c-basic-offset: 4
// tab-width: 4
// End:
// vim: set ft=cpp et ts=4 sw=4:
