#!/usr/bin/gawk -f
# -*- mode: awk; -*-
# Generates the tables of inst_hd6301.cpp; from debugger/mc6800:
#
#   gawk -f inst_hd6301.awk hd6301.txt \
#       | clang-format --assume-filename=inst_hd6301.cpp
#
# and replace the tables after the "// Generated by:" line in the .cpp.
# -v MODE=pretty prints the input tables back aligned instead.

# The "sequence" column is in debugger/match_legend.md's tokens. On the
# HD6301, A and B are at the operand's address, a direct page one 00xx; J
# goes to the operand, a branch's to the next + disp; x is a dummy read of
# FFFF.
# It fetches the next opcode ahead: an N before the end is that fetch,
# and an instruction's 1 then takes no cycle.

BEGIN {
    if (MODE == "")
        MODE = "table";
    if (MODE != "table" && MODE != "pretty") {
        print "MODE must be table or pretty" > "/dev/stderr";
        exit 1;
    }
    PRETTY_PRINT = MODE == "pretty";
    GENERATE_TABLE = MODE == "table";
    GENERATED_BY = generated_by("inst_hd6301.awk");
}

# The command that made the tables, wrapped to 80 columns so clang-format
# keeps it.
function generated_by(script,  i, cmd, line, word) {
    cmd = "";
    line = "// Generated by: gawk -f " script;
    for (i = 1; i <= ARGC; i++) {
        word = (i < ARGC) ? ARGV[i] : "| clang-format";
        if (length(line) + 1 + length(word) > 78) {
            cmd = cmd line "\n";
            line = "//     " word;
        } else {
            line = line " " word;
        }
    }
    return cmd line;
}

# Read the inputs twice: the first pass collects CYCLES in first-seen order,
# the second generates the tables.
BEGIN {
    if (GENERATE_TABLE) {
        NINPUTS = ARGC - 1;
        for (i = 1; i <= NINPUTS; i++)
            ARGV[ARGC++] = ARGV[i];
        COLLECTING = 1;
        GENERATE_TABLE = 0;
        GENERATE_CYCLES = 1;
    }
}

FNR == 1 && COLLECTING && ++NOPENED > NINPUTS {
    COLLECTING = 0;
    GENERATE_CYCLES = 0;
    GENERATE_TABLE = 1;
    start_TABLE();
}

function pretty_print(opc, nem, opr, clk, len, seq) {
    if (PRETTY_PRINT == 0)
        return;
    printf("%-2s  %-4s  %-4s  %2s  %s  %s\n", opc, nem, opr, clk, len, seq);
}

# The tokens of |seq| up to its first "@", a step after a data token
# in a group skipped, into |tok|; returns their count.
function tokens(seq, tok,  n, s, c) {
    n = 0;
    if (seq == "-")
        return 0;
    for (s = 1; s <= length(seq); ++s) {
        c = substr(seq, s, 1);
        if (c == "@")
            break;
        if (c ~ /[+-]/ && substr(seq, s + 1, 1) ~ /[1-9]/) {
            ++s;
            continue;
        }
        if (c ~ /[{}0.]/)
            continue;
        tok[++n] = c;
    }
    return n;
}

function inst_len(seq,  tok, n, i, len) {
    n = tokens(seq, tok);
    len = 0;
    for (i = 1; i <= n; ++i)
        if (tok[i] ~ /[12]/)
            ++len;
    return len;
}

# Its first byte fetched ahead or its next fetch looked at: one token
# takes no cycle.
function clock(seq,  tok) {
    return seq == "-" ? 0 : tokens(seq, tok) - 1;
}

function CYCLES_index(cyc, i) {
    for (i in CYCLES) {
        if (CYCLES[i] == cyc)
            return i;
    }
    return 0;
}

function add_CYCLES(cyc, n) {
    n = length(CYCLES);
    CYCLES[++n] = cyc;
}

function append_CYCLES(seq, cyc) {
    if (seq != "-")  {
        cyc = seq;
        if (CYCLES_index(cyc) == 0) {
            add_CYCLES(cyc);
            return 1;
        }
    }
    return 0;
}

function generate_CYCLES(seq) {
    if (GENERATE_CYCLES == 1)
        append_CYCLES(seq);
}

function generate_TABLE() {
    if (GENERATE_TABLE == 0)
        return;
    printf("%s\n", GENERATED_BY);
    printf("constexpr const char *const SEQUENCES[/*seq*/] = {\n");
    printf("        \"%s\",  // %2d\n", "", 0);
    for (c = 1; c <= length(CYCLES); c++) {
        cyc = CYCLES[c];
        printf("        \"%s\",  // %2d\n", cyc, c);
    }
    printf("};\n\n");

    # printf("constexpr uint8_t INST_LENS[] = {\n");
    # printf("        %d, // %2d: %s\n", 0, 0, "-");
    # for (c = 1; c <= length(CYCLES); c++) {
    #     cyc = CYCLES[c];
    #     printf("        %d, // %2d: %s\n", inst_len_cyc(cyc), c, cyc);
    # }
    # printf("};\n\n");

    # printf("constexpr uint8_t CLOCKS[] = {\n");
    # printf("        %d, // %2d: %s\n", 0, 0, "-");
    # for (c = 1; c <= length(CYCLES); c++) {
    #     cyc = CYCLES[c];
    #     printf("        %d, // %2d: %s\n", length(cyc), c, cyc);
    # }
    # printf("};\n\n");
}

function generate_ENTRY(opc, nem, opr, clk, len, seq, cyc) {
    if (GENERATE_TABLE == 0)
        return;
    cyc = seq;
    printf("        %d,   // %s: %-4s %-4s  %-2s:%s  %s\n",
           CYCLES_index(cyc), opc, nem, opr, clk, len, seq);
}

BEGIN {
    pretty_print("op", "nemo", "oper", " ~", "#", "sequence");
    pretty_print("--", "----", "----", "--", "-", "--------");

}

function start_TABLE() {
    generate_TABLE();
    printf("constexpr uint8_t INST_TABLE[] = {\n");
}
END {
    if (GENERATE_TABLE)
        printf("};\n");
}

$1 !~ /[0-9A-F][0-9A-F]/ { next; }
$1 ~ /[0-9A-F][0-9A-F]/ {
    opc = $1;
    nem = $2;
    opr = $3;
    clk = $4;
    len = $5;
    seq = $6;

    if (inst_len(seq) != len) {
        printf("@@ instruction length (#) mismatches with sequence\n");
        print $0;
        exit;
    }
    if (clock(seq) != clk) {
        printf("@@ instruction clock (~) mismatches with sequence\n");
        print $0;
        exit;
    }

    pretty_print(opc, nem, opr, clk, len, seq);
    generate_CYCLES(seq);
    generate_ENTRY(opc, nem, opr, clk, len, seq);
}
