# KL5C80A12CFP QFP definition
# https://github.com/tgtakaoka/dip
# A8-A11 and A16-A18 share P30-P33 through a 74ACT157 selected by P45 (ASEL); P33 reads GND as A19
name = "KL5C80A12CFP"
title = "KL5C80A12CFP"
qfp = "30x20"
pin1 = "bottom-left"
 1 = ",    P33,    OUTBP2"
 2 = "VCC, VDD"
 3 = "VCC, VDD"
 4 = ",    P32,    OUTBP1"
 5 = ",    P31,    SYNC"
 6 = ",    P30,    OUTBS0"
 7 = "P40, #EMRD"
 8 = "P41, #EMWR"
 9 = "P43, #EIORD"
10 = "P46, #EIOWR"
11 = ",    P27"
12 = ",    P26"
13 = ",    P25"
14 = "GND"
15 = "GND"
16 = "GND"
17 = ",    P24"
18 = ",    P23"
19 = ",    P22"
20 = ",    P21"
21 = "VCC, VDD"
22 = "GND"
23 = ",    P20"
24 = "P44, CLK"
25 = ",    BFSIO"
26 = "VCC, MODE1"
27 = "GND, MODE0"
28 = "P52, ERDY"
29 = ",    RXD"
30 = ",    TXD"
31 = "P37, A15"
32 = "P36, A14"
33 = "P35, A13"
34 = "VCC, VDD"
35 = "P34, A12"
36 = "P33, A11"
37 = "GND"
38 = "P32, A10"
39 = "P31, A9"
40 = "P30, A8"
41 = "P27, A7"
42 = "P26, A6"
43 = "P25, A5"
44 = "VCC, VDD"
45 = "P24, A4"
46 = "P23, A3"
47 = "P22, A2"
48 = "GND"
49 = "P21, A1"
50 = "P20, A0"
51 = "P17, D7"
52 = "VCC, VDD"
53 = "VCC, VDD"
54 = "P16, D6"
55 = "P15, D5"
56 = "P14, D4"
57 = "P13, D3"
58 = "P12, D2"
59 = "P53, #RESET"
60 = "P11, D1"
61 = "VCC, VDD"
62 = "P10, D0"
63 = "P47, XIN"
64 = ",    XOUT"
65 = "GND"
66 = "GND"
67 = "GND"
68 = "P32, A18,    #M1CS"
69 = "P31, A17,    #M0CS"
70 = "P30, A16"
71 = ",    P17,    #HALT"
72 = "P42, #M1,    P16"
73 = ",    P15,    RXC"
74 = ",    P14,    TXC"
75 = ",    P13,    XCLK1"
76 = ",    P12,    GATEA1"
77 = "GND"
78 = ",    P11,    XCLK0"
79 = ",    P10,    GATEA0"
80 = ",    P07,    IR7"
81 = ",    P06,    IR6"
82 = ",    P05,    IR5"
83 = ",    P04,    IR4"
84 = "VCC, VDD"
85 = "P51, #NMI,   P03, IR3"
86 = ",    P02,    IR2, GATEB2"
87 = ",    P01,    IR1, GATEB1"
88 = "P50, IR0,    P00, GATEB0"
89 = ",    P47,    SYNDBD"
90 = ",    P46,    #RTS"
91 = ",    P45,    #DTR"
92 = "P55, #BACK,  P44"
93 = ",    P43,    SYDTIN"
94 = ",    P42,    #CTS"
95 = ",    P41,    #DSR"
96 = "P54, #BREQ,  P40"
97 = ",    P37,    OUTBS2"
98 = ",    P36,    OUTBP0"
99 = ",    P35,    OUTA1"
100 = ",    P34,    OUTA0"
