# TMS9900 DIP definition
# https://github.com/tgtakaoka/dip
name = "TMS9900"
dip = 64
width = 900
 1 = "-5V,  VBB"
 2 = "+5V,  VCC"
 3 = "   ,  WAIT"
 4 = "out0, #LOAD"
 5 = "   ,  HOLDA"
 6 = "P53, #RESET"
 7 = "P43,  IAQ"
 8 = "phi1, PHI1"
 9 = "phi2, PHI2"
10 = "A1A,  A14"
11 = "A2A,  A13"
12 = "A3A,  A12"
13 = "A4A,  A11"
14 = "A5A,  A10"
15 = "A6A,  A9"
16 = "A7A,  A8"
17 = "A0B,  A7"
18 = "A1B,  A6"
19 = "A2B,  A5"
20 = "A3B,  A4"
21 = "A4B,  A3"
22 = "A5B,  A2"
23 = "A6B,  A1"
24 = "A7B,  A0"
25 = "phi4, PHI4"
26 = "GND,  VSS"
27 = "+12V, VDD"
28 = "phi3, PHI3"
29 = "P41,  DBIN"
30 = "A0A,  CRUOUT"
31 = "P45,  CRUIN"
32 = "out1, #INTREQ"
33 = "out4, IC3"
34 = "out5, IC2"
35 = "out6, IC1"
36 = "out7, IC0"
37 = ",     NC"
38 = ",     NC"
39 = ",     NC"
40 = "GND,  VSS"
41 = "P27,  D0"
42 = "P26,  D1"
43 = "P25,  D2"
44 = "P24,  D3"
45 = "P23,  D4"
46 = "P22,  D5"
47 = "P21,  D6"
48 = "P20,  D7"
49 = "P17,  D8"
50 = "P16,  D9"
51 = "P15,  D10"
52 = "P14,  D11"
53 = "P13,  D12"
54 = "P12,  D13"
55 = "P11,  D14"
56 = "P10,  D15"
57 = ",     NC"
58 = ",     NC"
59 = "+5V,  VCC"
60 = "P44,  CRUCLK"
61 = "P42,  #WE"
62 = "P54,  READY"
63 = "P40,  #MEMEN"
64 = "out3, #HOLD"
