#!/usr/bin/awk -f
# -*- mode: awk; -*-
#
# z280-PAGExx.txt -> the SEQUENCES[] and PAGExx_TABLE[] of inst_z280.cpp:
#
#   awk -f inst_z280.awk z280-PAGE00.txt z280-PAGECB.txt ... > tables.inc
#
# Measured by profile_z280.py/derive_z280.py, hand-maintained since.
# "#" is the instruction length, "~" the data transactions, "sequence":
#
# 1-6: instruction byte, a word read at that byte address (1 = the fetch)
# ~:   prefetch, a word read at the next unfetched address; greedy, capped
# B R: read byte / word (memory)        Y W: write byte / word (memory)
# b r: read byte / word (I/O)           y w: write byte / word (I/O)
# a:   interrupt acknowledge            h:   halt
# { }: repeat group (block instructions)
# --- control transfer: the read at the target ends the fetch stream
# j:   next+disp8      J: absolute nn   k: next+disp16    i: unknown target
# A:   target == last word read (byte-swapped)   C: target == opcode & 38H
# F:   flush without transfer: the next address is fetched again
# S:   trap: target == the PC word read from the vector table
# @:   taken@not-taken
#
# Unique sequences are collected in first-seen order and printed at END.

BEGIN {
    nseq = 0;
    npage = 0;
}

function seq_index(cyc, i) {
    for (i = 1; i <= nseq; i++)
        if (SEQ[i] == cyc)
            return i;
    SEQ[++nseq] = cyc;
    return nseq;
}

$1 !~ /^[0-9A-F][0-9A-F]$/ { next; }
{
    opc = $1;
    mne = $2;
    if (mne == "-") {
        line = sprintf("        {0,   0},  // %s", opc);
    } else {
        opr = $3;
        len = $4;
        seq = $6;
        if (seq == "" || seq == "-")
            seq = "-";
        cyc = seq;
        gsub(":", "", cyc);
        n = split(cyc, alt, "@");
        for (i = 1; i <= n; i++) {
            if (length(alt[i]) > 31) {   # InstZ280::SEQUENCE_MAX
                printf("%s: %s: alternative longer than 31: %s\n", FILENAME, opc, seq) > "/dev/stderr";
                exit 1;
            }
        }
        idx = (cyc == "-") ? 0 : seq_index(cyc);
        line = sprintf("        {%d, %3d},  // %s: %-7s %-18s %s",
                       len, idx, opc, mne, opr, seq);
    }
    if (FILENAME != current) {
        page = FILENAME;
        if (!sub(/^.*z280-PAGE/, "PAGE", page) || !sub(/\.txt$/, "", page)) {
            printf("Unknown file: %s\n", FILENAME) > "/dev/stderr";
            exit 1;
        }
        current = FILENAME;
        PAGE[++npage] = page;
        count[npage] = 0;
    }
    ROW[npage, ++count[npage]] = line;
}

END {
    printf("// Generated by inst_z280.awk from z280-PAGExx.txt; do not edit.\n");
    printf("constexpr const char *const SEQUENCES[/*seq*/] = {\n");
    printf("        %-16s  // %3d\n", "\"\",", 0);
    for (i = 1; i <= nseq; i++)
        printf("        %-16s  // %3d\n", "\"" SEQ[i] "\",", i);
    printf("};\n");
    for (p = 1; p <= npage; p++) {
        printf("\nconstexpr InstZ280::Table %s_TABLE[] = {\n", PAGE[p]);
        for (i = 1; i <= count[p]; i++)
            printf("%s\n", ROW[p, i]);
        printf("};\n");
    }
}
