#!/usr/bin/gawk -f
# -*- mode: awk; -*-
# Generates the tables of inst_i8096.cpp; from debugger/i8096:
#
#   gawk -f inst_i8096.awk i8096-PAGE00.txt i8096-PAGEFE.txt \
#       | clang-format --assume-filename=inst_i8096.cpp
#
# and replace the tables after the "// Generated by:" line in the .cpp.
# -v MODE=pretty prints the input tables back aligned instead.

# The "sequence" column is in debugger/match_legend.md's tokens, a "/"
# before the long index variant. A row is its sequence's index: its
# length is the sequence's bytes. J goes to the next + disp, RST's to 2080.
# A row ending in "80196KB" is an instruction the 80C196KB added, "80196KC"
# one only the 80C196KC has.

BEGIN {
    if (MODE == "")
        MODE = "table";
    if (MODE != "table" && MODE != "pretty") {
        print "MODE must be table or pretty" > "/dev/stderr";
        exit 1;
    }
    PRETTY_PRINT = MODE == "pretty";
    GENERATE_TABLE = MODE == "table";
    GENERATED_BY = generated_by("inst_i8096.awk");
}

# The command that made the tables, wrapped to 80 columns so clang-format
# keeps it.
function generated_by(script,  i, cmd, line, word) {
    cmd = "";
    line = "// Generated by: gawk -f " script;
    for (i = 1; i <= ARGC; i++) {
        word = (i < ARGC) ? ARGV[i] : "| clang-format";
        if (length(line) + 1 + length(word) > 78) {
            cmd = cmd line "\n";
            line = "//     " word;
        } else {
            line = line " " word;
        }
    }
    return cmd line;
}

# SEQUENCES are numbered in order of first appearance in the tables.
BEGIN {
    NCYCLES = 0;
    NLINES = 0;
}

BEGIN {
    if (PRETTY_PRINT) {
        pretty_print("op", "mnemo", "operands", "#",   "~", "sequence", "cpu");
        pretty_print("--", "-----", "--------", "---", "-", "--------", "---");
    }
}

function pretty_print(opc, mnemo, operand, len, bus, seq, cpu) {
    if (PRETTY_PRINT == 0)
        return;
    if (cpu == "")
        printf("%-2s  %-5s  %-8s  %-3s  %s  %s\n", opc, mnemo, operand, len, bus, seq);
    else
        printf("%-2s  %-5s  %-8s  %-3s  %s  %-24s  %s\n", opc, mnemo, operand, len, bus, seq, cpu);
}

function CYCLES_index(cyc) {
    if (!(cyc in INDEX)) {
        INDEX[cyc] = ++NCYCLES;
        CYCLES[NCYCLES] = cyc;
    }
    return INDEX[cyc];
}

function output(line) {
    LINES[++NLINES] = line;
}

function generate_ENTRY(opc, mnemo, opr, len, seq,  cyc) {
    if (len == "-") {
        output(sprintf("        0,  // %s", opc));
    } else {
        output(sprintf("        %d,  // %s: %-5s %-8s %s",
                       CYCLES_index(seq), opc, mnemo, opr, seq));
    }
}

function generate_OPCODES(kx,  i) {
    printf("\nconstexpr uint8_t %s_OPCODES[] = {\n", kx);
    for (i = 1; i <= N[kx]; i++)
        printf("        0x%s,  // %s\n", OPCODES[kx, i], MNEMOS[kx, i]);
    printf("};\n");
}

END {
    if (GENERATE_TABLE == 0)
        exit;
    printf("%s\n", GENERATED_BY);
    printf("constexpr const char *const SEQUENCES[/*seq*/] = {\n");
    printf("        \"%s\",  // %2d\n", "", 0);
    for (c = 1; c <= NCYCLES; c++)
        printf("        \"%s\",  // %2d\n", CYCLES[c], c);
    printf("};\n");
    for (l = 1; l <= NLINES; l++)
        print LINES[l];
    if (HEADER != "")
        printf("};\n");
    generate_OPCODES("KB");
    generate_OPCODES("KC");
}

$1 !~ /[0-9A-F][0-9A-F]/ { next; }
$1 ~ /[0-9A-F][0-9A-F]/ {
    opc = $1;
    mne = $2;
    opr = $3;
    len = $4;
    bus = $5;
    seq = $6
    if (seq == "") seq = "-"
    cpu = $7
    if (match(cpu, /^80196(K[BC])$/, kx) && FILENAME ~ /PAGE00/) {
        N[kx[1]]++;
        OPCODES[kx[1], N[kx[1]]] = opc;
        MNEMOS[kx[1], N[kx[1]]] = mne;
    }

    if (HEADER != FILENAME) {
        if (match(FILENAME, /i8096-(PAGE[0-9A-F]+).txt/, a) == 0) {
            printf("Unknown file: %s\n", FILENAME) > "/dev/stderr"
            exit 1;
        }
        if (HEADER != "")
            output("};");
        HEADER = FILENAME;
        output("");
        output(sprintf("constexpr uint8_t %s_TABLE[] = {", a[1]));
    }

    pretty_print(opc, mne, opr, len, bus, seq, cpu);
    if (GENERATE_TABLE)
        generate_ENTRY(opc, mne, opr, len, seq);
}
