#!/usr/bin/gawk -f
# -*- mode: awk; -*-
# Generates the tables of inst_i8096.cpp; from debugger/i8096:
#
#   gawk -f inst_i8096.awk i8096-PAGE00.txt i8096-PAGEFE.txt \
#       | clang-format --assume-filename=inst_i8096.cpp
#
# and replace the tables after the "// Generated by:" line in the .cpp.
# -v MODE=pretty prints the input tables back aligned instead.

# 1: instruction code (next=&1+1)
# 2: instruction operands (++next)
# 3: instruction operands (++next)
# 4: instruction operands (++next)
# 5: instruction operands (++next)
# 6: instruction operands (++next)
# 7: instruction operands (++next)
# ~: prefetch bytes (++next)
# B: read byte
# R: read low byte of word
# r: read high byte of word (=&R+1)
# Y: write byte
# W: write low byte of word
# w: write high byte of word (=&W+1)
# V: read low byte of vector
# v: read high byte of vector (=&V+1)
#--- following code invalidate prefetch bytes
# j: fetch instruction from next+8-bit disp
# k: fetch instruction from next+8-bit disp (JBC/JBS/DJNZ)
# K: fetch instruction from next+11-bit disp
# J: fetch instruction from next+16-bit disp
# i: fetch instruction from unknown address
# A: fetch instruction from previous read word
# C: fetch from reset origin (2080H)
#---- separator
# @: separator for conditional
# /: separator for 8/16 bit index
#---- interrupt
# V:v:W:w:A

BEGIN {
    if (MODE == "")
        MODE = "table";
    if (MODE != "table" && MODE != "pretty") {
        print "MODE must be table or pretty" > "/dev/stderr";
        exit 1;
    }
    PRETTY_PRINT = MODE == "pretty";
    GENERATE_TABLE = MODE == "table";
    GENERATED_BY = generated_by("inst_i8096.awk");
}

# The command that made the tables, wrapped to 80 columns so clang-format
# keeps it.
function generated_by(script,  i, cmd, line, word) {
    cmd = "";
    line = "// Generated by: gawk -f " script;
    for (i = 1; i <= ARGC; i++) {
        word = (i < ARGC) ? ARGV[i] : "| clang-format";
        if (length(line) + 1 + length(word) > 78) {
            cmd = cmd line "\n";
            line = "//     " word;
        } else {
            line = line " " word;
        }
    }
    return cmd line;
}

# SEQUENCES are numbered in order of first appearance in the tables.
BEGIN {
    NCYCLES = 0;
    NLINES = 0;
}

BEGIN {
    if (PRETTY_PRINT) {
        pretty_print("op", "mnemo", "operands", "#",   "~", "sequence");
        pretty_print("--", "-----", "--------", "---", "-", "--------");
    }
}

function pretty_print(opc, mnemo, operand, len, bus, seq) {
    if (PRETTY_PRINT == 0)
        return;
    printf("%-2s  %-5s  %-8s  %-3s  %s  %s\n", opc, mnemo, operand, len, bus, seq);
}

function CYCLES_index(cyc) {
    if (!(cyc in INDEX)) {
        INDEX[cyc] = ++NCYCLES;
        CYCLES[NCYCLES] = cyc;
    }
    return INDEX[cyc];
}

function output(line) {
    LINES[++NLINES] = line;
}

function generate_ENTRY(opc, mnemo, opr, len, seq,  cyc) {
    if (len == "-") {
        output(sprintf("        {0, 0},  // %s", opc));
    } else {
        cyc = seq;
        gsub(":", "", cyc);
        output(sprintf("        {%d, %d},  // %s: %-5s %-8s %s",
                       len, CYCLES_index(cyc), opc, mnemo, opr, seq));
    }
}

END {
    if (GENERATE_TABLE == 0)
        exit;
    printf("%s\n", GENERATED_BY);
    printf("constexpr const char *const SEQUENCES[/*seq*/] = {\n");
    printf("        \"%s\",  // %2d\n", "", 0);
    for (c = 1; c <= NCYCLES; c++)
        printf("        \"%s\",  // %2d\n", CYCLES[c], c);
    printf("};\n");
    for (l = 1; l <= NLINES; l++)
        print LINES[l];
    if (HEADER != "")
        printf("};\n");
}

$1 !~ /[0-9A-F][0-9A-F]/ { next; }
$1 ~ /[0-9A-F][0-9A-F]/ {
    opc = $1;
    mne = $2;
    opr = $3;
    len = $4;
    bus = $5;
    seq = $6
    if (seq == "") seq = "-"

    if (HEADER != FILENAME) {
        if (match(FILENAME, /i8096-(PAGE[0-9A-F]+).txt/, a) == 0) {
            printf("Unknown file: %s\n", FILENAME) > "/dev/stderr"
            exit 1;
        }
        if (HEADER != "")
            output("};");
        HEADER = FILENAME;
        output("");
        output(sprintf("constexpr InstI8096::Table %s_TABLE[] = {", a[1]));
    }

    pretty_print(opc, mne, opr, len, bus, seq);
    if (GENERATE_TABLE)
        generate_ENTRY(opc, mne, opr, len, seq);
}
