#include "inst_i8048.h"

namespace debugger {
namespace i8048 {

namespace {

// |flags| is a single F_ bit, kept as its number.
constexpr uint8_t flag_bit(uint8_t flags) {
    return flags == 8 ? 3 : flags == 4 ? 2 : flags == 2 ? 1 : 0;
}

// |intel| and |oki| are the machine cycles of |cyc| that don't strobe the
// bus, 0 or 1.
constexpr uint8_t E(
        uint8_t len, uint8_t cyc, uint8_t flags, uint8_t intel, uint8_t oki) {
    return (oki << 7) | (intel << 6) | (flag_bit(flags) << 4) | (cyc << 2) |
           (len << 0);
}

constexpr uint8_t inst_len(uint8_t entry) {
    return (entry >> 0) & 3;
}

// The machine cycles that strobe the bus, on the Intel or the OKI parts.
constexpr uint8_t bus_cyc(uint8_t entry, bool oki) {
    return ((entry >> 2) & 3) - ((entry >> (oki ? 7 : 6)) & 1);
}

constexpr uint8_t inst_flags(uint8_t entry) {
    return 1 << ((entry >> 4) & 3);
}

// Generated by: gawk -f inst_i8048.awk i8048.txt | clang-format
constexpr uint8_t INST_TABLE[] = {
        E(1, 1, 1, 0, 0),  // 00: NOP   -
        E(1, 1, 2, 0, 0),  // 01: HALT  -
        E(1, 2, 8, 0, 0),  // 02: OUTL  BUS,A
        E(2, 2, 1, 0, 0),  // 03: ADD   A,#n8
        E(2, 2, 1, 0, 0),  // 04: JMP   a11
        E(1, 1, 1, 0, 0),  // 05: EN    I
        0,                 // 06:
        E(1, 1, 1, 0, 0),  // 07: DEC   A
        E(1, 2, 8, 0, 0),  // 08: INS   A,BUS
        E(1, 2, 1, 1, 1),  // 09: IN    A,P1
        E(1, 2, 1, 1, 1),  // 0A: IN    A,P2
        0,                 // 0B:
        E(1, 2, 1, 0, 0),  // 0C: MOVD  A,P4
        E(1, 2, 1, 0, 0),  // 0D: MOVD  A,P5
        E(1, 2, 1, 0, 0),  // 0E: MOVD  A,P6
        E(1, 2, 1, 0, 0),  // 0F: MOVD  A,P7
        E(1, 1, 1, 0, 0),  // 10: INC   @R0
        E(1, 1, 1, 0, 0),  // 11: INC   @R1
        E(2, 2, 1, 0, 0),  // 12: JB    0,a8
        E(2, 2, 1, 0, 0),  // 13: ADDC  A,#n8
        E(2, 2, 1, 0, 0),  // 14: CALL  a11
        E(1, 1, 1, 0, 0),  // 15: DIS   I
        E(2, 2, 1, 0, 0),  // 16: JTF   a8
        E(1, 1, 1, 0, 0),  // 17: INC   A
        E(1, 1, 1, 0, 0),  // 18: INC   R0
        E(1, 1, 1, 0, 0),  // 19: INC   R1
        E(1, 1, 1, 0, 0),  // 1A: INC   R2
        E(1, 1, 1, 0, 0),  // 1B: INC   R3
        E(1, 1, 1, 0, 0),  // 1C: INC   R4
        E(1, 1, 1, 0, 0),  // 1D: INC   R5
        E(1, 1, 1, 0, 0),  // 1E: INC   R6
        E(1, 1, 1, 0, 0),  // 1F: INC   R7
        E(1, 1, 1, 0, 0),  // 20: XCH   A,@R0
        E(1, 1, 1, 0, 0),  // 21: XCH   A,@R1
        0,                 // 22:
        E(2, 2, 1, 0, 0),  // 23: MOV   A,#n8
        E(2, 2, 1, 0, 0),  // 24: JMP   a11
        E(1, 1, 1, 0, 0),  // 25: EN    TCNTI
        E(2, 2, 1, 0, 0),  // 26: JNT0  a8
        E(1, 1, 1, 0, 0),  // 27: CLR   A
        E(1, 1, 1, 0, 0),  // 28: XCH   A,R0
        E(1, 1, 1, 0, 0),  // 29: XCH   A,R1
        E(1, 1, 1, 0, 0),  // 2A: XCH   A,R2
        E(1, 1, 1, 0, 0),  // 2B: XCH   A,R3
        E(1, 1, 1, 0, 0),  // 2C: XCH   A,R4
        E(1, 1, 1, 0, 0),  // 2D: XCH   A,R5
        E(1, 1, 1, 0, 0),  // 2E: XCH   A,R6
        E(1, 1, 1, 0, 0),  // 2F: XCH   A,R7
        E(1, 1, 1, 0, 0),  // 30: XCHD  A,@R0
        E(1, 1, 1, 0, 0),  // 31: XCHD  A,@R1
        E(2, 2, 1, 0, 0),  // 32: JB    1,a8
        0,                 // 33:
        E(2, 2, 1, 0, 0),  // 34: CALL  a11
        E(1, 1, 1, 0, 0),  // 35: DIS   TCNTI
        E(2, 2, 1, 0, 0),  // 36: JT0   a8
        E(1, 1, 1, 0, 0),  // 37: CPL   A
        0,                 // 38:
        E(1, 2, 1, 1, 1),  // 39: OUTL  P1,A
        E(1, 2, 1, 1, 1),  // 3A: OUTL  P2,A
        0,                 // 3B:
        E(1, 2, 1, 0, 0),  // 3C: MOVD  P4,A
        E(1, 2, 1, 0, 0),  // 3D: MOVD  P5,A
        E(1, 2, 1, 0, 0),  // 3E: MOVD  P6,A
        E(1, 2, 1, 0, 0),  // 3F: MOVD  P7,A
        E(1, 1, 1, 0, 0),  // 40: ORL   A,@R0
        E(1, 1, 1, 0, 0),  // 41: ORL   A,@R1
        E(1, 1, 1, 0, 0),  // 42: MOV   A,T
        E(2, 2, 1, 0, 0),  // 43: ORL   A,#n8
        E(2, 2, 1, 0, 0),  // 44: JMP   a11
        E(1, 1, 1, 0, 0),  // 45: STRT  CNT
        E(2, 2, 1, 0, 0),  // 46: JNT1  a8
        E(1, 1, 1, 0, 0),  // 47: SWAP  A
        E(1, 1, 1, 0, 0),  // 48: ORL   A,R0
        E(1, 1, 1, 0, 0),  // 49: ORL   A,R1
        E(1, 1, 1, 0, 0),  // 4A: ORL   A,R2
        E(1, 1, 1, 0, 0),  // 4B: ORL   A,R3
        E(1, 1, 1, 0, 0),  // 4C: ORL   A,R4
        E(1, 1, 1, 0, 0),  // 4D: ORL   A,R5
        E(1, 1, 1, 0, 0),  // 4E: ORL   A,R6
        E(1, 1, 1, 0, 0),  // 4F: ORL   A,R7
        E(1, 1, 1, 0, 0),  // 50: ANL   A,@R0
        E(1, 1, 1, 0, 0),  // 51: ANL   A,@R1
        E(2, 2, 1, 0, 0),  // 52: JB    2,a8
        E(2, 2, 1, 0, 0),  // 53: ANL   A,#n8
        E(2, 2, 1, 0, 0),  // 54: CALL  a11
        E(1, 1, 1, 0, 0),  // 55: STRT  T
        E(2, 2, 1, 0, 0),  // 56: JT1   a8
        E(1, 1, 1, 0, 0),  // 57: DA    A
        E(1, 1, 1, 0, 0),  // 58: ANL   A,R0
        E(1, 1, 1, 0, 0),  // 59: ANL   A,R1
        E(1, 1, 1, 0, 0),  // 5A: ANL   A,R2
        E(1, 1, 1, 0, 0),  // 5B: ANL   A,R3
        E(1, 1, 1, 0, 0),  // 5C: ANL   A,R4
        E(1, 1, 1, 0, 0),  // 5D: ANL   A,R5
        E(1, 1, 1, 0, 0),  // 5E: ANL   A,R6
        E(1, 1, 1, 0, 0),  // 5F: ANL   A,R7
        E(1, 1, 1, 0, 0),  // 60: ADD   A,@R0
        E(1, 1, 1, 0, 0),  // 61: ADD   A,@R1
        E(1, 1, 1, 0, 0),  // 62: MOV   T,A
        E(1, 1, 4, 0, 0),  // 63: MOV   A,P1
        E(2, 2, 1, 0, 0),  // 64: JMP   a11
        E(1, 1, 1, 0, 0),  // 65: STOP  TCNT
        0,                 // 66:
        E(1, 1, 1, 0, 0),  // 67: RRC   A
        E(1, 1, 1, 0, 0),  // 68: ADD   A,R0
        E(1, 1, 1, 0, 0),  // 69: ADD   A,R1
        E(1, 1, 1, 0, 0),  // 6A: ADD   A,R2
        E(1, 1, 1, 0, 0),  // 6B: ADD   A,R3
        E(1, 1, 1, 0, 0),  // 6C: ADD   A,R4
        E(1, 1, 1, 0, 0),  // 6D: ADD   A,R5
        E(1, 1, 1, 0, 0),  // 6E: ADD   A,R6
        E(1, 1, 1, 0, 0),  // 6F: ADD   A,R7
        E(1, 1, 1, 0, 0),  // 70: ADDC  A,@R0
        E(1, 1, 1, 0, 0),  // 71: ADDC  A,@R1
        E(2, 2, 1, 0, 0),  // 72: JB    3,a8
        E(1, 1, 4, 0, 0),  // 73: MOV   A,P2
        E(2, 2, 1, 0, 0),  // 74: CALL  a11
        E(1, 1, 1, 0, 0),  // 75: ENT0  CLK
        E(2, 2, 1, 0, 0),  // 76: JF1   a8
        E(1, 1, 1, 0, 0),  // 77: RR    A
        E(1, 1, 1, 0, 0),  // 78: ADDC  A,R0
        E(1, 1, 1, 0, 0),  // 79: ADDC  A,R1
        E(1, 1, 1, 0, 0),  // 7A: ADDC  A,R2
        E(1, 1, 1, 0, 0),  // 7B: ADDC  A,R3
        E(1, 1, 1, 0, 0),  // 7C: ADDC  A,R4
        E(1, 1, 1, 0, 0),  // 7D: ADDC  A,R5
        E(1, 1, 1, 0, 0),  // 7E: ADDC  A,R6
        E(1, 1, 1, 0, 0),  // 7F: ADDC  A,R7
        E(1, 2, 1, 0, 0),  // 80: MOVX  A,@R0
        E(1, 2, 1, 0, 0),  // 81: MOVX  A,@R1
        E(1, 1, 4, 0, 0),  // 82: HLTS  -
        E(1, 2, 1, 0, 1),  // 83: RET   -
        E(2, 2, 1, 0, 0),  // 84: JMP   a11
        E(1, 1, 1, 0, 0),  // 85: CLR   F0
        E(2, 2, 1, 0, 0),  // 86: JNI   a8
        0,                 // 87:
        E(2, 2, 8, 0, 0),  // 88: ORL   BUS,#n8
        E(2, 2, 1, 0, 0),  // 89: ORL   P1,#n8
        E(2, 2, 1, 0, 0),  // 8A: ORL   P2,#n8
        0,                 // 8B:
        E(1, 2, 1, 0, 0),  // 8C: ORLD  P4,A
        E(1, 2, 1, 0, 0),  // 8D: ORLD  P5,A
        E(1, 2, 1, 0, 0),  // 8E: ORLD  P6,A
        E(1, 2, 1, 0, 0),  // 8F: ORLD  P7,A
        E(1, 2, 1, 0, 0),  // 90: MOVX  @R0,A
        E(1, 2, 1, 0, 0),  // 91: MOVX  @R1,A
        E(2, 2, 1, 0, 0),  // 92: JB    4,a8
        E(1, 2, 1, 0, 1),  // 93: RETR  -
        E(2, 2, 1, 0, 0),  // 94: CALL  a11
        E(1, 1, 1, 0, 0),  // 95: CPL   F0
        E(2, 2, 1, 0, 0),  // 96: JNZ   a8
        E(1, 1, 1, 0, 0),  // 97: CLR   C
        E(2, 2, 8, 0, 0),  // 98: ANL   BUS,#n8
        E(2, 2, 1, 0, 0),  // 99: ANL   P1,#n8
        E(2, 2, 1, 0, 0),  // 9A: ANL   P2,#n8
        0,                 // 9B:
        E(1, 2, 1, 0, 0),  // 9C: ANLD  P4,A
        E(1, 2, 1, 0, 0),  // 9D: ANLD  P5,A
        E(1, 2, 1, 0, 0),  // 9E: ANLD  P6,A
        E(1, 2, 1, 0, 0),  // 9F: ANLD  P7,A
        E(1, 1, 1, 0, 0),  // A0: MOV   @R0,A
        E(1, 1, 1, 0, 0),  // A1: MOV   @R1,A
        E(1, 1, 4, 0, 0),  // A2: FLT   -
        E(1, 2, 1, 0, 0),  // A3: MOVP  A,@A
        E(2, 2, 1, 0, 0),  // A4: JMP   a11
        E(1, 1, 1, 0, 0),  // A5: CLR   F1
        0,                 // A6:
        E(1, 1, 1, 0, 0),  // A7: CPL   C
        E(1, 1, 1, 0, 0),  // A8: MOV   R0,A
        E(1, 1, 1, 0, 0),  // A9: MOV   R1,A
        E(1, 1, 1, 0, 0),  // AA: MOV   R2,A
        E(1, 1, 1, 0, 0),  // AB: MOV   R3,A
        E(1, 1, 1, 0, 0),  // AC: MOV   R4,A
        E(1, 1, 1, 0, 0),  // AD: MOV   R5,A
        E(1, 1, 1, 0, 0),  // AE: MOV   R6,A
        E(1, 1, 1, 0, 0),  // AF: MOV   R7,A
        E(2, 2, 1, 0, 0),  // B0: MOV   @R0,#n8
        E(2, 2, 1, 0, 0),  // B1: MOV   @R1,#n8
        E(2, 2, 1, 0, 0),  // B2: JB    5,a8
        E(1, 2, 1, 0, 0),  // B3: JMPP  @A
        E(2, 2, 1, 0, 0),  // B4: CALL  a11
        E(1, 1, 1, 0, 0),  // B5: CPL   F1
        E(2, 2, 1, 0, 0),  // B6: JF0   a8
        0,                 // B7:
        E(2, 2, 1, 0, 0),  // B8: MOV   R0,#n8
        E(2, 2, 1, 0, 0),  // B9: MOV   R1,#n8
        E(2, 2, 1, 0, 0),  // BA: MOV   R2,#n8
        E(2, 2, 1, 0, 0),  // BB: MOV   R3,#n8
        E(2, 2, 1, 0, 0),  // BC: MOV   R4,#n8
        E(2, 2, 1, 0, 0),  // BD: MOV   R5,#n8
        E(2, 2, 1, 0, 0),  // BE: MOV   R6,#n8
        E(2, 2, 1, 0, 0),  // BF: MOV   R7,#n8
        E(1, 1, 4, 0, 0),  // C0: DEC   @R0
        E(1, 1, 4, 0, 0),  // C1: DEC   @R1
        E(1, 1, 4, 0, 0),  // C2: FLTT  -
        E(1, 2, 4, 0, 0),  // C3: MOVP1 P,@R3
        E(2, 2, 1, 0, 0),  // C4: JMP   a11
        E(1, 1, 1, 0, 0),  // C5: SEL   RB0
        E(2, 2, 1, 0, 0),  // C6: JZ    a8
        E(1, 1, 1, 0, 0),  // C7: MOV   A,PSW
        E(1, 1, 1, 0, 0),  // C8: DEC   R0
        E(1, 1, 1, 0, 0),  // C9: DEC   R1
        E(1, 1, 1, 0, 0),  // CA: DEC   R2
        E(1, 1, 1, 0, 0),  // CB: DEC   R3
        E(1, 1, 1, 0, 0),  // CC: DEC   R4
        E(1, 1, 1, 0, 0),  // CD: DEC   R5
        E(1, 1, 1, 0, 0),  // CE: DEC   R6
        E(1, 1, 1, 0, 0),  // CF: DEC   R7
        E(1, 1, 1, 0, 0),  // D0: XRL   A,@R0
        E(1, 1, 1, 0, 0),  // D1: XRL   A,@R1
        E(2, 2, 1, 0, 0),  // D2: JB    6,a8
        E(2, 2, 1, 0, 0),  // D3: XRL   A,#n8
        E(2, 2, 1, 0, 0),  // D4: CALL  a11
        E(1, 1, 1, 0, 0),  // D5: SEL   RB1
        0,                 // D6:
        E(1, 1, 1, 0, 0),  // D7: MOV   PSW,A
        E(1, 1, 1, 0, 0),  // D8: XRL   A,R0
        E(1, 1, 1, 0, 0),  // D9: XRL   A,R1
        E(1, 1, 1, 0, 0),  // DA: XRL   A,R2
        E(1, 1, 1, 0, 0),  // DB: XRL   A,R3
        E(1, 1, 1, 0, 0),  // DC: XRL   A,R4
        E(1, 1, 1, 0, 0),  // DD: XRL   A,R5
        E(1, 1, 1, 0, 0),  // DE: XRL   A,R6
        E(1, 1, 1, 0, 0),  // DF: XRL   A,R7
        E(2, 2, 4, 0, 0),  // E0: DJNZ  @R0,a8
        E(2, 2, 4, 0, 0),  // E1: DJNZ  @R1,a8
        E(1, 1, 4, 0, 0),  // E2: FRES  -
        E(1, 2, 1, 0, 0),  // E3: MOVP3 A,@A
        E(2, 2, 1, 0, 0),  // E4: JMP   a11
        E(1, 1, 1, 0, 0),  // E5: SEL   MB0
        E(2, 2, 1, 0, 0),  // E6: JNC   a8
        E(1, 1, 1, 0, 0),  // E7: RL    A
        E(2, 2, 1, 0, 0),  // E8: DJNZ  R0,a8
        E(2, 2, 1, 0, 0),  // E9: DJNZ  R1,a8
        E(2, 2, 1, 0, 0),  // EA: DJNZ  R2,a8
        E(2, 2, 1, 0, 0),  // EB: DJNZ  R3,a8
        E(2, 2, 1, 0, 0),  // EC: DJNZ  R4,a8
        E(2, 2, 1, 0, 0),  // ED: DJNZ  R5,a8
        E(2, 2, 1, 0, 0),  // EE: DJNZ  R6,a8
        E(2, 2, 1, 0, 0),  // EF: DJNZ  R7,a8
        E(1, 1, 1, 0, 0),  // F0: MOV   A,@R0
        E(1, 1, 1, 0, 0),  // F1: MOV   A,@R1
        E(2, 2, 1, 0, 0),  // F2: JB    7,a8
        E(1, 2, 4, 1, 1),  // F3: MOV   P1,@R3
        E(2, 2, 1, 0, 0),  // F4: CALL  a11
        E(1, 1, 1, 0, 0),  // F5: SEL   MB1
        E(2, 2, 1, 0, 0),  // F6: JC    a8
        E(1, 1, 1, 0, 0),  // F7: RLC   A
        E(1, 1, 1, 0, 0),  // F8: MOV   A,R0
        E(1, 1, 1, 0, 0),  // F9: MOV   A,R1
        E(1, 1, 1, 0, 0),  // FA: MOV   A,R2
        E(1, 1, 1, 0, 0),  // FB: MOV   A,R3
        E(1, 1, 1, 0, 0),  // FC: MOV   A,R4
        E(1, 1, 1, 0, 0),  // FD: MOV   A,R5
        E(1, 1, 1, 0, 0),  // FE: MOV   A,R6
        E(1, 1, 1, 0, 0),  // FF: MOV   A,R7
};
}  // namespace

uint8_t InstI8048::instLength(uint8_t inst) const {
    const auto entry = INST_TABLE[inst];
    if (entry == 0)
        return 0;
    const auto flags = inst_flags(entry);
    if ((flags & _flags) == 0)
        return 0;
    return inst_len(entry);
}

uint8_t InstI8048::busCycles(uint8_t inst) const {
    return bus_cyc(INST_TABLE[inst], _flags & F_MSM39);
}

}  // namespace i8048
}  // namespace debugger

// Local Variables:
// mode: c++
// c-basic-offset: 4
// tab-width: 4
// End:
// vim: set ft=cpp et ts=4 sw=4:
