#!/usr/bin/gawk -f
# -*- mode: awk; -*-
# Generates the tables of inst_i8048.cpp; from debugger/i8048:
#
#   gawk -f inst_i8048.awk i8048.txt \
#       | clang-format --assume-filename=inst_i8048.cpp
#
# and replace the tables after the "// Generated by:" line in the .cpp.
# -v MODE=pretty prints the input tables back aligned instead.

# FLAGS
# 1: i8039
# 2: i80C39
# 4: MSM80C39
# 8: x80x48
#
# s: the machine cycles that strobe the bus (the rest only pulse ALE), as
# Intel/OKI when they differ; - when every cycle strobes.

BEGIN {
    if (MODE == "")
        MODE = "table";
    if (MODE != "table" && MODE != "pretty") {
        print "MODE must be table or pretty" > "/dev/stderr";
        exit 1;
    }
    PRETTY_PRINT = MODE == "pretty";
    GENERATE_TABLE = MODE == "table";
    GENERATED_BY = generated_by("inst_i8048.awk");
}

# The command that made the tables, wrapped to 80 columns so clang-format
# keeps it.
function generated_by(script,  i, cmd, line, word) {
    cmd = "";
    line = "// Generated by: gawk -f " script;
    for (i = 1; i <= ARGC; i++) {
        word = (i < ARGC) ? ARGV[i] : "| clang-format";
        if (length(line) + 1 + length(word) > 78) {
            cmd = cmd line "\n";
            line = "//     " word;
        } else {
            line = line " " word;
        }
    }
    return cmd line;
}

function pretty_print(opc, mne, opr, len, cyc, flg, stb) {
    if (PRETTY_PRINT == 0)
        return;
    printf("%-2s  %-5s  %-7s  %s  %s  %s  %s\n", opc, mne, opr, len, cyc, flg, stb);
}

# The machine cycles of |cyc| that don't strobe: 0 or 1, per |stb|'s half.
function idle(cyc, stb) {
    if (cyc - stb != 0 && cyc - stb != 1) {
        printf("%s: idle cycles %d not 0 or 1\n", opc, cyc - stb) > "/dev/stderr";
        exit 1;
    }
    return cyc - stb;
}

function generate_TABLE(opc, mne, opr, len, cyc, flg, stb,  s) {
    if (GENERATE_TABLE == 0)
        return;
    if (mne == "-") {
        printf("        0,                // %s:\n", opc);
        return;
    }
    if (stb == "-")
        stb = cyc;
    if (split(stb, s, "/") == 1)
        s[2] = s[1];
    printf("        E(%d, %d, %d, %d, %d),  // %s: %-5s %s\n",
           len, cyc, flg, idle(cyc, s[1]), idle(cyc, s[2]), opc, mne, opr);
}
BEGIN {
    pretty_print("op", "mnemo", "operand", "#", "~", "F", "s");
    pretty_print("--", "-----", "-------", "-", "-", "-", "-");
    if (GENERATE_TABLE) {
        printf("%s\n", GENERATED_BY);
        printf("constexpr uint8_t INST_TABLE[] = {\n");
    }
}
END {
    if (GENERATE_TABLE)
        printf("};\n");
}

$1 !~ /[0-9A-F][0-9A-F]/ { next; }
$1 ~ /[0-9A-F][0-9A-F]/ {
    opc = $1;
    mne = $2;
    opr = $3;
    len = $4;
    cyc = $5;
    flg = $6;
    stb = $7;

    pretty_print(opc, mne, opr, len, cyc, flg, stb);
    generate_TABLE(opc, mne, opr, len, cyc, flg, stb);
}
