# P8095BH DIP definition
# https://github.com/tgtakaoka/dip
name = "P8095BH"
title = "P8095BH"
dip = 48
width = 600
 1 = "P45, RXD,   P2.1"
 2 = "P44, TXD,   P2.0"
 3 = "P34, HSI.0,      , SID.0"
 4 = "P35, HSI.1,      , SID.1"
 5 = "P36, HSI.2, HSO.4, SID.2"
 6 = "P37, HSI.3, HSO.5, SID.3"
 7 = "P30, HSO.0"
 8 = "P31, HSO.1"
 9 = "P32, HSO.2"
10 = "P33, HSO.3"
11 = "GND, Vss"
12 = ",    Vpp"
13 = "P46, PWM,   P2.5"
14 = "P42, #WR,   #WRL"
15 = "P43, #HBE,  #WRH"
16 = "P54, READY"
17 = "P27, AD15,  P4.7"
18 = "P26, AD14,  P4.6"
19 = "P25, AD13,  P4.5"
20 = "P24, AD12,  P4.4"
21 = "P23, AD11,  P4.3"
22 = "P22, AD10,  P4.2"
23 = "P21, AD9,   P4.1"
24 = "P20, AD8,   P4.0"
25 = "P17, AD7,   P3.7"
26 = "P16, AD6,   P3.6"
27 = "P15, AD5,   P3.5"
28 = "P14, AD4,   P3.4"
29 = "P13, AD3,   P3.3"
30 = "P12, AD2,   P3.2"
31 = "P11, AD1,   P3.1"
32 = "P10, AD0,   P3.0"
33 = "P41, #RD"
34 = "P40, #ADV,  ALE"
35 = ",    XTAL2"
36 = "P47, XTAL1"
37 = "GND, Vss"
38 = "Vcc"
39 = "GND, #EA"
40 = "P52, ACH6,  P0.6"
41 = "P57, ACH7,  P0.7"
42 = "P51, ACH5,  P0.5"
43 = "P50, ACH4,  P0.4"
44 = "GND, ANGND"
45 = "Vcc, Vref"
46 = "Vcc, Vpd"
47 = "P55, EXTINT, P2.2"
48 = "P53, #RESET"
