#!/usr/bin/gawk -f
# -*- mode: awk; -*-
# Generates the tables of inst_mc6805.cpp, inst_mc146805.cpp, inst_mc68hc05.cpp; from debugger/mc6805:
#
#   gawk -f inst_mc6805.awk mc6805.txt \
#       | clang-format --assume-filename=inst_mc6805.cpp
#   gawk -f inst_mc6805.awk mc146805.txt \
#       | clang-format --assume-filename=inst_mc146805.cpp
#   gawk -f inst_mc6805.awk mc68hc05.txt \
#       | clang-format --assume-filename=inst_mc68hc05.cpp
#
# and replace the tables after the "// Generated by:" line in the .cpp.
# -v MODE=pretty prints the input tables back aligned instead.

BEGIN {
    if (MODE == "")
        MODE = "table";
    if (MODE != "table" && MODE != "pretty") {
        print "MODE must be table or pretty" > "/dev/stderr";
        exit 1;
    }
    PRETTY_PRINT = MODE == "pretty";
    GENERATE_TABLE = MODE == "table";
    GENERATED_BY = generated_by("inst_mc6805.awk");

    BITS[0] = 0x80;
    BITS[1] = 0x40;
    BITS[2] = 0x20;
    BITS[3] = 0x10;
    BITS[4] = 0x08;
    BITS[5] = 0x04;
    BITS[6] = 0x02;
    BITS[7] = 0x01;
}

# The command that made the tables, wrapped to 80 columns so clang-format
# keeps it.
function generated_by(script,  i, cmd, line, word) {
    cmd = "";
    line = "// Generated by: gawk -f " script;
    for (i = 1; i <= ARGC; i++) {
        word = (i < ARGC) ? ARGV[i] : "| clang-format";
        if (length(line) + 1 + length(word) > 78) {
            cmd = cmd line "\n";
            line = "//     " word;
        } else {
            line = line " " word;
        }
    }
    return cmd line;
}

function pretty_print(opc, mne, opr, clk, len) {
    if (PRETTY_PRINT == 0)
        return;
    printf("%-2s  %-5s  %-7s  %2s  %s\n", opc, mne, opr, clk, len);
}

function generate_ENTRY(opc, len,  num, pos, bit) {
    if (GENERATE_TABLE == 0)
        return;
    num = strtonum("0x" opc);
    if (len != 0) {
        pos = int(num / 8);
        bit = BITS[num % 8];
        VALID[pos] = VALID[pos] + bit;
    }
}

BEGIN {
    pretty_print("op", "mnemo", "operand", " ~", "#");
    pretty_print("--", "-----", "-------", "--", "-");

    if (GENERATE_TABLE) {
        printf("%s\n", GENERATED_BY);
        # eight bytes a line, which clang-format would split
        printf("// clang-format off\n");
        printf("constexpr uint8_t INST_TABLE[] = {\n");

    }
}
END {
    if (GENERATE_TABLE) {
        for (i = 0; i < 256 / 8; ++i) {
            if (i % 8 == 0)
                sep = "        ";
            printf("%s0x%02X", sep, VALID[i]);
            sep = ", ";
            if (i % 8 == 7)
                printf(",  //  %02X~%02X\n", int(i/8)*8*8, i*8+7);
        }
        printf("};\n");
        printf("// clang-format on\n");
    }
}

$1 !~ /[0-9A-F][0-9A-F]/ { next; }
$1 ~ /[0-9A-F][0-9A-F]/ {
    opc = $1;
    mne = $2;
    opr = $3;
    clk = $4;
    len = $5;

    pretty_print(opc, mne, opr, clk, len);
    generate_ENTRY(opc, len);
}
