#!/usr/bin/gawk -f
# -*- mode: awk; -*-
# Generates the tables of inst_mc68hc08.cpp; from debugger/mc6805:
#
#   gawk -f inst_mc68hc08.awk mc68hc08-P00.txt mc68hc08-P9E.txt \
#       | clang-format --assume-filename=inst_mc68hc08.cpp
#
# and replace the tables after the "// Generated by:" line in the .cpp.
# -v MODE=pretty prints the input tables back aligned instead.

# 0: prefetched instruction code
# 2: instruction operands (disp, high(addr), ++next)
# 3: instruction operands (low(addr), ++next)
# R: read 1 byte (high(addr))
# r: read 1 byte at address R+1 or r+1 (low(addr))
# W: write 1 byte, equals to R if exists or w-1
# w: write 1 byte at address W+1
# A: read 1 byte at address |addr|
# D: read 1 byte from direct page (00|disp|)
# B: write 1 byte at address addr
# E: write 1 byte to direct page (00xx), equals to D if exists
# N: next instruction read from |next|
# J: next instruction read from |addr|
# j: next instruction read from |next| or |next|+disp
# i: next instruction read from unknown
# V: read 1 byte from address FFF8-FFFE (high(addr))
# v: read 1 byte from address V+1 (low(addr))
# d: read 1 byte from any address
#
# Interrupt sequence
# 1:R:d:w:W:W:W:W:V:v:J

function parseSeq(seq, r, i, c) {
    if (seq == "" || seq == "-")
        return "-";
    r = "";
    for (i = 1; i <= length(seq); i++) {
        c = substr(seq, i, 1);
        if (c == ":" || c == "V") {
            ;
        } else if (c == "N" || c == "J" || c == "j" || c == "i") {
            c = "N";
        } else if (c == "W" || c == "w" || c == "B" || c == "E") {
            c = "w";
        } else {
            c = "r";
        }
        r = r c;
    }
    return r;
}

BEGIN {
    if (MODE == "")
        MODE = "table";
    if (MODE != "table" && MODE != "pretty") {
        print "MODE must be table or pretty" > "/dev/stderr";
        exit 1;
    }
    PRETTY_PRINT = MODE == "pretty";
    GENERATE_TABLE = MODE == "table";
    GENERATED_BY = generated_by("inst_mc68hc08.awk");
}

# The command that made the tables, wrapped to 80 columns so clang-format
# keeps it.
function generated_by(script,  i, cmd, line, word) {
    cmd = "";
    line = "// Generated by: gawk -f " script;
    for (i = 1; i <= ARGC; i++) {
        word = (i < ARGC) ? ARGV[i] : "| clang-format";
        if (length(line) + 1 + length(word) > 78) {
            cmd = cmd line "\n";
            line = "//     " word;
        } else {
            line = line " " word;
        }
    }
    return cmd line;
}

# Read the inputs twice: the first pass collects CYCLES in first-seen order,
# the second generates the tables.
BEGIN {
    if (GENERATE_TABLE) {
        NINPUTS = ARGC - 1;
        for (i = 1; i <= NINPUTS; i++)
            ARGV[ARGC++] = ARGV[i];
        COLLECTING = 1;
        GENERATE_TABLE = 0;
        GENERATE_CYCLES = 1;
    }
}

FNR == 1 && COLLECTING && ++NOPENED > NINPUTS {
    COLLECTING = 0;
    GENERATE_CYCLES = 0;
    GENERATE_TABLE = 1;
}

function pretty_print(opc, nem, opr, len, clk, seq) {
    if (PRETTY_PRINT == 0)
        return;
    printf("%-2s  %-5s  %-8s  %s  %s  %s\n", opc, nem, opr, len, clk, seq);
}

function extract_number(str) {
    if (str == "-")
        return 0;
    sub(/[/+]+/, "", str);
    return str;
}

function inst_len(seq,  len, tmp, i, c) {
    len = 0;
    if (seq != "-") {
        split(seq, tmp, ":");
        for (i in tmp) {
            c = tmp[i];
            if (c ~ /[12345]/ && c >= len)
                len = c;
        }
    }
    return len;
}

function clock(seq,  clk, tmp) {
    clk = 0;
    if (seq != "-")
        clk = split(seq, tmp, ":") - 1;
    return clk;
}


function CYCLES_index(cyc, i) {
    for (i in CYCLES) {
        if (CYCLES[i] == cyc)
            return i;
    }
    return 0;
}

function add_CYCLES(cyc, n) {
    n = length(CYCLES);
    CYCLES[++n] = cyc;
}

function append_CYCLES(seq, cyc) {
    if (seq != "-")  {
        cyc = parseSeq(seq);
        gsub(":", "", cyc);
        if (CYCLES_index(cyc) == 0) {
            add_CYCLES(cyc);
            return 1;
        }
    }
    return 0;
}

function generate_CYCLES(seq) {
    if (GENERATE_CYCLES == 1)
        append_CYCLES(seq);
}

function generate_TABLE() {
    printf("%s\n", GENERATED_BY);
    printf("constexpr const char *const SEQUENCES[/*seq*/] = {\n");
    printf("        \"%s\",  // %2d\n", "", 0);
    for (c = 1; c <= length(CYCLES); c++) {
        cyc = CYCLES[c];
        printf("        \"%s\",  // %2d\n", cyc, c);
    }
    printf("};\n");
}

function generate_ENTRY(opc, nem, opr, clk, len, seq, cyc) {
    if (GENERATE_TABLE == 0)
        return;
    cyc = parseSeq(seq);
    gsub(":", "", cyc);
    if (clk > 0 && clk != length(cyc) - 1)
        printf("@@@@ ERROR\n");
    printf("        %d,   // %s: %-5s %-8s %s %s %s\n",
           CYCLES_index(cyc), opc, nem, opr, len, clk, seq);
}

BEGIN {
    pretty_print("op", "nemo",  "operand", "#", "~", "bus sequence");
    pretty_print("--", "-----", "-------", "-", "-", "------------");
}

$1 !~ /[0-9A-F][0-9A-F]/ { next; }
$1 ~ /[0-9A-F][0-9A-F]/ {
    opc = $1;
    nem = $2;
    opr = $3;
    len = $4;
    clk = $5;
    seq = ($6 == "") ? "-" : $6;

    if (GENERATE_TABLE && opc == "00") {
        if (match(FILENAME, /mc68hc08-(P[A-Z0-9]+).txt/, a) == 0) {
            printf("Unknown file: %s\n", FILENAME) > "/dev/stderr"
            exit;
        }
        if (FILENAME == "mc68hc08-P00.txt")
            generate_TABLE();
        page = a[1];
        printf("\nconstexpr uint8_t %s_TABLE[] = {\n", page);
    }

    # if (inst_len(seq) != extract_number(len)) {
    #     printf("@@ instruction length (#) mismatches with sequence\n");
    #     print $0;
    # }
    # if (clock(seq) != extract_number(clk)) {
    #     printf("@@ instruction clock (~) mismatches with sequence\n");
    #     print $0;
    # }

    pretty_print(opc, nem, opr, clk, len, seq);
    generate_CYCLES(seq);
    generate_ENTRY(opc, nem, opr, clk, len, seq);

    if (GENERATE_TABLE && opc == "FF")
        printf("};\n");
}
