# N8097BH PLCC definition
# https://github.com/tgtakaoka/dip
name = "N8097BH"
title = "N8097BH"
plcc = 68
pin1 = "top-center"
 1 = "Vcc"
 2 = "GND, #EA"
 3 = "P50, NMI"
 4 = ",    ACH3, P0.3"
 5 = ",    ACH1, P0.1"
 6 = ",    ACH0, P0.0"
 7 = ",    ACH2, P0.2"
 8 = "P52, ACH6, P0.6, PMODE.2"
 9 = ",    ACH7, P0.7, PMODE.3"
10 = "P51, ACH5, P0.5, PMODE.1"
11 = ",    ACH4, P0.4, PMODE.0"
12 = "GND, ANGND"
13 = "Vcc, VREF"
14 = "Vcc, VPD"
15 = "P55, EXTINT, P2.2, #PROG"
16 = "P53, #RESET"
17 = "P45, RXD, P2.1, #PALE"
18 = "P44, TXD, P2.0, PVER, SALE"
19 = ",    P1.0"
20 = ",    P1.1"
21 = ",    P1.2"
22 = ",    P1.3"
23 = ",    P1.4"
24 = "P34, HSI.0, SID.0"
25 = "P35, HSI.1, SID.1"
26 = "P36, HSI.2, SID.2, HSO.4"
27 = "P37, HSI.3, SID.3, HSO.5"
28 = "P30, HSO.0, #PACT"
29 = "P31, HSO.1"
30 = ",    P1.5"
31 = ",    P1.6"
32 = ",    P1.7"
33 = ",    P2.6"
34 = "P32, HSO.2"
35 = "P33, HSO.3"
36 = "GND, VSS"
37 = ",    VPP"
38 = ",    P2.7"
39 = ",    PWM, P2.5, #PDO, #SPROG"
40 = "P42, #WR, #WRL"
41 = "P43, #BHE, #WRH"
42 = ",    T2RST, P2.4"
43 = "P54, READY"
44 = ",    T2CLK, P2.3"
45 = "P27, AD15, P4.7"
46 = "P26, AD14, P4.6"
47 = "P25, AD13, P4.5"
48 = "P24, AD12, P4.4"
49 = "P23, AD11, P4.3"
50 = "P22, AD10, P4.2"
51 = "P21, AD9,  P4.1"
52 = "P20, AD8,  P4.0"
53 = "P17, AD7,  P3.7"
54 = "P16, AD6,  P3.6"
55 = "P15, AD5,  P3.5"
56 = "P14, AD4,  P3.4"
57 = "P13, AD3,  P3.3"
58 = "P12, AD2,  P3.2"
59 = "P11, AD1,  P3.1"
60 = "P10, AD0,  P3.0"
61 = "P41, #RD"
62 = "P40, ALE, #ADV"
63 = "P46, INST"
64 = ",    BUSWIDTH"
65 = ",    CLKOUT"
66 = ",    XTAL2"
67 = "P47, XTAL1"
68 = "GND, VSS"
