#!/usr/bin/gawk -f
# -*- mode: awk; -*-
# Generates the tables of inst_ins8070.cpp; from debugger/ins8070:
#
#   gawk -f inst_ins8070.awk ins8070.txt \
#       | clang-format --assume-filename=inst_ins8070.cpp
#
# and replace the tables after the "// Generated by:" line in the .cpp.
# -v MODE=pretty prints the input tables back aligned instead.

# 1: instruction code (next=&1)
# 2: instruction operands (disp, low(addr), ++next)
# 3: instruction operands (high(addr), ++next)
# R: read 1 byte (low(addr))
# r: read 1 byte at address R+1 (high(addr))
# Q: read 1 byte at PC-relative (next+disp+1)
# q: read 1 byet at PC-relative (Q+1)
# W: write 1 byte, equals to R if exists
# w: write 1 byte at address W+1
# X: write 1 byte at PC-relative (next+disp+1), equals to Q if exists
# x: write 1 byet at PC-relative (X+1)
# E: read 1 byte from direct page (FFxx)
# e: read 1 byte at address (E+1)
# F: write 1 byte to direct page (FFxx), equals to E if exists
# f: write 1 byte at address F+1
# V: read 1 byte from address 0020-003E (low(addr))
# v: read 1 byte from address V+1 (high(addr))
# S: read 1+ byte sequencially next address (S+1)
# @: separator for internal RAM access cycles
# N: next sequential instruction address (next)
# n: next unknown instruction
# s: next instruction address of SSM (next or next+2)
# A: 16-bit absolute address (addr)
# B: 8-bit relative branch (next or next+disp)
# P: poped from stack address (addr)

BEGIN {
    if (MODE == "")
        MODE = "table";
    if (MODE != "table" && MODE != "pretty") {
        print "MODE must be table or pretty" > "/dev/stderr";
        exit 1;
    }
    PRETTY_PRINT = MODE == "pretty";
    GENERATE_TABLE = MODE == "table";
    GENERATED_BY = generated_by("inst_ins8070.awk");
}

# The command that made the tables, wrapped to 80 columns so clang-format
# keeps it.
function generated_by(script,  i, cmd, line, word) {
    cmd = "";
    line = "// Generated by: gawk -f " script;
    for (i = 1; i <= ARGC; i++) {
        word = (i < ARGC) ? ARGV[i] : "| clang-format";
        if (length(line) + 1 + length(word) > 78) {
            cmd = cmd line "\n";
            line = "//     " word;
        } else {
            line = line " " word;
        }
    }
    return cmd line;
}

# Read the inputs twice: the first pass collects CYCLES in first-seen order,
# the second generates the tables.
BEGIN {
    if (GENERATE_TABLE) {
        NINPUTS = ARGC - 1;
        for (i = 1; i <= NINPUTS; i++)
            ARGV[ARGC++] = ARGV[i];
        COLLECTING = 1;
        GENERATE_TABLE = 0;
        GENERATE_CYCLES = 1;
    }
}

FNR == 1 && COLLECTING && ++NOPENED > NINPUTS {
    COLLECTING = 0;
    GENERATE_CYCLES = 0;
    GENERATE_TABLE = 1;
    start_TABLE();
}

function pretty_print(opc, nem, opr, mod, clk, len, cyc, seq) {
    if (PRETTY_PRINT == 0)
        return;
    printf("%-2s %-4s %-8s %-4s %-6s %s ", opc, nem, opr, mod, clk, len);
    printf("%-11s %s\n", cyc, seq);
}

function inst_len(cyc, s, i, c) {
    i = 0;
    for (s = 1; s <= length(cyc); ++s) {
        c = substr(cyc, s, 1);
        if (c == "@")
            break;
        if (c ~ /[123]/)
            ++i;
    }
    return i;
}

function bus_cycles(cyc, s, i, c) {
    i = 0;
    for (s = 1; s <= length(cyc); ++s) {
        c = substr(cyc, s, 1);
        if (c == "@")
            break;
        if (c ~ /[123RrQqWwXxEeFfVvS]/)
            ++i;
    }
    return i;
}

function external_cycles(cyc, s, i, c) {
    i = 0;
    for (s = 1; s <= length(cyc); ++s) {
        c = substr(cyc, s, 1);
        if (c == "@")
            break;
        if (c ~ /[123Vv]/)
            ++i;
    }
    return i;
}

function seq_cycles(seq, tmp, i, c, cyc, no_bus) {
    if (seq == "-")
        return "-";
    delete tmp;
    split(seq, tmp, ":");
    cyc = "";
    no_bus = "";
    for (i in tmp) {
        c = tmp[i];
        cyc = cyc c;
        if (c ~ /[123VvNnsABP]/) {
            if (c == "P")
                c = "n";
            no_bus = no_bus c;
        }
    }
    if (cyc != no_bus)
        cyc = cyc "@" no_bus;
    return cyc;
}

function seq_length(seq) {
    if (seq == "-")
        return 0;
    return length(seq);
}

function CYCLES_index(cyc, i) {
    for (i in CYCLES) {
        if (CYCLES[i] == cyc)
            return i;
    }
    return 0;
}

function add_CYCLES(cyc, n) {
    n = length(CYCLES);
    CYCLES[++n] = cyc;
}

function append_CYCLES(seq, cyc) {
    if (seq_length(seq) != 0) {
        cyc = seq_cycles(seq);
        if (CYCLES_index(cyc) == 0) {
            add_CYCLES(cyc);
            return 1;
        }
    }
    return 0;
}

function generate_CYCLES(seq) {
    if (GENERATE_CYCLES == 1)
        append_CYCLES(seq);
}

function generate_TABLE(op, nem, opr, mod, len, cyc, seq) {
    if (GENERATE_TABLE == 0)
        return;
    cycle = CYCLES_index(cyc);
    mode = (mod == "-" ? "M_NO" : "M_"mod);
    if (cycle == 0) {
        printf("        0,          // %s: %-4s %-8s ; %s\n",
               op, nem, opr, seq);
    } else {
        printf("        E(%s, %d),  // %s: %-4s %-8s ; %s\n", mode, cycle,
               op, nem, opr, seq);
    }
}

function generate_INSTLENS() {
    if (GENERATE_TABLE == 0)
        return;
    printf("%s\n", GENERATED_BY);
    printf("constexpr const char *const BUS_SEQUENCES[/*seq*/] = {\n");
    printf("        \"%s\",  // %2d\n", "", 0);
    for (c = 1; c <= length(CYCLES); c++) {
        cyc = CYCLES[c];
        printf("        \"%s\",  // %2d\n", cyc, c);
    }
    printf("};\n\n");

    printf("constexpr uint8_t INST_LENS[] = {\n");
    printf("        %d, // %2d: %s\n", 0, 0, "-");
    for (c = 1; c <= length(CYCLES); c++) {
        cyc = CYCLES[c];
        printf("        %d, // %2d: %s\n", inst_len(cyc), c, cyc);
    }
    printf("};\n\n");
}

function generate_BUSCYCLES() {
    if (GENERATE_TABLE == 0)
        return;
    printf("constexpr uint8_t BUS_CYCLES[] = {\n");
    printf("        %d, // %2d: %s\n", 0, 0, "-");
    for (c = 1; c <= length(CYCLES); c++) {
        cyc = CYCLES[c];
        printf("        %d, // %2d: %s\n", bus_cycles(cyc), c, cyc);
    }
    printf("};\n\n");
    printf("constexpr uint8_t EXTERNAL_CYCLES[] = {\n");
    printf("        %d, // %2d: %s\n", 0, 0, "-");
    for (c = 1; c <= length(CYCLES); c++) {
        cyc = CYCLES[c];
        printf("        %d, // %2d: %s\n", external_cycles(cyc), c, cyc);
    }
    printf("};\n\n");
}

BEGIN {
    pretty_print("op", "nemo", "operand", "mode", "clock", "#",
                 "cycle", "sequence");
    pretty_print("--", "----", "--------", "----", "------", "-",
                 "------", "--------");
}

function start_TABLE() {
    generate_INSTLENS();
    generate_BUSCYCLES();
    printf("constexpr uint8_t INST_TABLE[] = {\n");
}
END {
    if (GENERATE_TABLE)
        printf("};\n");
}

$1 !~ /[0-9A-F][0-9A-F]/ { next; }
$1 ~ /[0-9A-F][0-9A-F]/ {
    opc = $1;
    nem = $2;
    opr = $3;
    mod = $4;
    clk = $5;
    len = $6;
    cyc = $7;
    seq = $8;

    if (inst_len(cyc) > 0 && inst_len(cyc) != len) {
        printf("@@ instruction length (#) and cycle are mismatched\n");
        print $0;
        exit;
    }

    pretty_print(opc, nem, opr, mod, clk, len, cyc, seq);
    generate_CYCLES(seq);
    generate_TABLE(opc, nem, opr, mod, len, cyc, seq);
}
