#!/usr/bin/gawk -f
# -*- mode: awk; -*-
# Generates the tables of inst_ins8070.cpp; from debugger/ins8070:
#
#   gawk -f inst_ins8070.awk ins8070.txt \
#       | clang-format --assume-filename=inst_ins8070.cpp
#
# and replace the tables after the "// Generated by:" line in the .cpp.
# -v MODE=pretty prints the input tables back aligned instead.

# The "sequence" column is in debugger/match_legend.md's tokens. On the
# INS8070, J goes to the operand + 1 (the PC is incremented before a
# fetch), or for SSM to the next + 2; A and B are at the PC-relative or
# direct page (FFxx) effective address. The "cycle" column is derived: the
# sequence, then where it moves data, the same with only the cycles an
# internal RAM leaves on the bus.

BEGIN {
    if (MODE == "")
        MODE = "table";
    if (MODE != "table" && MODE != "pretty") {
        print "MODE must be table or pretty" > "/dev/stderr";
        exit 1;
    }
    PRETTY_PRINT = MODE == "pretty";
    GENERATE_TABLE = MODE == "table";
    GENERATED_BY = generated_by("inst_ins8070.awk");
}

# The command that made the tables, wrapped to 80 columns so clang-format
# keeps it.
function generated_by(script,  i, cmd, line, word) {
    cmd = "";
    line = "// Generated by: gawk -f " script;
    for (i = 1; i <= ARGC; i++) {
        word = (i < ARGC) ? ARGV[i] : "| clang-format";
        if (length(line) + 1 + length(word) > 78) {
            cmd = cmd line "\n";
            line = "//     " word;
        } else {
            line = line " " word;
        }
    }
    return cmd line;
}

# Read the inputs twice: the first pass collects CYCLES in first-seen order,
# the second generates the tables.
BEGIN {
    if (GENERATE_TABLE) {
        NINPUTS = ARGC - 1;
        for (i = 1; i <= NINPUTS; i++)
            ARGV[ARGC++] = ARGV[i];
        COLLECTING = 1;
        GENERATE_TABLE = 0;
        GENERATE_CYCLES = 1;
    }
}

FNR == 1 && COLLECTING && ++NOPENED > NINPUTS {
    COLLECTING = 0;
    GENERATE_CYCLES = 0;
    GENERATE_TABLE = 1;
    start_TABLE();
}

function pretty_print(opc, nem, opr, mod, clk, len, cyc, seq) {
    if (PRETTY_PRINT == 0)
        return;
    printf("%-2s %-4s %-8s %-4s %-6s %s ", opc, nem, opr, mod, clk, len);
    printf("%-11s %s\n", cyc, seq);
}

# The tokens of |seq| up to its first "@", a step after a data token
# in a group skipped, into |tok|; returns their count.
function tokens(seq, tok,  n, s, c) {
    n = 0;
    for (s = 1; s <= length(seq); ++s) {
        c = substr(seq, s, 1);
        if (c == "@")
            break;
        if (c ~ /[+-]/ && substr(seq, s + 1, 1) ~ /[1-9]/) {
            ++s;
            continue;
        }
        if (c ~ /[0.]/)
            continue;
        tok[++n] = c;
    }
    return n;
}
function inst_len(cyc,  tok, n, i, len) {
    n = tokens(cyc, tok);
    len = 0;
    for (i = 1; i <= n; ++i)
        if (tok[i] ~ /[12]/)
            ++len;
    return len;
}
function bus_cycles(cyc,  tok, n, i, cycles) {
    n = tokens(cyc, tok);
    cycles = 0;
    for (i = 1; i <= n; ++i)
        if (tok[i] ~ /[12RrAWwBVXx-]/)
            ++cycles;
    return cycles;
}
# The cycles to external memory: the instruction bytes and the vector.
function external_cycles(cyc,  tok, n, i, cycles, vector) {
    n = tokens(cyc, tok);
    cycles = 0;
    vector = 0;
    for (i = 1; i <= n; ++i) {
        if (tok[i] ~ /[RA]/)
            vector = 0;
        if (tok[i] == "V")
            vector = 1;
        if (tok[i] ~ /[12V]/ || (tok[i] == "r" && vector))
            ++cycles;
    }
    return cycles;
}
# |alt| with only what an internal RAM leaves on the bus: the instruction
# bytes, the vector and the next fetch; a P from data goes anywhere.
function internal(alt,  s, c, out, vector, depth) {
    out = "";
    vector = 0;
    depth = 0;
    for (s = 1; s <= length(alt); ++s) {
        c = substr(alt, s, 1);
        if (c == "{") {
            ++depth;
            continue;
        }
        if (c == "}") {
            --depth;
            continue;
        }
        if (depth)
            continue;
        if (c ~ /[RA]/)
            vector = 0;
        if (c == "V")
            vector = 1;
        if (c ~ /[12VNJ?]/ || (c == "r" && vector))
            out = out c;
        else if (c == "P")
            out = out (vector ? "P" : "?");
    }
    return out;
}
function seq_cycles(seq,  alts, n, i, ints, differ) {
    if (seq == "-")
        return "-";
    n = split(seq, alts, "@");
    ints = "";
    differ = 0;
    for (i = 1; i <= n; ++i) {
        ints = ints (i > 1 ? "@" : "") internal(alts[i]);
        if (internal(alts[i]) != alts[i])
            differ = 1;
    }
    return differ ? seq "@" ints : seq;
}
function seq_length(seq) {
    if (seq == "-")
        return 0;
    return length(seq);
}
function CYCLES_index(cyc, i) {
    for (i in CYCLES) {
        if (CYCLES[i] == cyc)
            return i;
    }
    return 0;
}

function add_CYCLES(cyc, n) {
    n = length(CYCLES);
    CYCLES[++n] = cyc;
}

function append_CYCLES(seq, cyc) {
    if (seq_length(seq) != 0) {
        cyc = seq_cycles(seq);
        if (CYCLES_index(cyc) == 0) {
            add_CYCLES(cyc);
            return 1;
        }
    }
    return 0;
}

function generate_CYCLES(seq) {
    if (GENERATE_CYCLES == 1)
        append_CYCLES(seq);
}

function generate_TABLE(op, nem, opr, mod, len, cyc, seq) {
    if (GENERATE_TABLE == 0)
        return;
    cycle = CYCLES_index(cyc);
    mode = (mod == "-" ? "M_NO" : "M_"mod);
    if (cycle == 0) {
        printf("        0,          // %s: %-4s %-8s ; %s\n",
               op, nem, opr, seq);
    } else {
        printf("        E(%s, %d),  // %s: %-4s %-8s ; %s\n", mode, cycle,
               op, nem, opr, seq);
    }
}

function generate_INSTLENS() {
    if (GENERATE_TABLE == 0)
        return;
    printf("%s\n", GENERATED_BY);
    printf("constexpr const char *const BUS_SEQUENCES[/*seq*/] = {\n");
    printf("        \"%s\",  // %2d\n", "", 0);
    for (c = 1; c <= length(CYCLES); c++) {
        cyc = CYCLES[c];
        printf("        \"%s\",  // %2d\n", cyc, c);
    }
    printf("};\n\n");

    printf("constexpr uint8_t INST_LENS[] = {\n");
    printf("        %d, // %2d: %s\n", 0, 0, "-");
    for (c = 1; c <= length(CYCLES); c++) {
        cyc = CYCLES[c];
        printf("        %d, // %2d: %s\n", inst_len(cyc), c, cyc);
    }
    printf("};\n\n");
}

function generate_BUSCYCLES() {
    if (GENERATE_TABLE == 0)
        return;
    printf("constexpr uint8_t BUS_CYCLES[] = {\n");
    printf("        %d, // %2d: %s\n", 0, 0, "-");
    for (c = 1; c <= length(CYCLES); c++) {
        cyc = CYCLES[c];
        printf("        %d, // %2d: %s\n", bus_cycles(cyc), c, cyc);
    }
    printf("};\n\n");
    printf("constexpr uint8_t EXTERNAL_CYCLES[] = {\n");
    printf("        %d, // %2d: %s\n", 0, 0, "-");
    for (c = 1; c <= length(CYCLES); c++) {
        cyc = CYCLES[c];
        printf("        %d, // %2d: %s\n", external_cycles(cyc), c, cyc);
    }
    printf("};\n\n");
}

BEGIN {
    pretty_print("op", "nemo", "operand", "mode", "clock", "#",
                 "cycle", "sequence");
    pretty_print("--", "----", "--------", "----", "------", "-",
                 "------", "--------");
}

function start_TABLE() {
    generate_INSTLENS();
    generate_BUSCYCLES();
    printf("constexpr uint8_t INST_TABLE[] = {\n");
}
END {
    if (GENERATE_TABLE)
        printf("};\n");
}

$1 !~ /[0-9A-F][0-9A-F]/ { next; }
$1 ~ /[0-9A-F][0-9A-F]/ {
    opc = $1;
    nem = $2;
    opr = $3;
    mod = $4;
    clk = $5;
    len = $6;
    seq = $8;
    cyc = seq_cycles(seq);

    if (inst_len(cyc) > 0 && inst_len(cyc) != len) {
        printf("@@ instruction length (#) and cycle are mismatched\n");
        print $0;
        exit;
    }

    pretty_print(opc, nem, opr, mod, clk, len, seq_cycles(seq), seq);
    generate_CYCLES(seq);
    generate_TABLE(opc, nem, opr, mod, len, cyc, seq);
}
