#include "inst_ins8070.h"
#include <string.h>

namespace debugger {
namespace ins8070 {

namespace {

constexpr uint8_t E(AddrMode mode, uint8_t seq) {
    return (uint16_t(mode) << 5) | seq;
}

constexpr AddrMode addr_mode(uint8_t entry) {
    return AddrMode(entry >> 5);
}

constexpr uint8_t inst_seq(uint8_t entry) {
    return entry & 0x1F;
}

// Generated by: gawk -f inst_ins8070.awk ins8070.txt | clang-format
constexpr const char *const BUS_SEQUENCES[/*seq*/] = {
        "",                       //  0
        "1N",                     //  1
        "1wWN@1N",                //  2
        "1WN@1N",                 //  3
        "1wWVrP@1VrP",            //  4
        "12wW2J@122J",            //  5
        "12wW2N@122N",            //  6
        "122J",                   //  7
        "122N",                   //  8
        "12J@12N",                //  9
        "1{R+1}J@1{R+1}N@1J@1N",  // 10
        "1RN@1N",                 // 11
        "12N",                    // 12
        "1RrN@1N",                // 13
        "1?",                     // 14
        "1RrP@1?",                // 15
        "12?",                    // 16
        "12ArN@12N",              // 17
        "12RrN@12N",              // 18
        "12BwN@12N",              // 19
        "12WwN@12N",              // 20
        "12ABN@12N",              // 21
        "12RWN@12N",              // 22
        "12AN@12N",               // 23
        "12RN@12N",               // 24
        "12BN@12N",               // 25
        "12WN@12N",               // 26
};

constexpr uint8_t INST_LENS[] = {
        0,  //  0: -
        1,  //  1: 1N
        1,  //  2: 1wWN@1N
        1,  //  3: 1WN@1N
        1,  //  4: 1wWVrP@1VrP
        3,  //  5: 12wW2J@122J
        3,  //  6: 12wW2N@122N
        3,  //  7: 122J
        3,  //  8: 122N
        2,  //  9: 12J@12N
        1,  // 10: 1{R+1}J@1{R+1}N@1J@1N
        1,  // 11: 1RN@1N
        2,  // 12: 12N
        1,  // 13: 1RrN@1N
        1,  // 14: 1?
        1,  // 15: 1RrP@1?
        2,  // 16: 12?
        2,  // 17: 12ArN@12N
        2,  // 18: 12RrN@12N
        2,  // 19: 12BwN@12N
        2,  // 20: 12WwN@12N
        2,  // 21: 12ABN@12N
        2,  // 22: 12RWN@12N
        2,  // 23: 12AN@12N
        2,  // 24: 12RN@12N
        2,  // 25: 12BN@12N
        2,  // 26: 12WN@12N
};

constexpr uint8_t BUS_CYCLES[] = {
        0,  //  0: -
        1,  //  1: 1N
        3,  //  2: 1wWN@1N
        2,  //  3: 1WN@1N
        5,  //  4: 1wWVrP@1VrP
        5,  //  5: 12wW2J@122J
        5,  //  6: 12wW2N@122N
        3,  //  7: 122J
        3,  //  8: 122N
        2,  //  9: 12J@12N
        2,  // 10: 1{R+1}J@1{R+1}N@1J@1N
        2,  // 11: 1RN@1N
        2,  // 12: 12N
        3,  // 13: 1RrN@1N
        1,  // 14: 1?
        3,  // 15: 1RrP@1?
        2,  // 16: 12?
        4,  // 17: 12ArN@12N
        4,  // 18: 12RrN@12N
        4,  // 19: 12BwN@12N
        4,  // 20: 12WwN@12N
        4,  // 21: 12ABN@12N
        4,  // 22: 12RWN@12N
        3,  // 23: 12AN@12N
        3,  // 24: 12RN@12N
        3,  // 25: 12BN@12N
        3,  // 26: 12WN@12N
};

constexpr uint8_t EXTERNAL_CYCLES[] = {
        0,  //  0: -
        1,  //  1: 1N
        1,  //  2: 1wWN@1N
        1,  //  3: 1WN@1N
        3,  //  4: 1wWVrP@1VrP
        3,  //  5: 12wW2J@122J
        3,  //  6: 12wW2N@122N
        3,  //  7: 122J
        3,  //  8: 122N
        2,  //  9: 12J@12N
        1,  // 10: 1{R+1}J@1{R+1}N@1J@1N
        1,  // 11: 1RN@1N
        2,  // 12: 12N
        1,  // 13: 1RrN@1N
        1,  // 14: 1?
        1,  // 15: 1RrP@1?
        2,  // 16: 12?
        2,  // 17: 12ArN@12N
        2,  // 18: 12RrN@12N
        2,  // 19: 12BwN@12N
        2,  // 20: 12WwN@12N
        2,  // 21: 12ABN@12N
        2,  // 22: 12RWN@12N
        2,  // 23: 12AN@12N
        2,  // 24: 12RN@12N
        2,  // 25: 12BN@12N
        2,  // 26: 12WN@12N
};

constexpr uint8_t INST_TABLE[] = {
        E(M_NO, 1),     // 00: NOP  -        ; 1N
        E(M_NO, 1),     // 01: XCH  A,E      ; 1N
        0,              // 02: -    -        ; -
        0,              // 03: -    -        ; -
        0,              // 04: -    -        ; -
        0,              // 05: -    -        ; -
        E(M_NO, 1),     // 06: LD   A,S      ; 1N
        E(M_NO, 1),     // 07: LD   S,A      ; 1N
        E(M_PUSH, 2),   // 08: PUSH EA       ; 1wWN
        E(M_NO, 1),     // 09: LD   T,EA     ; 1N
        E(M_PUSH, 3),   // 0A: PUSH A        ; 1WN
        E(M_NO, 1),     // 0B: LD   EA,T     ; 1N
        E(M_NO, 1),     // 0C: SR   EA       ; 1N
        E(M_NO, 1),     // 0D: DIV  EA,T     ; 1N
        E(M_NO, 1),     // 0E: SL   A        ; 1N
        E(M_NO, 1),     // 0F: SL   EA       ; 1N
        E(M_PUSH, 4),   // 10: CALL 0        ; 1wWVrP
        E(M_PUSH, 4),   // 11: CALL 1        ; 1wWVrP
        E(M_PUSH, 4),   // 12: CALL 2        ; 1wWVrP
        E(M_PUSH, 4),   // 13: CALL 3        ; 1wWVrP
        E(M_PUSH, 4),   // 14: CALL 4        ; 1wWVrP
        E(M_PUSH, 4),   // 15: CALL 5        ; 1wWVrP
        E(M_PUSH, 4),   // 16: CALL 6        ; 1wWVrP
        E(M_PUSH, 4),   // 17: CALL 7        ; 1wWVrP
        E(M_PUSH, 4),   // 18: CALL 8        ; 1wWVrP
        E(M_PUSH, 4),   // 19: CALL 9        ; 1wWVrP
        E(M_PUSH, 4),   // 1A: CALL 10       ; 1wWVrP
        E(M_PUSH, 4),   // 1B: CALL 11       ; 1wWVrP
        E(M_PUSH, 4),   // 1C: CALL 12       ; 1wWVrP
        E(M_PUSH, 4),   // 1D: CALL 13       ; 1wWVrP
        E(M_PUSH, 4),   // 1E: CALL 14       ; 1wWVrP
        E(M_PUSH, 4),   // 1F: CALL 15       ; 1wWVrP
        E(M_PUSH, 5),   // 20: JSR  a        ; 12wW2J
        0,              // 21: -    -        ; -
        E(M_PUSH, 6),   // 22: PLI  P2,=a    ; 12wW2N
        E(M_PUSH, 6),   // 23: PLI  P3,=a    ; 12wW2N
        E(M_NO, 7),     // 24: JMP  a        ; 122J
        E(M_NO, 8),     // 25: LD   SP,=a    ; 122N
        E(M_NO, 8),     // 26: LD   P2,=a    ; 122N
        E(M_NO, 8),     // 27: LD   P3,=a    ; 122N
        0,              // 28: -    -        ; -
        0,              // 29: -    -        ; -
        0,              // 2A: -    -        ; -
        0,              // 2B: -    -        ; -
        E(M_NO, 1),     // 2C: MPY  EA,T     ; 1N
        E(M_NO, 9),     // 2D: BND  a        ; 12J@12N
        E(M_SSM, 10),   // 2E: SSM  P2       ; 1{R+1}J@1{R+1}N
        E(M_SSM, 10),   // 2F: SSM  P3       ; 1{R+1}J@1{R+1}N
        E(M_NO, 1),     // 30: LD   EA,PC    ; 1N
        E(M_NO, 1),     // 31: LD   EA,SP    ; 1N
        E(M_NO, 1),     // 32: LD   EA,P2    ; 1N
        E(M_NO, 1),     // 33: LD   EA,P3    ; 1N
        0,              // 34: -    -        ; -
        0,              // 35: -    -        ; -
        0,              // 36: -    -        ; -
        0,              // 37: -    -        ; -
        E(M_POP, 11),   // 38: POP  A        ; 1RN
        E(M_NO, 12),    // 39: AND  S,=n     ; 12N
        E(M_POP, 13),   // 3A: POP  EA       ; 1RrN
        E(M_NO, 12),    // 3B: OR   S,=n     ; 12N
        E(M_NO, 1),     // 3C: SR   A        ; 1N
        E(M_NO, 1),     // 3D: SRL  A        ; 1N
        E(M_NO, 1),     // 3E: RR   A        ; 1N
        E(M_NO, 1),     // 3F: RRL  A        ; 1N
        E(M_NO, 1),     // 40: LD   A,E      ; 1N
        0,              // 41: -    -        ; -
        0,              // 42: -    -        ; -
        0,              // 43: -    -        ; -
        E(M_NO, 14),    // 44: LD   PC,EA    ; 1?
        E(M_NO, 1),     // 45: LD   SP,EA    ; 1N
        E(M_NO, 1),     // 46: LD   P2,EA    ; 1N
        E(M_NO, 1),     // 47: LD   P3,EA    ; 1N
        E(M_NO, 1),     // 48: LD   E,A      ; 1N
        0,              // 49: -    -        ; -
        0,              // 4A: -    -        ; -
        0,              // 4B: -    -        ; -
        E(M_NO, 14),    // 4C: XCH  EA,PC    ; 1?
        E(M_NO, 1),     // 4D: XCH  EA,SP    ; 1N
        E(M_NO, 1),     // 4E: XCH  EA,P2    ; 1N
        E(M_NO, 1),     // 4F: XCH  EA,P3    ; 1N
        E(M_NO, 1),     // 50: AND  A,E      ; 1N
        0,              // 51: -    -        ; -
        0,              // 52: -    -        ; -
        0,              // 53: -    -        ; -
        E(M_PUSH, 2),   // 54: PUSH PC       ; 1wWN
        0,              // 55: -    -        ; -
        E(M_PUSH, 2),   // 56: PUSH P2       ; 1wWN
        E(M_PUSH, 2),   // 57: PUSH P3       ; 1wWN
        E(M_NO, 1),     // 58: OR   A,E      ; 1N
        0,              // 59: -    -        ; -
        0,              // 5A: -    -        ; -
        0,              // 5B: -    -        ; -
        E(M_POP, 15),   // 5C: RET  -        ; 1RrP
        0,              // 5D: -    -        ; -
        E(M_POP, 13),   // 5E: POP  P2       ; 1RrN
        E(M_POP, 13),   // 5F: POP  P3       ; 1RrN
        E(M_NO, 1),     // 60: XOR  A,E      ; 1N
        0,              // 61: -    -        ; -
        0,              // 62: -    -        ; -
        0,              // 63: -    -        ; -
        E(M_NO, 9),     // 64: BP   a        ; 12J@12N
        0,              // 65: -    -        ; -
        E(M_NO, 16),    // 66: BP   d,P2     ; 12?
        E(M_NO, 16),    // 67: BP   d,P3     ; 12?
        0,              // 68: -    -        ; -
        0,              // 69: -    -        ; -
        0,              // 6A: -    -        ; -
        0,              // 6B: -    -        ; -
        E(M_NO, 9),     // 6C: BZ   a        ; 12J@12N
        0,              // 6D: -    -        ; -
        E(M_NO, 16),    // 6E: BZ   d,P2     ; 12?
        E(M_NO, 16),    // 6F: BZ   d,P3     ; 12?
        E(M_NO, 1),     // 70: ADD  A,E      ; 1N
        0,              // 71: -    -        ; -
        0,              // 72: -    -        ; -
        0,              // 73: -    -        ; -
        E(M_NO, 9),     // 74: BRA  a        ; 12J@12N
        0,              // 75: -    -        ; -
        E(M_NO, 16),    // 76: BRA  d,P2     ; 12?
        E(M_NO, 16),    // 77: BRA  d,P3     ; 12?
        E(M_NO, 1),     // 78: SUB  A,E      ; 1N
        0,              // 79: -    -        ; -
        0,              // 7A: -    -        ; -
        0,              // 7B: -    -        ; -
        E(M_NO, 9),     // 7C: BNZ  a        ; 12J@12N
        0,              // 7D: -    -        ; -
        E(M_NO, 16),    // 7E: BNZ  d,P2     ; 12?
        E(M_NO, 16),    // 7F: BNZ  d,P3     ; 12?
        E(M_DISP, 17),  // 80: LD   EA,d,PC  ; 12ArN
        E(M_DISP, 18),  // 81: LD   EA,d,SP  ; 12RrN
        E(M_DISP, 18),  // 82: LD   EA,d,P2  ; 12RrN
        E(M_DISP, 18),  // 83: LD   EA,d,P3  ; 12RrN
        E(M_NO, 8),     // 84: LD   EA,=nn   ; 122N
        E(M_DIR, 17),   // 85: LD   EA,n     ; 12ArN
        E(M_AUTO, 18),  // 86: LD   EA,@d,P2 ; 12RrN
        E(M_AUTO, 18),  // 87: LD   EA,@d,P3 ; 12RrN
        E(M_DISP, 19),  // 88: ST   EA,d,PC  ; 12BwN
        E(M_DISP, 20),  // 89: ST   EA,d,SP  ; 12WwN
        E(M_DISP, 20),  // 8A: ST   EA,d,P2  ; 12WwN
        E(M_DISP, 20),  // 8B: ST   EA,d,P3  ; 12WwN
        0,              // 8C: -    -        ; -
        E(M_DIR, 19),   // 8D: ST   EA,n     ; 12BwN
        E(M_AUTO, 20),  // 8E: ST   EA,@d,P2 ; 12WwN
        E(M_AUTO, 20),  // 8F: ST   EA,@d,P3 ; 12WwN
        E(M_DISP, 21),  // 90: ILD  A,d,PC   ; 12ABN
        E(M_DISP, 22),  // 91: ILD  A,d,SP   ; 12RWN
        E(M_DISP, 22),  // 92: ILD  A,d,P2   ; 12RWN
        E(M_DISP, 22),  // 93: ILD  A,d,P3   ; 12RWN
        0,              // 94: -    -        ; -
        E(M_DIR, 21),   // 95: ILD  A,n      ; 12ABN
        E(M_AUTO, 22),  // 96: ILD  A,@d,P2  ; 12RWN
        E(M_AUTO, 22),  // 97: ILD  A,@d,P3  ; 12RWN
        E(M_DISP, 21),  // 98: DLD  A,d,PC   ; 12ABN
        E(M_DISP, 22),  // 99: DLD  A,d,SP   ; 12RWN
        E(M_DISP, 22),  // 9A: DLD  A,d,P2   ; 12RWN
        E(M_DISP, 22),  // 9B: DLD  A,d,P3   ; 12RWN
        0,              // 9C: -    -        ; -
        E(M_DIR, 21),   // 9D: DLD  A,n      ; 12ABN
        E(M_AUTO, 22),  // 9E: DLD  A,@d,P2  ; 12RWN
        E(M_AUTO, 22),  // 9F: DLD  A,@d,P3  ; 12RWN
        E(M_DISP, 17),  // A0: LD   T,d,PC   ; 12ArN
        E(M_DISP, 18),  // A1: LD   T,d,SP   ; 12RrN
        E(M_DISP, 18),  // A2: LD   T,d,P2   ; 12RrN
        E(M_DISP, 18),  // A3: LD   T,d,P3   ; 12RrN
        E(M_NO, 8),     // A4: LD   T,=nn    ; 122N
        E(M_DIR, 17),   // A5: LD   T,n      ; 12ArN
        E(M_AUTO, 18),  // A6: LD   T,@d,P2  ; 12RrN
        E(M_AUTO, 18),  // A7: LD   T,@d,P3  ; 12RrN
        0,              // A8: -    -        ; -
        0,              // A9: -    -        ; -
        0,              // AA: -    -        ; -
        0,              // AB: -    -        ; -
        0,              // AC: -    -        ; -
        0,              // AD: -    -        ; -
        0,              // AE: -    -        ; -
        0,              // AF: -    -        ; -
        E(M_DISP, 17),  // B0: ADD  EA,d,PC  ; 12ArN
        E(M_DISP, 18),  // B1: ADD  EA,d,SP  ; 12RrN
        E(M_DISP, 18),  // B2: ADD  EA,d,P2  ; 12RrN
        E(M_DISP, 18),  // B3: ADD  EA,d,P3  ; 12RrN
        E(M_NO, 8),     // B4: ADD  EA,=nn   ; 122N
        E(M_DIR, 17),   // B5: ADD  EA,n     ; 12ArN
        E(M_AUTO, 18),  // B6: ADD  EA,@d,P2 ; 12RrN
        E(M_AUTO, 18),  // B7: ADD  EA,@d,P3 ; 12RrN
        E(M_DISP, 17),  // B8: SUB  EA,d,PC  ; 12ArN
        E(M_DISP, 18),  // B9: SUB  EA,d,SP  ; 12RrN
        E(M_DISP, 18),  // BA: SUB  EA,d,P2  ; 12RrN
        E(M_DISP, 18),  // BB: SUB  EA,d,P3  ; 12RrN
        E(M_NO, 8),     // BC: SUB  EA,=nn   ; 122N
        E(M_DIR, 17),   // BD: SUB  EA,n     ; 12ArN
        E(M_AUTO, 18),  // BE: SUB  EA,@d,P2 ; 12RrN
        E(M_AUTO, 18),  // BF: SUB  EA,@d,P3 ; 12RrN
        E(M_DISP, 23),  // C0: LD   A,d,PC   ; 12AN
        E(M_DISP, 24),  // C1: LD   A,d,SP   ; 12RN
        E(M_DISP, 24),  // C2: LD   A,d,P2   ; 12RN
        E(M_DISP, 24),  // C3: LD   A,d,P3   ; 12RN
        E(M_NO, 12),    // C4: LD   A,=n     ; 12N
        E(M_DIR, 23),   // C5: LD   A,n      ; 12AN
        E(M_AUTO, 24),  // C6: LD   A,@d,P2  ; 12RN
        E(M_AUTO, 24),  // C7: LD   A,@d,P3  ; 12RN
        E(M_DISP, 25),  // C8: ST   A,d,PC   ; 12BN
        E(M_DISP, 26),  // C9: ST   A,d,SP   ; 12WN
        E(M_DISP, 26),  // CA: ST   A,d,P2   ; 12WN
        E(M_DISP, 26),  // CB: ST   A,d,P3   ; 12WN
        0,              // CC: -    -        ; -
        E(M_DIR, 25),   // CD: ST   A,n      ; 12BN
        E(M_AUTO, 26),  // CE: ST   A,@d,P2  ; 12WN
        E(M_AUTO, 26),  // CF: ST   A,@d,P3  ; 12WN
        E(M_DISP, 23),  // D0: AND  A,d,PC   ; 12AN
        E(M_DISP, 24),  // D1: AND  A,d,SP   ; 12RN
        E(M_DISP, 24),  // D2: AND  A,d,P2   ; 12RN
        E(M_DISP, 24),  // D3: AND  A,d,P3   ; 12RN
        E(M_NO, 12),    // D4: AND  A,=n     ; 12N
        E(M_DIR, 23),   // D5: AND  A,n      ; 12AN
        E(M_AUTO, 24),  // D6: AND  A,@d,P2  ; 12RN
        E(M_AUTO, 24),  // D7: AND  A,@d,P3  ; 12RN
        E(M_DISP, 23),  // D8: OR   A,d,PC   ; 12AN
        E(M_DISP, 24),  // D9: OR   A,d,SP   ; 12RN
        E(M_DISP, 24),  // DA: OR   A,d,P2   ; 12RN
        E(M_DISP, 24),  // DB: OR   A,d,P3   ; 12RN
        E(M_NO, 12),    // DC: OR   A,=n     ; 12N
        E(M_DIR, 23),   // DD: OR   A,n      ; 12AN
        E(M_AUTO, 24),  // DE: OR   A,@d,P2  ; 12RN
        E(M_AUTO, 24),  // DF: OR   A,@d,P3  ; 12RN
        E(M_DISP, 23),  // E0: XOR  A,d,PC   ; 12AN
        E(M_DISP, 24),  // E1: XOR  A,d,SP   ; 12RN
        E(M_DISP, 24),  // E2: XOR  A,d,P2   ; 12RN
        E(M_DISP, 24),  // E3: XOR  A,d,P3   ; 12RN
        E(M_NO, 12),    // E4: XOR  A,=n     ; 12N
        E(M_DIR, 23),   // E5: XOR  A,n      ; 12AN
        E(M_AUTO, 24),  // E6: XOR  A,@d,P2  ; 12RN
        E(M_AUTO, 24),  // E7: XOR  A,@d,P3  ; 12RN
        0,              // E8: -    -        ;
        0,              // E9: -    -        ;
        0,              // EA: -    -        ;
        0,              // EB: -    -        ;
        0,              // EC: -    -        ;
        0,              // ED: -    -        ;
        0,              // EE: -    -        ;
        0,              // EF: -    -        ;
        E(M_DISP, 23),  // F0: ADD  A,d,PC   ; 12AN
        E(M_DISP, 24),  // F1: ADD  A,d,SP   ; 12RN
        E(M_DISP, 24),  // F2: ADD  A,d,P2   ; 12RN
        E(M_DISP, 24),  // F3: ADD  A,d,P3   ; 12RN
        E(M_NO, 12),    // F4: ADD  A,=n     ; 12N
        E(M_DIR, 23),   // F5: ADD  A,n      ; 12AN
        E(M_AUTO, 24),  // F6: ADD  A,@d,P2  ; 12RN
        E(M_AUTO, 24),  // F7: ADD  A,@d,P3  ; 12RN
        E(M_DISP, 23),  // F8: SUB  A,Q,PC   ; 12AN
        E(M_DISP, 24),  // F9: SUB  A,d,SP   ; 12RN
        E(M_DISP, 24),  // FA: SUB  A,d,P2   ; 12RN
        E(M_DISP, 24),  // FB: SUB  A,d,P3   ; 12RN
        E(M_NO, 12),    // FC: SUB  A,=n     ; 12N
        E(M_DIR, 23),   // FD: SUB  A,n      ; 12AN
        E(M_AUTO, 24),  // FE: SUB  A,@d,P2  ; 12RN
        E(M_AUTO, 24),  // FF: SUB  A,@d,P3  ; 12RN
};
}  // namespace

bool InstIns8070::get(uint8_t data) {
    opc = data;
    seq = inst_seq(INST_TABLE[opc]);
    return len() != 0;
}

uint8_t InstIns8070::len() const {
    return INST_LENS[seq];
}

uint8_t InstIns8070::busCycles() const {
    return BUS_CYCLES[seq];
}

uint8_t InstIns8070::externalCycles() const {
    return EXTERNAL_CYCLES[seq];
}

AddrMode InstIns8070::addrMode() const {
    return addr_mode(INST_TABLE[opc]);
}

const char *InstIns8070::sequence() const {
    return BUS_SEQUENCES[seq];
}

MatchWalker::Kind ArchIns8070::cycleKind(const SignalsImpl *impl) const {
    const auto s = static_cast<const Signals *>(impl);
    return s->read()    ? MatchWalker::K_READ
           : s->write() ? MatchWalker::K_WRITE
                        : MatchWalker::K_NONE;
}

// J goes to the operand + 1, as the PC is incremented before a fetch, a
// branch to the next + disp, SSM to the next + 2; A and B are at the
// PC-relative or direct page effective address.
bool ArchIns8070::decode(uint32_t pc, MatchWalker::Decoded &inst) const {
    pc &= 0xFFFF;
    InstIns8070 i;
    if (!i.get(_mems.read_byte(pc)))
        return false;
    inst.pc = pc;
    inst.seq = i.sequence();
    inst.length = i.len();
    const auto next = pc + inst.length;
    const auto disp = static_cast<int8_t>(_mems.read_byte((pc + 1) & 0xFFFF));
    const uint16_t operand = _mems.read_byte((pc + 1) & 0xFFFF) |
                             _mems.read_byte((pc + 2) & 0xFFFF) << 8;
    const auto mode = i.addrMode();
    inst.hasTarget = true;
    if (mode == M_SSM) {
        inst.target = (next + 2) & 0xFFFF;
    } else if (inst.length == 3) {
        inst.target = (operand + 1) & 0xFFFF;
    } else {
        inst.target = (next + disp) & 0xFFFF;
    }
    inst.hasEa = mode == M_DIR || mode == M_DISP;
    inst.ea =
            mode == M_DIR ? 0xFF00 | uint8_t(disp) : uint16_t(next - 1 + disp);
    return true;
}

// The vector table of CALL n: 0020-003E.
// An interrupt pushes the PC, then fetches the next instruction at 0004
// or 0007.
const char *ArchIns8070::interruptSequence() const {
    return "WW?";
}

bool ArchIns8070::isVectorTable(uint32_t addr) const {
    return (addr & ~UINT32_C(0x1E)) == 0x20;
}

void ArchIns8070::markCycle(
        SignalsImpl *impl, MatchWalker::Role role, uint_fast8_t) const {
    static_cast<Signals *>(impl)->markFetch(role == MatchWalker::R_FETCH);
}

}  // namespace ins8070
}  // namespace debugger

// Local Variables:
// mode: c++
// c-basic-offset: 4
// tab-width: 4
// End:
// vim: set ft=cpp et ts=4 sw=4:
