# MC68HC11A0 DIP definition
# https://github.com/tgtakaoka/dip
name = "MC68HC11A0"
title = "MC68HC11A0 Mode3"
dip = 48
width = 600
1 = "P37, PA7"
2 = "P36, PA6"
3 = "P35, PA5"
4 = "P34, PA4"
5 = "P33, PA3"
6 = "P32, PA2"
7 = "P31, PA1"
8 = "P30, PA0"
9 = "P27, A15"
10 = "P26, A14"
11 = "P25, A13"
12 = "P24, A12"
13 = "P23, A11"
14 = "P22, A10"
15 = "P21, A9"
16 = "P20, A8"
17 = ", PE0"
18 = ", PE1"
19 = ", PE2"
20 = ", PE3"
21 = "VSS, VRL"
22 = "VDD, VRH"
23 = "VSS"
24 = "P51, MODB, STBY"
25 = "P50, MODA, #LIR"
26 = "P40, AS"
27 = "P47, E"
28 = "P41, R/W"
29 = "P46, EXTAL"
30 = ", XTAL"
31 = "P10, AD0"
32 = "P11, AD1"
33 = "P12, AD2"
34 = "P13, AD3"
35 = "P14, AD4"
36 = "P15, AD5"
37 = "P16, AD6"
38 = "P17, AD7"
39 = "P53, #RESET"
40 = "P43, #XIRQ"
41 = "P42, #IRQ"
42 = "P45, PD0, RxD"
43 = "P44, PD1, TxD"
44 = "P52, PD2, MISO"
45 = "P54, PD3, MOSI"
46 = "P55, PD4, SCK"
47 = "P56, PD5, #SS"
48 = "VDD"
