#!/usr/bin/gawk -f
# -*- mode: awk; -*-
# Generates the tables of inst_hd6309.cpp; from debugger/mc6809:
#
#   gawk -f inst_hd6309.awk hd6309-IX.txt hd6309-P00.txt hd6309-P10.txt hd6309-P11.txt \
#       | clang-format --assume-filename=inst_hd6309.cpp
#
# and replace the tables after the "// Generated by:" line in the .cpp.
# -v MODE=pretty prints the input tables back aligned instead.

# The "sequence" column is in debugger/match_legend.md's tokens, a "/"
# before the HD6309's native mode variant. A page's 1 follows a prefix's;
# the IX table's fragments take the place of a #, after the postbyte. A
# and B are at the operand's address; J goes to the operand, a branch's to
# the next + disp; x is a dummy read of FFFF.

BEGIN {
    if (MODE == "")
        MODE = "table";
    if (MODE != "table" && MODE != "pretty") {
        print "MODE must be table or pretty" > "/dev/stderr";
        exit 1;
    }
    PRETTY_PRINT = MODE == "pretty";
    GENERATE_TABLE = MODE == "table";
    GENERATED_BY = generated_by("inst_hd6309.awk");
}

# The command that made the tables, wrapped to 80 columns so clang-format
# keeps it.
function generated_by(script,  i, cmd, line, word) {
    cmd = "";
    line = "// Generated by: gawk -f " script;
    for (i = 1; i <= ARGC; i++) {
        word = (i < ARGC) ? ARGV[i] : "| clang-format";
        if (length(line) + 1 + length(word) > 78) {
            cmd = cmd line "\n";
            line = "//     " word;
        } else {
            line = line " " word;
        }
    }
    return cmd line;
}

# Read the inputs twice: the first pass collects CYCLES in first-seen order,
# the second generates the tables.
BEGIN {
    if (GENERATE_TABLE) {
        NINPUTS = ARGC - 1;
        for (i = 1; i <= NINPUTS; i++)
            ARGV[ARGC++] = ARGV[i];
        COLLECTING = 1;
        GENERATE_TABLE = 0;
        GENERATE_CYCLES = 1;
    }
}

FNR == 1 && COLLECTING && ++NOPENED > NINPUTS {
    COLLECTING = 0;
    GENERATE_CYCLES = 0;
    GENERATE_TABLE = 1;
}

function print_number(n, len, num, rem) {
    len = match(n, /^[0-9]+/);
    if (len == 0) {
        printf("%2s    ", n);
    } else if (length(n) == RLENGTH) {
        printf("%2d    ", n);
    } else {
        num = substr(n, RSTART, RLENGTH);
        rem = length(n) - RLENGTH;
        printf("%2d%s", num, substr(n, RLENGTH+1));
        for (num = rem; num <= 3; ++num)
            printf(" ");
    }
}

function pretty_print(opc, nem, opr, clk, len, seq) {
    if (PRETTY_PRINT == 0)
        return;
    printf("%-2s  %-9s  %-5s  ", opc, nem, opr);
    print_number(clk);
    printf(" ");
    print_number(len);
    printf(" %s\n", seq);
}

function extract_number(str) {
    if (str == "-")
        return 0;
    sub(/[/+]+/, "", str);
    return str;
}

function tokens(seq, tok,  n, s, c) {
    n = 0;
    if (seq == "-")
        return 0;
    for (s = 1; s <= length(seq); ++s) {
        c = substr(seq, s, 1);
        if (c == "@")
            break;
        if (c ~ /[+-]/ && substr(seq, s + 1, 1) ~ /[1-9]/) {
            ++s;
            continue;
        }
        if (c ~ /[{}0.]/)
            continue;
        tok[++n] = c;
    }
    return n;
}

function inst_len(seq,  tok, n, i, len) {
    n = tokens(seq, tok);
    len = 0;
    for (i = 1; i <= n; ++i)
        if (tok[i] ~ /[12]/)
            ++len;
    return len;
}

# Its next fetch looked at: one token takes no cycle.
function clock(seq,  tok) {
    return seq == "-" ? 0 : tokens(seq, tok) - 1;
}

function CYCLES_index(cyc, i) {
    for (i in CYCLES) {
        if (CYCLES[i] == cyc)
            return i;
    }
    return 0;
}

function add_CYCLES(cyc, n) {
    n = length(CYCLES);
    CYCLES[++n] = cyc;
}

function append_CYCLES(seq, cyc) {
    if (seq != "-")  {
        cyc = seq;
        gsub(":", "", cyc);
        if (CYCLES_index(cyc) == 0) {
            add_CYCLES(cyc);
            return 1;
        }
    }
    return 0;
}

function generate_CYCLES(seq) {
    if (GENERATE_CYCLES == 1)
        append_CYCLES(seq);
}

function generate_TABLE() {
    printf("%s\n", GENERATED_BY);
    printf("constexpr const char *const SEQUENCES[/*seq*/] = {\n");
    printf("        \"%s\",  // %2d\n", "", 0);
    for (c = 1; c <= length(CYCLES); c++) {
        cyc = CYCLES[c];
        printf("        \"%s\",  // %2d\n", cyc, c);
    }
    printf("};\n");
}

function generate_ENTRY(opc, nem, opr, clk, len, seq, cyc) {
    if (GENERATE_TABLE == 0)
        return;
    cyc = seq;
    gsub(":", "", cyc);
    printf("        %d,   // %s: %-9s %-5s ",
           CYCLES_index(cyc), opc, nem, opr);
    print_number(clk);
    print_number(len);
    printf("%s\n", seq);
}

BEGIN {
    pretty_print("op", "nemo", "oper",  " ~", " #", "sequence");
    pretty_print("--", "----", "-----", "--", "--", "--------");
}

$1 !~ /[0-9A-F][0-9A-F]/ { next; }
$1 ~ /[0-9A-F][0-9A-F]/ {
    opc = $1;
    nem = $2;
    opr = $3;
    clk = $4;
    len = $5;
    seq = ($6 == "") ? "-" : $6;

    if (GENERATE_TABLE && opc == "00") {
        if (match(FILENAME, /hd6309-([A-Z0-9]+).txt/, a) == 0) {
            printf("Unknown file: %s\n", FILENAME) > "/dev/stderr"
            exit;
        }
        if (FILENAME == "hd6309-IX.txt")
            generate_TABLE();
        page = a[1];
        printf("\nconstexpr uint8_t %s_TABLE[] = {\n", page);
    }

    # if (inst_len(seq) != extract_number(len)) {
    #     printf("@@ instruction length (#) mismatches with sequence\n");
    #     print $0;
    # }
    # if (clock(seq) != extract_number(clk)) {
    #     printf("@@ instruction clock (~) mismatches with sequence\n");
    #     print $0;
    # }

    pretty_print(opc, nem, opr, clk, len, seq);
    generate_CYCLES(seq);
    generate_ENTRY(opc, nem, opr, clk, len, seq);

    if (GENERATE_TABLE && opc == "FF")
        printf("};\n");
}
