#include "inst_hd6309.h"
#include <string.h>

namespace debugger {
namespace hd6309 {

namespace {
// Sequences: debugger/match_legend.md. The MC6809's interrupts, and the
// HD6309's, its native mode's too.
constexpr const char INTERRUPT_6809[] = "XXxwWWWWWWWWWWWxVrxP@XXxwWWxVrxP";
constexpr const char INTERRUPT_6309[] =
        "XXxwWWWWWWWWWWWxVrxP@XXxwWWxVrxP"
        // native: a read more before the pushes, and E and F pushed
        "@XXXxwWWxVrxP@XXXxwWWWWWWWWWWWWWxVrxP";

// Generated by: gawk -f inst_hd6309.awk hd6309-IX.txt hd6309-P00.txt
//     hd6309-P10.txt hd6309-P11.txt | clang-format
constexpr const char *const SEQUENCES[/*seq*/] = {
        "",                                             //  0
        "nx",                                           //  1
        "nxx/nx",                                       //  2
        "nxxx/nxx",                                     //  3
        "n",                                            //  4
        "2x",                                           //  5
        "22Xxx/22xx",                                   //  6
        "nXXxx/nXx",                                    //  7
        "22Xxxx/22xx",                                  //  8
        "nRrx",                                         //  9
        "nxxxRrx/nxxRrx",                               // 10
        "nxxxRrx/nxxRrX",                               // 11
        "nxRrx",                                        // 12
        "2xRrx",                                        // 13
        "22XxxRrx/22xxRrx",                             // 14
        "nXXxxRrx/nXxRrx",                              // 15
        "22XxxxRrx/22xxRrx",                            // 16
        "22XRrx/22Rrx",                                 // 17
        "22x",                                          // 18
        "22xRrx",                                       // 19
        "12xRxWN/12RxWN",                               // 20
        "122RxWN",                                      // 21
        "122RN",                                        // 22
        "12xRxxN/12RxN",                                // 23
        "12x?/12?",                                     // 24
        "1nN/1N",                                       // 25
        "1nXXN",                                        // 26
        "1nxxN",                                        // 27
        "122xxJ@122xxN/122xJ@122xN",                    // 28
        "122xxXxwWJ@122xxXxwWN/122xxwWJ@122xxwWN",      // 29
        "12nN/12xN",                                    // 30
        "12xxxxxxN/12xxxN",                             // 31
        "12xxxxN/12xxN",                                // 32
        "12xJ@12xN",                                    // 33
        "12xN",                                         // 34
        "12#xN",                                        // 35
        "12xxX>N/12xX>N",                               // 36
        "12xx<X?/12x<X?",                               // 37
        "1nRrxP/1nRrP",                                 // 38
        "1nxN/1N",                                      // 39
        "1nRrrrrrrrrrrrXP@1nRrrXP/1nRrrrrrrrrrrrrrXP",  // 40
        "12nxwWWWWWWWWWWWN/12nxwWWWWWWWWWWWWWN",        // 41
        "1n{x}N",                                       // 42
        "1nxwWWWWWWWWWWWxVrxP/1nxwWWWWWWWWWWWWWXVrxP",  // 43
        "12#RxWN",                                      // 44
        "122#RxWN",                                     // 45
        "122#RN",                                       // 46
        "12#RxxN/12#RxN",                               // 47
        "12#?",                                         // 48
        "122xAxBN/122RxWN",                             // 49
        "1222AxBN",                                     // 50
        "1222AN",                                       // 51
        "122xAxxN/122RxN",                              // 52
        "122xJ/122J",                                   // 53
        "12N",                                          // 54
        "122xN/122N",                                   // 55
        "12xXxwWJ@12xXxwWN/12xxwWJ@12xxwWN",            // 56
        "122N",                                         // 57
        "12xRN/12RN",                                   // 58
        "12xRrxN/12RrN",                                // 59
        "12xWN/12WN",                                   // 60
        "12xXxwW?/12xXwW?",                             // 61
        "12xRrN/12RrN",                                 // 62
        "12xWwN/12WwN",                                 // 63
        "12#RN",                                        // 64
        "12#RrxN/12#RrN",                               // 65
        "12#WN",                                        // 66
        "12#XxwW?/12#XwW?",                             // 67
        "12#RrN",                                       // 68
        "12#WwN",                                       // 69
        "122xAN/122AN",                                 // 70
        "122xArxN/122ArN",                              // 71
        "122xWN/122WN",                                 // 72
        "122xAxwWJ/122xAwWJ",                           // 73
        "122xArN/122ArN",                               // 74
        "122xWwN/122WwN",                               // 75
        "12222N",                                       // 76
        "122xBN/122BN",                                 // 77
        "122xBwN/122BwN",                               // 78
        "122xN",                                        // 79
        "122xN@122xxJ@122xxN/122xJ@122xN",              // 80
        "1nxwWN",                                       // 81
        "1nxRrN",                                       // 82
        "12xRrrrN/12RrrrN",                             // 83
        "12xWwwwN/12WwwwN",                             // 84
        "12#RrrrN",                                     // 85
        "12#WwwwN",                                     // 86
        "122xArrrN/122ArrrN",                           // 87
        "122xBwwwN/122BwwwN",                           // 88
        "122xRxN/122RxN",                               // 89
        "122xRxWN/122RxWN",                             // 90
        "12xxx{R+1xW+1}N",                              // 91
        "12xxx{R-1xW-1}N",                              // 92
        "12xxx{R+1xW0}N",                               // 93
        "12xxx{R0xW+1}N",                               // 94
        "12XxN",                                        // 95
        "12{x}N",                                       // 96
        "122{x}N",                                      // 97
        "12xR{x}N/12R{x}N",                             // 98
        "12xRr{x}N/12Rr{x}N",                           // 99
        "12#R{x}N",                                     // 100
        "12#Rr{x}N",                                    // 101
        "122xR{x}N/122R{x}N",                           // 102
        "122xRr{x}N/122Rr{x}N",                         // 103
};

constexpr uint8_t IX_TABLE[] = {
        1,   // 00: 0,X       -      1     0    nx
        1,   // 01: 1,X       -      1     0    nx
        1,   // 02: 2,X       -      1     0    nx
        1,   // 03: 3,X       -      1     0    nx
        1,   // 04: 4,X       -      1     0    nx
        1,   // 05: 5,X       -      1     0    nx
        1,   // 06: 6,X       -      1     0    nx
        1,   // 07: 7,X       -      1     0    nx
        1,   // 08: 8,X       -      1     0    nx
        1,   // 09: 9,X       -      1     0    nx
        1,   // 0A: 10,X      -      1     0    nx
        1,   // 0B: 11,X      -      1     0    nx
        1,   // 0C: 12,X      -      1     0    nx
        1,   // 0D: 13,X      -      1     0    nx
        1,   // 0E: 14,X      -      1     0    nx
        1,   // 0F: 15,X      -      1     0    nx
        1,   // 10: -16,X     -      1     0    nx
        1,   // 11: -15,X     -      1     0    nx
        1,   // 12: -14,X     -      1     0    nx
        1,   // 13: -13,X     -      1     0    nx
        1,   // 14: -12,X     -      1     0    nx
        1,   // 15: -11,X     -      1     0    nx
        1,   // 16: -10,X     -      1     0    nx
        1,   // 17: -9,X      -      1     0    nx
        1,   // 18: -8,X      -      1     0    nx
        1,   // 19: -7,X      -      1     0    nx
        1,   // 1A: -6,X      -      1     0    nx
        1,   // 1B: -5,X      -      1     0    nx
        1,   // 1C: -4,X      -      1     0    nx
        1,   // 1D: -3,X      -      1     0    nx
        1,   // 1E: -2,X      -      1     0    nx
        1,   // 1F: -1,X      -      1     0    nx
        1,   // 20: 0,Y       -      1     0    nx
        1,   // 21: 1,Y       -      1     0    nx
        1,   // 22: 2,Y       -      1     0    nx
        1,   // 23: 3,Y       -      1     0    nx
        1,   // 24: 4,Y       -      1     0    nx
        1,   // 25: 5,Y       -      1     0    nx
        1,   // 26: 6,Y       -      1     0    nx
        1,   // 27: 7,Y       -      1     0    nx
        1,   // 28: 8,Y       -      1     0    nx
        1,   // 29: 9,Y       -      1     0    nx
        1,   // 2A: 10,Y      -      1     0    nx
        1,   // 2B: 11,Y      -      1     0    nx
        1,   // 2C: 12,Y      -      1     0    nx
        1,   // 2D: 13,Y      -      1     0    nx
        1,   // 2E: 14,Y      -      1     0    nx
        1,   // 2F: 15,Y      -      1     0    nx
        1,   // 30: -16,Y     -      1     0    nx
        1,   // 31: -15,Y     -      1     0    nx
        1,   // 32: -14,Y     -      1     0    nx
        1,   // 33: -13,Y     -      1     0    nx
        1,   // 34: -12,Y     -      1     0    nx
        1,   // 35: -11,Y     -      1     0    nx
        1,   // 36: -10,Y     -      1     0    nx
        1,   // 37: -9,Y      -      1     0    nx
        1,   // 38: -8,Y      -      1     0    nx
        1,   // 39: -7,Y      -      1     0    nx
        1,   // 3A: -6,Y      -      1     0    nx
        1,   // 3B: -5,Y      -      1     0    nx
        1,   // 3C: -4,Y      -      1     0    nx
        1,   // 3D: -3,Y      -      1     0    nx
        1,   // 3E: -2,Y      -      1     0    nx
        1,   // 3F: -1,Y      -      1     0    nx
        1,   // 40: 0,U       -      1     0    nx
        1,   // 41: 1,U       -      1     0    nx
        1,   // 42: 2,U       -      1     0    nx
        1,   // 43: 3,U       -      1     0    nx
        1,   // 44: 4,U       -      1     0    nx
        1,   // 45: 5,U       -      1     0    nx
        1,   // 46: 6,U       -      1     0    nx
        1,   // 47: 7,U       -      1     0    nx
        1,   // 48: 8,U       -      1     0    nx
        1,   // 49: 9,U       -      1     0    nx
        1,   // 4A: 10,U      -      1     0    nx
        1,   // 4B: 11,U      -      1     0    nx
        1,   // 4C: 12,U      -      1     0    nx
        1,   // 4D: 13,U      -      1     0    nx
        1,   // 4E: 14,U      -      1     0    nx
        1,   // 4F: 15,U      -      1     0    nx
        1,   // 50: -16,U     -      1     0    nx
        1,   // 51: -15,U     -      1     0    nx
        1,   // 52: -14,U     -      1     0    nx
        1,   // 53: -13,U     -      1     0    nx
        1,   // 54: -12,U     -      1     0    nx
        1,   // 55: -11,U     -      1     0    nx
        1,   // 56: -10,U     -      1     0    nx
        1,   // 57: -9,U      -      1     0    nx
        1,   // 58: -8,U      -      1     0    nx
        1,   // 59: -7,U      -      1     0    nx
        1,   // 5A: -6,U      -      1     0    nx
        1,   // 5B: -5,U      -      1     0    nx
        1,   // 5C: -4,U      -      1     0    nx
        1,   // 5D: -3,U      -      1     0    nx
        1,   // 5E: -2,U      -      1     0    nx
        1,   // 5F: -1,U      -      1     0    nx
        1,   // 60: 0,S       -      1     0    nx
        1,   // 61: 1,S       -      1     0    nx
        1,   // 62: 2,S       -      1     0    nx
        1,   // 63: 3,S       -      1     0    nx
        1,   // 64: 4,S       -      1     0    nx
        1,   // 65: 5,S       -      1     0    nx
        1,   // 66: 6,S       -      1     0    nx
        1,   // 67: 7,S       -      1     0    nx
        1,   // 68: 8,S       -      1     0    nx
        1,   // 69: 9,S       -      1     0    nx
        1,   // 6A: 10,S      -      1     0    nx
        1,   // 6B: 11,S      -      1     0    nx
        1,   // 6C: 12,S      -      1     0    nx
        1,   // 6D: 13,S      -      1     0    nx
        1,   // 6E: 14,S      -      1     0    nx
        1,   // 6F: 15,S      -      1     0    nx
        1,   // 70: -16,S     -      1     0    nx
        1,   // 71: -15,S     -      1     0    nx
        1,   // 72: -14,S     -      1     0    nx
        1,   // 73: -13,S     -      1     0    nx
        1,   // 74: -12,S     -      1     0    nx
        1,   // 75: -11,S     -      1     0    nx
        1,   // 76: -10,S     -      1     0    nx
        1,   // 77: -9,S      -      1     0    nx
        1,   // 78: -8,S      -      1     0    nx
        1,   // 79: -7,S      -      1     0    nx
        1,   // 7A: -6,S      -      1     0    nx
        1,   // 7B: -5,S      -      1     0    nx
        1,   // 7C: -4,S      -      1     0    nx
        1,   // 7D: -3,S      -      1     0    nx
        1,   // 7E: -2,S      -      1     0    nx
        1,   // 7F: -1,S      -      1     0    nx
        2,   // 80: ,X+       -      2/1   0    nxx/nx
        3,   // 81: ,X++      -      3/2   0    nxxx/nxx
        2,   // 82: ,-X       -      2/1   0    nxx/nx
        3,   // 83: ,--X      -      3/2   0    nxxx/nxx
        4,   // 84: ,X        -      0     0    n
        1,   // 85: B,X       -      1     0    nx
        1,   // 86: A,X       -      1     0    nx
        1,   // 87: E,X       -      1     0    nx
        5,   // 88: n8,X      -      1     1    2x
        6,   // 89: n16,X     -      4/3   2    22Xxx/22xx
        1,   // 8A: F,X       -      1     0    nx
        7,   // 8B: D,X       -      4/2   0    nXXxx/nXx
        5,   // 8C: n8,PCR    -      1     1    2x
        8,   // 8D: n16,PCR   -      5/3   2    22Xxxx/22xx
        1,   // 8E: W,X       -      1     0    nx
        4,   // 8F: ,W        -      0     0    n
        9,   // 90: [,W]      -      3     0    nRrx
        10,  // 91: [,X++]    -      6/5   0    nxxxRrx/nxxRrx
        0,   // 92: -         -      -     -    -
        11,  // 93: [,--X]    -      6/5   0    nxxxRrx/nxxRrX
        9,   // 94: [,X]      -      3     0    nRrx
        12,  // 95: [B,X]     -      4     0    nxRrx
        12,  // 96: [A,X]     -      4     0    nxRrx
        12,  // 97: [E,X]     -      4     0    nxRrx
        13,  // 98: [n8,X]    -      4     1    2xRrx
        14,  // 99: [n16,X]   -      7/6   2    22XxxRrx/22xxRrx
        12,  // 9A: [F,X]     -      4     0    nxRrx
        15,  // 9B: [D,X]     -      7/5   0    nXXxxRrx/nXxRrx
        13,  // 9C: [n8,PCR]  -      4     1    2xRrx
        16,  // 9D: [n16,PCR] -      8/6   2    22XxxxRrx/22xxRrx
        12,  // 9E: [W,X]     4      -     0    nxRrx
        17,  // 9F: [a16]     5/4    -     2    22XRrx/22Rrx
        2,   // A0: ,Y+       -      2/1   0    nxx/nx
        3,   // A1: ,Y++      -      3/2   0    nxxx/nxx
        2,   // A2: ,-Y       -      2/1   0    nxx/nx
        3,   // A3: ,--Y      -      3/2   0    nxxx/nxx
        4,   // A4: ,Y        -      0     0    n
        1,   // A5: B,Y       -      1     0    nx
        1,   // A6: A,Y       -      1     0    nx
        1,   // A7: E,Y       -      1     0    nx
        5,   // A8: n8,Y      -      1     1    2x
        6,   // A9: n16,Y     -      4/3   2    22Xxx/22xx
        1,   // AA: F,Y       -      1     0    nx
        7,   // AB: D,Y       -      4/2   0    nXXxx/nXx
        5,   // AC: n8,PCR    -      1     1    2x
        8,   // AD: n16,PCR   -      5/3   2    22Xxxx/22xx
        1,   // AE: W,Y       -      1     0    nx
        18,  // AF: n16,W     -      2     2    22x
        19,  // B0: [n16,W]   -      5     2    22xRrx
        10,  // B1: [,Y++]    -      6/5   0    nxxxRrx/nxxRrx
        0,   // B2: -         -      -     -    -
        11,  // B3: [,--Y]    -      6/5   0    nxxxRrx/nxxRrX
        9,   // B4: [,Y]      -      3     0    nRrx
        12,  // B5: [B,Y]     -      4     0    nxRrx
        12,  // B6: [A,Y]     -      4     0    nxRrx
        12,  // B7: [E,Y]     -      4     0    nxRrx
        13,  // B8: [n8,Y]    -      4     1    2xRrx
        14,  // B9: [n16,Y]   -      7/6   2    22XxxRrx/22xxRrx
        12,  // BA: [F,Y]     -      4     0    nxRrx
        15,  // BB: [D,Y]     -      7/5   0    nXXxxRrx/nXxRrx
        13,  // BC: [n8,PCR]  -      4     1    2xRrx
        16,  // BD: [n16,PCR] -      8/6   2    22XxxxRrx/22xxRrx
        12,  // BE: [W,Y]     4      -     0    nxRrx
        0,   // BF: -         -      -     -    -
        2,   // C0: ,U+       -      2/1   0    nxx/nx
        3,   // C1: ,U++      -      3/2   0    nxxx/nxx
        2,   // C2: ,-U       -      2/1   0    nxx/nx
        3,   // C3: ,--U      -      3/2   0    nxxx/nxx
        4,   // C4: ,U        -      0     0    n
        1,   // C5: B,U       -      1     0    nx
        1,   // C6: A,U       -      1     0    nx
        1,   // C7: E,U       -      1     0    nx
        5,   // C8: n8,U      -      1     1    2x
        6,   // C9: n16,U     -      4/3   2    22Xxx/22xx
        1,   // CA: F,U       -      1     0    nx
        7,   // CB: D,U       -      4/2   0    nXXxx/nXx
        5,   // CC: n8,PCR    -      1     1    2x
        8,   // CD: n16,PCR   -      5/3   2    22Xxxx/22xx
        1,   // CE: W,U       -      1     0    nx
        1,   // CF: ,W++      -      1     0    nx
        12,  // D0: [,W++]    -      4     0    nxRrx
        10,  // D1: [,U++]    -      6/5   0    nxxxRrx/nxxRrx
        0,   // D2: -         -      -     -    -
        11,  // D3: [,--U]    -      6/5   0    nxxxRrx/nxxRrX
        9,   // D4: [,U]      -      3     0    nRrx
        12,  // D5: [B,U]     -      4     0    nxRrx
        12,  // D6: [A,U]     -      4     0    nxRrx
        12,  // D7: [E,U]     -      4     0    nxRrx
        13,  // D8: [n8,U]    -      4     1    2xRrx
        14,  // D9: [n16,U]   -      7/6   2    22XxxRrx/22xxRrx
        12,  // DA: [F,U]     -      4     0    nxRrx
        15,  // DB: [D,U]     -      7/5   0    nXXxxRrx/nXxRrx
        13,  // DC: [n8,PCR]  -      4     1    2xRrx
        16,  // DD: [n16,PCR] -      8/6   2    22XxxxRrx/22xxRrx
        12,  // DE: [W,U]     4      -     0    nxRrx
        0,   // DF: -         -      -     -    -
        2,   // E0: ,S+       -      2/1   0    nxx/nx
        3,   // E1: ,S++      -      3/2   0    nxxx/nxx
        2,   // E2: ,-S       -      2/1   0    nxx/nx
        3,   // E3: ,--S      -      3/2   0    nxxx/nxx
        4,   // E4: ,S        -      0     0    n
        1,   // E5: B,S       -      1     0    nx
        1,   // E6: A,S       -      1     0    nx
        1,   // E7: E,S       -      1     0    nx
        5,   // E8: n8,S      -      1     1    2x
        6,   // E9: n16,S     -      4/3   2    22Xxx/22xx
        1,   // EA: F,S       -      1     0    nx
        7,   // EB: D,S       -      4/2   0    nXXxx/nXx
        5,   // EC: n8,PCR    -      1     1    2x
        8,   // ED: n16,PCR   -      5/3   2    22Xxxx/22xx
        1,   // EE: W,S       -      1     0    nx
        1,   // EF: ,--W      -      1     0    nx
        12,  // F0: [,--W]    -      4     0    nxRrx
        10,  // F1: [,S++]    -      6/5   0    nxxxRrx/nxxRrx
        0,   // F2: -         -      -     -    -
        11,  // F3: [,--S]    -      6/5   0    nxxxRrx/nxxRrX
        9,   // F4: [,S]      -      3     0    nRrx
        12,  // F5: [B,S]     -      4     0    nxRrx
        12,  // F6: [A,S]     -      4     0    nxRrx
        12,  // F7: [E,S]     -      4     0    nxRrx
        13,  // F8: [n8,S]    -      4     1    2xRrx
        14,  // F9: [n16,S]   -      7/6   2    22XxxRrx/22xxRrx
        12,  // FA: [F,S]     -      4     0    nxRrx
        15,  // FB: [D,S]     -      7/5   0    nXXxxRrx/nXxRrx
        13,  // FC: [n8,PCR]  -      4     1    2xRrx
        16,  // FD: [n16,PCR] -      8/6   2    22XxxxRrx/22xxRrx
        12,  // FE: [W,S]     4      -     0    nxRrx
        0,   // FF: -         -      -     -    -
};

constexpr uint8_t P00_TABLE[] = {
        20,  // 00: NEG       d8     6/5   2    12xRxWN/12RxWN
        21,  // 01: OIM       #,d8   6     3    122RxWN
        21,  // 02: AIM       #,d8   6     3    122RxWN
        20,  // 03: COM       d8     6/5   2    12xRxWN/12RxWN
        20,  // 04: LSR       d8     6/5   2    12xRxWN/12RxWN
        21,  // 05: EIM       #,d8   6     3    122RxWN
        20,  // 06: ROR       d8     6/5   2    12xRxWN/12RxWN
        20,  // 07: ASR       d8     6/5   2    12xRxWN/12RxWN
        20,  // 08: ASL       d8     6/5   2    12xRxWN/12RxWN
        20,  // 09: ROL       d8     6/5   2    12xRxWN/12RxWN
        20,  // 0A: DEC       d8     6/5   2    12xRxWN/12RxWN
        22,  // 0B: TIM       #,d8   4     3    122RN
        20,  // 0C: INC       d8     6/5   2    12xRxWN/12RxWN
        23,  // 0D: TST       d8     6/4   2    12xRxxN/12RxN
        24,  // 0E: JMP       d8     3/2   2    12x?/12?
        20,  // 0F: CLR       d8     6/5   2    12xRxWN/12RxWN
        0,   // 10: P10       -      1+    1+   -
        0,   // 11: P11       -      1+    1+   -
        25,  // 12: NOP       -      2/1   1    1nN/1N
        26,  // 13: SYNC      -      4     1    1nXXN
        27,  // 14: SEXW      -      4     1    1nxxN
        0,   // 15: -         -      -     -    -
        28,  // 16: LBRA      r16    5/4   3    122xxJ@122xxN/122xJ@122xN
        29,  // 17: LBSR      r16    9/7   3
             // 122xxXxwWJ@122xxXxwWN/122xxwWJ@122xxwWN
        0,   // 18: -         -      -     -    -
        25,  // 19: DAA       -      2/1   1    1nN/1N
        30,  // 1A: ORCC      #n8    3     2    12nN/12xN
        0,   // 1B: -         -      -     -    -
        30,  // 1C: ANDCC     #n8    3     2    12nN/12xN
        25,  // 1D: SEX       -      2/1   1    1nN/1N
        31,  // 1E: EXG       #n8    8/5   2    12xxxxxxN/12xxxN
        32,  // 1F: TFR       #n8    6/4   2    12xxxxN/12xxN
        33,  // 20: BRA       r8     3     2    12xJ@12xN
        34,  // 21: BRN       r8     3     2    12xN
        33,  // 22: BHI       r8     3     2    12xJ@12xN
        33,  // 23: BLS       r8     3     2    12xJ@12xN
        33,  // 24: BCC       r8     3     2    12xJ@12xN
        33,  // 25: BCS       r8     3     2    12xJ@12xN
        33,  // 26: BNE       r8     3     2    12xJ@12xN
        33,  // 27: BEQ       r8     3     2    12xJ@12xN
        33,  // 28: BVC       r8     3     2    12xJ@12xN
        33,  // 29: BVS       r8     3     2    12xJ@12xN
        33,  // 2A: BPL       r8     3     2    12xJ@12xN
        33,  // 2B: BMI       r8     3     2    12xJ@12xN
        33,  // 2C: BGE       r8     3     2    12xJ@12xN
        33,  // 2D: BLT       r8     3     2    12xJ@12xN
        33,  // 2E: BGT       r8     3     2    12xJ@12xN
        33,  // 2F: BLE       r8     3     2    12xJ@12xN
        35,  // 30: LEAX      ix     4+    2+   12#xN
        35,  // 31: LEAY      ix     4+    2+   12#xN
        35,  // 32: LEAS      ix     4+    2+   12#xN
        35,  // 33: LEAU      ix     4+    2+   12#xN
        36,  // 34: PSHS      #n8    5+/4+ 2    12xxX>N/12xX>N
        37,  // 35: PULS      #n8    5+/4+ 2    12xx<X?/12x<X?
        36,  // 36: PSHU      #n8    5+/4+ 2    12xxX>N/12xX>N
        37,  // 37: PULU      #n8    5+/4+ 2    12xx<X?/12x<X?
        0,   // 38: -         -      -     -    -
        38,  // 39: RTS       -      5/4   1    1nRrxP/1nRrP
        39,  // 3A: ABX       -      3/1   1    1nxN/1N
        40,  // 3B: RTI       -     15/17  1
             // 1nRrrrrrrrrrrrXP@1nRrrXP/1nRrrrrrrrrrrrrrXP
        41,  // 3C: CWAI      -     20/22  2
             // 12nxwWWWWWWWWWWWN/12nxwWWWWWWWWWWWWWN
        42,  // 3D: MUL       -     11/10  1    1n{x}N
        0,   // 3E: -         -      -     -    -
        43,  // 3F: SWI       -     19/21  1
             // 1nxwWWWWWWWWWWWxVrxP/1nxwWWWWWWWWWWWWWXVrxP
        25,  // 40: NEGA      -      2/1   1    1nN/1N
        0,   // 41: -         -      -     -    -
        0,   // 42: -         -      -     -    -
        25,  // 43: COMA      -      2/1   1    1nN/1N
        25,  // 44: LSRA      -      2/1   1    1nN/1N
        0,   // 45: -         -      -     -    -
        25,  // 46: RORA      -      2/1   1    1nN/1N
        25,  // 47: ASRA      -      2/1   1    1nN/1N
        25,  // 48: ASLA      -      2/1   1    1nN/1N
        25,  // 49: ROLA      -      2/1   1    1nN/1N
        25,  // 4A: DECA      -      2/1   1    1nN/1N
        0,   // 4B: -         -      -     -    -
        25,  // 4C: INCA      -      2/1   1    1nN/1N
        25,  // 4D: TSTA      -      2/1   1    1nN/1N
        0,   // 4E: -         -      -     -    -
        25,  // 4F: CLRA      -      2/1   1    1nN/1N
        25,  // 50: NEGB      -      2/1   1    1nN/1N
        0,   // 51: -         -      -     -    -
        0,   // 52: -         -      -     -    -
        25,  // 53: COMB      -      2/1   1    1nN/1N
        25,  // 54: LSRB      -      2/1   1    1nN/1N
        0,   // 55: -         -      -     -    -
        25,  // 56: RORB      -      2/1   1    1nN/1N
        25,  // 57: ASRB      -      2/1   1    1nN/1N
        25,  // 58: ASLB      -      2/1   1    1nN/1N
        25,  // 59: ROLB      -      2/1   1    1nN/1N
        25,  // 5A: DECB      -      2/1   1    1nN/1N
        0,   // 5B: -         -      -     -    -
        25,  // 5C: INCB      -      2/1   1    1nN/1N
        25,  // 5D: TSTB      -      2/1   1    1nN/1N
        0,   // 5E: -         -      -     -    -
        25,  // 5F: CLRB      -      2/1   1    1nN/1N
        44,  // 60: NEG       ix     6+    2    12#RxWN
        45,  // 61: OIM       #,ix   7+    3+   122#RxWN
        45,  // 62: AIM       #,ix   7+    3+   122#RxWN
        44,  // 63: COM       ix     6+    2+   12#RxWN
        44,  // 64: LSR       ix     6+    2+   12#RxWN
        45,  // 65: EIM       #,ix   7+    3+   122#RxWN
        44,  // 66: ROR       ix     6+    2+   12#RxWN
        44,  // 67: ASR       ix     6+    2+   12#RxWN
        44,  // 68: ASL       ix     6+    2+   12#RxWN
        44,  // 69: ROL       ix     6+    2+   12#RxWN
        44,  // 6A: DEC       ix     6+    2+   12#RxWN
        46,  // 6B: TIM       #,ix   5+    3+   122#RN
        44,  // 6C: INC       ix     6+    2+   12#RxWN
        47,  // 6D: TST       ix     6+/5+ 2+   12#RxxN/12#RxN
        48,  // 6E: JMP       ix     3+    2+   12#?
        44,  // 6F: CLR       ix     6+    2+   12#RxWN
        49,  // 70: NEG       a16    7/6   3    122xAxBN/122RxWN
        50,  // 71: OIM       #,a16  7     4    1222AxBN
        50,  // 72: AIM       #,a16  7     4    1222AxBN
        49,  // 73: COM       a16    7/6   3    122xAxBN/122RxWN
        49,  // 74: LSR       a16    7/6   3    122xAxBN/122RxWN
        50,  // 75: EIM       #,a16  7     4    1222AxBN
        49,  // 76: ROR       a16    7/6   3    122xAxBN/122RxWN
        49,  // 77: ASR       a16    7/6   3    122xAxBN/122RxWN
        49,  // 78: ASL       a16    7/6   3    122xAxBN/122RxWN
        49,  // 79: ROL       a16    7/6   3    122xAxBN/122RxWN
        49,  // 7A: DEC       a16    7/6   3    122xAxBN/122RxWN
        51,  // 7B: TIM       #,a16  5     4    1222AN
        49,  // 7C: INC       a16    7/6   3    122xAxBN/122RxWN
        52,  // 7D: TST       a16    7/5   3    122xAxxN/122RxN
        53,  // 7E: JMP       a16    4/3   3    122xJ/122J
        49,  // 7F: CLR       a16    7/6   3    122xAxBN/122RxWN
        54,  // 80: SUBA      #n8    2     2    12N
        54,  // 81: CMPA      #n8    2     2    12N
        54,  // 82: SBCA      #n8    2     2    12N
        55,  // 83: SUBD      #n16   4/3   3    122xN/122N
        54,  // 84: ANDA      #n8    2     2    12N
        54,  // 85: BITA      #n8    2     2    12N
        54,  // 86: LDA       #n8    2     2    12N
        0,   // 87: -         -      -     -    -
        54,  // 88: EORA      #n8    2     2    12N
        54,  // 89: ADCA      #n8    2     2    12N
        54,  // 8A: ORA       #n8    2     2    12N
        54,  // 8B: ADDA      #n8    2     2    12N
        55,  // 8C: CMPX      #n16   4/3   3    122xN/122N
        56,  // 8D: BSR       r8     7/6   2 12xXxwWJ@12xXxwWN/12xxwWJ@12xxwWN
        57,  // 8E: LDX       #n16   3     3    122N
        0,   // 8F: -         -      -     -    -
        58,  // 90: SUBA      d8     4/3   2    12xRN/12RN
        58,  // 91: CMPA      d8     4/3   2    12xRN/12RN
        58,  // 92: SBCA      d8     4/3   2    12xRN/12RN
        59,  // 93: SUBD      d8     6/4   2    12xRrxN/12RrN
        58,  // 94: ANDA      d8     4/3   2    12xRN/12RN
        58,  // 95: BITA      d8     4/3   2    12xRN/12RN
        58,  // 96: LDA       d8     4/3   2    12xRN/12RN
        60,  // 97: STA       d8     4/3   2    12xWN/12WN
        58,  // 98: EORA      d8     4/3   2    12xRN/12RN
        58,  // 99: ADCA      d8     4/3   2    12xRN/12RN
        58,  // 9A: ORA       d8     4/3   2    12xRN/12RN
        58,  // 9B: ADDA      d8     4/3   2    12xRN/12RN
        59,  // 9C: CMPX      d8     6/4   2    12xRrxN/12RrN
        61,  // 9D: JSR       d8     7/6   2    12xXxwW?/12xXwW?
        62,  // 9E: LDX       d8     5/4   2    12xRrN/12RrN
        63,  // 9F: STX       d8     5/4   2    12xWwN/12WwN
        64,  // A0: SUBA      ix     4+    2+   12#RN
        64,  // A1: CMPA      ix     4+    2+   12#RN
        64,  // A2: SBCA      ix     4+    2+   12#RN
        65,  // A3: SUBD      ix     6+/5+ 2+   12#RrxN/12#RrN
        64,  // A4: ANDA      ix     4+    2+   12#RN
        64,  // A5: BITA      ix     4+    2+   12#RN
        64,  // A6: LDA       ix     4+    2+   12#RN
        66,  // A7: STA       ix     4+    2+   12#WN
        64,  // A8: EORA      ix     4+    2+   12#RN
        64,  // A9: ADCA      ix     4+    2+   12#RN
        64,  // AA: ORA       ix     4+    2+   12#RN
        64,  // AB: ADDA      ix     4+    2+   12#RN
        65,  // AC: CMPX      ix     6+/5+ 2+   12#RrxN/12#RrN
        67,  // AD: JSR       ix     7+/6+ 2+   12#XxwW?/12#XwW?
        68,  // AE: LDX       ix     5+    2+   12#RrN
        69,  // AF: STX       ix     5+    2+   12#WwN
        70,  // B0: SUBA      a16    5/4   3    122xAN/122AN
        70,  // B1: CMPA      a16    5/4   3    122xAN/122AN
        70,  // B2: SBCA      a16    5/4   3    122xAN/122AN
        71,  // B3: SUBD      a16    7/5   3    122xArxN/122ArN
        70,  // B4: ANDA      a16    5/4   3    122xAN/122AN
        70,  // B5: BITA      a16    5/4   3    122xAN/122AN
        70,  // B6: LDA       a16    5/4   3    122xAN/122AN
        72,  // B7: STA       a16    5/4   3    122xWN/122WN
        70,  // B8: EORA      a16    5/4   3    122xAN/122AN
        70,  // B9: ADCA      a16    5/4   3    122xAN/122AN
        70,  // BA: ORA       a16    5/4   3    122xAN/122AN
        70,  // BB: ADDA      a16    5/4   3    122xAN/122AN
        71,  // BC: CMPX      a16    7/5   3    122xArxN/122ArN
        73,  // BD: JSR       a16    8/7   3    122xAxwWJ/122xAwWJ
        74,  // BE: LDX       a16    6/5   3    122xArN/122ArN
        75,  // BF: STX       a16    6/5   3    122xWwN/122WwN
        54,  // C0: SUBB      #n8    2     2    12N
        54,  // C1: CMPB      #n8    2     2    12N
        54,  // C2: SBCB      #n8    2     2    12N
        55,  // C3: ADDD      #n16   4/3   3    122xN/122N
        54,  // C4: ANDB      #n8    2     2    12N
        54,  // C5: BITB      #n8    2     2    12N
        54,  // C6: LDB       #n8    2     2    12N
        0,   // C7: -         -      -     -    -
        54,  // C8: EORB      #n8    2     2    12N
        54,  // C9: ADCB      #n8    2     2    12N
        54,  // CA: ORB       #n8    2     2    12N
        54,  // CB: ADDB      #n8    2     2    12N
        57,  // CC: LDD       #n16   3     3    122N
        76,  // CD: LDQ       #n32   5     5    12222N
        57,  // CE: LDU       #n16   3     3    122N
        0,   // CF: -         -      -     -    -
        58,  // D0: SUBB      d8     4/3   2    12xRN/12RN
        58,  // D1: CMPB      d8     4/3   2    12xRN/12RN
        58,  // D2: SBCB      d8     4/3   2    12xRN/12RN
        59,  // D3: ADDD      d8     6/4   2    12xRrxN/12RrN
        58,  // D4: ANDB      d8     4/3   2    12xRN/12RN
        58,  // D5: BITB      d8     4/3   2    12xRN/12RN
        58,  // D6: LDB       d8     4/3   2    12xRN/12RN
        60,  // D7: STB       d8     4/3   2    12xWN/12WN
        58,  // D8: EORB      d8     4/3   2    12xRN/12RN
        58,  // D9: ADCB      d8     4/3   2    12xRN/12RN
        58,  // DA: ORB       d8     4/3   2    12xRN/12RN
        58,  // DB: ADDB      d8     4/3   2    12xRN/12RN
        62,  // DC: LDD       d8     5/4   2    12xRrN/12RrN
        63,  // DD: STD       d8     5/4   2    12xWwN/12WwN
        62,  // DE: LDU       d8     5/4   2    12xRrN/12RrN
        63,  // DF: STU       d8     5/4   2    12xWwN/12WwN
        64,  // E0: SUBB      ix     4+    2+   12#RN
        64,  // E1: CMPB      ix     4+    2+   12#RN
        64,  // E2: SBCB      ix     4+    2+   12#RN
        65,  // E3: ADDD      ix     6+/5+ 2+   12#RrxN/12#RrN
        64,  // E4: ANDB      ix     4+    2+   12#RN
        64,  // E5: BITB      ix     4+    2+   12#RN
        64,  // E6: LDB       ix     4+    2+   12#RN
        66,  // E7: STB       ix     4+    2+   12#WN
        64,  // E8: EORB      ix     4+    2+   12#RN
        64,  // E9: ADCB      ix     4+    2+   12#RN
        64,  // EA: ORB       ix     4+    2+   12#RN
        64,  // EB: ADDB      ix     4+    2+   12#RN
        68,  // EC: LDD       ix     5+    2+   12#RrN
        69,  // ED: STD       ix     5+    2+   12#WwN
        68,  // EE: LDU       ix     5+    2+   12#RrN
        69,  // EF: STU       ix     5+    2+   12#WwN
        70,  // F0: SUBB      a16    5/4   3    122xAN/122AN
        70,  // F1: CMPB      a16    5/4   3    122xAN/122AN
        70,  // F2: SBCB      a16    5/4   3    122xAN/122AN
        71,  // F3: ADDD      a16    7/5   3    122xArxN/122ArN
        70,  // F4: ANDB      a16    5/4   3    122xAN/122AN
        70,  // F5: BITB      a16    5/4   3    122xAN/122AN
        70,  // F6: LDB       a16    5/4   3    122xAN/122AN
        77,  // F7: STB       a16    5/4   3    122xBN/122BN
        70,  // F8: EORB      a16    5/4   3    122xAN/122AN
        70,  // F9: ADCB      a16    5/4   3    122xAN/122AN
        70,  // FA: ORB       a16    5/4   3    122xAN/122AN
        70,  // FB: ADDB      a16    5/4   3    122xAN/122AN
        74,  // FC: LDD       a16    6/5   3    122xArN/122ArN
        78,  // FD: STD       a16    6/5   3    122xBwN/122BwN
        74,  // FE: LDU       a16    6/5   3    122xArN/122ArN
        78,  // FF: STU       a16    6/5   3    122xBwN/122BwN
};

constexpr uint8_t P10_TABLE[] = {
        0,   // 00: -         -      -     -    -
        0,   // 01: -         -      -     -    -
        0,   // 02: -         -      -     -    -
        0,   // 03: -         -      -     -    -
        0,   // 04: -         -      -     -    -
        0,   // 05: -         -      -     -    -
        0,   // 06: -         -      -     -    -
        0,   // 07: -         -      -     -    -
        0,   // 08: -         -      -     -    -
        0,   // 09: -         -      -     -    -
        0,   // 0A: -         -      -     -    -
        0,   // 0B: -         -      -     -    -
        0,   // 0C: -         -      -     -    -
        0,   // 0D: -         -      -     -    -
        0,   // 0E: -         -      -     -    -
        0,   // 0F: -         -      -     -    -
        0,   // 10: -         -      -     -    -
        0,   // 11: -         -      -     -    -
        0,   // 12: -         -      -     -    -
        0,   // 13: -         -      -     -    -
        0,   // 14: -         -      -     -    -
        0,   // 15: -         -      -     -    -
        0,   // 16: -         -      -     -    -
        0,   // 17: -         -      -     -    -
        0,   // 18: -         -      -     -    -
        0,   // 19: -         -      -     -    -
        0,   // 1A: -         -      -     -    -
        0,   // 1B: -         -      -     -    -
        0,   // 1C: -         -      -     -    -
        0,   // 1D: -         -      -     -    -
        0,   // 1E: -         -      -     -    -
        0,   // 1F: -         -      -     -    -
        0,   // 20: -         -      -     -    -
        79,  // 21: LBRN      r16    4     3    122xN
        80,  // 22: LBHI      r16    4+/4  3    122xN@122xxJ@122xxN/122xJ@122xN
        80,  // 23: LBLS      r16    4+/4  3    122xN@122xxJ@122xxN/122xJ@122xN
        80,  // 24: LBCC      r16    4+/4  3    122xN@122xxJ@122xxN/122xJ@122xN
        80,  // 25: LBCS      r16    4+/4  3    122xN@122xxJ@122xxN/122xJ@122xN
        80,  // 26: LBNE      r16    4+/4  3    122xN@122xxJ@122xxN/122xJ@122xN
        80,  // 27: LBEQ      r16    4+/4  3    122xN@122xxJ@122xxN/122xJ@122xN
        80,  // 28: LBVC      r16    4+/4  3    122xN@122xxJ@122xxN/122xJ@122xN
        80,  // 29: LBVS      r16    4+/4  3    122xN@122xxJ@122xxN/122xJ@122xN
        80,  // 2A: LBPL      r16    4+/4  3    122xN@122xxJ@122xxN/122xJ@122xN
        80,  // 2B: LBMI      r16    4+/4  3    122xN@122xxJ@122xxN/122xJ@122xN
        80,  // 2C: LBGE      r16    4+/4  3    122xN@122xxJ@122xxN/122xJ@122xN
        80,  // 2D: LBLT      r16    4+/4  3    122xN@122xxJ@122xxN/122xJ@122xN
        80,  // 2E: LBGT      r16    4+/4  3    122xN@122xxJ@122xxN/122xJ@122xN
        80,  // 2F: LBLE      r16    4+/4  3    122xN@122xxJ@122xxN/122xJ@122xN
        34,  // 30: ADDR      r,r    3     2    12xN
        34,  // 31: ADCR      r,r    3     2    12xN
        34,  // 32: SUBR      r,r    3     2    12xN
        34,  // 33: SBCR      r,r    3     2    12xN
        34,  // 34: ANDR      r,r    3     2    12xN
        34,  // 35: ORR       r,r    3     2    12xN
        34,  // 36: EORR      r,r    3     2    12xN
        34,  // 37: CMPR      r,r    3     2    12xN
        81,  // 38: PSHSW     -      5     1    1nxwWN
        82,  // 39: PULSW     -      5     1    1nxRrN
        81,  // 3A: PSHUW     -      5     1    1nxwWN
        82,  // 3B: PULUW     -      5     1    1nxRrN
        0,   // 3C: -         -      -     -    -
        0,   // 3D: -         -      -     -    -
        0,   // 3E: -         -      -     -    -
        43,  // 3F: SWI2      -     19/21  1
             // 1nxwWWWWWWWWWWWxVrxP/1nxwWWWWWWWWWWWWWXVrxP
        25,  // 40: NEGD      -      2/1   1    1nN/1N
        0,   // 41: -         -      -     -    -
        0,   // 42: -         -      -     -    -
        25,  // 43: COMD      -      2/1   1    1nN/1N
        25,  // 44: LSRD      -      2/1   1    1nN/1N
        0,   // 45: -         -      -     -    -
        25,  // 46: RORD      -      2/1   1    1nN/1N
        25,  // 47: ASRD      -      2/1   1    1nN/1N
        25,  // 48: ASLD      -      2/1   1    1nN/1N
        25,  // 49: ROLD      -      2/1   1    1nN/1N
        25,  // 4A: DECD      -      2/1   1    1nN/1N
        0,   // 4B: -         -      -     -    -
        25,  // 4C: INCD      -      2/1   1    1nN/1N
        25,  // 4D: TSTD      -      2/1   1    1nN/1N
        0,   // 4E: -         -      -     -    -
        25,  // 4F: CLRD      -      2/1   1    1nN/1N
        0,   // 50: -         -      -     -    -
        0,   // 51: -         -      -     -    -
        0,   // 52: -         -      -     -    -
        25,  // 53: COMW      -      2/1   1    1nN/1N
        25,  // 54: LSRW      -      2/1   1    1nN/1N
        0,   // 55: -         -      -     -    -
        25,  // 56: RORW      -      2/1   1    1nN/1N
        0,   // 57: -         -      -     -    -
        0,   // 58: -         -      -     -    -
        25,  // 59: ROLW      -      2/1   1    1nN/1N
        25,  // 5A: DECW      -      2/1   1    1nN/1N
        0,   // 5B: -         -      -     -    -
        25,  // 5C: INCW      -      2/1   1    1nN/1N
        25,  // 5D: TSTW      -      2/1   1    1nN/1N
        0,   // 5E: -         -      -     -    -
        25,  // 5F: CLRW      -      2/1   1    1nN/1N
        0,   // 60: -         -      -     -    -
        0,   // 61: -         -      -     -    -
        0,   // 62: -         -      -     -    -
        0,   // 63: -         -      -     -    -
        0,   // 64: -         -      -     -    -
        0,   // 65: -         -      -     -    -
        0,   // 66: -         -      -     -    -
        0,   // 67: -         -      -     -    -
        0,   // 68: -         -      -     -    -
        0,   // 69: -         -      -     -    -
        0,   // 6A: -         -      -     -    -
        0,   // 6B: -         -      -     -    -
        0,   // 6C: -         -      -     -    -
        0,   // 6D: -         -      -     -    -
        0,   // 6E: -         -      -     -    -
        0,   // 6F: -         -      -     -    -
        0,   // 70: -         -      -     -    -
        0,   // 71: -         -      -     -    -
        0,   // 72: -         -      -     -    -
        0,   // 73: -         -      -     -    -
        0,   // 74: -         -      -     -    -
        0,   // 75: -         -      -     -    -
        0,   // 76: -         -      -     -    -
        0,   // 77: -         -      -     -    -
        0,   // 78: -         -      -     -    -
        0,   // 79: -         -      -     -    -
        0,   // 7A: -         -      -     -    -
        0,   // 7B: -         -      -     -    -
        0,   // 7C: -         -      -     -    -
        0,   // 7D: -         -      -     -    -
        0,   // 7E: -         -      -     -    -
        0,   // 7F: -         -      -     -    -
        55,  // 80: SUBW      #n16   4/3   3    122xN/122N
        55,  // 81: CMPW      #n16   4/3   3    122xN/122N
        55,  // 82: SBCD      #n16   4/3   3    122xN/122N
        55,  // 83: CMPD      #n16   4/3   3    122xN/122N
        55,  // 84: ANDD      #n16   4/3   3    122xN/122N
        55,  // 85: BITD      #n16   4/3   3    122xN/122N
        57,  // 86: LDW       #n16   3     3    122N
        0,   // 87: -         -      -     -    -
        55,  // 88: EORD      #n16   4/3   3    122xN/122N
        55,  // 89: ADCD      #n16   4/3   3    122xN/122N
        55,  // 8A: ORD       #n16   4/3   3    122xN/122N
        55,  // 8B: ADDW      #n16   4/3   3    122xN/122N
        55,  // 8C: CMPY      #n16   4/3   3    122xN/122N
        0,   // 8D: -         -      -     -    -
        57,  // 8E: LDY       #n16   3     3    122N
        0,   // 8F: -         -      -     -    -
        59,  // 90: SUBW      d8     6/4   2    12xRrxN/12RrN
        59,  // 91: CMPW      d8     6/4   2    12xRrxN/12RrN
        59,  // 92: SBCD      d8     6/4   2    12xRrxN/12RrN
        59,  // 93: CMPD      d8     6/4   2    12xRrxN/12RrN
        59,  // 94: ANDD      d8     6/4   2    12xRrxN/12RrN
        59,  // 95: BITD      d8     6/4   2    12xRrxN/12RrN
        62,  // 96: LDW       d8     5/4   2    12xRrN/12RrN
        63,  // 97: STW       d8     5/4   2    12xWwN/12WwN
        59,  // 98: EORD      d8     6/4   2    12xRrxN/12RrN
        59,  // 99: ADCD      d8     6/4   2    12xRrxN/12RrN
        59,  // 9A: ORD       d8     6/4   2    12xRrxN/12RrN
        59,  // 9B: ADDW      d8     6/4   2    12xRrxN/12RrN
        59,  // 9C: CMPY      d8     6/4   2    12xRrxN/12RrN
        0,   // 9D: -         -      -     -    -
        62,  // 9E: LDY       d8     5/4   2    12xRrN/12RrN
        63,  // 9F: STY       d8     5/4   2    12xWwN/12WwN
        65,  // A0: SUBW      ix     6+/5+ 2+   12#RrxN/12#RrN
        65,  // A1: CMPW      ix     6+/5+ 2+   12#RrxN/12#RrN
        65,  // A2: SBCD      ix     6+/5+ 2+   12#RrxN/12#RrN
        65,  // A3: CMPD      ix     6+/5+ 2+   12#RrxN/12#RrN
        65,  // A4: ANDD      ix     6+/5+ 2+   12#RrxN/12#RrN
        65,  // A5: BITD      ix     6+/5+ 2+   12#RrxN/12#RrN
        68,  // A6: LDW       ix     5+    2+   12#RrN
        69,  // A7: STW       ix     5+    2+   12#WwN
        65,  // A8: EORD      ix     6+/5+ 2+   12#RrxN/12#RrN
        65,  // A9: ADCD      ix     6+/5+ 2+   12#RrxN/12#RrN
        65,  // AA: ORD       ix     6+/5+ 2+   12#RrxN/12#RrN
        65,  // AB: ADDW      ix     6+/5+ 2+   12#RrxN/12#RrN
        65,  // AC: CMPY      ix     6+/5+ 2+   12#RrxN/12#RrN
        0,   // AD: -         -      -     -    -
        68,  // AE: LDY       ix     5+    2+   12#RrN
        69,  // AF: STY       ix     5+    2+   12#WwN
        71,  // B0: SUBW      a16    7/5   3    122xArxN/122ArN
        71,  // B1: CMPW      a16    7/5   3    122xArxN/122ArN
        71,  // B2: SBCD      a16    7/5   3    122xArxN/122ArN
        71,  // B3: CMPD      a16    7/5   3    122xArxN/122ArN
        71,  // B4: ANDD      a16    7/5   3    122xArxN/122ArN
        71,  // B5: BITD      a16    7/5   3    122xArxN/122ArN
        74,  // B6: LDW       a16    6/5   3    122xArN/122ArN
        78,  // B7: STW       a16    6/5   3    122xBwN/122BwN
        71,  // B8: EORD      a16    7/5   3    122xArxN/122ArN
        71,  // B9: ADCD      a16    7/5   3    122xArxN/122ArN
        71,  // BA: ORD       a16    7/5   3    122xArxN/122ArN
        71,  // BB: ADDW      a16    7/5   3    122xArxN/122ArN
        71,  // BC: CMPY      a16    7/5   3    122xArxN/122ArN
        0,   // BD: -         -      -     -    -
        74,  // BE: LDY       a16    6/5   3    122xArN/122ArN
        78,  // BF: STY       a16    6/5   3    122xBwN/122BwN
        0,   // C0: -         -      -     -    -
        0,   // C1: -         -      -     -    -
        0,   // C2: -         -      -     -    -
        0,   // C3: -         -      -     -    -
        0,   // C4: -         -      -     -    -
        0,   // C5: -         -      -     -    -
        0,   // C6: -         -      -     -    -
        0,   // C7: -         -      -     -    -
        0,   // C8: -         -      -     -    -
        0,   // C9: -         -      -     -    -
        0,   // CA: -         -      -     -    -
        0,   // CB: -         -      -     -    -
        0,   // CC: -         -      -     -    -
        0,   // CD: -         -      -     -    -
        57,  // CE: LDS       #16    3     3    122N
        0,   // CF: -         -      -     -    -
        0,   // D0: -         -      -     -    -
        0,   // D1: -         -      -     -    -
        0,   // D2: -         -      -     -    -
        0,   // D3: -         -      -     -    -
        0,   // D4: -         -      -     -    -
        0,   // D5: -         -      -     -    -
        0,   // D6: -         -      -     -    -
        0,   // D7: -         -      -     -    -
        0,   // D8: -         -      -     -    -
        0,   // D9: -         -      -     -    -
        0,   // DA: -         -      -     -    -
        0,   // DB: -         -      -     -    -
        83,  // DC: LDQ       d8     7/6   2    12xRrrrN/12RrrrN
        84,  // DD: STQ       d8     7/6   2    12xWwwwN/12WwwwN
        62,  // DE: LDS       d8     5/4   2    12xRrN/12RrN
        63,  // DF: STS       d8     5/4   2    12xWwN/12WwN
        0,   // E0: -         -      -     -    -
        0,   // E1: -         -      -     -    -
        0,   // E2: -         -      -     -    -
        0,   // E3: -         -      -     -    -
        0,   // E4: -         -      -     -    -
        0,   // E5: -         -      -     -    -
        0,   // E6: -         -      -     -    -
        0,   // E7: -         -      -     -    -
        0,   // E8: -         -      -     -    -
        0,   // E9: -         -      -     -    -
        0,   // EA: -         -      -     -    -
        0,   // EB: -         -      -     -    -
        85,  // EC: LDQ       ix     7+    2+   12#RrrrN
        86,  // ED: STQ       ix     7+    2+   12#WwwwN
        68,  // EE: LDS       ix     5+    2+   12#RrN
        69,  // EF: STS       ix     5+    2+   12#WwN
        0,   // F0: -         -      -     -    -
        0,   // F1: -         -      -     -    -
        0,   // F2: -         -      -     -    -
        0,   // F3: -         -      -     -    -
        0,   // F4: -         -      -     -    -
        0,   // F5: -         -      -     -    -
        0,   // F6: -         -      -     -    -
        0,   // F7: -         -      -     -    -
        0,   // F8: -         -      -     -    -
        0,   // F9: -         -      -     -    -
        0,   // FA: -         -      -     -    -
        0,   // FB: -         -      -     -    -
        87,  // FC: LDQ       a16    8/7   2    122xArrrN/122ArrrN
        88,  // FD: STQ       a16    8/7   2    122xBwwwN/122BwwwN
        74,  // FE: LDS       a16    6/5   3    122xArN/122ArN
        78,  // FF: STS       a16    6/5   3    122xBwN/122BwN
};

constexpr uint8_t P11_TABLE[] = {
        0,    // 00: -         -      -     -    -
        0,    // 01: -         -      -     -    -
        0,    // 02: -         -      -     -    -
        0,    // 03: -         -      -     -    -
        0,    // 04: -         -      -     -    -
        0,    // 05: -         -      -     -    -
        0,    // 06: -         -      -     -    -
        0,    // 07: -         -      -     -    -
        0,    // 08: -         -      -     -    -
        0,    // 09: -         -      -     -    -
        0,    // 0A: -         -      -     -    -
        0,    // 0B: -         -      -     -    -
        0,    // 0C: -         -      -     -    -
        0,    // 0D: -         -      -     -    -
        0,    // 0E: -         -      -     -    -
        0,    // 0F: -         -      -     -    -
        0,    // 10: -         -      -     -    -
        0,    // 11: -         -      -     -    -
        0,    // 12: -         -      -     -    -
        0,    // 13: -         -      -     -    -
        0,    // 14: -         -      -     -    -
        0,    // 15: -         -      -     -    -
        0,    // 16: -         -      -     -    -
        0,    // 17: -         -      -     -    -
        0,    // 18: -         -      -     -    -
        0,    // 19: -         -      -     -    -
        0,    // 1A: -         -      -     -    -
        0,    // 1B: -         -      -     -    -
        0,    // 1C: -         -      -     -    -
        0,    // 1D: -         -      -     -    -
        0,    // 1E: -         -      -     -    -
        0,    // 1F: -         -      -     -    -
        0,    // 20: -         -      -     -    -
        0,    // 21: -         -      -     -    -
        0,    // 22: -         -      -     -    -
        0,    // 23: -         -      -     -    -
        0,    // 24: -         -      -     -    -
        0,    // 25: -         -      -     -    -
        0,    // 26: -         -      -     -    -
        0,    // 27: -         -      -     -    -
        0,    // 28: -         -      -     -    -
        0,    // 29: -         -      -     -    -
        0,    // 2A: -         -      -     -    -
        0,    // 2B: -         -      -     -    -
        0,    // 2C: -         -      -     -    -
        0,    // 2D: -         -      -     -    -
        0,    // 2E: -         -      -     -    -
        0,    // 2F: -         -      -     -    -
        89,   // 30: BAND      b,d8   6/5   3    122xRxN/122RxN
        89,   // 31: BIAND     b,d8   6/5   3    122xRxN/122RxN
        89,   // 32: BOR       b,d8   6/5   3    122xRxN/122RxN
        89,   // 33: BIOR      b,d8   6/5   3    122xRxN/122RxN
        89,   // 34: BEOR      b,d8   6/5   3    122xRxN/122RxN
        89,   // 35: BIEOR     b,d8   6/5   3    122xRxN/122RxN
        89,   // 36: LDBT      b,d8   6/5   3    122xRxN/122RxN
        90,   // 37: STBT      b,d8   7/6   3    122xRxWN/122RxWN
        91,   // 38: TFM       r+,r+  5+    2    12xxx{R+1xW+1}N
        92,   // 39: TFM       r-,r-  5+    2    12xxx{R-1xW-1}N
        93,   // 3A: TFM       r+,r   5+    2    12xxx{R+1xW0}N
        94,   // 3B: TFM       r,r+   5+    2    12xxx{R0xW+1}N
        34,   // 3C: BITMD     #n8    3     2    12xN
        95,   // 3D: LDMD      #n8    4     2    12XxN
        0,    // 3E: -         -      -     -    -
        43,   // 3F: SWI3      -     19/21  1
              // 1nxwWWWWWWWWWWWxVrxP/1nxwWWWWWWWWWWWWWXVrxP
        0,    // 40: -         -      -     -    -
        0,    // 41: -         -      -     -    -
        0,    // 42: -         -      -     -    -
        25,   // 43: COME      -      2/1   1    1nN/1N
        0,    // 44: -         -      -     -    -
        0,    // 45: -         -      -     -    -
        0,    // 46: -         -      -     -    -
        0,    // 47: -         -      -     -    -
        0,    // 48: -         -      -     -    -
        0,    // 49: -         -      -     -    -
        25,   // 4A: DECE      -      2/1   1    1nN/1N
        0,    // 4B: -         -      -     -    -
        25,   // 4C: INCE      -      2/1   1    1nN/1N
        25,   // 4D: TSTE      -      2/1   1    1nN/1N
        0,    // 4E: -         -      -     -    -
        25,   // 4F: CLRE      -      2/1   1    1nN/1N
        0,    // 50: -         -      -     -    -
        0,    // 51: -         -      -     -    -
        0,    // 52: -         -      -     -    -
        25,   // 53: COMF      -      2/1   1    1nN/1N
        0,    // 54: -         -      -     -    -
        0,    // 55: -         -      -     -    -
        0,    // 56: -         -      -     -    -
        0,    // 57: -         -      -     -    -
        0,    // 58: -         -      -     -    -
        0,    // 59: -         -      -     -    -
        25,   // 5A: DECF      -      2/1   1    1nN/1N
        0,    // 5B: -         -      -     -    -
        25,   // 5C: INCF      -      2/1   1    1nN/1N
        25,   // 5D: TSTF      -      2/1   1    1nN/1N
        0,    // 5E: -         -      -     -    -
        25,   // 5F: CLRF      -      2/1   1    1nN/1N
        0,    // 60: -         -      -     -    -
        0,    // 61: -         -      -     -    -
        0,    // 62: -         -      -     -    -
        0,    // 63: -         -      -     -    -
        0,    // 64: -         -      -     -    -
        0,    // 65: -         -      -     -    -
        0,    // 66: -         -      -     -    -
        0,    // 67: -         -      -     -    -
        0,    // 68: -         -      -     -    -
        0,    // 69: -         -      -     -    -
        0,    // 6A: -         -      -     -    -
        0,    // 6B: -         -      -     -    -
        0,    // 6C: -         -      -     -    -
        0,    // 6D: -         -      -     -    -
        0,    // 6E: -         -      -     -    -
        0,    // 6F: -         -      -     -    -
        0,    // 70: -         -      -     -    -
        0,    // 71: -         -      -     -    -
        0,    // 72: -         -      -     -    -
        0,    // 73: -         -      -     -    -
        0,    // 74: -         -      -     -    -
        0,    // 75: -         -      -     -    -
        0,    // 76: -         -      -     -    -
        0,    // 77: -         -      -     -    -
        0,    // 78: -         -      -     -    -
        0,    // 79: -         -      -     -    -
        0,    // 7A: -         -      -     -    -
        0,    // 7B: -         -      -     -    -
        0,    // 7C: -         -      -     -    -
        0,    // 7D: -         -      -     -    -
        0,    // 7E: -         -      -     -    -
        0,    // 7F: -         -      -     -    -
        54,   // 80: SUBE      #n8    2     2    12N
        54,   // 81: CMPE      #n8    2     2    12N
        0,    // 82: -         -      -     -    -
        55,   // 83: CMPU      #n16   4/3   3    122xN/122N
        0,    // 84: -         -      -     -    -
        0,    // 85: -         -      -     -    -
        54,   // 86: LDE       #n8    2     2    12N
        0,    // 87: -         -      -     -    -
        0,    // 88: -         -      -     -    -
        0,    // 89: -         -      -     -    -
        0,    // 8A: -         -      -     -    -
        54,   // 8B: ADDE      #n8    2     2    12N
        55,   // 8C: CMPS      #n16   4/3   3    122xN/122N
        96,   // 8D: DIVD      #n8   24     2    12{x}N
        97,   // 8E: DIVQ      #n16  33     3    122{x}N
        97,   // 8F: MULD      #n18  27     2    122{x}N
        58,   // 90: SUBE      d8     4/3   2    12xRN/12RN
        58,   // 91: CMPE      d8     4/3   2    12xRN/12RN
        0,    // 92: -         -      -     -    -
        59,   // 93: CMPU      d8     6/4   2    12xRrxN/12RrN
        0,    // 94: -         -      -     -    -
        0,    // 95: -         -      -     -    -
        58,   // 96: LDE       d8     4/3   2    12xRN/12RN
        60,   // 97: STE       d8     4/3   2    12xWN/12WN
        0,    // 98: -         -      -     -    -
        0,    // 99: -         -      -     -    -
        0,    // 9A: -         -      -     -    -
        58,   // 9B: ADDE      d8     4/3   2    12xRN/12RN
        59,   // 9C: CMPS      d8     6/4   2    12xRrxN/12RrN
        98,   // 9D: DIVD      d8    26/25  2    12xR{x}N/12R{x}N
        99,   // 9E: DIVQ      d8    35/34  2    12xRr{x}N/12Rr{x}N
        99,   // 9F: MULD      d8    29/28  2    12xRr{x}N/12Rr{x}N
        64,   // A0: SUBE      ix     4+    2+   12#RN
        64,   // A1: CMPE      ix     4+    2+   12#RN
        0,    // A2: -         -      -     -    -
        65,   // A3: CMPU      ix     6+/5+ 2+   12#RrxN/12#RrN
        0,    // A4: -         -      -     -    -
        0,    // A5: -         -      -     -    -
        64,   // A6: LDE       ix     4+    2+   12#RN
        66,   // A7: STE       ix     4+    2+   12#WN
        0,    // A8: -         -      -     -    -
        0,    // A9: -         -      -     -    -
        0,    // AA: -         -      -     -    -
        64,   // AB: ADDE      ix     4+    2+   12#RN
        65,   // AC: CMPS      ix     6+/5+ 2+   12#RrxN/12#RrN
        100,  // AD: DIVD      ix    26+    2+   12#R{x}N
        101,  // AE: DIVQ      ix    35+    2+   12#Rr{x}N
        101,  // AF: MULD      ix    29+    2+   12#Rr{x}N
        70,   // B0: SUBE      a16    5/4   3    122xAN/122AN
        70,   // B1: CMPE      a16    5/4   3    122xAN/122AN
        0,    // B2: -         -      -     -    -
        71,   // B3: CMPU      a16    7/5   3    122xArxN/122ArN
        0,    // B4: -         -      -     -    -
        0,    // B5: -         -      -     -    -
        70,   // B6: LDE       a16    5/4   3    122xAN/122AN
        77,   // B7: STE       a16    5/4   3    122xBN/122BN
        0,    // B8: -         -      -     -    -
        0,    // B9: -         -      -     -    -
        0,    // BA: -         -      -     -    -
        70,   // BB: ADDE      a16    5/4   3    122xAN/122AN
        71,   // BC: CMPS      a16    7/5   3    122xArxN/122ArN
        102,  // BD: DIVD      a16   27/26  3    122xR{x}N/122R{x}N
        103,  // BE: DIVQ      a16   36/35  3    122xRr{x}N/122Rr{x}N
        103,  // BF: MULD      a16   30/29  3    122xRr{x}N/122Rr{x}N
        54,   // C0: SUBF      #n8    2     2    12N
        54,   // C1: CMPF      #n8    2     2    12N
        0,    // C2: -         -      -     -    -
        0,    // C3: -         -      -     -    -
        0,    // C4: -         -      -     -    -
        0,    // C5: -         -      -     -    -
        54,   // C6: LDF       #n8    2     2    12N
        0,    // C7: -         -      -     -    -
        0,    // C8: -         -      -     -    -
        0,    // C9: -         -      -     -    -
        0,    // CA: -         -      -     -    -
        54,   // CB: ADDF      #n8    2     2    12N
        0,    // CC: -         -      -     -    -
        0,    // CD: -         -      -     -    -
        0,    // CE: -         -      -     -    -
        0,    // CF: -         -      -     -    -
        58,   // D0: SUBF      d8     4/3   2    12xRN/12RN
        58,   // D1: CMPF      d8     4/3   2    12xRN/12RN
        0,    // D2: -         -      -     -    -
        0,    // D3: -         -      -     -    -
        0,    // D4: -         -      -     -    -
        0,    // D5: -         -      -     -    -
        58,   // D6: LDF       d8     4/3   2    12xRN/12RN
        60,   // D7: STF       d8     4/3   2    12xWN/12WN
        0,    // D8: -         -      -     -    -
        0,    // D9: -         -      -     -    -
        0,    // DA: -         -      -     -    -
        58,   // DB: ADDF      d8     4/3   2    12xRN/12RN
        0,    // DC: -         -      -     -    -
        0,    // DD: -         -      -     -    -
        0,    // DE: -         -      -     -    -
        0,    // DF: -         -      -     -    -
        64,   // E0: SUBF      ix     4+    2+   12#RN
        64,   // E1: CMPF      ix     4+    2+   12#RN
        0,    // E2: -         -      -     -    -
        0,    // E3: -         -      -     -    -
        0,    // E4: -         -      -     -    -
        0,    // E5: -         -      -     -    -
        64,   // E6: LDF       ix     4+    2+   12#RN
        66,   // E7: STF       ix     4+    2+   12#WN
        0,    // E8: -         -      -     -    -
        0,    // E9: -         -      -     -    -
        0,    // EA: -         -      -     -    -
        64,   // EB: ADDF      ix     4+    2+   12#RN
        0,    // EC: -         -      -     -    -
        0,    // ED: -         -      -     -    -
        0,    // EE: -         -      -     -    -
        0,    // EF: -         -      -     -    -
        70,   // F0: SUBF      a16    5/4   3    122xAN/122AN
        70,   // F1: CMPF      a16    5/4   3    122xAN/122AN
        0,    // F2: -         -      -     -    -
        0,    // F3: -         -      -     -    -
        0,    // F4: -         -      -     -    -
        0,    // F5: -         -      -     -    -
        70,   // F6: LDF       a16    5/4   3    122xAN/122AN
        77,   // F7: STF       a16    5/4   3    122xBN/122BN
        0,    // F8: -         -      -     -    -
        0,    // F9: -         -      -     -    -
        0,    // FA: -         -      -     -    -
        70,   // FB: ADDF      a16    5/4   3    122xAN/122AN
        0,    // FC: -         -      -     -    -
        0,    // FD: -         -      -     -    -
        0,    // FE: -         -      -     -    -
        0,    // FF: -         -      -     -    -
};

// Puts a sequence together, as long as it fits.
struct Text {
    char *out;
    const char *const last;
    bool put(char c) {
        if (out == last)
            return false;
        *out++ = c;
        return true;
    }
    bool stack(uint8_t post, uint8_t mask, char c) {
        if ((post & mask) == 0)
            return true;
        return put(c) && (mask < 0x10 || put(c));
    }
};

// The alternatives of [seq, end): a prefix's 1 before each's, the
// postbyte |post|'s fragment for #, in native mode if |native|, and pulls
// and pushes of its registers for < and >.
bool assemble(const char *seq, const char *end, bool prefix, uint8_t post,
        bool native, Text &text) {
    auto first = true;
    for (auto p = seq; p < end; ++p) {
        const auto c = *p;
        if (c == '@') {
            first = true;
            if (!text.put(c))
                return false;
            continue;
        }
        if (first && prefix && !text.put('1'))
            return false;
        if (c == '1' && first && prefix) {
            if (!text.put('2'))
                return false;
        } else if (c == '#') {
            auto ix = SEQUENCES[IX_TABLE[post]];
            const auto variant = strchr(ix, '/');
            if (native && variant)
                ix = variant + 1;
            for (; *ix && *ix != '/'; ++ix) {
                if (!text.put(*ix))
                    return false;
            }
        } else if (c == '<') {  // the first pulled starts the value
            const auto bottom = text.out;
            constexpr uint8_t pulls[] = {0x01, 0x02, 0x04, 0x08, 0x10, 0x20,
                    0x40, 0x80};  // CC A B DP X Y U PC
            for (const auto mask : pulls) {
                if (!text.stack(post, mask, 'r'))
                    return false;
            }
            if (text.out != bottom)
                *bottom = 'R';
        } else if (c == '>') {  // the first pushed is the top
            const auto top = text.out;
            constexpr uint8_t pushes[] = {0x80, 0x40, 0x20, 0x10, 0x08, 0x04,
                    0x02, 0x01};  // PC U Y X DP B A CC
            for (const auto mask : pushes) {
                if (!text.stack(post, mask, 'W'))
                    return false;
            }
            if (text.out != top)
                *top = 'w';
        } else if (!text.put(c)) {
            return false;
        }
        first = false;
    }
    return true;
}

}  // namespace

// The MC6809's alternatives, and on an HD6309 the native mode's after
// them: its variant after a /, or the same with the postbyte's. J goes to
// the operand, a branch's to the next + disp.
bool InstHd6309::decode(uint32_t pc, MatchWalker::Decoded &inst) const {
    pc &= 0xFFFF;
    auto read = [&](uint32_t addr) { return _mems->read_byte(addr & 0xFFFF); };
    auto table = P00_TABLE;
    auto opc = read(pc);
    const auto prefix = opc == 0x10 || opc == 0x11;
    if (prefix) {
        table = opc == 0x10 ? P10_TABLE : P11_TABLE;
        opc = read(pc + 1);
    }
    const auto seq = SEQUENCES[table[opc]];
    if (*seq == 0)
        return false;
    const auto end = seq + strlen(seq);
    const auto variant = strchr(seq, '/');
    const auto post = read(pc + prefix + 1);
    Text text{inst.text, inst.text + sizeof(inst.text) - 1};
    if (!assemble(seq, variant ? variant : end, prefix, post, false, text))
        return false;
    if (_type != mc6809::SW_MC6809 && (variant || strchr(seq, '#'))) {
        const auto mc6809 = text.out;
        const auto from = variant ? variant + 1 : seq;
        if (!text.put('@') || !assemble(from, end, prefix, post, true, text))
            return false;
        const auto len = mc6809 - inst.text;
        if (text.out - mc6809 - 1 == len &&
                memcmp(inst.text, mc6809 + 1, len) == 0)
            text.out = mc6809;  // the same in either mode
    }
    *text.out = 0;
    inst.pc = pc;
    inst.seq = inst.text;
    inst.length = MatchWalker::instructionBytes(inst.text);
    const auto next = pc + inst.length;
    const uint16_t operand = read(next - 2) << 8 | read(next - 1);
    inst.hasEa = inst.hasTarget = true;
    inst.ea = operand;
    const auto page0 = table == P00_TABLE;
    if ((page0 && ((opc & 0xF0) == 0x20 || opc == 0x8D))) {  // Bcc, BSR
        inst.target = (next + static_cast<int8_t>(operand)) & 0xFFFF;
    } else if ((page0 && (opc == 0x16 || opc == 0x17)) ||
               (table == P10_TABLE && (opc & 0xF0) == 0x20)) {  // LBcc
        inst.target = (next + static_cast<int16_t>(operand)) & 0xFFFF;
    } else {
        inst.target = operand;
    }
    return true;
}

const char *InstHd6309::intrSequence() const {
    return _type == mc6809::SW_MC6809 ? INTERRUPT_6809 : INTERRUPT_6309;
}

}  // namespace hd6309
}  // namespace debugger

// Local Variables:
// mode: c++
// c-basic-offset: 4
// tab-width: 4
// End:
// vim: set ft=cpp et ts=4 sw=4:
