# MC68HC912BD32 QFP definition
# https://github.com/tgtakaoka/dip
name = "MC68HC912BD32"
title = "MC68HC912BD32 Special Expanded Wide"
qfp = 80
pin1 = "bottom-left"
 1 = ",    PP5"
 2 = ",    PP4"
 3 = ",    PP3, PW3"
 4 = ",    PP2, PW2"
 5 = ",    PP1, PW1"
 6 = ",    PP0, PW0"
 7 = "P55, PT0, IOC0"
 8 = ",    PT1, IOC1"
 9 = ",    PT2, IOC2"
10 = "VCC, VDD"
11 = "GND, VSS"
12 = ",    PT3, IOC3"
13 = ",    PT4, IOC4"
14 = ",    PT5, IOC5"
15 = ",    PT6, IOC6"
16 = "P52, PT7, IOC7, PAI"
17 = "P44, BKGD, #TAGHI, SMODN"
18 = "P10, ADDR0, DATA0, PB0"
19 = "P11, ADDR1, DATA1, PB1"
20 = "P12, ADDR2, DATA2, PB2"
21 = "P13, ADDR3, DATA3, PB3"
22 = "P14, ADDR4, DATA4, PB4"
23 = "P15, ADDR5, DATA5, PB5"
24 = "P16, ADDR6, DATA6, PB6"
25 = "P17, ADDR7, DATA7, PB7"
26 = "P40, #DBE, PE7"
27 = "P43, MODB, PE6, IPIPE1"
28 = "P42, MODA, PE5, IPIPE0"
29 = "P47, ECLK, PE4"
30 = "GND, VSSX"
31 = "VCC, VDDX"
32 = "P53, #RESET"
33 = "P46, EXTAL"
34 = ",    XTAL"
35 = "P54, #LSTRB, PE3, #TAGLO"
36 = "P41, R/#W,  PE2"
37 = "P50, #IRQ,  PE1"
38 = "P51, #XIRQ, PE0"
39 = "P20, ADDR8,  DATA8,  PA0"
40 = "P21, ADDR9,  DATA9,  PA1"
41 = "P22, ADDR10, DATA10, PA2"
42 = "P23, ADDR11, DATA11, PA3"
43 = "P24, ADDR12, DATA12, PA4"
44 = "P25, ADDR13, DATA13, PA5"
45 = "P26, ADDR14, DATA14, PA6"
46 = "P27, ADDR15, DATA15, PA7"
47 = "VCC, VDD"
48 = "GND, VSS"
49 = "VCC, VRH"
50 = "GND, VRL"
51 = ",    PAD0, AN0"
52 = ",    PAD1, AN1"
53 = ",    PAD2, AN2"
54 = ",    PAD3, AN3"
55 = ",    PAD4, AN4"
56 = ",    PAD5, AN5"
57 = ",    PAD6, AN6"
58 = ",    PAD7, AN7"
59 = "VCC, VDDA"
60 = "GND, VSSA"
61 = "P30, PS0, RxD"
62 = "P31, PS1, TxD"
63 = "P32, PS2"
64 = "P33, PS3"
65 = "P34, PS4, SDI, MISO"
66 = "P35, PS5, SDO, MOSI"
67 = "P36, PS6, SCK"
68 = "P37, PS7, #CS, #SS"
69 = "VCC, VFP"
70 = "P45, DIVBYP"
71 = ",    PSBI5"
72 = ",    PSBI4"
73 = ",    PSBI3"
74 = ",    PSBI2"
75 = ",    Tx"
76 = ",    Rx"
77 = "GND, VSSX"
78 = "VCC, VDDX"
79 = ",    PP7"
80 = ",    PP6"
