#!/usr/bin/gawk -f
# -*- mode: awk; -*-
# Generates the tables of inst_tlcs90.cpp; from debugger/tlcs90:
#
#   gawk -f inst_tlcs90.awk tlcs90-PAGE0.txt tlcs90-PAGE1.txt tlcs90-PAGE2.txt tlcs90-PAGE3.txt \
#       | clang-format --assume-filename=inst_tlcs90.cpp
#
# and replace the tables after the "// Generated by:" line in the .cpp.
# -v MODE=pretty prints the input tables back aligned instead.

# The true_seq (taken) and false_seq (not taken) columns are in
# debugger/match_legend.md's tokens; "bus" is them without the - cycles,
# which strobe nothing the board records. The TLCS-90 fetches ahead: an N
# before the end is the next opcode's fetch, and an instruction's 1 then
# takes no cycle. A prefix's sequence comes before its page's. A and B are
# on the direct page FFxx; J goes to the operand, or for a relative branch
# to the instruction's address + 2 + disp.

BEGIN {
    if (MODE == "")
        MODE = "table";
    if (MODE != "table" && MODE != "pretty") {
        print "MODE must be table or pretty" > "/dev/stderr";
        exit 1;
    }
    PRETTY_PRINT = MODE == "pretty";
    GENERATE_TABLE = MODE == "table";
    GENERATED_BY = generated_by("inst_tlcs90.awk");
}

# The command that made the tables, wrapped to 80 columns so clang-format
# keeps it.
function generated_by(script,  i, cmd, line, word) {
    cmd = "";
    line = "// Generated by: gawk -f " script;
    for (i = 1; i <= ARGC; i++) {
        word = (i < ARGC) ? ARGV[i] : "| clang-format";
        if (length(line) + 1 + length(word) > 78) {
            cmd = cmd line "\n";
            line = "//     " word;
        } else {
            line = line " " word;
        }
    }
    return cmd line;
}

# Read the inputs twice: the first pass collects CYCLES in first-seen order,
# the second generates the tables.
BEGIN {
    if (GENERATE_TABLE) {
        NINPUTS = ARGC - 1;
        for (i = 1; i <= NINPUTS; i++)
            ARGV[ARGC++] = ARGV[i];
        COLLECTING = 1;
        GENERATE_TABLE = 0;
        GENERATE_CYCLES = 1;
    }
}

FNR == 1 && COLLECTING && ++NOPENED > NINPUTS {
    COLLECTING = 0;
    GENERATE_CYCLES = 0;
    GENERATE_TABLE = 1;
}

function bus_cycles(sequence, cycles) {
    if (sequence == "-")
        return "-";
    cycles = sequence;
    gsub(/-/, "", cycles);
    return cycles;
}

function bus_length(cycles) {
    if (cycles == "-")
        return 0;
    return length(cycles);
}

function CYCLES_index(sequence, s) {
    for (s in CYCLES) {
        if (CYCLES[s] == sequence)
            return s;
    }
    return 0;
}

function pretty_print(op, nemo, opr, len, bus, true_seq, false_seq) {
    if (PRETTY_PRINT == 0)
        return;
    printf("%-2s %-4s %-7s %s ", op, nemo, opr, len);
    printf("%-17s ", bus);
    printf("%-21s %s\n", true_seq, false_seq);
}

function add_CYCLES(bus) {
    CYCLES[length(CYCLES)+1] = bus;
}

function append_CYCLES(bus) {
    if (bus_length(bus) != 0 && CYCLES_index(bus) == 0)
        add_CYCLES(bus);
}

function generate_CYCLES(bus) {
    if (GENERATE_CYCLES == 0)
        return 0;
    if (GENERATE_CYCLES == 1)
        append_CYCLES(bus);
}

function generate_TABLE() {
    printf("%s\n", GENERATED_BY);
    printf("constexpr const char *const SEQUENCES[/*seq*/] = {\n");
    printf("        \"%s\",  // %2d\n", "", 0);
    for (c = 1; c <= length(CYCLES); c++) {
        cyc = CYCLES[c];
        printf("        \"%s\",  // %2d\n", cyc, c);
    }
    printf("};\n");
}

function generate_ENTRY(op, nemo, opr, len, bus, true_seq, false_seq, cycle) {
    if (GENERATE_TABLE == 0)
        return;
    cycle = CYCLES_index(bus);
    printf("       %d,  // %s: %-4s %-7s; %s\n",
           cycle, op, nemo, opr, bus);
}

BEGIN {
    pretty_print("op", "mnem", "operand", "#", "bus", "true_seq", "false_seq");
    pretty_print("--", "----", "-------", "-", "---", "--------", "---------");
}

$1 !~ /[0-9A-F][0-9A-F]/ { next; }
$1 ~ /[0-9A-F][0-9A-F]/ {
    opc = $1;
    mne = $2;
    opr = $3;
    len = $4;
    true_seq = $6;
    false_seq = $7;

    if (GENERATE_TABLE && opc == "00") {
        if (match(FILENAME, /tlcs90-(PAGE[0-3]).txt/, a) == 0) {
            printf("Unknown file: %s\n", FILENAME) > "/dev/stderr"
            exit;
        }
        if (FILENAME == "tlcs90-PAGE0.txt")
            generate_TABLE();
        page = a[1];
        printf("\nconstexpr uint8_t %s[] = {\n", page);
    }

    true_bus = bus_cycles(true_seq);
    false_bus = bus_cycles(false_seq);
    bus = true_bus;
    if (false_bus != "-")
        bus = bus "@" false_bus;

    pretty_print(opc, mne, opr, len, bus, true_seq, false_seq);
    generate_CYCLES(bus);
    generate_ENTRY(opc, mne, opr, len, bus, true_seq, false_seq);

    if (GENERATE_TABLE && opc == "FF")
        printf("};\n");
}
