#!/usr/bin/gawk -f
# -*- mode: awk; -*-
# Generates the tables of inst_scn2650.cpp; from debugger/scn2650:
#
#   gawk -f inst_scn2650.awk scn2650.txt \
#       | clang-format --assume-filename=inst_scn2650.cpp
#
# and replace the tables after the "// Generated by:" line in the .cpp.
# -v MODE=pretty prints the input tables back aligned instead.

BEGIN {
    if (MODE == "")
        MODE = "table";
    if (MODE != "table" && MODE != "pretty") {
        print "MODE must be table or pretty" > "/dev/stderr";
        exit 1;
    }
    PRETTY_PRINT = MODE == "pretty";
    GENERATE_TABLE = MODE == "table";
    GENERATED_BY = generated_by("inst_scn2650.awk");
}

# The command that made the tables, wrapped to 80 columns so clang-format
# keeps it.
function generated_by(script,  i, cmd, line, word) {
    cmd = "";
    line = "// Generated by: gawk -f " script;
    for (i = 1; i <= ARGC; i++) {
        word = (i < ARGC) ? ARGV[i] : "| clang-format";
        if (length(line) + 1 + length(word) > 78) {
            cmd = cmd line "\n";
            line = "//     " word;
        } else {
            line = line " " word;
        }
    }
    return cmd line;
}

function pretty_print(opc, nem, opr, len, clk, bus, indir) {
    if (PRETTY_PRINT == 0)
        return;
    printf("%-2s  %-4s  %-7s  %s  %s  %2s  %4s\n",
           opc, nem, opr, len, clk, bus, indir);
}

function generate_TABLE(opc, nem, opr, len, clk, bus, indir) {
    if (GENERATE_TABLE == 0)
        return;
    printf("        %s(%d, %d),  // %s: %-4s %s\n",
           indir == 0 ? "E" : "I",
           len, bus, opc, nem, opr);
}

BEGIN {
    pretty_print("op", "nemo", "opr", "#", "~", "bus", "indir");
    pretty_print("--", "----", "-------", "-", "-", "---", "-----");
    if (GENERATE_TABLE) {
        printf("%s\n", GENERATED_BY);
        printf("constexpr uint8_t INST_TABLE[] = {\n");
    }
}
END {
    if (GENERATE_TABLE)
        printf("};\n");
}

$1 !~ /[0-9A-F][0-9A-F]/ { next; }
$1 ~ /[0-9A-F][0-9A-F]/ {
    opc = $1;
    nem = $2;
    opr = $3;
    len = $4;
    clk = $5;
    bus = $6;
    indir = $7;

    pretty_print(opc, nem, opr, len, clk, bus, indir);
    generate_TABLE(opc, nem, opr, len, clk, bus, indir);
}
