#!/usr/bin/awk -f
# -*- mode: awk; -*-
#
# z380-PAGExx.txt -> the SEQUENCES[] and PAGExx_TABLE[] of inst_z380.cpp:
#
#   gawk -f inst_z380.awk z380-PAGE00.txt z380-PAGECB.txt z380-PAGEED.txt z380-PAGEEDCB.txt z380-PAGEDD.txt z380-PAGEFD.txt z380-PAGEDDCB.txt z380-PAGEFDCB.txt \
#       | clang-format --assume-filename=inst_z380.cpp
#
# and replace the tables after the "// Generated by:" line in the .cpp.
# tools/derive_tables.py writes the pages from the recording. "#" is the
# length, "sequence" in debugger/match_legend.md's tokens: a "/" before
# the Long Word mode's variant and the Extended mode's, empty where the
# same. A DDIR IB or IW widens the "a" bytes. A row is its sequence's
# index.

BEGIN {
    nseq = 0;
    npage = 0;
    GENERATED_BY = generated_by("inst_z380.awk");
}

# The command that made the tables, wrapped to 80 columns so clang-format
# keeps it.
function generated_by(script,  i, cmd, line, word) {
    cmd = "";
    line = "// Generated by: gawk -f " script;
    for (i = 1; i <= ARGC; i++) {
        word = (i < ARGC) ? ARGV[i] : "| clang-format";
        if (length(line) + 1 + length(word) > 78) {
            cmd = cmd line "\n";
            line = "//     " word;
        } else {
            line = line " " word;
        }
    }
    return cmd line;
}

function seq_index(seq, i) {
    for (i = 1; i <= nseq; i++)
        if (SEQ[i] == seq)
            return i;
    SEQ[++nseq] = seq;
    return nseq;
}

$1 !~ /^[0-9A-F][0-9A-F]$/ { next; }
{
    if (NF < 5) {
        line = sprintf("        0,  // %s", $1);
    } else {
        idx = seq_index($5);
        if (idx > 255) {
            printf("%s: %s: more than 255 sequences\n", FILENAME, $1) > "/dev/stderr";
            exit 1;
        }
        line = sprintf("        %3d,  // %s: %-7s %-18s %s", idx, $1, $2, $3, $5);
    }
    if (FILENAME != current) {
        page = FILENAME;
        if (!sub(/^.*z380-PAGE/, "PAGE", page) || !sub(/\.txt$/, "", page)) {
            printf("Unknown file: %s\n", FILENAME) > "/dev/stderr";
            exit 1;
        }
        current = FILENAME;
        PAGE[++npage] = page;
        count[npage] = 0;
    }
    ROW[npage, ++count[npage]] = line;
}

END {
    printf("%s\n", GENERATED_BY);
    printf("constexpr const char *const SEQUENCES[/*seq*/] = {\n");
    printf("        %-16s  // %3d\n", "\"\",", 0);
    for (i = 1; i <= nseq; i++)
        printf("        %-16s  // %3d\n", "\"" SEQ[i] "\",", i);
    printf("};\n");
    for (p = 1; p <= npage; p++) {
        printf("\nconstexpr uint8_t %s_TABLE[] = {\n", PAGE[p]);
        for (i = 1; i <= count[p]; i++)
            printf("%s\n", ROW[p, i]);
        printf("};\n");
    }
}
