#include "inst_z380.h"

#include "signals_z380.h"

namespace debugger {
namespace z380 {

namespace {

// From z380-PAGExx.txt (tools/derive_tables.py writes them):
//   gawk -f inst_z380.awk z380-PAGE{00,CB,ED,EDCB,DD,FD,DDCB,FDCB}.txt
// clang-format off
// BEGIN GENERATED
// Generated by: gawk -f inst_z380.awk z380-PAGE00.txt z380-PAGECB.txt
//     z380-PAGEED.txt z380-PAGEEDCB.txt z380-PAGEDD.txt z380-PAGEFD.txt
//     z380-PAGEDDCB.txt z380-PAGEFDCB.txt | clang-format
constexpr const char *const SEQUENCES[/*seq*/] = {
        "",                                            //   0
        "1~N",                                         //   1
        "1aa~N",                                       //   2
        "1~[W]N",                                      //   3
        "12~N",                                        //   4
        "1~[R]N",                                      //   5
        "12~[J]@12~N",                                 //   6
        "12~[J]",                                      //   7
        "1aa~[Ww]N/1aa~[Wwww]N/",                      //   8
        "1aa~[Rr]N/1aa~[Rrrr]N/",                      //   9
        "1aa~[W]N",                                    //  10
        "1~[RW]N",                                     //  11
        "12~[W]N",                                     //  12
        "1aa~[R]N",                                    //  13
        "1~{h}N",                                      //  14
        "1~[Rr?]@1~N//1~[Rrrr?]@1~N",                  //  15
        "1~[Rr]N/1~[Rrrr]N/",                          //  16
        "1aa~[J]@1aa~N",                               //  17
        "1aa~[J]",                                     //  18
        "1aa~[WwJ]@1aa~N//1aa~[WwwwJ]@1aa~N",          //  19
        "1~[Ww]N/1~[Wwww]N/",                          //  20
        "1~[WwJ]//1~[WwwwJ]",                          //  21
        "1~[Rr?]//1~[Rrrr?]",                          //  22
        "1aa~[WwJ]//1aa~[WwwwJ]",                      //  23
        "12~[O]N",                                     //  24
        "12~[I]N",                                     //  25
        "1~[RrWw]N/1~[RrrrWwww]N/",                    //  26
        "1~[?]",                                       //  27
        "1~[Rr]N",                                     //  28
        "12~[RW]N",                                    //  29
        "12~[R]N",                                     //  30
        "122~N",                                       //  31
        "12aa~[Ww]N/12aa~[Wwww]N/",                    //  32
        "122~[I]N",                                    //  33
        "12~[Rr?]//12~[Rrrr?]",                        //  34
        "12aa~[Rr]N/12aa~[Rrrr]N/",                    //  35
        "12~[RrII?]//12~[RrrrII?]",                    //  36
        "122~[O]N",                                    //  37
        "12~{h}N",                                     //  38
        "12aa~N",                                      //  39
        "1222~N",                                      //  40
        "12~{R+1}N",                                   //  41
        "12~{R-1}N",                                   //  42
        "12~[WI]N",                                    //  43
        "12~[RO]N",                                    //  44
        "12~{R+1W+1}N",                                //  45
        "12~{I.W+1}N",                                 //  46
        "12~{R+1O.}N",                                 //  47
        "12~{R-1W-1}N",                                //  48
        "12~{I.W-1}N",                                 //  49
        "12~{R-1O.}N",                                 //  50
        "12~[Rr]N/12~[Rrrr]N/",                        //  51
        "122~[WwJ]@122~N//122~[WwwwJ]@122~N",          //  52
        "12~[Ww]N/12~[Wwww]N/",                        //  53
        "12aa~[Rr]N",                                  //  54
        "122~[WwJ]//122~[WwwwJ]",                      //  55
        "12aa~[O]N",                                   //  56
        "12aa~[I]N",                                   //  57
        "12~[RrWw]N",                                  //  58
        "12~[WwI]N",                                   //  59
        "12~[RrO]N",                                   //  60
        "12~{R+2rW+2w}N",                              //  61
        "12~{I.W+2w}N",                                //  62
        "12~{R+2rO.}N",                                //  63
        "12~{R-2rW-2w}N",                              //  64
        "12~{I.W-2w}N",                                //  65
        "12~{R-2rO.}N",                                //  66
        "122~[RrWw]N",                                 //  67
        "12222~N",                                     //  68
        "1222~[J]@1222~N",                             //  69
        "1222~[J]",                                    //  70
        "1aa~[RW]N",                                   //  71
        "12aa~[W]N",                                   //  72
        "1222~[WwJ]@1222~N//1222~[WwwwJ]@1222~N",      //  73
        "1aa~[Rr]N",                                   //  74
        "1222~[WwJ]//1222~[WwwwJ]",                    //  75
        "12~[RrWw]N/12~[RrrrWwww]N/",                  //  76
        "12~[?]",                                      //  77
        "12222~[J]@12222~N",                           //  78
        "12222~[J]",                                   //  79
        "1222~[O]N",                                   //  80
        "12222~[WwJ]@12222~N//12222~[WwwwJ]@12222~N",  //  81
        "12222~[WwJ]//12222~[WwwwJ]",                  //  82
        "12~[Ww]N",                                    //  83
        "12aa~[RrWw]N",                                //  84
        "12aa~[RW]N",                                  //  85
        "12aa~[R]N",                                   //  86
        "1222~[R]N",                                   //  87
        "1222~[RW]N",                                  //  88
};

constexpr uint8_t PAGE00_TABLE[] = {
        1,   // 00: NOP     -                  1~N
        2,   // 01: LD      BC,0302H           1aa~N
        3,   // 02: LD      (BC),A             1~[W]N
        1,   // 03: INC     BC                 1~N
        1,   // 04: INC     B                  1~N
        1,   // 05: DEC     B                  1~N
        4,   // 06: LD      B,7                12~N
        1,   // 07: RLCA    -                  1~N
        1,   // 08: EX      AF,AF'             1~N
        1,   // 09: ADD     HL,BC              1~N
        5,   // 0A: LD      A,(BC)             1~[R]N
        1,   // 0B: DEC     BC                 1~N
        1,   // 0C: INC     C                  1~N
        1,   // 0D: DEC     C                  1~N
        4,   // 0E: LD      C,15               12~N
        1,   // 0F: RRCA    -                  1~N
        6,   // 10: DJNZ    $+19               12~[J]@12~N
        2,   // 11: LD      DE,1312H           1aa~N
        3,   // 12: LD      (DE),A             1~[W]N
        1,   // 13: INC     DE                 1~N
        1,   // 14: INC     D                  1~N
        1,   // 15: DEC     D                  1~N
        4,   // 16: LD      D,23               12~N
        1,   // 17: RLA     -                  1~N
        7,   // 18: JR      $+27               12~[J]
        1,   // 19: ADD     HL,DE              1~N
        5,   // 1A: LD      A,(DE)             1~[R]N
        1,   // 1B: DEC     DE                 1~N
        1,   // 1C: INC     E                  1~N
        1,   // 1D: DEC     E                  1~N
        4,   // 1E: LD      E,31               12~N
        1,   // 1F: RRA     -                  1~N
        6,   // 20: JR      NZ,$+35            12~[J]@12~N
        2,   // 21: LD      HL,2322H           1aa~N
        8,   // 22: LD      (2423H),HL         1aa~[Ww]N/1aa~[Wwww]N/
        1,   // 23: INC     HL                 1~N
        1,   // 24: INC     H                  1~N
        1,   // 25: DEC     H                  1~N
        4,   // 26: LD      H,27H              12~N
        1,   // 27: DAA     -                  1~N
        6,   // 28: JR      Z,$+43             12~[J]@12~N
        1,   // 29: ADD     HL,HL              1~N
        9,   // 2A: LD      HL,(2C2BH)         1aa~[Rr]N/1aa~[Rrrr]N/
        1,   // 2B: DEC     HL                 1~N
        1,   // 2C: INC     L                  1~N
        1,   // 2D: DEC     L                  1~N
        4,   // 2E: LD      L,2FH              12~N
        1,   // 2F: CPL     -                  1~N
        6,   // 30: JR      NC,$+51            12~[J]@12~N
        2,   // 31: LD      SP,3332H           1aa~N
        10,  // 32: LD      (3433H),A          1aa~[W]N
        1,   // 33: INC     SP                 1~N
        11,  // 34: INC     (HL)               1~[RW]N
        11,  // 35: DEC     (HL)               1~[RW]N
        12,  // 36: LD      (HL),37H           12~[W]N
        1,   // 37: SCF     -                  1~N
        6,   // 38: JR      C,$+59             12~[J]@12~N
        1,   // 39: ADD     HL,SP              1~N
        13,  // 3A: LD      A,(3C3BH)          1aa~[R]N
        1,   // 3B: DEC     SP                 1~N
        1,   // 3C: INC     A                  1~N
        1,   // 3D: DEC     A                  1~N
        4,   // 3E: LD      A,3FH              12~N
        1,   // 3F: CCF     -                  1~N
        1,   // 40: LD      B,B                1~N
        1,   // 41: LD      B,C                1~N
        1,   // 42: LD      B,D                1~N
        1,   // 43: LD      B,E                1~N
        1,   // 44: LD      B,H                1~N
        1,   // 45: LD      B,L                1~N
        5,   // 46: LD      B,(HL)             1~[R]N
        1,   // 47: LD      B,A                1~N
        1,   // 48: LD      C,B                1~N
        1,   // 49: LD      C,C                1~N
        1,   // 4A: LD      C,D                1~N
        1,   // 4B: LD      C,E                1~N
        1,   // 4C: LD      C,H                1~N
        1,   // 4D: LD      C,L                1~N
        5,   // 4E: LD      C,(HL)             1~[R]N
        1,   // 4F: LD      C,A                1~N
        1,   // 50: LD      D,B                1~N
        1,   // 51: LD      D,C                1~N
        1,   // 52: LD      D,D                1~N
        1,   // 53: LD      D,E                1~N
        1,   // 54: LD      D,H                1~N
        1,   // 55: LD      D,L                1~N
        5,   // 56: LD      D,(HL)             1~[R]N
        1,   // 57: LD      D,A                1~N
        1,   // 58: LD      E,B                1~N
        1,   // 59: LD      E,C                1~N
        1,   // 5A: LD      E,D                1~N
        1,   // 5B: LD      E,E                1~N
        1,   // 5C: LD      E,H                1~N
        1,   // 5D: LD      E,L                1~N
        5,   // 5E: LD      E,(HL)             1~[R]N
        1,   // 5F: LD      E,A                1~N
        1,   // 60: LD      H,B                1~N
        1,   // 61: LD      H,C                1~N
        1,   // 62: LD      H,D                1~N
        1,   // 63: LD      H,E                1~N
        1,   // 64: LD      H,H                1~N
        1,   // 65: LD      H,L                1~N
        5,   // 66: LD      H,(HL)             1~[R]N
        1,   // 67: LD      H,A                1~N
        1,   // 68: LD      L,B                1~N
        1,   // 69: LD      L,C                1~N
        1,   // 6A: LD      L,D                1~N
        1,   // 6B: LD      L,E                1~N
        1,   // 6C: LD      L,H                1~N
        1,   // 6D: LD      L,L                1~N
        5,   // 6E: LD      L,(HL)             1~[R]N
        1,   // 6F: LD      L,A                1~N
        3,   // 70: LD      (HL),B             1~[W]N
        3,   // 71: LD      (HL),C             1~[W]N
        3,   // 72: LD      (HL),D             1~[W]N
        3,   // 73: LD      (HL),E             1~[W]N
        3,   // 74: LD      (HL),H             1~[W]N
        3,   // 75: LD      (HL),L             1~[W]N
        14,  // 76: HALT    -                  1~{h}N
        3,   // 77: LD      (HL),A             1~[W]N
        1,   // 78: LD      A,B                1~N
        1,   // 79: LD      A,C                1~N
        1,   // 7A: LD      A,D                1~N
        1,   // 7B: LD      A,E                1~N
        1,   // 7C: LD      A,H                1~N
        1,   // 7D: LD      A,L                1~N
        5,   // 7E: LD      A,(HL)             1~[R]N
        1,   // 7F: LD      A,A                1~N
        1,   // 80: ADD     A,B                1~N
        1,   // 81: ADD     A,C                1~N
        1,   // 82: ADD     A,D                1~N
        1,   // 83: ADD     A,E                1~N
        1,   // 84: ADD     A,H                1~N
        1,   // 85: ADD     A,L                1~N
        5,   // 86: ADD     A,(HL)             1~[R]N
        1,   // 87: ADD     A,A                1~N
        1,   // 88: ADC     A,B                1~N
        1,   // 89: ADC     A,C                1~N
        1,   // 8A: ADC     A,D                1~N
        1,   // 8B: ADC     A,E                1~N
        1,   // 8C: ADC     A,H                1~N
        1,   // 8D: ADC     A,L                1~N
        5,   // 8E: ADC     A,(HL)             1~[R]N
        1,   // 8F: ADC     A,A                1~N
        1,   // 90: SUB     B                  1~N
        1,   // 91: SUB     C                  1~N
        1,   // 92: SUB     D                  1~N
        1,   // 93: SUB     E                  1~N
        1,   // 94: SUB     H                  1~N
        1,   // 95: SUB     L                  1~N
        5,   // 96: SUB     (HL)               1~[R]N
        1,   // 97: SUB     A                  1~N
        1,   // 98: SBC     A,B                1~N
        1,   // 99: SBC     A,C                1~N
        1,   // 9A: SBC     A,D                1~N
        1,   // 9B: SBC     A,E                1~N
        1,   // 9C: SBC     A,H                1~N
        1,   // 9D: SBC     A,L                1~N
        5,   // 9E: SBC     A,(HL)             1~[R]N
        1,   // 9F: SBC     A,A                1~N
        1,   // A0: AND     B                  1~N
        1,   // A1: AND     C                  1~N
        1,   // A2: AND     D                  1~N
        1,   // A3: AND     E                  1~N
        1,   // A4: AND     H                  1~N
        1,   // A5: AND     L                  1~N
        5,   // A6: AND     (HL)               1~[R]N
        1,   // A7: AND     A                  1~N
        1,   // A8: XOR     B                  1~N
        1,   // A9: XOR     C                  1~N
        1,   // AA: XOR     D                  1~N
        1,   // AB: XOR     E                  1~N
        1,   // AC: XOR     H                  1~N
        1,   // AD: XOR     L                  1~N
        5,   // AE: XOR     (HL)               1~[R]N
        1,   // AF: XOR     A                  1~N
        1,   // B0: OR      B                  1~N
        1,   // B1: OR      C                  1~N
        1,   // B2: OR      D                  1~N
        1,   // B3: OR      E                  1~N
        1,   // B4: OR      H                  1~N
        1,   // B5: OR      L                  1~N
        5,   // B6: OR      (HL)               1~[R]N
        1,   // B7: OR      A                  1~N
        1,   // B8: CP      B                  1~N
        1,   // B9: CP      C                  1~N
        1,   // BA: CP      D                  1~N
        1,   // BB: CP      E                  1~N
        1,   // BC: CP      H                  1~N
        1,   // BD: CP      L                  1~N
        5,   // BE: CP      (HL)               1~[R]N
        1,   // BF: CP      A                  1~N
        15,  // C0: RET     NZ                 1~[Rr?]@1~N//1~[Rrrr?]@1~N
        16,  // C1: POP     BC                 1~[Rr]N/1~[Rrrr]N/
        17,  // C2: JP      NZ,0C4C3H          1aa~[J]@1aa~N
        18,  // C3: JP      0C5C4H             1aa~[J]
        19,  // C4: CALL    NZ,0C6C5H 1aa~[WwJ]@1aa~N//1aa~[WwwwJ]@1aa~N
        20,  // C5: PUSH    BC                 1~[Ww]N/1~[Wwww]N/
        4,   // C6: ADD     A,0C7H             12~N
        21,  // C7: RST     0                  1~[WwJ]//1~[WwwwJ]
        15,  // C8: RET     Z                  1~[Rr?]@1~N//1~[Rrrr?]@1~N
        22,  // C9: RET     -                  1~[Rr?]//1~[Rrrr?]
        17,  // CA: JP      Z,0CCCBH           1aa~[J]@1aa~N
        0,   // CB
        19,  // CC: CALL    Z,0CECDH 1aa~[WwJ]@1aa~N//1aa~[WwwwJ]@1aa~N
        23,  // CD: CALL    0CFCEH             1aa~[WwJ]//1aa~[WwwwJ]
        4,   // CE: ADC     A,0CFH             12~N
        21,  // CF: RST     8                  1~[WwJ]//1~[WwwwJ]
        15,  // D0: RET     NC                 1~[Rr?]@1~N//1~[Rrrr?]@1~N
        16,  // D1: POP     DE                 1~[Rr]N/1~[Rrrr]N/
        17,  // D2: JP      NC,0D4D3H          1aa~[J]@1aa~N
        24,  // D3: OUT     (0D4H),A           12~[O]N
        19,  // D4: CALL    NC,0D6D5H 1aa~[WwJ]@1aa~N//1aa~[WwwwJ]@1aa~N
        20,  // D5: PUSH    DE                 1~[Ww]N/1~[Wwww]N/
        4,   // D6: SUB     0D7H               12~N
        21,  // D7: RST     16                 1~[WwJ]//1~[WwwwJ]
        15,  // D8: RET     C                  1~[Rr?]@1~N//1~[Rrrr?]@1~N
        1,   // D9: EXX     -                  1~N
        17,  // DA: JP      C,0DCDBH           1aa~[J]@1aa~N
        25,  // DB: IN      A,(0DCH)           12~[I]N
        19,  // DC: CALL    C,0DEDDH 1aa~[WwJ]@1aa~N//1aa~[WwwwJ]@1aa~N
        0,   // DD
        4,   // DE: SBC     A,0DFH             12~N
        21,  // DF: RST     24                 1~[WwJ]//1~[WwwwJ]
        15,  // E0: RET     PO                 1~[Rr?]@1~N//1~[Rrrr?]@1~N
        16,  // E1: POP     HL                 1~[Rr]N/1~[Rrrr]N/
        17,  // E2: JP      PO,0E4E3H          1aa~[J]@1aa~N
        26,  // E3: EX      (SP),HL            1~[RrWw]N/1~[RrrrWwww]N/
        19,  // E4: CALL    PO,0E6E5H 1aa~[WwJ]@1aa~N//1aa~[WwwwJ]@1aa~N
        20,  // E5: PUSH    HL                 1~[Ww]N/1~[Wwww]N/
        4,   // E6: AND     0E7H               12~N
        21,  // E7: RST     32                 1~[WwJ]//1~[WwwwJ]
        15,  // E8: RET     PE                 1~[Rr?]@1~N//1~[Rrrr?]@1~N
        27,  // E9: JP      (HL)               1~[?]
        17,  // EA: JP      PE,0ECEBH          1aa~[J]@1aa~N
        1,   // EB: EX      DE,HL              1~N
        19,  // EC: CALL    PE,0EEEDH 1aa~[WwJ]@1aa~N//1aa~[WwwwJ]@1aa~N
        0,   // ED
        4,   // EE: XOR     0EFH               12~N
        21,  // EF: RST     28H                1~[WwJ]//1~[WwwwJ]
        15,  // F0: RET     P                  1~[Rr?]@1~N//1~[Rrrr?]@1~N
        28,  // F1: POP     AF                 1~[Rr]N
        17,  // F2: JP      P,0F4F3H           1aa~[J]@1aa~N
        1,   // F3: DI      -                  1~N
        19,  // F4: CALL    P,0F6F5H 1aa~[WwJ]@1aa~N//1aa~[WwwwJ]@1aa~N
        20,  // F5: PUSH    AF                 1~[Ww]N/1~[Wwww]N/
        4,   // F6: OR      0F7H               12~N
        21,  // F7: RST     30H                1~[WwJ]//1~[WwwwJ]
        15,  // F8: RET     M                  1~[Rr?]@1~N//1~[Rrrr?]@1~N
        1,   // F9: LD      SP,HL              1~N
        17,  // FA: JP      M,0FCFBH           1aa~[J]@1aa~N
        1,   // FB: EI      -                  1~N
        19,  // FC: CALL    M,0FEFDH 1aa~[WwJ]@1aa~N//1aa~[WwwwJ]@1aa~N
        0,   // FD
        4,   // FE: CP      0FFH               12~N
        21,  // FF: RST     38H                1~[WwJ]//1~[WwwwJ]
};

constexpr uint8_t PAGECB_TABLE[] = {
        4,   // 00: RLC     B                  12~N
        4,   // 01: RLC     C                  12~N
        4,   // 02: RLC     D                  12~N
        4,   // 03: RLC     E                  12~N
        4,   // 04: RLC     H                  12~N
        4,   // 05: RLC     L                  12~N
        29,  // 06: RLC     (HL)               12~[RW]N
        4,   // 07: RLC     A                  12~N
        4,   // 08: RRC     B                  12~N
        4,   // 09: RRC     C                  12~N
        4,   // 0A: RRC     D                  12~N
        4,   // 0B: RRC     E                  12~N
        4,   // 0C: RRC     H                  12~N
        4,   // 0D: RRC     L                  12~N
        29,  // 0E: RRC     (HL)               12~[RW]N
        4,   // 0F: RRC     A                  12~N
        4,   // 10: RL      B                  12~N
        4,   // 11: RL      C                  12~N
        4,   // 12: RL      D                  12~N
        4,   // 13: RL      E                  12~N
        4,   // 14: RL      H                  12~N
        4,   // 15: RL      L                  12~N
        29,  // 16: RL      (HL)               12~[RW]N
        4,   // 17: RL      A                  12~N
        4,   // 18: RR      B                  12~N
        4,   // 19: RR      C                  12~N
        4,   // 1A: RR      D                  12~N
        4,   // 1B: RR      E                  12~N
        4,   // 1C: RR      H                  12~N
        4,   // 1D: RR      L                  12~N
        29,  // 1E: RR      (HL)               12~[RW]N
        4,   // 1F: RR      A                  12~N
        4,   // 20: SLA     B                  12~N
        4,   // 21: SLA     C                  12~N
        4,   // 22: SLA     D                  12~N
        4,   // 23: SLA     E                  12~N
        4,   // 24: SLA     H                  12~N
        4,   // 25: SLA     L                  12~N
        29,  // 26: SLA     (HL)               12~[RW]N
        4,   // 27: SLA     A                  12~N
        4,   // 28: SRA     B                  12~N
        4,   // 29: SRA     C                  12~N
        4,   // 2A: SRA     D                  12~N
        4,   // 2B: SRA     E                  12~N
        4,   // 2C: SRA     H                  12~N
        4,   // 2D: SRA     L                  12~N
        29,  // 2E: SRA     (HL)               12~[RW]N
        4,   // 2F: SRA     A                  12~N
        4,   // 30: EX      B,B'               12~N
        4,   // 31: EX      C,C'               12~N
        4,   // 32: EX      D,D'               12~N
        4,   // 33: EX      E,E'               12~N
        4,   // 34: EX      H,H'               12~N
        4,   // 35: EX      L,L'               12~N
        0,   // 36
        4,   // 37: EX      A,A'               12~N
        4,   // 38: SRL     B                  12~N
        4,   // 39: SRL     C                  12~N
        4,   // 3A: SRL     D                  12~N
        4,   // 3B: SRL     E                  12~N
        4,   // 3C: SRL     H                  12~N
        4,   // 3D: SRL     L                  12~N
        29,  // 3E: SRL     (HL)               12~[RW]N
        4,   // 3F: SRL     A                  12~N
        4,   // 40: BIT     0,B                12~N
        4,   // 41: BIT     0,C                12~N
        4,   // 42: BIT     0,D                12~N
        4,   // 43: BIT     0,E                12~N
        4,   // 44: BIT     0,H                12~N
        4,   // 45: BIT     0,L                12~N
        30,  // 46: BIT     0,(HL)             12~[R]N
        4,   // 47: BIT     0,A                12~N
        4,   // 48: BIT     1,B                12~N
        4,   // 49: BIT     1,C                12~N
        4,   // 4A: BIT     1,D                12~N
        4,   // 4B: BIT     1,E                12~N
        4,   // 4C: BIT     1,H                12~N
        4,   // 4D: BIT     1,L                12~N
        30,  // 4E: BIT     1,(HL)             12~[R]N
        4,   // 4F: BIT     1,A                12~N
        4,   // 50: BIT     2,B                12~N
        4,   // 51: BIT     2,C                12~N
        4,   // 52: BIT     2,D                12~N
        4,   // 53: BIT     2,E                12~N
        4,   // 54: BIT     2,H                12~N
        4,   // 55: BIT     2,L                12~N
        30,  // 56: BIT     2,(HL)             12~[R]N
        4,   // 57: BIT     2,A                12~N
        4,   // 58: BIT     3,B                12~N
        4,   // 59: BIT     3,C                12~N
        4,   // 5A: BIT     3,D                12~N
        4,   // 5B: BIT     3,E                12~N
        4,   // 5C: BIT     3,H                12~N
        4,   // 5D: BIT     3,L                12~N
        30,  // 5E: BIT     3,(HL)             12~[R]N
        4,   // 5F: BIT     3,A                12~N
        4,   // 60: BIT     4,B                12~N
        4,   // 61: BIT     4,C                12~N
        4,   // 62: BIT     4,D                12~N
        4,   // 63: BIT     4,E                12~N
        4,   // 64: BIT     4,H                12~N
        4,   // 65: BIT     4,L                12~N
        30,  // 66: BIT     4,(HL)             12~[R]N
        4,   // 67: BIT     4,A                12~N
        4,   // 68: BIT     5,B                12~N
        4,   // 69: BIT     5,C                12~N
        4,   // 6A: BIT     5,D                12~N
        4,   // 6B: BIT     5,E                12~N
        4,   // 6C: BIT     5,H                12~N
        4,   // 6D: BIT     5,L                12~N
        30,  // 6E: BIT     5,(HL)             12~[R]N
        4,   // 6F: BIT     5,A                12~N
        4,   // 70: BIT     6,B                12~N
        4,   // 71: BIT     6,C                12~N
        4,   // 72: BIT     6,D                12~N
        4,   // 73: BIT     6,E                12~N
        4,   // 74: BIT     6,H                12~N
        4,   // 75: BIT     6,L                12~N
        30,  // 76: BIT     6,(HL)             12~[R]N
        4,   // 77: BIT     6,A                12~N
        4,   // 78: BIT     7,B                12~N
        4,   // 79: BIT     7,C                12~N
        4,   // 7A: BIT     7,D                12~N
        4,   // 7B: BIT     7,E                12~N
        4,   // 7C: BIT     7,H                12~N
        4,   // 7D: BIT     7,L                12~N
        30,  // 7E: BIT     7,(HL)             12~[R]N
        4,   // 7F: BIT     7,A                12~N
        4,   // 80: RES     0,B                12~N
        4,   // 81: RES     0,C                12~N
        4,   // 82: RES     0,D                12~N
        4,   // 83: RES     0,E                12~N
        4,   // 84: RES     0,H                12~N
        4,   // 85: RES     0,L                12~N
        29,  // 86: RES     0,(HL)             12~[RW]N
        4,   // 87: RES     0,A                12~N
        4,   // 88: RES     1,B                12~N
        4,   // 89: RES     1,C                12~N
        4,   // 8A: RES     1,D                12~N
        4,   // 8B: RES     1,E                12~N
        4,   // 8C: RES     1,H                12~N
        4,   // 8D: RES     1,L                12~N
        29,  // 8E: RES     1,(HL)             12~[RW]N
        4,   // 8F: RES     1,A                12~N
        4,   // 90: RES     2,B                12~N
        4,   // 91: RES     2,C                12~N
        4,   // 92: RES     2,D                12~N
        4,   // 93: RES     2,E                12~N
        4,   // 94: RES     2,H                12~N
        4,   // 95: RES     2,L                12~N
        29,  // 96: RES     2,(HL)             12~[RW]N
        4,   // 97: RES     2,A                12~N
        4,   // 98: RES     3,B                12~N
        4,   // 99: RES     3,C                12~N
        4,   // 9A: RES     3,D                12~N
        4,   // 9B: RES     3,E                12~N
        4,   // 9C: RES     3,H                12~N
        4,   // 9D: RES     3,L                12~N
        29,  // 9E: RES     3,(HL)             12~[RW]N
        4,   // 9F: RES     3,A                12~N
        4,   // A0: RES     4,B                12~N
        4,   // A1: RES     4,C                12~N
        4,   // A2: RES     4,D                12~N
        4,   // A3: RES     4,E                12~N
        4,   // A4: RES     4,H                12~N
        4,   // A5: RES     4,L                12~N
        29,  // A6: RES     4,(HL)             12~[RW]N
        4,   // A7: RES     4,A                12~N
        4,   // A8: RES     5,B                12~N
        4,   // A9: RES     5,C                12~N
        4,   // AA: RES     5,D                12~N
        4,   // AB: RES     5,E                12~N
        4,   // AC: RES     5,H                12~N
        4,   // AD: RES     5,L                12~N
        29,  // AE: RES     5,(HL)             12~[RW]N
        4,   // AF: RES     5,A                12~N
        4,   // B0: RES     6,B                12~N
        4,   // B1: RES     6,C                12~N
        4,   // B2: RES     6,D                12~N
        4,   // B3: RES     6,E                12~N
        4,   // B4: RES     6,H                12~N
        4,   // B5: RES     6,L                12~N
        29,  // B6: RES     6,(HL)             12~[RW]N
        4,   // B7: RES     6,A                12~N
        4,   // B8: RES     7,B                12~N
        4,   // B9: RES     7,C                12~N
        4,   // BA: RES     7,D                12~N
        4,   // BB: RES     7,E                12~N
        4,   // BC: RES     7,H                12~N
        4,   // BD: RES     7,L                12~N
        29,  // BE: RES     7,(HL)             12~[RW]N
        4,   // BF: RES     7,A                12~N
        4,   // C0: SET     0,B                12~N
        4,   // C1: SET     0,C                12~N
        4,   // C2: SET     0,D                12~N
        4,   // C3: SET     0,E                12~N
        4,   // C4: SET     0,H                12~N
        4,   // C5: SET     0,L                12~N
        29,  // C6: SET     0,(HL)             12~[RW]N
        4,   // C7: SET     0,A                12~N
        4,   // C8: SET     1,B                12~N
        4,   // C9: SET     1,C                12~N
        4,   // CA: SET     1,D                12~N
        4,   // CB: SET     1,E                12~N
        4,   // CC: SET     1,H                12~N
        4,   // CD: SET     1,L                12~N
        29,  // CE: SET     1,(HL)             12~[RW]N
        4,   // CF: SET     1,A                12~N
        4,   // D0: SET     2,B                12~N
        4,   // D1: SET     2,C                12~N
        4,   // D2: SET     2,D                12~N
        4,   // D3: SET     2,E                12~N
        4,   // D4: SET     2,H                12~N
        4,   // D5: SET     2,L                12~N
        29,  // D6: SET     2,(HL)             12~[RW]N
        4,   // D7: SET     2,A                12~N
        4,   // D8: SET     3,B                12~N
        4,   // D9: SET     3,C                12~N
        4,   // DA: SET     3,D                12~N
        4,   // DB: SET     3,E                12~N
        4,   // DC: SET     3,H                12~N
        4,   // DD: SET     3,L                12~N
        29,  // DE: SET     3,(HL)             12~[RW]N
        4,   // DF: SET     3,A                12~N
        4,   // E0: SET     4,B                12~N
        4,   // E1: SET     4,C                12~N
        4,   // E2: SET     4,D                12~N
        4,   // E3: SET     4,E                12~N
        4,   // E4: SET     4,H                12~N
        4,   // E5: SET     4,L                12~N
        29,  // E6: SET     4,(HL)             12~[RW]N
        4,   // E7: SET     4,A                12~N
        4,   // E8: SET     5,B                12~N
        4,   // E9: SET     5,C                12~N
        4,   // EA: SET     5,D                12~N
        4,   // EB: SET     5,E                12~N
        4,   // EC: SET     5,H                12~N
        4,   // ED: SET     5,L                12~N
        29,  // EE: SET     5,(HL)             12~[RW]N
        4,   // EF: SET     5,A                12~N
        4,   // F0: SET     6,B                12~N
        4,   // F1: SET     6,C                12~N
        4,   // F2: SET     6,D                12~N
        4,   // F3: SET     6,E                12~N
        4,   // F4: SET     6,H                12~N
        4,   // F5: SET     6,L                12~N
        29,  // F6: SET     6,(HL)             12~[RW]N
        4,   // F7: SET     6,A                12~N
        4,   // F8: SET     7,B                12~N
        4,   // F9: SET     7,C                12~N
        4,   // FA: SET     7,D                12~N
        4,   // FB: SET     7,E                12~N
        4,   // FC: SET     7,H                12~N
        4,   // FD: SET     7,L                12~N
        29,  // FE: SET     7,(HL)             12~[RW]N
        4,   // FF: SET     7,A                12~N
};

constexpr uint8_t PAGEED_TABLE[] = {
        31,  // 00: IN0     B,(1)              122~N
        31,  // 01: OUT0    (2),B              122~N
        4,   // 02: LDW     BC,BC              12~N
        4,   // 03: EX      BC,IX              12~N
        4,   // 04: TST     B                  12~N
        4,   // 05: EX      BC,DE              12~N
        32,  // 06: LDW     (BC),0807H         12aa~[Ww]N/12aa~[Wwww]N/
        4,   // 07: EX      A,B                12~N
        31,  // 08: IN0     C,(9)              122~N
        31,  // 09: OUT0    (10),C             122~N
        0,   // 0A
        4,   // 0B: EX      BC,IY              12~N
        4,   // 0C: TST     C                  12~N
        4,   // 0D: EX      BC,HL              12~N
        4,   // 0E: SWAP    BC                 12~N
        4,   // 0F: EX      A,C                12~N
        31,  // 10: IN0     D,(17)             122~N
        33,  // 11: OUT0    (18),D             122~[I]N
        4,   // 12: LDW     DE,BC              12~N
        4,   // 13: EX      DE,IX              12~N
        4,   // 14: TST     D                  12~N
        0,   // 15
        32,  // 16: LDW     (DE),1817H         12aa~[Ww]N/12aa~[Wwww]N/
        4,   // 17: EX      A,D                12~N
        31,  // 18: IN0     E,(25)             122~N
        31,  // 19: OUT0    (26),E             122~N
        0,   // 1A
        4,   // 1B: EX      DE,IY              12~N
        4,   // 1C: TST     E                  12~N
        0,   // 1D
        4,   // 1E: SWAP    DE                 12~N
        4,   // 1F: EX      A,E                12~N
        31,  // 20: IN0     H,(21H)            122~N
        31,  // 21: OUT0    (22H),H            122~N
        0,   // 22
        0,   // 23
        4,   // 24: TST     H                  12~N
        0,   // 25
        0,   // 26
        4,   // 27: EX      A,H                12~N
        31,  // 28: IN0     L,(29H)            122~N
        31,  // 29: OUT0    (2AH),L            122~N
        0,   // 2A
        4,   // 2B: EX      IX,IY              12~N
        4,   // 2C: TST     L                  12~N
        0,   // 2D
        0,   // 2E
        4,   // 2F: EX      A,L                12~N
        31,  // 30: IN0     (31H)              122~N
        0,   // 31
        4,   // 32: LDW     HL,BC              12~N
        4,   // 33: EX      HL,IX              12~N
        30,  // 34: TST     (HL)               12~[R]N
        0,   // 35
        32,  // 36: LDW     (HL),3837H         12aa~[Ww]N/12aa~[Wwww]N/
        29,  // 37: EX      A,(HL)             12~[RW]N
        31,  // 38: IN0     A,(39H)            122~N
        31,  // 39: OUT0    (3AH),A            122~N
        0,   // 3A
        4,   // 3B: EX      HL,IY              12~N
        4,   // 3C: TST     A                  12~N
        0,   // 3D
        4,   // 3E: SWAP    HL                 12~N
        4,   // 3F: EX      A,A                12~N
        25,  // 40: IN      B,(C)              12~[I]N
        24,  // 41: OUT     (C),B              12~[O]N
        4,   // 42: SBC     HL,BC              12~N
        32,  // 43: LD      (4544H),BC         12aa~[Ww]N/12aa~[Wwww]N/
        4,   // 44: NEG     -                  12~N
        34,  // 45: RETN    -                  12~[Rr?]//12~[Rrrr?]
        4,   // 46: IM      0                  12~N
        4,   // 47: LD      I,A                12~N
        25,  // 48: IN      C,(C)              12~[I]N
        24,  // 49: OUT     (C),C              12~[O]N
        4,   // 4A: ADC     HL,BC              12~N
        35,  // 4B: LD      BC,(4D4CH)         12aa~[Rr]N/12aa~[Rrrr]N/
        4,   // 4C: MLT     BC                 12~N
        36,  // 4D: RETI    -                  12~[RrII?]//12~[RrrrII?]
        4,   // 4E: IM      3                  12~N
        4,   // 4F: LD      R,A                12~N
        25,  // 50: IN      D,(C)              12~[I]N
        24,  // 51: OUT     (C),D              12~[O]N
        4,   // 52: SBC     HL,DE              12~N
        32,  // 53: LD      (5554H),DE         12aa~[Ww]N/12aa~[Wwww]N/
        4,   // 54: NEGW    HL                 12~N
        0,   // 55
        4,   // 56: IM      1                  12~N
        4,   // 57: LD      A,I                12~N
        25,  // 58: IN      E,(C)              12~[I]N
        24,  // 59: OUT     (C),E              12~[O]N
        4,   // 5A: ADC     HL,DE              12~N
        35,  // 5B: LD      DE,(5D5CH)         12aa~[Rr]N/12aa~[Rrrr]N/
        4,   // 5C: MLT     DE                 12~N
        0,   // 5D
        4,   // 5E: IM      2                  12~N
        4,   // 5F: LD      A,R                12~N
        25,  // 60: IN      H,(C)              12~[I]N
        24,  // 61: OUT     (C),H              12~[O]N
        4,   // 62: SBC     HL,HL              12~N
        32,  // 63: LDW     (6564H),HL         12aa~[Ww]N/12aa~[Wwww]N/
        31,  // 64: TST     65H                122~N
        4,   // 65: EXTS    A                  12~N
        0,   // 66
        29,  // 67: RRD     -                  12~[RW]N
        25,  // 68: IN      L,(C)              12~[I]N
        24,  // 69: OUT     (C),L              12~[O]N
        4,   // 6A: ADC     HL,HL              12~N
        35,  // 6B: LDW     HL,(6D6CH)         12aa~[Rr]N/12aa~[Rrrr]N/
        4,   // 6C: MLT     HL                 12~N
        0,   // 6D
        0,   // 6E
        29,  // 6F: RLD     -                  12~[RW]N
        0,   // 70
        37,  // 71: OUT     (C),72H            122~[O]N
        4,   // 72: SBC     HL,SP              12~N
        32,  // 73: LD      (7574H),SP         12aa~[Ww]N/12aa~[Wwww]N/
        31,  // 74: TSTIO   75H                122~N
        4,   // 75: EXTSW   HL                 12~N
        38,  // 76: SLP     -                  12~{h}N
        0,   // 77
        25,  // 78: IN      A,(C)              12~[I]N
        24,  // 79: OUT     (C),A              12~[O]N
        4,   // 7A: ADC     HL,SP              12~N
        35,  // 7B: LD      SP,(7D7CH)         12aa~[Rr]N/12aa~[Rrrr]N/
        4,   // 7C: MLT     SP                 12~N
        0,   // 7D
        0,   // 7E
        0,   // 7F
        0,   // 80
        0,   // 81
        39,  // 82: ADD     SP,8483H           12aa~N
        30,  // 83: OTIM    -                  12~[R]N
        4,   // 84: ADDW    HL,BC              12~N
        4,   // 85: ADDW    HL,DE              12~N
        40,  // 86: ADDW    HL,8887H           1222~N
        4,   // 87: ADDW    HL,HL              12~N
        0,   // 88
        0,   // 89
        0,   // 8A
        30,  // 8B: OTDM    -                  12~[R]N
        4,   // 8C: ADCW    HL,BC              12~N
        4,   // 8D: ADCW    HL,DE              12~N
        40,  // 8E: ADCW    HL,908FH           1222~N
        4,   // 8F: ADCW    HL,HL              12~N
        0,   // 90
        0,   // 91
        39,  // 92: SUB     SP,9493H           12aa~N
        41,  // 93: OTIMR   -                  12~{R+1}N
        4,   // 94: SUBW    HL,BC              12~N
        4,   // 95: SUBW    HL,DE              12~N
        40,  // 96: SUBW    HL,9897H           1222~N
        4,   // 97: SUBW    HL,HL              12~N
        0,   // 98
        0,   // 99
        0,   // 9A
        42,  // 9B: OTDMR   -                  12~{R-1}N
        4,   // 9C: SBCW    HL,BC              12~N
        4,   // 9D: SBCW    HL,DE              12~N
        40,  // 9E: SBCW    HL,0A09FH          1222~N
        4,   // 9F: SBCW    HL,HL              12~N
        29,  // A0: LDI     -                  12~[RW]N
        30,  // A1: CPI     -                  12~[R]N
        43,  // A2: INI     -                  12~[WI]N
        44,  // A3: OUTI    -                  12~[RO]N
        4,   // A4: ANDW    HL,BC              12~N
        4,   // A5: ANDW    HL,DE              12~N
        40,  // A6: ANDW    HL,0A8A7H          1222~N
        4,   // A7: ANDW    HL,HL              12~N
        29,  // A8: LDD     -                  12~[RW]N
        30,  // A9: CPD     -                  12~[R]N
        43,  // AA: IND     -                  12~[WI]N
        44,  // AB: OUTD    -                  12~[RO]N
        4,   // AC: XORW    HL,BC              12~N
        4,   // AD: XORW    HL,DE              12~N
        40,  // AE: XORW    HL,0B0AFH          1222~N
        4,   // AF: XORW    HL,HL              12~N
        45,  // B0: LDIR    -                  12~{R+1W+1}N
        41,  // B1: CPIR    -                  12~{R+1}N
        46,  // B2: INIR    -                  12~{I.W+1}N
        47,  // B3: OTIR    -                  12~{R+1O.}N
        4,   // B4: ORW     HL,BC              12~N
        4,   // B5: ORW     HL,DE              12~N
        40,  // B6: ORW     HL,0B8B7H          1222~N
        4,   // B7: ORW     HL,HL              12~N
        48,  // B8: LDDR    -                  12~{R-1W-1}N
        42,  // B9: CPDR    -                  12~{R-1}N
        49,  // BA: INDR    -                  12~{I.W-1}N
        50,  // BB: OTDR    -                  12~{R-1O.}N
        4,   // BC: CPW     HL,BC              12~N
        4,   // BD: CPW     HL,DE              12~N
        40,  // BE: CPW     HL,0C0BFH          1222~N
        4,   // BF: CPW     HL,HL              12~N
        4,   // C0: LDCTL   HL,SR              12~N
        51,  // C1: POP     SR                 12~[Rr]N/12~[Rrrr]N/
        0,   // C2
        0,   // C3
        52,  // C4: CALR    NZ,$-56 122~[WwJ]@122~N//122~[WwwwJ]@122~N
        53,  // C5: PUSH    SR                 12~[Ww]N/12~[Wwww]N/
        54,  // C6: ADD     HL,(0C8C7H)        12aa~[Rr]N
        0,   // C7
        4,   // C8: LDCTL   SR,HL              12~N
        0,   // C9
        0,   // CA
        0,   // CB
        52,  // CC: CALR    Z,$-48 122~[WwJ]@122~N//122~[WwwwJ]@122~N
        55,  // CD: CALR    $-47               122~[WwJ]//122~[WwwwJ]
        0,   // CE
        4,   // CF: BTEST   -                  12~N
        4,   // D0: LDCTL   A,DSR              12~N
        0,   // D1
        0,   // D2
        56,  // D3: OUTA    (0D5D4H),A         12aa~[O]N
        52,  // D4: CALR    NC,$-40 122~[WwJ]@122~N//122~[WwwwJ]@122~N
        0,   // D5
        54,  // D6: SUB     HL,(0D8D7H)        12aa~[Rr]N
        0,   // D7
        4,   // D8: LDCTL   DSR,A              12~N
        4,   // D9: EXALL   -                  12~N
        31,  // DA: LDCTL   DSR,0DBH           122~N
        57,  // DB: INA     A,(0DDDCH)         12aa~[I]N
        52,  // DC: CALR    C,$-32 122~[WwJ]@122~N//122~[WwwwJ]@122~N
        0,   // DD
        0,   // DE
        0,   // DF
        58,  // E0: LDIW    -                  12~[RrWw]N
        0,   // E1
        59,  // E2: INIW    -                  12~[WwI]N
        60,  // E3: OUTIW   -                  12~[RrO]N
        52,  // E4: CALR    PO,$-24 122~[WwJ]@122~N//122~[WwwwJ]@122~N
        0,   // E5
        0,   // E6
        0,   // E7
        58,  // E8: LDDW    -                  12~[RrWw]N
        0,   // E9
        59,  // EA: INDW    -                  12~[WwI]N
        60,  // EB: OUTDW   -                  12~[RrO]N
        52,  // EC: CALR    PE,$-16 122~[WwJ]@122~N//122~[WwwwJ]@122~N
        0,   // ED
        0,   // EE
        0,   // EF
        61,  // F0: LDIRW   -                  12~{R+2rW+2w}N
        0,   // F1
        62,  // F2: INIRW   -                  12~{I.W+2w}N
        63,  // F3: OTIRW   -                  12~{R+2rO.}N
        52,  // F4: CALR    P,$-8 122~[WwJ]@122~N//122~[WwwwJ]@122~N
        0,   // F5
        0,   // F6
        4,   // F7: SETC    LCK                12~N
        64,  // F8: LDDRW   -                  12~{R-2rW-2w}N
        0,   // F9
        65,  // FA: INDRW   -                  12~{I.W-2w}N
        66,  // FB: OTDRW   -                  12~{R-2rO.}N
        52,  // FC: CALR    M,$ 122~[WwJ]@122~N//122~[WwwwJ]@122~N
        0,   // FD
        0,   // FE
        4,   // FF: RESC    LCK                12~N
};

constexpr uint8_t PAGEEDCB_TABLE[] = {
        31,  // 00: RLCW    BC                 122~N
        31,  // 01: RLCW    DE                 122~N
        67,  // 02: RLCW    (HL)               122~[RrWw]N
        31,  // 03: RLCW    HL                 122~N
        31,  // 04: RLCW    IX                 122~N
        31,  // 05: RLCW    IY                 122~N
        0,   // 06
        0,   // 07
        31,  // 08: RRCW    BC                 122~N
        31,  // 09: RRCW    DE                 122~N
        67,  // 0A: RRCW    (HL)               122~[RrWw]N
        31,  // 0B: RRCW    HL                 122~N
        31,  // 0C: RRCW    IX                 122~N
        31,  // 0D: RRCW    IY                 122~N
        0,   // 0E
        0,   // 0F
        31,  // 10: RLW     BC                 122~N
        31,  // 11: RLW     DE                 122~N
        67,  // 12: RLW     (HL)               122~[RrWw]N
        31,  // 13: RLW     HL                 122~N
        31,  // 14: RLW     IX                 122~N
        31,  // 15: RLW     IY                 122~N
        0,   // 16
        0,   // 17
        31,  // 18: RRW     BC                 122~N
        31,  // 19: RRW     DE                 122~N
        67,  // 1A: RRW     (HL)               122~[RrWw]N
        31,  // 1B: RRW     HL                 122~N
        31,  // 1C: RRW     IX                 122~N
        31,  // 1D: RRW     IY                 122~N
        0,   // 1E
        0,   // 1F
        31,  // 20: SLAW    BC                 122~N
        31,  // 21: SLAW    DE                 122~N
        67,  // 22: SLAW    (HL)               122~[RrWw]N
        31,  // 23: SLAW    HL                 122~N
        31,  // 24: SLAW    IX                 122~N
        31,  // 25: SLAW    IY                 122~N
        0,   // 26
        0,   // 27
        31,  // 28: SRAW    BC                 122~N
        31,  // 29: SRAW    DE                 122~N
        67,  // 2A: SRAW    (HL)               122~[RrWw]N
        31,  // 2B: SRAW    HL                 122~N
        31,  // 2C: SRAW    IX                 122~N
        31,  // 2D: SRAW    IY                 122~N
        0,   // 2E
        0,   // 2F
        31,  // 30: EX      BC,BC'             122~N
        31,  // 31: EX      DE,DE'             122~N
        0,   // 32
        31,  // 33: EX      HL,HL'             122~N
        31,  // 34: EX      IX,IX'             122~N
        31,  // 35: EX      IY,IY'             122~N
        0,   // 36
        0,   // 37
        31,  // 38: SRLW    BC                 122~N
        31,  // 39: SRLW    DE                 122~N
        67,  // 3A: SRLW    (HL)               122~[RrWw]N
        31,  // 3B: SRLW    HL                 122~N
        31,  // 3C: SRLW    IX                 122~N
        31,  // 3D: SRLW    IY                 122~N
        0,   // 3E
        0,   // 3F
        0,   // 40
        0,   // 41
        0,   // 42
        0,   // 43
        0,   // 44
        0,   // 45
        0,   // 46
        0,   // 47
        0,   // 48
        0,   // 49
        0,   // 4A
        0,   // 4B
        0,   // 4C
        0,   // 4D
        0,   // 4E
        0,   // 4F
        0,   // 50
        0,   // 51
        0,   // 52
        0,   // 53
        0,   // 54
        0,   // 55
        0,   // 56
        0,   // 57
        0,   // 58
        0,   // 59
        0,   // 5A
        0,   // 5B
        0,   // 5C
        0,   // 5D
        0,   // 5E
        0,   // 5F
        0,   // 60
        0,   // 61
        0,   // 62
        0,   // 63
        0,   // 64
        0,   // 65
        0,   // 66
        0,   // 67
        0,   // 68
        0,   // 69
        0,   // 6A
        0,   // 6B
        0,   // 6C
        0,   // 6D
        0,   // 6E
        0,   // 6F
        0,   // 70
        0,   // 71
        0,   // 72
        0,   // 73
        0,   // 74
        0,   // 75
        0,   // 76
        0,   // 77
        0,   // 78
        0,   // 79
        0,   // 7A
        0,   // 7B
        0,   // 7C
        0,   // 7D
        0,   // 7E
        0,   // 7F
        0,   // 80
        0,   // 81
        0,   // 82
        0,   // 83
        0,   // 84
        0,   // 85
        0,   // 86
        0,   // 87
        0,   // 88
        0,   // 89
        0,   // 8A
        0,   // 8B
        0,   // 8C
        0,   // 8D
        0,   // 8E
        0,   // 8F
        31,  // 90: MULTW   HL,BC              122~N
        31,  // 91: MULTW   HL,DE              122~N
        0,   // 92
        31,  // 93: MULTW   HL,HL              122~N
        31,  // 94: MULTW   HL,IX              122~N
        31,  // 95: MULTW   HL,IY              122~N
        0,   // 96
        68,  // 97: MULTW   HL,9998H           12222~N
        31,  // 98: MULTUW  HL,BC              122~N
        31,  // 99: MULTUW  HL,DE              122~N
        0,   // 9A
        31,  // 9B: MULTUW  HL,HL              122~N
        31,  // 9C: MULTUW  HL,IX              122~N
        31,  // 9D: MULTUW  HL,IY              122~N
        0,   // 9E
        68,  // 9F: MULTUW  HL,0A1A0H          12222~N
        0,   // A0
        0,   // A1
        0,   // A2
        0,   // A3
        0,   // A4
        0,   // A5
        0,   // A6
        0,   // A7
        0,   // A8
        0,   // A9
        0,   // AA
        0,   // AB
        0,   // AC
        0,   // AD
        0,   // AE
        0,   // AF
        0,   // B0
        0,   // B1
        0,   // B2
        0,   // B3
        0,   // B4
        0,   // B5
        0,   // B6
        0,   // B7
        31,  // B8: DIVUW   HL,BC              122~N
        31,  // B9: DIVUW   HL,DE              122~N
        0,   // BA
        31,  // BB: DIVUW   HL,HL              122~N
        31,  // BC: DIVUW   HL,IX              122~N
        31,  // BD: DIVUW   HL,IY              122~N
        0,   // BE
        68,  // BF: DIVUW   HL,0C1C0H          12222~N
        0,   // C0
        0,   // C1
        0,   // C2
        0,   // C3
        0,   // C4
        0,   // C5
        0,   // C6
        0,   // C7
        0,   // C8
        0,   // C9
        0,   // CA
        0,   // CB
        0,   // CC
        0,   // CD
        0,   // CE
        0,   // CF
        0,   // D0
        0,   // D1
        0,   // D2
        0,   // D3
        0,   // D4
        0,   // D5
        0,   // D6
        0,   // D7
        0,   // D8
        0,   // D9
        0,   // DA
        0,   // DB
        0,   // DC
        0,   // DD
        0,   // DE
        0,   // DF
        0,   // E0
        0,   // E1
        0,   // E2
        0,   // E3
        0,   // E4
        0,   // E5
        0,   // E6
        0,   // E7
        0,   // E8
        0,   // E9
        0,   // EA
        0,   // EB
        0,   // EC
        0,   // ED
        0,   // EE
        0,   // EF
        0,   // F0
        0,   // F1
        0,   // F2
        0,   // F3
        0,   // F4
        0,   // F5
        0,   // F6
        0,   // F7
        0,   // F8
        0,   // F9
        0,   // FA
        0,   // FB
        0,   // FC
        0,   // FD
        0,   // FE
        0,   // FF
};

constexpr uint8_t PAGEDD_TABLE[] = {
        0,   // 00
        53,  // 01: LDW     (BC),IX            12~[Ww]N/12~[Wwww]N/
        4,   // 02: LDW     BC,DE              12~N
        51,  // 03: LDW     IX,(BC)            12~[Rr]N/12~[Rrrr]N/
        0,   // 04
        0,   // 05
        0,   // 06
        4,   // 07: LDW     IX,BC              12~N
        0,   // 08
        4,   // 09: ADD     IX,BC              12~N
        0,   // 0A
        4,   // 0B: LDW     BC,IX              12~N
        51,  // 0C: LDW     BC,(BC)            12~[Rr]N/12~[Rrrr]N/
        51,  // 0D: LDW     BC,(DE)            12~[Rr]N/12~[Rrrr]N/
        0,   // 0E
        51,  // 0F: LDW     BC,(HL)            12~[Rr]N/12~[Rrrr]N/
        69,  // 10: DJNZ    $+1215H            1222~[J]@1222~N
        53,  // 11: LDW     (DE),IX            12~[Ww]N/12~[Wwww]N/
        4,   // 12: LDW     DE,DE              12~N
        51,  // 13: LDW     IX,(DE)            12~[Rr]N/12~[Rrrr]N/
        0,   // 14
        0,   // 15
        0,   // 16
        4,   // 17: LDW     IX,DE              12~N
        70,  // 18: JR      $+1A1DH            1222~[J]
        4,   // 19: ADD     IX,DE              12~N
        0,   // 1A
        4,   // 1B: LDW     DE,IX              12~N
        51,  // 1C: LDW     DE,(BC)            12~[Rr]N/12~[Rrrr]N/
        51,  // 1D: LDW     DE,(DE)            12~[Rr]N/12~[Rrrr]N/
        0,   // 1E
        51,  // 1F: LDW     DE,(HL)            12~[Rr]N/12~[Rrrr]N/
        69,  // 20: JR      NZ,$+2225H         1222~[J]@1222~N
        39,  // 21: LD      IX,2322H           12aa~N
        32,  // 22: LD      (2423H),IX         12aa~[Ww]N/12aa~[Wwww]N/
        4,   // 23: INC     IX                 12~N
        4,   // 24: INC     IXU                12~N
        4,   // 25: DEC     IXU                12~N
        31,  // 26: LD      IXU,27H            122~N
        4,   // 27: LDW     IX,IY              12~N
        69,  // 28: JR      Z,$+2A2DH          1222~[J]@1222~N
        4,   // 29: ADD     IX,IX              12~N
        35,  // 2A: LD      IX,(2C2BH)         12aa~[Rr]N/12aa~[Rrrr]N/
        4,   // 2B: DEC     IX                 12~N
        4,   // 2C: INC     IXL                12~N
        4,   // 2D: DEC     IXL                12~N
        31,  // 2E: LD      IXL,2FH            122~N
        4,   // 2F: CPLW    HL                 12~N
        69,  // 30: JR      NC,$+3235H         1222~[J]@1222~N
        53,  // 31: LDW     (HL),IX            12~[Ww]N/12~[Wwww]N/
        4,   // 32: LDW     HL,DE              12~N
        51,  // 33: LDW     IX,(HL)            12~[Rr]N/12~[Rrrr]N/
        71,  // 34: INC     (IX+53)            1aa~[RW]N
        71,  // 35: DEC     (IX+54)            1aa~[RW]N
        72,  // 36: LD      (IX+55),38H        12aa~[W]N
        4,   // 37: LDW     IX,HL              12~N
        69,  // 38: JR      C,$+3A3DH          1222~[J]@1222~N
        4,   // 39: ADD     IX,SP              12~N
        0,   // 3A
        4,   // 3B: LDW     HL,IX              12~N
        51,  // 3C: LDW     HL,(BC)            12~[Rr]N/12~[Rrrr]N/
        51,  // 3D: LDW     HL,(DE)            12~[Rr]N/12~[Rrrr]N/
        4,   // 3E: SWAP    IX                 12~N
        51,  // 3F: LDW     HL,(HL)            12~[Rr]N/12~[Rrrr]N/
        25,  // 40: INW     BC,(C)             12~[I]N
        24,  // 41: OUTW    (C),BC             12~[O]N
        0,   // 42
        0,   // 43
        4,   // 44: LD      B,IXU              12~N
        4,   // 45: LD      B,IXL              12~N
        13,  // 46: LD      B,(IX+71)          1aa~[R]N
        4,   // 47: LDW     I,HL               12~N
        0,   // 48
        0,   // 49
        0,   // 4A
        0,   // 4B
        4,   // 4C: LD      C,IXU              12~N
        4,   // 4D: LD      C,IXL              12~N
        13,  // 4E: LD      C,(IX+79)          1aa~[R]N
        0,   // 4F
        25,  // 50: INW     DE,(C)             12~[I]N
        24,  // 51: OUTW    (C),DE             12~[O]N
        0,   // 52
        0,   // 53
        4,   // 54: LD      D,IXU              12~N
        4,   // 55: LD      D,IXL              12~N
        13,  // 56: LD      D,(IX+87)          1aa~[R]N
        4,   // 57: LDW     HL,I               12~N
        0,   // 58
        0,   // 59
        0,   // 5A
        0,   // 5B
        4,   // 5C: LD      E,IXU              12~N
        4,   // 5D: LD      E,IXL              12~N
        13,  // 5E: LD      E,(IX+95)          1aa~[R]N
        0,   // 5F
        4,   // 60: LD      IXU,B              12~N
        4,   // 61: LD      IXU,C              12~N
        4,   // 62: LD      IXU,D              12~N
        4,   // 63: LD      IXU,E              12~N
        4,   // 64: LD      IXU,IXU            12~N
        4,   // 65: LD      IXU,IXL            12~N
        13,  // 66: LD      H,(IX+103)         1aa~[R]N
        4,   // 67: LD      IXU,A              12~N
        4,   // 68: LD      IXL,B              12~N
        4,   // 69: LD      IXL,C              12~N
        4,   // 6A: LD      IXL,D              12~N
        4,   // 6B: LD      IXL,E              12~N
        4,   // 6C: LD      IXL,IXU            12~N
        4,   // 6D: LD      IXL,IXL            12~N
        13,  // 6E: LD      L,(IX+111)         1aa~[R]N
        4,   // 6F: LD      IXL,A              12~N
        10,  // 70: LD      (IX+113),B         1aa~[W]N
        10,  // 71: LD      (IX+114),C         1aa~[W]N
        10,  // 72: LD      (IX+115),D         1aa~[W]N
        10,  // 73: LD      (IX+116),E         1aa~[W]N
        10,  // 74: LD      (IX+117),H         1aa~[W]N
        10,  // 75: LD      (IX+118),L         1aa~[W]N
        0,   // 76
        10,  // 77: LD      (IX+120),A         1aa~[W]N
        25,  // 78: INW     HL,(C)             12~[I]N
        24,  // 79: OUTW    (C),HL             12~[O]N
        0,   // 7A
        0,   // 7B
        4,   // 7C: LD      A,IXU              12~N
        4,   // 7D: LD      A,IXL              12~N
        13,  // 7E: LD      A,(IX+127)         1aa~[R]N
        0,   // 7F
        0,   // 80
        0,   // 81
        0,   // 82
        0,   // 83
        4,   // 84: ADD     A,IXU              12~N
        4,   // 85: ADD     A,IXL              12~N
        13,  // 86: ADD     A,(IX-121)         1aa~[R]N
        4,   // 87: ADDW    HL,IX              12~N
        0,   // 88
        0,   // 89
        0,   // 8A
        0,   // 8B
        4,   // 8C: ADC     A,IXU              12~N
        4,   // 8D: ADC     A,IXL              12~N
        13,  // 8E: ADC     A,(IX-113)         1aa~[R]N
        4,   // 8F: ADCW    HL,IX              12~N
        0,   // 90
        0,   // 91
        0,   // 92
        0,   // 93
        4,   // 94: SUB     A,IXU              12~N
        4,   // 95: SUB     A,IXL              12~N
        13,  // 96: SUB     (IX-105)           1aa~[R]N
        4,   // 97: SUBW    HL,IX              12~N
        0,   // 98
        0,   // 99
        0,   // 9A
        0,   // 9B
        4,   // 9C: SBC     A,IXU              12~N
        4,   // 9D: SBC     A,IXL              12~N
        13,  // 9E: SBC     A,(IX-97)          1aa~[R]N
        4,   // 9F: SBCW    HL,IX              12~N
        0,   // A0
        0,   // A1
        0,   // A2
        0,   // A3
        4,   // A4: AND     A,IXU              12~N
        4,   // A5: AND     A,IXL              12~N
        13,  // A6: AND     (IX-89)            1aa~[R]N
        4,   // A7: ANDW    HL,IX              12~N
        0,   // A8
        0,   // A9
        0,   // AA
        0,   // AB
        4,   // AC: XOR     A,IXU              12~N
        4,   // AD: XOR     A,IXL              12~N
        13,  // AE: XOR     (IX-81)            1aa~[R]N
        4,   // AF: XORW    HL,IX              12~N
        0,   // B0
        0,   // B1
        0,   // B2
        0,   // B3
        4,   // B4: OR      A,IXU              12~N
        4,   // B5: OR      A,IXL              12~N
        13,  // B6: OR      (IX-73)            1aa~[R]N
        4,   // B7: ORW     HL,IX              12~N
        0,   // B8
        0,   // B9
        0,   // BA
        0,   // BB
        4,   // BC: CP      A,IXU              12~N
        4,   // BD: CP      A,IXL              12~N
        13,  // BE: CP      (IX-65)            1aa~[R]N
        4,   // BF: CPW     HL,IX              12~N
        4,   // C0: DDIR    W                  12~N
        4,   // C1: DDIR    IB,W               12~N
        4,   // C2: DDIR    IW,W               12~N
        4,   // C3: DDIR    IB                 12~N
        73,  // C4: CALR    NZ,$-3937H 1222~[WwJ]@1222~N//1222~[WwwwJ]@1222~N
        0,   // C5
        74,  // C6: ADDW    HL,(IX-57)         1aa~[Rr]N
        0,   // C7
        4,   // C8: LDCTL   SR,A               12~N
        0,   // C9
        31,  // CA: LDCTL   SR,0CBH            122~N
        0,   // CB
        73,  // CC: CALR    Z,$-312FH 1222~[WwJ]@1222~N//1222~[WwwwJ]@1222~N
        75,  // CD: CALR    $-302EH            1222~[WwJ]//1222~[WwwwJ]
        74,  // CE: ADCW    HL,(IX-49)         1aa~[Rr]N
        4,   // CF: MTEST   -                  12~N
        4,   // D0: LDCTL   A,XSR              12~N
        0,   // D1
        0,   // D2
        0,   // D3
        73,  // D4: CALR    NC,$-2927H 1222~[WwJ]@1222~N//1222~[WwwwJ]@1222~N
        0,   // D5
        74,  // D6: SUBW    HL,(IX-41)         1aa~[Rr]N
        0,   // D7
        4,   // D8: LDCTL   XSR,A              12~N
        4,   // D9: EXXX    -                  12~N
        31,  // DA: LDCTL   XSR,0DBH           122~N
        0,   // DB
        73,  // DC: CALR    C,$-211FH 1222~[WwJ]@1222~N//1222~[WwwwJ]@1222~N
        0,   // DD
        74,  // DE: SBCW    HL,(IX-33)         1aa~[Rr]N
        0,   // DF
        0,   // E0
        51,  // E1: POP     IX                 12~[Rr]N/12~[Rrrr]N/
        0,   // E2
        76,  // E3: EX      (SP),IX            12~[RrWw]N/12~[RrrrWwww]N/
        73,  // E4: CALR    PO,$-1917H 1222~[WwJ]@1222~N//1222~[WwwwJ]@1222~N
        53,  // E5: PUSH    IX                 12~[Ww]N/12~[Wwww]N/
        74,  // E6: ANDW    HL,(IX-25)         1aa~[Rr]N
        0,   // E7
        0,   // E8
        77,  // E9: JP      (IX)               12~[?]
        0,   // EA
        0,   // EB
        73,  // EC: CALR    PE,$-110FH 1222~[WwJ]@1222~N//1222~[WwwwJ]@1222~N
        0,   // ED
        74,  // EE: XORW    HL,(IX-17)         1aa~[Rr]N
        0,   // EF
        0,   // F0
        0,   // F1
        0,   // F2
        31,  // F3: DI      0F4H               122~N
        73,  // F4: CALR    P,$-0907H 1222~[WwJ]@1222~N//1222~[WwwwJ]@1222~N
        0,   // F5
        74,  // F6: ORW     HL,(IX-9)          1aa~[Rr]N
        4,   // F7: SETC    LW                 12~N
        0,   // F8
        4,   // F9: LD      SP,IX              12~N
        0,   // FA
        31,  // FB: EI      0FCH               122~N
        73,  // FC: CALR    M,$-00FFH 1222~[WwJ]@1222~N//1222~[WwwwJ]@1222~N
        0,   // FD
        74,  // FE: CPW     HL,(IX-1)          1aa~[Rr]N
        4,   // FF: RESC    LW                 12~N
};

constexpr uint8_t PAGEFD_TABLE[] = {
        0,   // 00
        53,  // 01: LDW     (BC),IY            12~[Ww]N/12~[Wwww]N/
        4,   // 02: LDW     BC,HL              12~N
        51,  // 03: LDW     IY,(BC)            12~[Rr]N/12~[Rrrr]N/
        0,   // 04
        0,   // 05
        0,   // 06
        4,   // 07: LDW     IY,BC              12~N
        0,   // 08
        4,   // 09: ADD     IY,BC              12~N
        0,   // 0A
        4,   // 0B: LDW     BC,IY              12~N
        53,  // 0C: LDW     (BC),BC            12~[Ww]N/12~[Wwww]N/
        53,  // 0D: LDW     (DE),BC            12~[Ww]N/12~[Wwww]N/
        0,   // 0E
        53,  // 0F: LDW     (HL),BC            12~[Ww]N/12~[Wwww]N/
        78,  // 10: DJNZ    $+131216H          12222~[J]@12222~N
        53,  // 11: LDW     (DE),IY            12~[Ww]N/12~[Wwww]N/
        4,   // 12: LDW     DE,HL              12~N
        51,  // 13: LDW     IY,(DE)            12~[Rr]N/12~[Rrrr]N/
        0,   // 14
        0,   // 15
        0,   // 16
        4,   // 17: LDW     IY,DE              12~N
        79,  // 18: JR      $+1B1A1EH          12222~[J]
        4,   // 19: ADD     IY,DE              12~N
        0,   // 1A
        4,   // 1B: LDW     DE,IY              12~N
        53,  // 1C: LDW     (BC),DE            12~[Ww]N/12~[Wwww]N/
        53,  // 1D: LDW     (DE),DE            12~[Ww]N/12~[Wwww]N/
        0,   // 1E
        53,  // 1F: LDW     (HL),DE            12~[Ww]N/12~[Wwww]N/
        78,  // 20: JR      NZ,$+232226H       12222~[J]@12222~N
        39,  // 21: LD      IY,2322H           12aa~N
        32,  // 22: LD      (2423H),IY         12aa~[Ww]N/12aa~[Wwww]N/
        4,   // 23: INC     IY                 12~N
        4,   // 24: INC     IYU                12~N
        4,   // 25: DEC     IYU                12~N
        31,  // 26: LD      IYU,27H            122~N
        4,   // 27: LDW     IY,IX              12~N
        78,  // 28: JR      Z,$+2B2A2EH        12222~[J]@12222~N
        4,   // 29: ADD     IY,IY              12~N
        35,  // 2A: LD      IY,(2C2BH)         12aa~[Rr]N/12aa~[Rrrr]N/
        4,   // 2B: DEC     IY                 12~N
        4,   // 2C: INC     IYL                12~N
        4,   // 2D: DEC     IYL                12~N
        31,  // 2E: LD      IYL,2FH            122~N
        0,   // 2F
        78,  // 30: JR      NC,$+333236H       12222~[J]@12222~N
        53,  // 31: LDW     (HL),IY            12~[Ww]N/12~[Wwww]N/
        4,   // 32: LDW     HL,HL              12~N
        51,  // 33: LDW     IY,(HL)            12~[Rr]N/12~[Rrrr]N/
        71,  // 34: INC     (IY+53)            1aa~[RW]N
        71,  // 35: DEC     (IY+54)            1aa~[RW]N
        72,  // 36: LD      (IY+55),38H        12aa~[W]N
        4,   // 37: LDW     IY,HL              12~N
        78,  // 38: JR      C,$+3B3A3EH        12222~[J]@12222~N
        4,   // 39: ADD     IY,SP              12~N
        0,   // 3A
        4,   // 3B: LDW     HL,IY              12~N
        53,  // 3C: LDW     (BC),HL            12~[Ww]N/12~[Wwww]N/
        53,  // 3D: LDW     (DE),HL            12~[Ww]N/12~[Wwww]N/
        4,   // 3E: SWAP    IY                 12~N
        53,  // 3F: LDW     (HL),HL            12~[Ww]N/12~[Wwww]N/
        0,   // 40
        0,   // 41
        0,   // 42
        0,   // 43
        4,   // 44: LD      B,IYU              12~N
        4,   // 45: LD      B,IYL              12~N
        13,  // 46: LD      B,(IY+71)          1aa~[R]N
        0,   // 47
        0,   // 48
        0,   // 49
        0,   // 4A
        0,   // 4B
        4,   // 4C: LD      C,IYU              12~N
        4,   // 4D: LD      C,IYL              12~N
        13,  // 4E: LD      C,(IY+79)          1aa~[R]N
        0,   // 4F
        0,   // 50
        0,   // 51
        0,   // 52
        0,   // 53
        4,   // 54: LD      D,IYU              12~N
        4,   // 55: LD      D,IYL              12~N
        13,  // 56: LD      D,(IY+87)          1aa~[R]N
        0,   // 57
        0,   // 58
        0,   // 59
        0,   // 5A
        0,   // 5B
        4,   // 5C: LD      E,IYU              12~N
        4,   // 5D: LD      E,IYL              12~N
        13,  // 5E: LD      E,(IY+95)          1aa~[R]N
        0,   // 5F
        4,   // 60: LD      IYU,B              12~N
        4,   // 61: LD      IYU,C              12~N
        4,   // 62: LD      IYU,D              12~N
        4,   // 63: LD      IYU,E              12~N
        4,   // 64: LD      IYU,IYU            12~N
        4,   // 65: LD      IYU,IYL            12~N
        13,  // 66: LD      H,(IY+103)         1aa~[R]N
        4,   // 67: LD      IYU,A              12~N
        4,   // 68: LD      IYL,B              12~N
        4,   // 69: LD      IYL,C              12~N
        4,   // 6A: LD      IYL,D              12~N
        4,   // 6B: LD      IYL,E              12~N
        4,   // 6C: LD      IYL,IYU            12~N
        4,   // 6D: LD      IYL,IYL            12~N
        13,  // 6E: LD      L,(IY+111)         1aa~[R]N
        4,   // 6F: LD      IYL,A              12~N
        10,  // 70: LD      (IY+113),B         1aa~[W]N
        10,  // 71: LD      (IY+114),C         1aa~[W]N
        10,  // 72: LD      (IY+115),D         1aa~[W]N
        10,  // 73: LD      (IY+116),E         1aa~[W]N
        10,  // 74: LD      (IY+117),H         1aa~[W]N
        10,  // 75: LD      (IY+118),L         1aa~[W]N
        0,   // 76
        10,  // 77: LD      (IY+120),A         1aa~[W]N
        0,   // 78
        80,  // 79: OUTW    (C),7B7AH          1222~[O]N
        0,   // 7A
        0,   // 7B
        4,   // 7C: LD      A,IYU              12~N
        4,   // 7D: LD      A,IYL              12~N
        13,  // 7E: LD      A,(IY+127)         1aa~[R]N
        0,   // 7F
        0,   // 80
        0,   // 81
        0,   // 82
        0,   // 83
        4,   // 84: ADD     A,IYU              12~N
        4,   // 85: ADD     A,IYL              12~N
        13,  // 86: ADD     A,(IY-121)         1aa~[R]N
        4,   // 87: ADDW    HL,IY              12~N
        0,   // 88
        0,   // 89
        0,   // 8A
        0,   // 8B
        4,   // 8C: ADC     A,IYU              12~N
        4,   // 8D: ADC     A,IYL              12~N
        13,  // 8E: ADC     A,(IY-113)         1aa~[R]N
        4,   // 8F: ADCW    HL,IY              12~N
        0,   // 90
        0,   // 91
        0,   // 92
        0,   // 93
        4,   // 94: SUB     A,IYU              12~N
        4,   // 95: SUB     A,IYL              12~N
        13,  // 96: SUB     (IY-105)           1aa~[R]N
        4,   // 97: SUBW    HL,IY              12~N
        0,   // 98
        0,   // 99
        0,   // 9A
        0,   // 9B
        4,   // 9C: SBC     A,IYU              12~N
        4,   // 9D: SBC     A,IYL              12~N
        13,  // 9E: SBC     A,(IY-97)          1aa~[R]N
        4,   // 9F: SBCW    HL,IY              12~N
        0,   // A0
        0,   // A1
        0,   // A2
        0,   // A3
        4,   // A4: AND     A,IYU              12~N
        4,   // A5: AND     A,IYL              12~N
        13,  // A6: AND     (IY-89)            1aa~[R]N
        4,   // A7: ANDW    HL,IY              12~N
        0,   // A8
        0,   // A9
        0,   // AA
        0,   // AB
        4,   // AC: XOR     A,IYU              12~N
        4,   // AD: XOR     A,IYL              12~N
        13,  // AE: XOR     (IY-81)            1aa~[R]N
        4,   // AF: XORW    HL,IY              12~N
        0,   // B0
        0,   // B1
        0,   // B2
        0,   // B3
        4,   // B4: OR      A,IYU              12~N
        4,   // B5: OR      A,IYL              12~N
        13,  // B6: OR      (IY-73)            1aa~[R]N
        4,   // B7: ORW     HL,IY              12~N
        0,   // B8
        0,   // B9
        0,   // BA
        0,   // BB
        4,   // BC: CP      A,IYU              12~N
        4,   // BD: CP      A,IYL              12~N
        13,  // BE: CP      (IY-65)            1aa~[R]N
        4,   // BF: CPW     HL,IY              12~N
        4,   // C0: DDIR    LW                 12~N
        4,   // C1: DDIR    IB,LW              12~N
        4,   // C2: DDIR    IW,LW              12~N
        4,   // C3: DDIR    IW                 12~N
        81,  // C4: CALR    NZ,$-003936H
             // 12222~[WwJ]@12222~N//12222~[WwwwJ]@12222~N
        0,   // C5
        74,  // C6: ADDW    HL,(IY-57)         1aa~[Rr]N
        0,   // C7
        0,   // C8
        0,   // C9
        0,   // CA
        0,   // CB
        81,  // CC: CALR    Z,$-00312EH
             // 12222~[WwJ]@12222~N//12222~[WwwwJ]@12222~N
        82,  // CD: CALR    $-00302DH          12222~[WwJ]//12222~[WwwwJ]
        74,  // CE: ADCW    HL,(IY-49)         1aa~[Rr]N
        0,   // CF
        4,   // D0: LDCTL   A,YSR              12~N
        0,   // D1
        0,   // D2
        56,  // D3: OUTAW   (0D5D4H),HL        12aa~[O]N
        81,  // D4: CALR    NC,$-002926H
             // 12222~[WwJ]@12222~N//12222~[WwwwJ]@12222~N
        0,   // D5
        74,  // D6: SUBW    HL,(IY-41)         1aa~[Rr]N
        0,   // D7
        4,   // D8: LDCTL   YSR,A              12~N
        4,   // D9: EXXY    -                  12~N
        31,  // DA: LDCTL   YSR,0DBH           122~N
        57,  // DB: INAW    HL,(0DDDCH)        12aa~[I]N
        81,  // DC: CALR    C,$-00211EH
             // 12222~[WwJ]@12222~N//12222~[WwwwJ]@12222~N
        0,   // DD
        74,  // DE: SBCW    HL,(IY-33)         1aa~[Rr]N
        0,   // DF
        0,   // E0
        51,  // E1: POP     IY                 12~[Rr]N/12~[Rrrr]N/
        0,   // E2
        76,  // E3: EX      (SP),IY            12~[RrWw]N/12~[RrrrWwww]N/
        81,  // E4: CALR    PO,$-001916H
             // 12222~[WwJ]@12222~N//12222~[WwwwJ]@12222~N
        53,  // E5: PUSH    IY                 12~[Ww]N/12~[Wwww]N/
        74,  // E6: ANDW    HL,(IY-25)         1aa~[Rr]N
        0,   // E7
        0,   // E8
        77,  // E9: JP      (IY)               12~[?]
        0,   // EA
        0,   // EB
        81,  // EC: CALR    PE,$-01110EH
             // 12222~[WwJ]@12222~N//12222~[WwwwJ]@12222~N
        0,   // ED
        74,  // EE: XORW    HL,(IY-17)         1aa~[Rr]N
        0,   // EF
        0,   // F0
        0,   // F1
        0,   // F2
        0,   // F3
        81,  // F4: CALR    P,$-010906H
             // 12222~[WwJ]@12222~N//12222~[WwwwJ]@12222~N
        32,  // F5: PUSH    0F7F6H             12aa~[Ww]N/12aa~[Wwww]N/
        74,  // F6: ORW     HL,(IY-9)          1aa~[Rr]N
        83,  // F7: SETC    XM                 12~[Ww]N
        0,   // F8
        4,   // F9: LD      SP,IY              12~N
        0,   // FA
        0,   // FB
        81,  // FC: CALR    M,$-0000FEH
             // 12222~[WwJ]@12222~N//12222~[WwwwJ]@12222~N
        0,   // FD
        74,  // FE: CPW     HL,(IY-1)          1aa~[Rr]N
        0,   // FF
};

constexpr uint8_t PAGEDDCB_TABLE[] = {
        0,   // 00
        35,  // 01: LDW     BC,(SP-52)         12aa~[Rr]N/12aa~[Rrrr]N/
        84,  // 02: RLCW    (IX-52)            12aa~[RrWw]N
        35,  // 03: LDW     BC,(IX-52)         12aa~[Rr]N/12aa~[Rrrr]N/
        0,   // 04
        0,   // 05
        85,  // 06: RLC     (IX-52)            12aa~[RW]N
        0,   // 07
        0,   // 08
        32,  // 09: LDW     (SP-52),BC         12aa~[Ww]N/12aa~[Wwww]N/
        84,  // 0A: RRCW    (IX-52)            12aa~[RrWw]N
        32,  // 0B: LDW     (IX-52),BC         12aa~[Ww]N/12aa~[Wwww]N/
        0,   // 0C
        0,   // 0D
        85,  // 0E: RRC     (IX-52)            12aa~[RW]N
        0,   // 0F
        0,   // 10
        35,  // 11: LDW     DE,(SP-52)         12aa~[Rr]N/12aa~[Rrrr]N/
        84,  // 12: RLW     (IX-52)            12aa~[RrWw]N
        35,  // 13: LDW     DE,(IX-52)         12aa~[Rr]N/12aa~[Rrrr]N/
        0,   // 14
        0,   // 15
        85,  // 16: RL      (IX-52)            12aa~[RW]N
        0,   // 17
        0,   // 18
        32,  // 19: LDW     (SP-52),DE         12aa~[Ww]N/12aa~[Wwww]N/
        84,  // 1A: RRW     (IX-52)            12aa~[RrWw]N
        32,  // 1B: LDW     (IX-52),DE         12aa~[Ww]N/12aa~[Wwww]N/
        0,   // 1C
        0,   // 1D
        85,  // 1E: RR      (IX-52)            12aa~[RW]N
        0,   // 1F
        0,   // 20
        35,  // 21: LDW     IX,(SP-52)         12aa~[Rr]N/12aa~[Rrrr]N/
        84,  // 22: SLAW    (IX-52)            12aa~[RrWw]N
        35,  // 23: LDW     IY,(IX-52)         12aa~[Rr]N/12aa~[Rrrr]N/
        0,   // 24
        0,   // 25
        85,  // 26: SLA     (IX-52)            12aa~[RW]N
        0,   // 27
        0,   // 28
        32,  // 29: LDW     (SP-52),IX         12aa~[Ww]N/12aa~[Wwww]N/
        84,  // 2A: SRAW    (IX-52)            12aa~[RrWw]N
        32,  // 2B: LDW     (IX-52),IY         12aa~[Ww]N/12aa~[Wwww]N/
        0,   // 2C
        0,   // 2D
        85,  // 2E: SRA     (IX-52)            12aa~[RW]N
        0,   // 2F
        0,   // 30
        35,  // 31: LDW     HL,(SP-52)         12aa~[Rr]N/12aa~[Rrrr]N/
        0,   // 32
        35,  // 33: LDW     HL,(IX-52)         12aa~[Rr]N/12aa~[Rrrr]N/
        0,   // 34
        0,   // 35
        0,   // 36
        0,   // 37
        0,   // 38
        32,  // 39: LDW     (SP-52),HL         12aa~[Ww]N/12aa~[Wwww]N/
        84,  // 3A: SRLW    (IX-52)            12aa~[RrWw]N
        32,  // 3B: LDW     (IX-52),HL         12aa~[Ww]N/12aa~[Wwww]N/
        0,   // 3C
        0,   // 3D
        85,  // 3E: SRL     (IX-52)            12aa~[RW]N
        0,   // 3F
        0,   // 40
        0,   // 41
        0,   // 42
        0,   // 43
        0,   // 44
        0,   // 45
        86,  // 46: BIT     0,(IX-52)          12aa~[R]N
        0,   // 47
        0,   // 48
        0,   // 49
        0,   // 4A
        0,   // 4B
        0,   // 4C
        0,   // 4D
        87,  // 4E: BIT     1,(IX+5)           1222~[R]N
        0,   // 4F
        0,   // 50
        0,   // 51
        0,   // 52
        0,   // 53
        0,   // 54
        0,   // 55
        87,  // 56: BIT     2,(IX+5)           1222~[R]N
        0,   // 57
        0,   // 58
        0,   // 59
        0,   // 5A
        0,   // 5B
        0,   // 5C
        0,   // 5D
        87,  // 5E: BIT     3,(IX+5)           1222~[R]N
        0,   // 5F
        0,   // 60
        0,   // 61
        0,   // 62
        0,   // 63
        0,   // 64
        0,   // 65
        87,  // 66: BIT     4,(IX+5)           1222~[R]N
        0,   // 67
        0,   // 68
        0,   // 69
        0,   // 6A
        0,   // 6B
        0,   // 6C
        0,   // 6D
        87,  // 6E: BIT     5,(IX+5)           1222~[R]N
        0,   // 6F
        0,   // 70
        0,   // 71
        0,   // 72
        0,   // 73
        0,   // 74
        0,   // 75
        87,  // 76: BIT     6,(IX+5)           1222~[R]N
        0,   // 77
        0,   // 78
        0,   // 79
        0,   // 7A
        0,   // 7B
        0,   // 7C
        0,   // 7D
        87,  // 7E: BIT     7,(IX+5)           1222~[R]N
        0,   // 7F
        0,   // 80
        0,   // 81
        0,   // 82
        0,   // 83
        0,   // 84
        0,   // 85
        85,  // 86: RES     0,(IX-52)          12aa~[RW]N
        0,   // 87
        0,   // 88
        0,   // 89
        0,   // 8A
        0,   // 8B
        0,   // 8C
        0,   // 8D
        88,  // 8E: RES     1,(IX+5)           1222~[RW]N
        0,   // 8F
        0,   // 90
        0,   // 91
        54,  // 92: MULTW   HL,(IX-52)         12aa~[Rr]N
        0,   // 93
        0,   // 94
        0,   // 95
        88,  // 96: RES     2,(IX+5)           1222~[RW]N
        0,   // 97
        0,   // 98
        0,   // 99
        54,  // 9A: MULTUW  HL,(IX-52)         12aa~[Rr]N
        0,   // 9B
        0,   // 9C
        0,   // 9D
        88,  // 9E: RES     3,(IX+5)           1222~[RW]N
        0,   // 9F
        0,   // A0
        0,   // A1
        0,   // A2
        0,   // A3
        0,   // A4
        0,   // A5
        88,  // A6: RES     4,(IX+5)           1222~[RW]N
        0,   // A7
        0,   // A8
        0,   // A9
        0,   // AA
        0,   // AB
        0,   // AC
        0,   // AD
        88,  // AE: RES     5,(IX+5)           1222~[RW]N
        0,   // AF
        0,   // B0
        0,   // B1
        0,   // B2
        0,   // B3
        0,   // B4
        0,   // B5
        88,  // B6: RES     6,(IX+5)           1222~[RW]N
        0,   // B7
        0,   // B8
        0,   // B9
        54,  // BA: DIVUW   HL,(IX-52)         12aa~[Rr]N
        0,   // BB
        0,   // BC
        0,   // BD
        88,  // BE: RES     7,(IX+5)           1222~[RW]N
        0,   // BF
        0,   // C0
        0,   // C1
        0,   // C2
        0,   // C3
        0,   // C4
        0,   // C5
        88,  // C6: SET     0,(IX+5)           1222~[RW]N
        0,   // C7
        0,   // C8
        0,   // C9
        0,   // CA
        0,   // CB
        0,   // CC
        0,   // CD
        85,  // CE: SET     1,(IX-52)          12aa~[RW]N
        0,   // CF
        0,   // D0
        0,   // D1
        0,   // D2
        0,   // D3
        0,   // D4
        0,   // D5
        85,  // D6: SET     2,(IX+5)           12aa~[RW]N
        0,   // D7
        0,   // D8
        0,   // D9
        0,   // DA
        0,   // DB
        0,   // DC
        0,   // DD
        88,  // DE: SET     3,(IX+5)           1222~[RW]N
        0,   // DF
        0,   // E0
        0,   // E1
        0,   // E2
        0,   // E3
        0,   // E4
        0,   // E5
        88,  // E6: SET     4,(IX+5)           1222~[RW]N
        0,   // E7
        0,   // E8
        0,   // E9
        0,   // EA
        0,   // EB
        0,   // EC
        0,   // ED
        88,  // EE: SET     5,(IX+5)           1222~[RW]N
        0,   // EF
        0,   // F0
        0,   // F1
        0,   // F2
        0,   // F3
        0,   // F4
        0,   // F5
        88,  // F6: SET     6,(IX+5)           1222~[RW]N
        0,   // F7
        0,   // F8
        0,   // F9
        0,   // FA
        0,   // FB
        0,   // FC
        0,   // FD
        88,  // FE: SET     7,(IX+5)           1222~[RW]N
        0,   // FF
};

constexpr uint8_t PAGEFDCB_TABLE[] = {
        0,   // 00
        75,  // 01: LDW     BC,(SP+5)          1222~[WwJ]//1222~[WwwwJ]
        84,  // 02: RLCW    (IY-52)            12aa~[RrWw]N
        35,  // 03: LDW     BC,(IY-52)         12aa~[Rr]N/12aa~[Rrrr]N/
        0,   // 04
        0,   // 05
        85,  // 06: RLC     (IY-52)            12aa~[RW]N
        0,   // 07
        0,   // 08
        75,  // 09: LDW     (SP+5),BC          1222~[WwJ]//1222~[WwwwJ]
        84,  // 0A: RRCW    (IY-52)            12aa~[RrWw]N
        32,  // 0B: LDW     (IY-52),BC         12aa~[Ww]N/12aa~[Wwww]N/
        0,   // 0C
        0,   // 0D
        85,  // 0E: RRC     (IY-52)            12aa~[RW]N
        0,   // 0F
        0,   // 10
        75,  // 11: LDW     DE,(SP+5)          1222~[WwJ]//1222~[WwwwJ]
        84,  // 12: RLW     (IY-52)            12aa~[RrWw]N
        35,  // 13: LDW     DE,(IY-52)         12aa~[Rr]N/12aa~[Rrrr]N/
        0,   // 14
        0,   // 15
        85,  // 16: RL      (IY-52)            12aa~[RW]N
        0,   // 17
        0,   // 18
        75,  // 19: LDW     (SP+5),DE          1222~[WwJ]//1222~[WwwwJ]
        84,  // 1A: RRW     (IY-52)            12aa~[RrWw]N
        32,  // 1B: LDW     (IY-52),DE         12aa~[Ww]N/12aa~[Wwww]N/
        0,   // 1C
        0,   // 1D
        85,  // 1E: RR      (IY-52)            12aa~[RW]N
        0,   // 1F
        0,   // 20
        35,  // 21: LDW     IY,(SP-52)         12aa~[Rr]N/12aa~[Rrrr]N/
        84,  // 22: SLAW    (IY-52)            12aa~[RrWw]N
        35,  // 23: LDW     IX,(IY-52)         12aa~[Rr]N/12aa~[Rrrr]N/
        0,   // 24
        0,   // 25
        85,  // 26: SLA     (IY-52)            12aa~[RW]N
        0,   // 27
        0,   // 28
        32,  // 29: LDW     (SP-52),IY         12aa~[Ww]N/12aa~[Wwww]N/
        84,  // 2A: SRAW    (IY-52)            12aa~[RrWw]N
        32,  // 2B: LDW     (IY-52),IX         12aa~[Ww]N/12aa~[Wwww]N/
        0,   // 2C
        0,   // 2D
        85,  // 2E: SRA     (IY-52)            12aa~[RW]N
        0,   // 2F
        0,   // 30
        75,  // 31: LDW     HL,(SP+5)          1222~[WwJ]//1222~[WwwwJ]
        0,   // 32
        35,  // 33: LDW     HL,(IY-52)         12aa~[Rr]N/12aa~[Rrrr]N/
        0,   // 34
        0,   // 35
        0,   // 36
        0,   // 37
        0,   // 38
        75,  // 39: LDW     (SP+5),HL          1222~[WwJ]//1222~[WwwwJ]
        84,  // 3A: SRLW    (IY-52)            12aa~[RrWw]N
        32,  // 3B: LDW     (IY-52),HL         12aa~[Ww]N/12aa~[Wwww]N/
        0,   // 3C
        0,   // 3D
        85,  // 3E: SRL     (IY-52)            12aa~[RW]N
        0,   // 3F
        0,   // 40
        0,   // 41
        0,   // 42
        0,   // 43
        0,   // 44
        0,   // 45
        86,  // 46: BIT     0,(IY-52)          12aa~[R]N
        0,   // 47
        0,   // 48
        0,   // 49
        0,   // 4A
        0,   // 4B
        0,   // 4C
        0,   // 4D
        87,  // 4E: BIT     1,(IY+5)           1222~[R]N
        0,   // 4F
        0,   // 50
        0,   // 51
        0,   // 52
        0,   // 53
        0,   // 54
        0,   // 55
        87,  // 56: BIT     2,(IY+5)           1222~[R]N
        0,   // 57
        0,   // 58
        0,   // 59
        0,   // 5A
        0,   // 5B
        0,   // 5C
        0,   // 5D
        87,  // 5E: BIT     3,(IY+5)           1222~[R]N
        0,   // 5F
        0,   // 60
        0,   // 61
        0,   // 62
        0,   // 63
        0,   // 64
        0,   // 65
        87,  // 66: BIT     4,(IY+5)           1222~[R]N
        0,   // 67
        0,   // 68
        0,   // 69
        0,   // 6A
        0,   // 6B
        0,   // 6C
        0,   // 6D
        87,  // 6E: BIT     5,(IY+5)           1222~[R]N
        0,   // 6F
        0,   // 70
        0,   // 71
        0,   // 72
        0,   // 73
        0,   // 74
        0,   // 75
        87,  // 76: BIT     6,(IY+5)           1222~[R]N
        0,   // 77
        0,   // 78
        0,   // 79
        0,   // 7A
        0,   // 7B
        0,   // 7C
        0,   // 7D
        87,  // 7E: BIT     7,(IY+5)           1222~[R]N
        0,   // 7F
        0,   // 80
        0,   // 81
        0,   // 82
        0,   // 83
        0,   // 84
        0,   // 85
        85,  // 86: RES     0,(IY-52)          12aa~[RW]N
        0,   // 87
        0,   // 88
        0,   // 89
        0,   // 8A
        0,   // 8B
        0,   // 8C
        0,   // 8D
        88,  // 8E: RES     1,(IY+5)           1222~[RW]N
        0,   // 8F
        0,   // 90
        0,   // 91
        54,  // 92: MULTW   HL,(IY-52)         12aa~[Rr]N
        0,   // 93
        0,   // 94
        0,   // 95
        88,  // 96: RES     2,(IY+5)           1222~[RW]N
        0,   // 97
        0,   // 98
        0,   // 99
        54,  // 9A: MULTUW  HL,(IY-52)         12aa~[Rr]N
        0,   // 9B
        0,   // 9C
        0,   // 9D
        88,  // 9E: RES     3,(IY+5)           1222~[RW]N
        0,   // 9F
        0,   // A0
        0,   // A1
        0,   // A2
        0,   // A3
        0,   // A4
        0,   // A5
        88,  // A6: RES     4,(IY+5)           1222~[RW]N
        0,   // A7
        0,   // A8
        0,   // A9
        0,   // AA
        0,   // AB
        0,   // AC
        0,   // AD
        88,  // AE: RES     5,(IY+5)           1222~[RW]N
        0,   // AF
        0,   // B0
        0,   // B1
        0,   // B2
        0,   // B3
        0,   // B4
        0,   // B5
        88,  // B6: RES     6,(IY+5)           1222~[RW]N
        0,   // B7
        0,   // B8
        0,   // B9
        54,  // BA: DIVUW   HL,(IY-52)         12aa~[Rr]N
        0,   // BB
        0,   // BC
        0,   // BD
        88,  // BE: RES     7,(IY+5)           1222~[RW]N
        0,   // BF
        0,   // C0
        0,   // C1
        0,   // C2
        0,   // C3
        0,   // C4
        0,   // C5
        88,  // C6: SET     0,(IY+5)           1222~[RW]N
        0,   // C7
        0,   // C8
        0,   // C9
        0,   // CA
        0,   // CB
        0,   // CC
        0,   // CD
        85,  // CE: SET     1,(IY-52)          12aa~[RW]N
        0,   // CF
        0,   // D0
        0,   // D1
        0,   // D2
        0,   // D3
        0,   // D4
        0,   // D5
        85,  // D6: SET     2,(IY+5)           12aa~[RW]N
        0,   // D7
        0,   // D8
        0,   // D9
        0,   // DA
        0,   // DB
        0,   // DC
        0,   // DD
        88,  // DE: SET     3,(IY+5)           1222~[RW]N
        0,   // DF
        0,   // E0
        0,   // E1
        0,   // E2
        0,   // E3
        0,   // E4
        0,   // E5
        88,  // E6: SET     4,(IY+5)           1222~[RW]N
        0,   // E7
        0,   // E8
        0,   // E9
        0,   // EA
        0,   // EB
        0,   // EC
        0,   // ED
        88,  // EE: SET     5,(IY+5)           1222~[RW]N
        0,   // EF
        0,   // F0
        0,   // F1
        0,   // F2
        0,   // F3
        0,   // F4
        0,   // F5
        88,  // F6: SET     6,(IY+5)           1222~[RW]N
        0,   // F7
        0,   // F8
        0,   // F9
        0,   // FA
        0,   // FB
        0,   // FC
        0,   // FD
        88,  // FE: SET     7,(IY+5)           1222~[RW]N
        0,   // FF
};
// END GENERATED
// clang-format on

// Sequences: debugger/match_legend.md. An interrupt, NMI or trap, where
// the queue may have fetched ahead: an acknowledge but for the NMI's and a
// trap's, then the PC pushed and the vector fetched in either order.
constexpr const char INTERRUPT[] = "~![Ww?]@~[Ww?]";
constexpr const char INTERRUPT_XM[] = "~![Wwww?]@~[Wwww?]";

// The |n|th of |seq|'s variants: [from, to), empty where it has none.
void variant(const char *seq, int n, const char *&from, const char *&to) {
    from = seq;
    for (; n > 0; --n) {
        while (*from && *from != '/')
            ++from;
        if (*from == 0) {
            to = from;
            return;
        }
        ++from;
    }
    to = from;
    while (*to && *to != '/')
        ++to;
}

bool has(const char *from, const char *to, char c) {
    for (; from < to; ++from) {
        if (*from == c)
            return true;
    }
    return false;
}

// How an instruction moves the PC, by its page and opcode.
enum Flow : uint8_t { F_NONE, F_ABS, F_REL, F_RST, F_TRAP };

Flow flowOf(uint8_t page, uint8_t opc) {
    const auto group = opc & 0xC7;
    const auto jr = opc == 0x10 || opc == 0x18 || (opc & 0xE7) == 0x20;
    if (page == 0x00) {
        if (group == 0xC2 || group == 0xC4 || opc == 0xC3 || opc == 0xCD)
            return F_ABS;  // JP, CALL
        if (jr)
            return F_REL;  // JR, DJNZ
        if (group == 0xC7)
            return F_RST;
    } else if (page == 0xDD || page == 0xFD || page == 0xED) {
        if ((page != 0xED && jr) || opc == 0xCD || group == 0xC4)
            return F_REL;       // JR, DJNZ, CALR with a longer displacement
    } else if (page == 0xFC) {  // FD CB
        if ((opc & 0xC7) == 0x01 && opc != 0x21 && opc != 0x29)
            return F_TRAP;
    }
    return F_NONE;
}

}  // namespace

// A DDIR in front adds its IB/IW bytes after the "a" ones, widens a
// target, and picks the word size; one the instruction doesn't care for is
// two bytes of its own. J goes to a JP's or CALL's operand, a relative
// one's next + displacement, a RST's opcode & 38H, or a trap's 0000H.
bool InstZ380::decode(uint32_t pc, MatchWalker::Decoded &inst) const {
    auto read = [&](uint32_t addr) { return _mems->read_byte(addr); };
    auto b0 = read(pc);
    auto b1 = read(pc + 1);
    uint8_t extension = 0;  // DDIR IB/IW bytes
    uint8_t ddirWord = 0;   // DDIR: 0 none, 1 W, 2 LW
    uint8_t ddirLength = 0;
    // DDIR decoder directives: DD C0-C3 W, IB W, IW W, IB; FD C0-C3 LW,
    // IB LW, IW LW, IW.
    if ((b0 == 0xDD || b0 == 0xFD) && (b1 & 0xFC) == 0xC0) {
        const auto d = b1 & 3;
        extension = d == 3 ? (b0 == 0xDD ? 1 : 2) : d;
        ddirWord = d == 3 ? 0 : (b0 == 0xDD ? 1 : 2);
        ddirLength = 2;
        b0 = read(pc + 2);
        b1 = read(pc + 3);
    }
    const auto base = pc + ddirLength;
    const uint8_t *row;
    uint8_t page = b0;
    uint8_t opc = b1;
    uint8_t opcodeLength = 2;
    if (b0 == 0xCB) {
        row = &PAGECB_TABLE[b1];
    } else if (b0 == 0xED) {
        if (b1 == 0xCB) {
            opc = read(base + 2);
            page = 0xEC;  // ED CB
            row = &PAGEEDCB_TABLE[opc];
        } else {
            row = &PAGEED_TABLE[b1];
        }
    } else if (b0 == 0xDD || b0 == 0xFD) {
        if (b1 == 0xCB) {
            // the displacement, widened by IB or IW, before the opcode
            opc = read(base + 3 + extension);
            page = b0 == 0xDD ? 0xDC : 0xFC;  // DD CB, FD CB
            row = b0 == 0xDD ? &PAGEDDCB_TABLE[opc] : &PAGEFDCB_TABLE[opc];
        } else {
            row = b0 == 0xDD ? &PAGEDD_TABLE[b1] : &PAGEFD_TABLE[b1];
        }
    } else {
        page = 0x00;
        opc = b0;
        opcodeLength = 1;
        row = &PAGE00_TABLE[b0];
    }
    const auto seq = SEQUENCES[*row];
    if (*seq == 0)
        return false;
    const char *from, *to, *lwFrom, *lwTo, *xmFrom, *xmTo;
    variant(seq, 0, from, to);
    variant(seq, 1, lwFrom, lwTo);
    variant(seq, 2, xmFrom, xmTo);
    inst.pc = pc;
    inst.hasEa = false;
    inst.hasTarget = false;
    const auto widened = has(from, to, 'a');
    const auto block = has(from, to, '{') && !has(from, to, 'h');
    if (ddirLength && !widened) {
        if (block || lwFrom == lwTo) {
            // one the directive doesn't affect: two bytes of its own
            inst.seq = "12~N";
            inst.length = 2;
            return true;
        }
        extension = 0;
    }
    const auto lw = ddirWord == 2 || (ddirWord == 0 && _lw);
    if (_xm && xmFrom != xmTo) {
        from = xmFrom;
        to = xmTo;
    } else if (lw && lwFrom != lwTo) {
        from = lwFrom;
        to = lwTo;
    }
    // each alternative: the DDIR, then its own bytes and its IB/IW
    auto out = inst.text;
    const auto last = inst.text + sizeof(inst.text) - 1;
    auto put = [&](char c) {
        if (out == last)
            return false;
        *out++ = c;
        return true;
    };
    for (auto p = from; p < to; ++p) {
        if (p == from || p[-1] == '@') {
            if (ddirLength && !(put('1') && put('2')))
                return false;
            if (ddirLength && *p == '1') {
                if (!put('2'))
                    return false;
                continue;
            }
        }
        if (*p == 'a') {
            if (!put('2'))
                return false;
            if (p + 1 < to && p[1] != 'a') {
                for (auto k = 0u; k < extension; ++k) {
                    if (!put('2'))
                        return false;
                }
            }
            continue;
        }
        if (!put(*p))
            return false;
    }
    *out = 0;
    inst.seq = inst.text;
    inst.length = MatchWalker::instructionBytes(inst.text);
    const auto mask = _xm ? UINT32_MAX : UINT32_C(0xFFFF);
    const auto end = pc + inst.length;
    // the instruction's last |n| bytes, little endian
    auto operand = [&](uint_fast8_t n) {
        uint32_t v = 0;
        for (auto i = 0u; i < n; ++i)
            v |= static_cast<uint32_t>(read(end - n + i)) << (8 * i);
        return v;
    };
    switch (flowOf(page, opc)) {
    case F_ABS:
        inst.hasTarget = true;
        inst.target = operand(2 + extension) & mask;
        break;
    case F_REL: {
        const auto n = inst.length - ddirLength - opcodeLength;
        auto v = operand(n);
        const auto sign = UINT32_C(1) << (8 * n - 1);
        v = (v ^ sign) - sign;  // sign extended
        inst.hasTarget = true;
        inst.target = (end + v) & mask;
        break;
    }
    case F_RST:
        inst.hasTarget = true;
        inst.target = read(base) & 0x38;
        break;
    case F_TRAP:
        inst.hasTarget = true;
        inst.target = ORG_RESET;
        break;
    default:
        break;
    }
    return true;
}

MatchWalker::Kind InstZ380::cycleKind(const SignalsImpl *impl) const {
    const auto s = static_cast<const Signals *>(impl);
    if (s->halt())
        return MatchWalker::K_HALT;
    if (s->memReq())
        return s->read() ? MatchWalker::K_READ : MatchWalker::K_WRITE;
    if (s->intAck())
        return MatchWalker::K_ACK;
    if (!s->any())
        return MatchWalker::K_NONE;
    // RETI's I/O read too
    return s->write() ? MatchWalker::K_IO_WRITE : MatchWalker::K_IO_READ;
}

uint_fast8_t InstZ380::fetchBytes(const SignalsImpl *s) const {
    return static_cast<const Signals *>(s)->wordAccess() ? 2 : 1;
}

uint_fast8_t InstZ380::dataBytes(const SignalsImpl *s) const {
    return fetchBytes(s);
}

// A word's even byte rides the high lane, as a lone byte at an even
// address does.
uint8_t InstZ380::dataByte(const SignalsImpl *impl, uint_fast8_t k) const {
    const auto s = static_cast<const Signals *>(impl);
    const auto odd = s->wordAccess() ? k != 0 : (s->addr & 1) != 0;
    return odd ? s->data & 0xFF : s->data >> 8;
}

// Mode 0's acknowledge brings a RST; else the trap's, mode 1's or the
// NMI's.
bool InstZ380::entersInterrupt(
        const SignalsImpl *s, const SignalsImpl *ack) const {
    if (ack) {
        const auto v = ack->data & 0xFF;
        if ((v & 0xC7) == 0xC7)
            return s->addr == (v & 0x38u);
    }
    return s->addr == ORG_RESET || s->addr == ORG_RST38 || s->addr == ORG_NMI;
}

// One word pushed: where the CPU would have gone on, or for a trap the
// instruction it aborts.
bool InstZ380::pushesPc(
        const SignalsImpl *impl, uint32_t next, uint32_t last) const {
    const auto s = static_cast<const Signals *>(impl);
    if (_xm || next == UINT32_MAX)
        return true;
    const uint16_t pushed = (s->data << 8) | (s->data >> 8);
    return pushed == static_cast<uint16_t>(next) ||
           pushed == static_cast<uint16_t>(last);
}

const char *InstZ380::interruptSequence() const {
    return _xm ? INTERRUPT_XM : INTERRUPT;
}

void InstZ380::markCycle(
        SignalsImpl *impl, MatchWalker::Role role, uint_fast8_t) const {
    const auto s = static_cast<Signals *>(impl);
    switch (role) {
    case MatchWalker::R_FETCH:
        s->markFetch();
        break;
    case MatchWalker::R_BYTE:
        s->markByte();
        break;
    case MatchWalker::R_DATA:
        s->markOperand();
        break;
    default:
        if (!s->halt())
            s->clearMark();
        break;
    }
}

bool InstZ380::walk(Signals *begin, const Signals *end, const Memory &mems,
        uint32_t pc, bool xm, bool lw) {
    const InstZ380 arch(&mems, xm, lw);
    return MatchWalker::shared().walk(arch, begin, end, pc);
}

#ifndef ARDUINO
std::vector<const char *> InstZ380::sequences() {
    return std::vector<const char *>(
            std::begin(SEQUENCES), std::end(SEQUENCES));
}

std::vector<const char *> InstZ380::interrupts() {
    return {INTERRUPT, INTERRUPT_XM};
}
#endif

}  // namespace z380
}  // namespace debugger

// Local Variables:
// mode: c++
// c-basic-offset: 4
// tab-width: 4
// End:
// vim: set ft=cpp et ts=4 sw=4:
