#!/usr/bin/awk -f
# -*- mode: awk; -*-
#
# z380-PAGExx.txt -> the BUS_BYTES[], REPEATS[] and PAGExx_TABLE[] of inst_z380.cpp:
#
#   gawk -f inst_z380.awk z380-PAGE00.txt z380-PAGECB.txt z380-PAGEED.txt z380-PAGEEDCB.txt z380-PAGEDD.txt z380-PAGEFD.txt z380-PAGEDDCB.txt z380-PAGEFDCB.txt \
#       | clang-format --assume-filename=inst_z380.cpp
#
# and replace the tables after the "// Generated by:" line in the .cpp.
# tools/derive_tables.py writes the pages from the recording; its
# docstring has the legend of the columns.

BEGIN {
    ndata = 0;
    nblock = 0;
    npage = 0;
    GENERATED_BY = generated_by("inst_z380.awk");
    FLOW["-"] = "F_NONE";
    FLOW["A"] = "F_ABS";
    FLOW["L"] = "F_REL";
    FLOW["I"] = "F_IND";
    FLOW["T"] = "F_RST";
    FLOW["H"] = "F_STOP";
    FLOW["B"] = "F_REPEAT";
    FLOW["X"] = "F_TRAP";
}

# The command that made the tables, wrapped to 80 columns so clang-format
# keeps it.
function generated_by(script,  i, cmd, line, word) {
    cmd = "";
    line = "// Generated by: gawk -f " script;
    for (i = 1; i <= ARGC; i++) {
        word = (i < ARGC) ? ARGV[i] : "| clang-format";
        if (length(line) + 1 + length(word) > 78) {
            cmd = cmd line "\n";
            line = "//     " word;
        } else {
            line = line " " word;
        }
    }
    return cmd line;
}

# "R2W2" -> "B(2, 2, 0, 0)"; "-" -> SAME.
function counts(text,  n, k, i, m) {
    if (text == "-")
        return "SAME";
    if (text == "?") {
        printf("%s: %s: not measured\n", FILENAME, $1) > "/dev/stderr";
        exit 1;
    }
    split("R W r w", k, " ");
    for (i = 1; i <= 4; i++) {
        n[i] = 0;
        if (match(text, k[i] "[0-9]+"))
            n[i] = substr(text, RSTART + 1, RLENGTH - 1) + 0;
    }
    return sprintf("B(%d, %d, %d, %d)", n[1], n[2], n[3], n[4]);
}

function data_index(row,  i) {
    for (i = 1; i <= ndata; i++)
        if (DATA[i] == row)
            return i - 1;
    DATA[++ndata] = row;
    return ndata - 1;
}

# "R+1W+1" -> "{2, {'R', 'W'}, {1, 1}}"; "." is any address.
function block_index(text,  n, kind, step, s, i, row) {
    n = 0;
    s = text;
    while (match(s, /^[RWrw]([+-][0-9]|\.)/)) {
        n++;
        kind[n] = substr(s, 1, 1);
        step[n] = substr(s, 2, RLENGTH - 1);
        if (step[n] == ".")
            step[n] = "ANY";
        else
            step[n] = step[n] + 0;
        s = substr(s, RLENGTH + 1);
    }
    if (s != "" || n == 0 || n > 2) {
        printf("%s: %s: bad block %s\n", FILENAME, $1, text) > "/dev/stderr";
        exit 1;
    }
    if (n == 1) {
        kind[2] = kind[1];
        step[2] = step[1];
    }
    row = sprintf("{%d, {'%s', '%s'}, {%s, %s}}", n, kind[1], kind[2], step[1], step[2]);
    for (i = 1; i <= nblock; i++)
        if (BLOCK[i] == row)
            return i - 1;
    BLOCK[++nblock] = row;
    return nblock - 1;
}

$1 !~ /^[0-9A-F][0-9A-F]$/ { next; }
{
    opc = $1;
    mne = $2;
    if (mne == "-") {
        line = sprintf("        OP(0, F_NONE, 0),  // %s", opc);
    } else {
        opr = $3;
        len = $4;
        c = $5;
        cls = toupper(c);
        if (!(cls in FLOW)) {
            printf("%s: %s: unknown class %s\n", FILENAME, opc, c) > "/dev/stderr";
            exit 1;
        }
        flow = FLOW[cls];
        if (c != cls)
            flow = flow " | F_COND";
        if ($6 == "+")
            flow = flow " | F_WIDE";
        if (cls == "B")
            idx = block_index($7);
        else
            idx = data_index(sprintf("{%s, %s, %s, %s}",
                    counts($7), ($8 == "-") ? "0" : counts($8), counts($9),
                    counts($10)));
        if (len > 7 || idx > 31) {  # Opcode's bit fields
            printf("%s: %s: length %d or data index %d too large\n", FILENAME, opc,
                   len, idx) > "/dev/stderr";
            exit 1;
        }
        line = sprintf("        OP(%d, %s, %d),  // %s: %-7s %s", len, flow,
                       idx, opc, mne, opr);
    }
    if (FILENAME != current) {
        page = FILENAME;
        if (!sub(/^.*z380-PAGE/, "PAGE", page) || !sub(/\.txt$/, "", page)) {
            printf("Unknown file: %s\n", FILENAME) > "/dev/stderr";
            exit 1;
        }
        current = FILENAME;
        PAGE[++npage] = page;
        count[npage] = 0;
    }
    ROW[npage, ++count[npage]] = line;
}

END {
    printf("%s\n", GENERATED_BY);
    printf("const InstZ380::BusBytes InstZ380::BUS_BYTES[] = {\n");
    for (i = 1; i <= ndata; i++)
        printf("        %s,  // %d\n", DATA[i], i - 1);
    printf("};\n\n");
    printf("const InstZ380::Repeat InstZ380::REPEATS[] = {\n");
    for (i = 1; i <= nblock; i++)
        printf("        %s,  // %d\n", BLOCK[i], i - 1);
    printf("};\n");
    for (p = 1; p <= npage; p++) {
        printf("\nconst InstZ380::Opcode InstZ380::%s_TABLE[] = {\n", PAGE[p]);
        for (i = 1; i <= count[p]; i++)
            printf("%s\n", ROW[p, i]);
        printf("};\n");
    }
}
