# Z80180FSC QFP definition
# https://github.com/tgtakaoka/dip
# A8-A11 and A16-A19 share P30-P33 through a 74AHCT157 selected by P45 (ASEL)
# #INT1 and #INT2 are pulled up by 10k
name = "Z180"
title = "Z80180FSC"
qfp = "24x16"
pin1 = "bottom-left"
 1 = "P51, #NMI"
 2 = ",    (nc)"
 3 = ",    (nc)"
 4 = "P50, #INT0"
 5 = "VCC, #INT1"
 6 = "VCC, #INT2"
 7 = ",    ST"
 8 = "P20, A0"
 9 = "P21, A1"
10 = "P22, A2"
11 = "P23, A3"
12 = "GND, VSS"
13 = "P24, A4"
14 = ",    (nc)"
15 = "P25, A5"
16 = "P26, A6"
17 = "P27, A7"
18 = "P30, A8"
19 = "P31, A9"
20 = "P32, A10"
21 = "P33, A11"
22 = ",    (nc)"
23 = ",    (nc)"
24 = "P34, A12"
25 = "P35, A13"
26 = "P36, A14"
27 = "P37, A15"
28 = "P30, A16"
29 = "P31, A17"
30 = ",    (nc)"
31 = "P32, A18,  TOUT"
32 = "VCC"
33 = "P33, A19"
34 = "GND, VSS"
35 = "P10, D0"
36 = "P11, D1"
37 = "P12, D2"
38 = "P13, D3"
39 = "P14, D4"
40 = "P15, D5"
41 = "P16, D6"
42 = ",    (nc)"
43 = ",    (nc)"
44 = "P17, D7"
45 = ",    #RTS0"
46 = ",    #CTS0"
47 = ",    #DCD0"
48 = ",    TXA0"
49 = ",    RXA0"
50 = ",    CKA0, #DREQ0"
51 = ",    (nc)"
52 = ",    TXA1"
53 = ",    TEST"
54 = ",    RXA1"
55 = ",    CKA1, #TEND0"
56 = ",    TXS"
57 = ",    RXS,  #CTS1"
58 = ",    CKS"
59 = "VCC, #DREQ1"
60 = ",    #TEND1"
61 = ",    #HALT"
62 = ",    (nc)"
63 = ",    (nc)"
64 = ",    #RFSH"
65 = "P46, #IORQ"
66 = "P43, #MREQ"
67 = ",    E"
68 = "P42, #M1"
69 = "P41, #WR"
70 = "P40, #RD"
71 = "P44, PHI"
72 = "GND, VSS"
73 = "GND, VSS"
74 = ",    XTAL"
75 = ",    (nc)"
76 = "P47, EXTAL"
77 = "P52, #WAIT"
78 = "P55, #BUSACK"
79 = "P54, #BUSREQ"
80 = "P53, #RESET"
