# MC68HC08AZ0 QFP definition
# https://github.com/tgtakaoka/dip
name = "MC68HC08AZ0"
title = "MC68HC08AZ0"
qfp = 100
pin1 = "left-top"
 1 = ",    PTC4"
 2 = "P50, #IRQ"
 3 = "P53, #RST"
 4 = ",    PTF0, TACH2"
 5 = ",    PTF1, TACH3"
 6 = ",    PTF2"
 7 = ",    PTF3"
 8 = ",    PTF4, TBCH0"
 9 = "VCC, EVDD1"
10 = "P17, EDB7"
11 = "P20, EAB0"
12 = "P21, EAB1"
13 = "P22, EAB2"
14 = "P23, EAB3"
15 = "P24, EAB4"
16 = "P25, EAB5"
17 = "GND, EVSS1"
18 = ",    CANRx"
19 = ",    CANTx"
20 = ",    PTF5, TBCH1"
21 = ",    PTF6"
22 = "P44, PTE0, TxD"
23 = "P45, PTE1, RxD"
24 = ",    PTE2, TACH0"
25 = ",    PTE3, TACH1"
26 = ",    PTE4, #SS"
27 = ",    PTE5, MISO"
28 = ",    PTE6, MOSI"
29 = ",    PTE7, SPSCK"
30 = "GND, VSS"
31 = "VCC, VDD"
32 = ",    PTG0, KBD0"
33 = ",    PTG1, KBD1"
34 = ",    PTG2, KBD2"
35 = "VCC, EVDD2"
36 = "P26, EAB6"
37 = "P27, EAB7"
38 = "P30, EAB8"
39 = "P31, EAB9"
40 = "P32, EAB10"
41 = "P33, EAB11"
42 = "P34, EAB12"
43 = "GND, EVSS2"
44 = "P54, PTA0"
45 = ",    PTA1"
46 = ",    PTA2"
47 = ",    PTA3"
48 = ",    PTA4"
49 = ",    PTA5"
50 = ",    PTA6"
51 = ",    PTA7"
52 = ",    PTB0, ATD0"
53 = ",    PTB1, ATD1"
54 = ",    PTB2, ATD2"
55 = ",    PTB3, ATD3"
56 = ",    PTB4, ATD4"
57 = ",    PTB5, ATD5"
58 = ",    PTB6, ATD6"
59 = ",    PTB7, ATD7"
60 = "GND, EVSS3"
61 = "P35, EAB13"
62 = "P36, EAB14"
63 = "P37, EAB15"
64 = ",    CS0"
65 = ",    CS1"
66 = "P40, REB"
67 = "P41, WEB"
68 = ",    WSCLK"
69 = ",    PTD0"
70 = ",    PTD1"
71 = "VCC, VDDAREF"
72 = "GND, AVSS, VREFL"
73 = ",    PTD2"
74 = ",    PTD3"
75 = "P51, PTH0, KBD3"
76 = "P52, PTH1, KBD4"
77 = ",    PTD4, TBLCK"
78 = ",    PTD5"
79 = ",    PTD6, TACLK"
80 = ",    PTD7"
81 = "VCC, VREFH"
82 = "GND, EVSS4"
83 = "P10, EDB0"
84 = "P11, EDB1"
85 = "P12, EDB2"
86 = "P13, EDB3"
87 = "P14, EDB4"
88 = "P15, EDB5"
89 = "P16, EDB6"
90 = "VCC, EVDD3"
91 = "VCC, VDDA"
92 = "GND, VSSA"
93 = "Cap, CGMXFC"
94 = ",    OSC2"
95 = "P47, OSC1"
96 = "P42, PTC0"
97 = "P43, PTC1"
98 = "P46, PTC2, MCLK"
99 = "P55, PTC3"
100 = ",    PTC5"
